ROS Motion Planning: utils::Angle Class Reference
utils::Angle Class Reference
#include <angle.hpp>
Public Types
enum AngleRange { PositiveOnlyRange, PositiveNegativeRange }
Public Member Functions
Angle ()
virtual ~Angle ()
double toRadian (AngleRange range=PositiveNegativeRange) const
double cos () const
double sin () const
double toDegree (AngleRange range=PositiveNegativeRange) const
void setRadian (double value)
void setDegree (double value)
int sign () const
Angle operator+ (const Angle &other) const
Angle operator- (const Angle &other) const
Angle & operator+= (const Angle &other)
Angle & operator-= (const Angle &other)
bool operator== (const Angle &other) const
bool operator!= (const Angle &other) const
bool operator< (const Angle &other) const
bool operator<= (const Angle &other) const
bool operator> (const Angle &other) const
bool operator>= (const Angle &other) const
Static Public Member Functions
static Angle fromRadian (double value)
static Angle fromDegree (double value)
Private Member Functions
Angle (double value)
void normalize ()
Private Attributes
double value
Member Enumeration Documentation
AngleRange
enum utils::Angle::AngleRange
Enumerator
PositiveOnlyRange
PositiveNegativeRange
   {
     // [0, 2*pi) or [0째, 360째)
     PositiveOnlyRange,
     // (-pi, +pi] or (-180째, 180째]
     PositiveNegativeRange
   };
Constructor & Destructor Documentation
Angle() [1/2]
utils::Angle::Angle () inline
           : value(0)
   {
   }
Referenced by fromDegree(), fromRadian(), operator+(), and operator-().
~Angle()
virtual utils::Angle::~Angle () inline virtual
   {
   }
Angle() [2/2]
utils::Angle::Angle (double value) inline private
   {
     Angle::value = value;
     normalize();
   }
References normalize(), and value.
Member Function Documentation
cos()
double utils::Angle::cos () const inline
   {
     return std::cos(value);
   }
References value.
Referenced by sfm::Agent::move().
fromDegree()
static Angle utils::Angle::fromDegree (double value) inline static
   {
     return Angle(value / 180 * M_PI);
   }
References Angle(), and value.
Referenced by sfm::SocialForceModel::computeGroupForce().
fromRadian()
static Angle utils::Angle::fromRadian (double value) inline static
   {
     return Angle(value);
   }
References Angle(), and value.
Referenced by utils::Vector2d::angle(), sfm::SocialForceModel::computeGroupForce(), gazebo::PedestrianSFMPlugin::handlePedestrians(), sfm::Agent::move(), gazebo::PedestrianSFMPlugin::OnUpdate(), gazebo::PedestrianSFMPlugin::Reset(), and sfm::SocialForceModel::updatePosition().
normalize()
void utils::Angle::normalize () inline private
   {
     while (value <= -M_PI)
       value += 2 * M_PI;
     while (value > M_PI)
       value -= 2 * M_PI;
   }
References value.
Referenced by Angle(), operator+=(), operator-=(), setDegree(), and setRadian().
operator!=()
bool utils::Angle::operator!= (const Angle & other) const inline
   {
     return value != other.value;
   }
References value.
operator+()
Angle utils::Angle::operator+ (const Angle & other) const inline
   {
     return Angle(value + other.value);
   }
References Angle(), and value.
operator+=()
Angle& utils::Angle::operator+= (const Angle & other) inline
   {
     value += other.value;
     normalize();
     return *this;
   }
References normalize(), and value.
operator-()
Angle utils::Angle::operator- (const Angle & other) const inline
   {
     return Angle(value - other.value);
   }
References Angle(), and value.
operator-=()
Angle& utils::Angle::operator-= (const Angle & other) inline
   {
     value -= other.value;
     normalize();
     return *this;
   }
References normalize(), and value.
operator<()
bool utils::Angle::operator< (const Angle & other) const inline
   {
     return value < other.value;
   }
References value.
operator<=()
bool utils::Angle::operator<= (const Angle & other) const inline
   {
     return value <= other.value;
   }
References value.
operator==()
bool utils::Angle::operator== (const Angle & other) const inline
   {
     return value == other.value;
   }
References value.
operator>()
bool utils::Angle::operator> (const Angle & other) const inline
   {
     return value > other.value;
   }
References value.
operator>=()
bool utils::Angle::operator>= (const Angle & other) const inline
   {
     return value >= other.value;
   }
References value.
setDegree()
void utils::Angle::setDegree (double value) inline
   {
     Angle::value = value / 180 * M_PI;
     normalize();
   }
References normalize(), and value.
setRadian()
void utils::Angle::setRadian (double value) inline
   {
     Angle::value = value;
     normalize();
   }
References normalize(), and value.
sign()
int utils::Angle::sign () const inline
   {
     if (value == 0)
     {
       return 0;
     }
     else if (value > 0)
     {
       return 1;
     }
     else
     {
       return -1;
     }
   }
References value.
Referenced by sfm::SocialForceModel::computeSocialForce().
sin()
double utils::Angle::sin () const inline
   {
     return std::sin(value);
   }
References value.
Referenced by sfm::Agent::move().
toDegree()
double utils::Angle::toDegree (AngleRange range = PositiveNegativeRange) const inline
   {
     double degreeValue = value * 180 / M_PI;
     if (range == PositiveNegativeRange)
     {
       return degreeValue;
     }
     else
     {
       return (degreeValue >= 0) ? degreeValue : (degreeValue + 360);
     }
   }
References PositiveNegativeRange, and value.
toRadian()
double utils::Angle::toRadian (AngleRange range = PositiveNegativeRange) const inline
   {
     if (range == PositiveNegativeRange)
     {
       return value;
     }
     else
     {
       return (value >= 0) ? value : (value + 2 * M_PI);
     }
   }
References PositiveNegativeRange, and value.
Referenced by sfm::SocialForceModel::computeGroupForce(), sfm::SocialForceModel::computeSocialForce(), sfm::Agent::move(), and gazebo::PedestrianSFMPlugin::OnUpdate().
Member Data Documentation
value
double utils::Angle::value private
Referenced by Angle(), cos(), fromDegree(), fromRadian(), normalize(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), setDegree(), setRadian(), sign(), sin(), toDegree(), and toRadian().
The documentation for this class was generated from the following file:
src/third_party/gazebo_plugins/pedestrian_sfm_plugin/include/lightsfm/angle.hpp