ROS Motion Planning: spencer_tracking_rviz_plugin::TrackedGroupsDisplay Class Reference
spencer_tracking_rviz_plugin::TrackedGroupsDisplay Class Reference
The display which can be added in RViz to display tracked groups.
#include <tracked_groups_display.h>
Classes
struct GroupVisual
Public Member Functions
TrackedGroupsDisplay ()
virtual ~TrackedGroupsDisplay ()
virtual void onInitialize ()
Overrides base class method.
virtual void update (float wall_dt, float ros_dt)
Public Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >
PersonDisplayCommon ()
virtual ~PersonDisplayCommon ()
Public Member Functions inherited from spencer_tracking_rviz_plugin::StylesChangedSubscriber
virtual ~StylesChangedSubscriber ()
virtual void stylesChanged ()
Protected Member Functions
virtual void reset ()
virtual rviz::DisplayContext * getContext ()
Must be implemented by derived classes because MOC doesn't work in templates.
Protected Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >
bool preprocessMessage (const typename spencer_tracking_msgs::TrackedGroups ::ConstPtr &msg)
Common message processing. This method needs to be called by derived classes.
void createPersonVisualIfRequired (Ogre::SceneNode *sceneNode, boost::shared_ptr< PersonVisual > &personVisual)
Create a visual representation of the person itself, if not set yet.
void applyCommonStyles (boost::shared_ptr< PersonVisual > &personVisual)
Applies common styles which apply to person visuals, such as line width etc.
Ogre::Vector3 getVelocityVector (const geometry_msgs::TwistWithCovariance &twist)
bool hasValidOrientation (const geometry_msgs::PoseWithCovariance &pose)
Returns true if all xyz rotation variances are finite.
Ogre::Matrix3 covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance &pose)
void setPoseOrientation (Ogre::SceneNode *sceneNode, const geometry_msgs::PoseWithCovariance &pose, const Ogre::Matrix3 &covXYZinTargetFrame, double personVisualHeight)
Set pose and orientation of person visual.
Ogre::ColourValue getColorFromId (unsigned int object_id)
Get a color based upon track / detection ID.
bool isPersonHidden (person_id personId)
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
Private Slots
void personVisualTypeChanged ()
virtual void stylesChanged ()
Private Member Functions
void processMessage (const spencer_tracking_msgs::TrackedGroups::ConstPtr &msg)
void updateGroupVisualStyles (boost::shared_ptr< GroupVisual > &groupVisual)
void updateHistoryStyles ()
bool isGroupHidden (group_id groupId)
Private Attributes
boost::shared_ptr< Ogre::SceneNode > m_groupAffiliationHistorySceneNode
boost::shared_ptr< Ogre::SceneNode > m_groupsSceneNode
std::string m_realFixedFrame
rviz::StringProperty * m_excluded_group_ids_property
rviz::StringProperty * m_included_group_ids_property
rviz::BoolProperty * m_render_intragroup_connections_property
rviz::BoolProperty * m_render_ids_property
rviz::BoolProperty * m_render_history_property
rviz::BoolProperty * m_single_person_groups_in_constant_color_property
rviz::BoolProperty * m_hide_ids_of_single_person_groups_property
rviz::IntProperty * m_history_length_property
rviz::FloatProperty * m_occlusion_alpha_property
rviz::FloatProperty * m_group_id_offset
vector< boost::shared_ptr< GroupVisual > > m_groupVisuals
map< track_id, group_id > m_groupAffiliations
GroupAffiliationHistory m_groupAffiliationHistory
set< group_id > m_excludedGroupIDs
set< group_id > m_includedGroupIDs
Ogre::Matrix4 m_frameTransform
TrackedPersonsCache m_trackedPersonsCache
Additional Inherited Members
Protected Attributes inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >
PersonDisplayCommonProperties * m_commonProperties
Common properties for the displays in this plugin.
Ogre::Quaternion m_frameOrientation
Ogre::Matrix3 m_frameRotationMatrix
Ogre::Vector3 m_framePosition
const double m_veryLargeVariance
Detailed Description
The display which can be added in RViz to display tracked groups.
Constructor & Destructor Documentation
TrackedGroupsDisplay()
spencer_tracking_rviz_plugin::TrackedGroupsDisplay::TrackedGroupsDisplay () inline
 {};
~TrackedGroupsDisplay()
spencer_tracking_rviz_plugin::TrackedGroupsDisplay::~TrackedGroupsDisplay () virtual
 {
 }
Member Function Documentation
getContext()
virtual rviz::DisplayContext* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::getContext () inline protected virtual
Must be implemented by derived classes because MOC doesn't work in templates.
Implements spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >.
{
             return context_;
         }
Referenced by processMessage(), and update().
isGroupHidden()
bool spencer_tracking_rviz_plugin::TrackedGroupsDisplay::isGroupHidden (group_id groupId) private
{
     bool isIncluded = m_includedGroupIDs.find(groupId) != m_includedGroupIDs.end();
     if(isIncluded) return false;
     if(!m_includedGroupIDs.empty()) return true;
     return m_excludedGroupIDs.find(groupId) != m_excludedGroupIDs.end();
 }
References m_excludedGroupIDs, and m_includedGroupIDs.
Referenced by updateGroupVisualStyles(), and updateHistoryStyles().
onInitialize()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::onInitialize () virtual
Overrides base class method.
Reimplemented from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >.
 {
     m_realFixedFrame = "map";
     m_trackedPersonsCache.initialize(this, context_, update_nh_);
     PersonDisplayCommon::onInitialize();
     QObject::connect(m_commonProperties->style, SIGNAL(changed()), this, SLOT(personVisualTypeChanged()) );
     m_excluded_group_ids_property = new rviz::StringProperty( "Excluded group IDs", "", "Comma-separated list of group IDs whose group visualization should be hidden", this, SLOT(stylesChanged()) );
     m_included_group_ids_property = new rviz::StringProperty( "Included group IDs", "", "Comma-separated list of group IDs whose group visualization should be visible, overrides excluded", this, SLOT(stylesChanged()) );
     m_render_intragroup_connections_property = new rviz::BoolProperty( "Connect group members", true, "Connect all members of a group by lines", this, SLOT(stylesChanged()));
     m_render_ids_property = new rviz::BoolProperty( "Render group IDs", true, "Render group IDs as text", this, SLOT(stylesChanged()));
     m_render_history_property = new rviz::BoolProperty( "Render history", false, "Render group affiliation history", this, SLOT(stylesChanged()));
     m_single_person_groups_in_constant_color_property  = new rviz::BoolProperty( "Single-person groups in constant color", true, "Render single-person groups in constant color", this, SLOT(stylesChanged()));
     m_hide_ids_of_single_person_groups_property = new rviz::BoolProperty( "Hide IDs of single-person groups", false, "Hide IDs of single-person groups", m_render_ids_property, SLOT(stylesChanged()), this);
     m_history_length_property = new rviz::IntProperty( "Global history size", 1000, "Global number of group affiliation history entries to display.", this, SLOT(stylesChanged()));
     m_history_length_property->setMin( 1 );
     m_history_length_property->setMax( 10000000 );
     m_occlusion_alpha_property = new rviz::FloatProperty( "Occlusion alpha", 0.5, "Alpha multiplier for history of occluded tracks", this, SLOT(stylesChanged()) );
     m_occlusion_alpha_property->setMin( 0.0 );
     m_group_id_offset = new rviz::FloatProperty( "Group ID Z offset", 2.0, "Offset in z position (height) of the group ID text", this, SLOT(stylesChanged()) );
     // Create a scene node for visualizing group affiliation history
     m_groupAffiliationHistorySceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
     m_groupsSceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
 }
References spencer_tracking_rviz_plugin::TrackedPersonsCache::initialize(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_commonProperties, m_excluded_group_ids_property, m_group_id_offset, m_groupAffiliationHistorySceneNode, m_groupsSceneNode, m_hide_ids_of_single_person_groups_property, m_history_length_property, m_included_group_ids_property, m_occlusion_alpha_property, m_realFixedFrame, m_render_history_property, m_render_ids_property, m_render_intragroup_connections_property, m_single_person_groups_in_constant_color_property, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::onInitialize(), personVisualTypeChanged(), spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::style, and stylesChanged().
personVisualTypeChanged
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::personVisualTypeChanged () private slot
 {
     foreach(boost::shared_ptr<GroupVisual> groupVisual, m_groupVisuals) {
         foreach(boost::shared_ptr<PersonVisual>& personVisual, groupVisual->personVisuals) {
             Ogre::SceneNode* parentSceneNode = personVisual->getParentSceneNode();
             personVisual.reset();
             createPersonVisualIfRequired(parentSceneNode, personVisual);
         }
     }
     stylesChanged();
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::createPersonVisualIfRequired(), m_groupVisuals, and stylesChanged().
Referenced by onInitialize().
processMessage()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::processMessage (const spencer_tracking_msgs::TrackedGroups::ConstPtr & msg) private
 {
     // Get transforms into fixed frame etc.
     if(!preprocessMessage(msg)) return;
     // Transform from map/odometry frame into fixed frame, required to display track history if the fixed frame is not really "fixed" (e.g. base_link)
     Ogre::Vector3 mapFramePosition; Ogre::Quaternion mapFrameOrientation;
     getContext()->getFrameManager()->getTransform(m_realFixedFrame, msg->header.stamp, mapFramePosition, mapFrameOrientation);
     Ogre::Matrix4 mapFrameTransform(mapFrameOrientation); mapFrameTransform.setTrans(mapFramePosition);
     // Transform into Rviz fixed frame
     m_frameTransform = Ogre::Matrix4(m_frameOrientation);
     m_frameTransform.setTrans(m_framePosition);
     const Ogre::Quaternion shapeQuaternion( Ogre::Degree(90), Ogre::Vector3(1,0,0) ); // required to fix orientation of any Cylinder shapes
     stringstream ss;
     // Clear previous visualization
     m_groupVisuals.clear();
     m_groupsSceneNode->removeAndDestroyAllChildren();
     unsigned int numTracksWithUnknownPosition = 0;
     m_groupAffiliations.clear();
     //
     // Iterate over all groups in this message
     //
     foreach (const spencer_tracking_msgs::TrackedGroup& trackedGroup, msg->groups)
     {
         // Create a new visual representation of the tracked group
         boost::shared_ptr<GroupVisual> groupVisual = boost::shared_ptr<GroupVisual>(new GroupVisual);
         groupVisual->groupId = trackedGroup.group_id;
         groupVisual->personCount = trackedGroup.track_ids.size();
         m_groupVisuals.push_back(groupVisual);
         //
         // Group visualization circles, person visuals (if enabled) + connections between group members
         //
         for(size_t trackIndex = 0; trackIndex < trackedGroup.track_ids.size(); trackIndex++)
         {
             const track_id trackId = trackedGroup.track_ids[trackIndex];
             boost::shared_ptr<CachedTrackedPerson> trackedPerson = m_trackedPersonsCache.lookup(trackId);
             // Get current track position
             if(!trackedPerson) {
                 numTracksWithUnknownPosition++;
             }
             else
             {
                 Ogre::Vector3 trackCenterAtGroundPlane(trackedPerson->center.x, trackedPerson->center.y, m_commonProperties->z_offset->getFloat());
                 m_groupAffiliations[trackId] = trackedGroup.group_id; // required to hide certain groups later on
                 //
                 // Group visualization circles (below tracks)
                 //
                 const double groupAssignmentCircleHeight = 0;
                 const double groupAssignmentCircleDiameter = 0.9;
                 boost::shared_ptr<rviz::Shape> groupAssignmentCircle = boost::shared_ptr<rviz::Shape>(new rviz::Shape(rviz::Shape::Cylinder, context_->getSceneManager(), m_groupsSceneNode.get()));
                 groupAssignmentCircle->setScale(shapeQuaternion * Ogre::Vector3(groupAssignmentCircleDiameter, groupAssignmentCircleDiameter, groupAssignmentCircleHeight));
                 groupAssignmentCircle->setOrientation(shapeQuaternion);
                 Ogre::Vector3 groupAssignmentCirclePos = trackCenterAtGroundPlane + Ogre::Vector3(0, 0, -0.5*groupAssignmentCircleHeight - 0.01);
                 groupAssignmentCircle->setPosition(groupAssignmentCirclePos);
                 groupVisual->groupAssignmentCircles.push_back(groupAssignmentCircle);
                 //
                 // Person visuals (colored in group color)
                 //
                 // This scene node is the parent of all visualization elements for the tracked person
                 boost::shared_ptr<Ogre::SceneNode> sceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
                 groupVisual->personVisualSceneNodes.push_back(sceneNode);
                 // Create new visual for the person itself, if needed
                 boost::shared_ptr<PersonVisual> personVisual;
                 createPersonVisualIfRequired(sceneNode.get(), personVisual);
                 groupVisual->personVisuals.push_back(personVisual);
                 const double personHeight = personVisual ? personVisual->getHeight() : 0;
                 const Ogre::Matrix3 covXYZinTargetFrame = covarianceXYZIntoTargetFrame(trackedPerson->pose);
                 setPoseOrientation(sceneNode.get(), trackedPerson->pose, covXYZinTargetFrame, personHeight);
                 //
                 // Intra-group connections
                 //
                 // Iterate over all neighbouring group tracks to render intra-group connections
                 for(size_t otherTrackIndex = trackIndex + 1; otherTrackIndex < trackedGroup.track_ids.size(); otherTrackIndex++)
                 {
                     const track_id otherTrackId = trackedGroup.track_ids[otherTrackIndex];
                     boost::shared_ptr<CachedTrackedPerson> otherTrackedPerson = m_trackedPersonsCache.lookup(otherTrackId);
                     // Get other track's position
                     if(otherTrackedPerson) {
                         // Get positions. These are already in fixed frame coordinates!
                         const Ogre::Vector3 verticalShift(0,0, 0.5 + m_commonProperties->z_offset->getFloat());
                         const Ogre::Vector3& position1 = verticalShift + trackedPerson->center;
                         const Ogre::Vector3& position2 = verticalShift + otherTrackedPerson->center;
                         // Add line connecting the two tracks
                         boost::shared_ptr<rviz::BillboardLine> connectionLine(new rviz::BillboardLine(context_->getSceneManager(), m_groupsSceneNode.get()));
                         connectionLine->setMaxPointsPerLine(2);
                         connectionLine->addPoint(position1);
                         connectionLine->addPoint(position2);
                         groupVisual->connectionLines.push_back(connectionLine);
                     }
                 } // end loop over neighbouring group tracks
                 //
                 // Group affiliation history
                 //
                 boost::shared_ptr<GroupAffiliationHistoryEntry> newHistoryEntry(new GroupAffiliationHistoryEntry);
                 newHistoryEntry->shape = boost::shared_ptr<rviz::Shape>(new rviz::Shape(rviz::Shape::Cylinder, context_->getSceneManager(), m_groupAffiliationHistorySceneNode.get()));
                 newHistoryEntry->shape->setPosition(mapFrameTransform.inverse() * trackCenterAtGroundPlane);
                 newHistoryEntry->shape->setOrientation(shapeQuaternion);
                 newHistoryEntry->wasOccluded = trackedPerson->isOccluded;
                 newHistoryEntry->wasSinglePersonGroup = trackedGroup.track_ids.size() <= 1;
                 newHistoryEntry->groupId = trackedGroup.group_id;
                 m_groupAffiliationHistory.push_back(newHistoryEntry);
             } // end if track found
         } // end for loop over tracks
         //
         // Texts
         //
         const geometry_msgs::Point& groupCenter = trackedGroup.centerOfGravity.pose.position;
         groupVisual->groupCenter = groupCenter;
         // Group ID
         boost::shared_ptr<TextNode> idText(new TextNode(context_->getSceneManager(), m_groupsSceneNode.get()));
         ss.str(""); ss << "group " << trackedGroup.group_id;
         idText->setCaption(ss.str());
         idText->showOnTop();
         groupVisual->idText = idText;
         // Set adjustable styles such as color etc.
         updateGroupVisualStyles(groupVisual);
         updateHistoryStyles();
     } // end for loop over all tracked groups
     //
     // Update status (shown in property pane)
     //
     ss.str("");
     ss << msg->groups.size() << " group(s)";
     setStatusStd(rviz::StatusProperty::Ok, "Groups", ss.str());
     ss.str("");
     ss << numTracksWithUnknownPosition << " track(s) with unknown position";
     setStatusStd(0 == numTracksWithUnknownPosition ? rviz::StatusProperty::Ok : rviz::StatusProperty::Warn, "Track-to-group assignment", ss.str());
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::covarianceXYZIntoTargetFrame(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::createPersonVisualIfRequired(), getContext(), spencer_tracking_rviz_plugin::TrackedPersonsCache::lookup(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_commonProperties, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_frameOrientation, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_framePosition, m_frameTransform, m_groupAffiliationHistory, m_groupAffiliationHistorySceneNode, m_groupAffiliations, m_groupsSceneNode, m_groupVisuals, m_realFixedFrame, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::preprocessMessage(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::setPoseOrientation(), shapeQuaternion(), updateGroupVisualStyles(), updateHistoryStyles(), and spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::z_offset.
reset()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::reset () protected virtual
 {
     PersonDisplayCommon::reset();
     m_trackedPersonsCache.reset();
     m_groupVisuals.clear();
     m_groupAffiliationHistory.clear();
     m_groupAffiliations.clear();
 }
References m_groupAffiliationHistory, m_groupAffiliations, m_groupVisuals, m_trackedPersonsCache, and spencer_tracking_rviz_plugin::TrackedPersonsCache::reset().
stylesChanged
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::stylesChanged () private virtual slot
 {
      // Get list of group IDs belonging to tracks that shall be hidden or visible
      m_excludedGroupIDs.clear();
      {
          string groupIDString = m_excluded_group_ids_property->getStdString();
          char_separator<char> separator(",");
          tokenizer< char_separator<char> > tokens(groupIDString, separator);
          foreach(const string& token, tokens) {
              try { m_excludedGroupIDs.insert(lexical_cast<track_id>(token)); }
              catch(bad_lexical_cast &) {}
          }
      }
      m_includedGroupIDs.clear();
      {
         string groupIDString = m_included_group_ids_property->getStdString();
         char_separator<char> separator(",");
         tokenizer< char_separator<char> > tokens(groupIDString, separator);
         foreach(const string& token, tokens) {
             try { m_includedGroupIDs.insert(lexical_cast<track_id>(token)); }
             catch(bad_lexical_cast &) {}
         }
     }
     foreach(boost::shared_ptr<GroupVisual> groupVisual, m_groupVisuals) {
         updateGroupVisualStyles(groupVisual);
     }
      // Update history size
     m_groupAffiliationHistory.rset_capacity(m_history_length_property->getInt());
     // Update history color etc.
     updateHistoryStyles();
 }
References m_excluded_group_ids_property, m_excludedGroupIDs, m_groupAffiliationHistory, m_groupVisuals, m_history_length_property, m_included_group_ids_property, m_includedGroupIDs, updateGroupVisualStyles(), and updateHistoryStyles().
Referenced by onInitialize(), and personVisualTypeChanged().
update()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::update (float wall_dt, float ros_dt) virtual
 {
     // Move map scene node
     Ogre::Vector3 mapFramePosition; Ogre::Quaternion mapFrameOrientation;
     getContext()->getFrameManager()->getTransform(m_realFixedFrame, ros::Time(0), mapFramePosition, mapFrameOrientation);
     Ogre::Matrix4 mapFrameTransform(mapFrameOrientation); mapFrameTransform.setTrans(mapFramePosition);
     m_groupAffiliationHistorySceneNode->setPosition(mapFramePosition);
     m_groupAffiliationHistorySceneNode->setOrientation(mapFrameOrientation);
 }
References getContext(), m_groupAffiliationHistorySceneNode, and m_realFixedFrame.
updateGroupVisualStyles()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::updateGroupVisualStyles (boost::shared_ptr< GroupVisual > & groupVisual) private
 {
     bool hideGroup = isGroupHidden(groupVisual->groupId);
     // Apply current group color
     Ogre::ColourValue groupColor = m_commonProperties->constant_color->getOgreColor();
     if(groupVisual->personCount > 1 || !m_single_person_groups_in_constant_color_property->getBool()) {
         groupColor = getColorFromId(groupVisual->groupId);
     }
     groupColor.a *= m_commonProperties->alpha->getFloat(); // general alpha
     if(hideGroup) groupColor.a = 0;
     foreach(boost::shared_ptr<rviz::Shape> groupAssignmentCircle, groupVisual->groupAssignmentCircles) {
         groupAssignmentCircle->setColor(groupColor.r, groupColor.g, groupColor.b, groupColor.a);
     }
     foreach(boost::shared_ptr<PersonVisual>& personVisual, groupVisual->personVisuals) {
         if(personVisual) {
             // Update common styles to person visual, such as line width
             applyCommonStyles(personVisual);
             personVisual->setColor(groupColor);
         }
     }
     double connectionLineVisibilityAlpha = m_render_intragroup_connections_property->getBool() ? 1.0 : 0.0;
     foreach(boost::shared_ptr<rviz::BillboardLine> connectionLine, groupVisual->connectionLines) {
         connectionLine->setColor(groupColor.r, groupColor.g, groupColor.b, groupColor.a * connectionLineVisibilityAlpha);
         connectionLine->setLineWidth(0.05);
     }
     // Update text colors, size and visibility
     Ogre::ColourValue fontColor = m_commonProperties->font_color_style->getOptionInt() == FONT_COLOR_CONSTANT ? m_commonProperties->constant_font_color->getOgreColor() : groupColor;
     fontColor.a = m_commonProperties->alpha->getFloat();
     if(hideGroup) fontColor.a = 0;
     bool groupIdVisible = groupVisual->personCount > 1 ? true : !m_hide_ids_of_single_person_groups_property->getBool();
     groupVisual->idText->setVisible(m_render_ids_property->getBool() && groupIdVisible);
     groupVisual->idText->setCharacterHeight(0.23 * m_commonProperties->font_scale->getFloat());
     groupVisual->idText->setColor(fontColor);
     groupVisual->idText->setPosition(m_frameTransform * Ogre::Vector3(
         groupVisual->groupCenter.x,
         groupVisual->groupCenter.y,
         groupVisual->groupCenter.z + m_group_id_offset->getFloat() + m_commonProperties->z_offset->getFloat()));
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::alpha, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::applyCommonStyles(), spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::constant_color, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::constant_font_color, spencer_tracking_rviz_plugin::FONT_COLOR_CONSTANT, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_color_style, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_scale, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::getColorFromId(), isGroupHidden(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_commonProperties, m_frameTransform, m_group_id_offset, m_hide_ids_of_single_person_groups_property, m_render_ids_property, m_render_intragroup_connections_property, m_single_person_groups_in_constant_color_property, and spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::z_offset.
Referenced by processMessage(), and stylesChanged().
updateHistoryStyles()
void spencer_tracking_rviz_plugin::TrackedGroupsDisplay::updateHistoryStyles () private
 {
     const Ogre::Quaternion shapeQuaternion( Ogre::Degree(90), Ogre::Vector3(1,0,0) );
     foreach(boost::shared_ptr<GroupAffiliationHistoryEntry> groupAffiliationHistoryEntry, m_groupAffiliationHistory) {
         bool hideGroup = isGroupHidden(groupAffiliationHistoryEntry->groupId);
         const double historyShapeDiameter = 0.1;
         Ogre::ColourValue historyColor = m_commonProperties->constant_color->getOgreColor();
         if(!groupAffiliationHistoryEntry->wasSinglePersonGroup || !m_single_person_groups_in_constant_color_property->getBool()) {
             historyColor = getColorFromId(groupAffiliationHistoryEntry->groupId);
         }
         historyColor.a = m_commonProperties->alpha->getFloat();
         if(groupAffiliationHistoryEntry->wasOccluded) historyColor.a *= m_occlusion_alpha_property->getFloat();
         if(hideGroup) historyColor.a = 0;
         if(!m_render_history_property->getBool()) historyColor.a = 0;
         groupAffiliationHistoryEntry->shape->setColor(historyColor);
         groupAffiliationHistoryEntry->shape->setScale(shapeQuaternion * Ogre::Vector3(historyShapeDiameter, historyShapeDiameter, 0.05));
     }
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::alpha, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::constant_color, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::getColorFromId(), isGroupHidden(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >::m_commonProperties, m_groupAffiliationHistory, m_occlusion_alpha_property, m_render_history_property, m_single_person_groups_in_constant_color_property, and shapeQuaternion().
Referenced by processMessage(), and stylesChanged().
Member Data Documentation
m_excluded_group_ids_property
rviz::StringProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_excluded_group_ids_property private
Referenced by onInitialize(), and stylesChanged().
m_excludedGroupIDs
set<group_id> spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_excludedGroupIDs private
Referenced by isGroupHidden(), and stylesChanged().
m_frameTransform
Ogre::Matrix4 spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_frameTransform private
Referenced by processMessage(), and updateGroupVisualStyles().
m_group_id_offset
rviz::FloatProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_group_id_offset private
Referenced by onInitialize(), and updateGroupVisualStyles().
m_groupAffiliationHistory
GroupAffiliationHistory spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_groupAffiliationHistory private
Referenced by processMessage(), reset(), stylesChanged(), and updateHistoryStyles().
m_groupAffiliationHistorySceneNode
boost::shared_ptr<Ogre::SceneNode> spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_groupAffiliationHistorySceneNode private
Referenced by onInitialize(), processMessage(), and update().
m_groupAffiliations
map<track_id, group_id> spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_groupAffiliations private
Referenced by processMessage(), and reset().
m_groupsSceneNode
boost::shared_ptr<Ogre::SceneNode> spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_groupsSceneNode private
Referenced by onInitialize(), and processMessage().
m_groupVisuals
vector<boost::shared_ptr<GroupVisual> > spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_groupVisuals private
Referenced by personVisualTypeChanged(), processMessage(), reset(), and stylesChanged().
m_hide_ids_of_single_person_groups_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_hide_ids_of_single_person_groups_property private
Referenced by onInitialize(), and updateGroupVisualStyles().
m_history_length_property
rviz::IntProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_history_length_property private
Referenced by onInitialize(), and stylesChanged().
m_included_group_ids_property
rviz::StringProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_included_group_ids_property private
Referenced by onInitialize(), and stylesChanged().
m_includedGroupIDs
set<group_id> spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_includedGroupIDs private
Referenced by isGroupHidden(), and stylesChanged().
m_occlusion_alpha_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_occlusion_alpha_property private
Referenced by onInitialize(), and updateHistoryStyles().
m_realFixedFrame
std::string spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_realFixedFrame private
Referenced by onInitialize(), processMessage(), and update().
m_render_history_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_render_history_property private
Referenced by onInitialize(), and updateHistoryStyles().
m_render_ids_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_render_ids_property private
Referenced by onInitialize(), and updateGroupVisualStyles().
m_render_intragroup_connections_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_render_intragroup_connections_property private
Referenced by onInitialize(), and updateGroupVisualStyles().
m_single_person_groups_in_constant_color_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_single_person_groups_in_constant_color_property private
Referenced by onInitialize(), updateGroupVisualStyles(), and updateHistoryStyles().
m_trackedPersonsCache
TrackedPersonsCache spencer_tracking_rviz_plugin::TrackedGroupsDisplay::m_trackedPersonsCache private
Referenced by onInitialize(), processMessage(), and reset().
The documentation for this class was generated from the following files:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/tracked_groups_display.h
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/tracked_groups_display.cpp