ROS Motion Planning: global_planner::RRTConnect Class Reference
global_planner::RRTConnect Class Reference
Class for objects that plan using the RRT Connect algorithm.
#include <rrt_connect.h>
Public Member Functions
RRTConnect (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
RRT implementation.
Public Member Functions inherited from global_planner::RRT
RRT (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
std::vector< Node > _convertClosedListToPath (const Node &boundary)
convert closed list to path
Protected Member Functions inherited from global_planner::RRT
Node _findNearestPoint (std::unordered_map< int, Node > list, const Node &node)
Regular the sample node by the nearest node in the sample list.
bool _isAnyObstacleInPath (const Node &n1, const Node &n2)
Check if there is any obstacle between the 2 nodes.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
std::unordered_map< int, Node > sample_list_f_
std::unordered_map< int, Node > sample_list_b_
Protected Attributes inherited from global_planner::RRT
const unsigned char * costs_
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the RRT Connect algorithm.
Constructor & Destructor Documentation
RRTConnect()
global_planner::RRTConnect::RRTConnect (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
sample_num andom sample points
max_dist max distance between sample points
nx pixel number in costmap x direction
ny pixel number in costmap y direction
sample_num andom sample points
max_dist max distance between sample points
   : RRT(nx, ny, resolution, sample_num, max_dist)
 {
 }
Member Function Documentation
_convertClosedListToPath()
std::vector< Node > global_planner::RRTConnect::_convertClosedListToPath (const Node & boundary) protected
convert closed list to path
Parameters
boundary connected node that the boudary of forward and backward
Returns
ector containing path nodes
 {
   if (sample_list_f_.find(start_.id_) == sample_list_.end())
     std::swap(sample_list_f_, sample_list_b_);
   std::vector<Node> path;
   // backward
   std::vector<Node> path_b;
   auto current = sample_list_b_.find(boundary.id_);
   while (current->second != goal_)
   {
     path_b.push_back(current->second);
     auto it = sample_list_b_.find(current->second.pid_);
     if (it != sample_list_b_.end())
       current = it;
     else
       return {};
   }
   path_b.push_back(goal_);
   // forward
   for (auto rit = path_b.rbegin(); rit != path_b.rend(); rit++)
     path.push_back(*rit);
   current = sample_list_f_.find(boundary.id_);
   while (current->second != start_)
   {
     auto it = sample_list_f_.find(current->second.pid_);
     if (it != sample_list_f_.end())
     {
       current = it;
     }
     else
       return {};
     path.push_back(current->second);
   }
   return path;
 }
References global_planner::RRT::goal_, Node::id_, global_planner::RRT::sample_list_, sample_list_b_, sample_list_f_, and global_planner::RRT::start_.
Referenced by plan().
plan()
bool global_planner::RRTConnect::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
RRT implementation.
RRT-Connect implementation.
Parameters
costs costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Parameters
global_costmap costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Reimplemented from global_planner::RRT.
 {
   sample_list_f_.clear();
   sample_list_b_.clear();
   // copy
   start_ = start, goal_ = goal;
   costs_ = global_costmap;
   sample_list_f_.insert(std::make_pair(start.id_, start));
   sample_list_b_.insert(std::make_pair(goal.id_, goal));
   expand.push_back(start);
   expand.push_back(goal);
   // main loop
   int iteration = 0;
   while (iteration < sample_num_)
   {
     // generate a random node in the map
     Node sample_node = _generateRandomNode();
     // obstacle
     if (global_costmap[sample_node.id_] >= lethal_cost_ * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id_) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_f_, sample_node);
     if (new_node.id_ == -1)
       continue;
     else
     {
       sample_list_f_.insert(std::make_pair(new_node.id_, new_node));
       expand.push_back(new_node);
       // backward exploring
       Node new_node_b = _findNearestPoint(sample_list_b_, new_node);
       if (new_node_b.id_ != -1)
       {
         sample_list_b_.insert(std::make_pair(new_node_b.id_, new_node_b));
         expand.push_back(new_node_b);
         // greedy extending
         while (true)
         {
           double dist_ = std::min(max_dist_, helper::dist(new_node, new_node_b));
           double theta = helper::angle(new_node_b, new_node);
           Node new_node_b2;
           new_node_b2.x_ = new_node_b.x_ + (int)(dist_ * cos(theta));
           new_node_b2.y_ = new_node_b.y_ + (int)(dist_ * sin(theta));
           new_node_b2.id_ = grid2Index(new_node_b2.x_, new_node_b2.y_);
           new_node_b2.pid_ = new_node_b.id_;
           new_node_b2.g_ = dist_ + new_node_b.g_;
           if (!_isAnyObstacleInPath(new_node_b, new_node_b2))
           {
             sample_list_b_.insert(std::make_pair(new_node_b2.id_, new_node_b2));
             expand.push_back(new_node_b2);
             new_node_b = new_node_b2;
           }
           else
             break;
           // connected -> goal found
           if (new_node_b == new_node)
           {
             path = _convertClosedListToPath(new_node_b);
             return true;
           }
         }
       }
     }
     // swap
     if (sample_list_b_.size() < sample_list_f_.size())
       std::swap(sample_list_f_, sample_list_b_);
     iteration++;
   }
   return false;
 }
References _convertClosedListToPath(), global_planner::RRT::_findNearestPoint(), global_planner::RRT::_generateRandomNode(), global_planner::RRT::_isAnyObstacleInPath(), helper::angle(), global_planner::RRT::costs_, helper::dist(), global_planner::GlobalPlanner::factor_, Node::g_, global_planner::RRT::goal_, global_planner::GlobalPlanner::grid2Index(), Node::id_, global_planner::GlobalPlanner::lethal_cost_, global_planner::RRT::max_dist_, Node::pid_, global_planner::RRT::sample_list_, sample_list_b_, sample_list_f_, global_planner::RRT::sample_num_, global_planner::RRT::start_, Node::x_, and Node::y_.
Member Data Documentation
sample_list_b_
std::unordered_map<int, Node> global_planner::RRTConnect::sample_list_b_ protected
Referenced by _convertClosedListToPath(), and plan().
sample_list_f_
std::unordered_map<int, Node> global_planner::RRTConnect::sample_list_f_ protected
Referenced by _convertClosedListToPath(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/sample_planner/include/rrt_connect.h
src/core/global_planner/sample_planner/src/rrt_connect.cpp