ROS Motion Planning: rpp_planner::RPPPlanner Class Reference
rpp_planner::RPPPlanner Class Reference
A class implementing a local planner using the RPP.
#include <rpp_planner.h>
Public Member Functions
RPPPlanner ()
Construct a new RPP planner object.
RPPPlanner (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Construct a new RPP planner object.
~RPPPlanner ()
Destroy the RPP planner object.
void initialize (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Initialization of the local planner.
bool setPlan (const std::vector< geometry_msgs::PoseStamped > &orig_global_plan)
Set the plan that the controller is following.
bool isGoalReached ()
Check if the goal pose has been achieved.
bool computeVelocityCommands (geometry_msgs::Twist &cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Protected Member Functions
double _dphi (geometry_msgs::PointStamped lookahead_pt, geometry_msgs::PoseStamped robot_pose_global)
calculate the relative angle between robot' yaw and relative lookahead vector
Private Member Functions
double _applyCurvatureConstraint (const double raw_linear_vel, const double curvature)
Applying curvature constraints to regularize the speed of robot turning.
double _applyObstacleConstraint (const double raw_linear_vel)
Applying obstacle constraints to regularize the speed of robot approaching obstacles.
double _applyApproachConstraint (const double raw_linear_vel, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > &prune_plan)
Applying approach constraints to regularize the speed of robot approaching final goal.
Private Member Functions inherited from local_planner::LocalPlanner
LocalPlanner ()
Construct a new Local Planner object.
~LocalPlanner ()
Destroy the Local Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setBaseFrame (std::string base_frame)
Set or reset frame name.
void setMapFrame (std::string map_frame)
double regularizeAngle (double angle)
Regularize angle to [-pi, pi].
Eigen::Vector3d getEulerAngles (geometry_msgs::PoseStamped &ps)
Get the Euler Angles from PoseStamped.
bool shouldRotateToGoal (const geometry_msgs::PoseStamped &cur, const geometry_msgs::PoseStamped &goal)
Whether to reach the target pose through rotation operation.
bool shouldRotateToPath (double angle_to_path, double tolerance=0.0)
Whether to correct the tracking path with rotation operation.
double linearRegularization (nav_msgs::Odometry &base_odometry, double v_d)
linear velocity regularization
double angularRegularization (nav_msgs::Odometry &base_odometry, double w_d)
angular velocity regularization
void transformPose (tf2_ros::Buffer *tf, const std::string out_frame, const geometry_msgs::PoseStamped &in_pose, geometry_msgs::PoseStamped &out_pose) const
Tranform from in_pose to out_pose with out frame using tf.
bool worldToMap (double wx, double wy, int &mx, int &my)
Tranform from world map(x, y) to costmap(x, y)
std::vector< geometry_msgs::PoseStamped > prune (const geometry_msgs::PoseStamped robot_pose_global)
Prune the path, removing the waypoints that the robot has already passed and distant waypoints.
double getLookAheadDistance (double vt)
Calculate the look-ahead distance with current speed dynamically.
void getLookAheadPoint (double lookahead_dist, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > &prune_plan, geometry_msgs::PointStamped &pt, double &theta, double &kappa)
find the point on the path that is exactly the lookahead distance away from the robot
Private Attributes
bool initialized_
bool goal_reached_
tf2_ros::Buffer * tf_
double d_t_
double regulated_min_radius_
double inflation_cost_factor_
double scaling_dist_
double scaling_gain_
double approach_dist_
double approach_min_v_
ros::Publisher target_pt_pub_
ros::Publisher current_pose_pub_
double goal_x_
double goal_y_
Eigen::Vector3d goal_rpy_
Private Attributes inherited from local_planner::LocalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double origin_x_
double origin_y_
double resolution_
double convert_offset_
double factor_
double max_v_
double min_v_
double max_v_inc_
double max_w_
double min_w_
double max_w_inc_
double goal_dist_tol_
double rotate_tol_
std::string base_frame_
std::string map_frame_
std::string odom_frame_
base_local_planner::OdometryHelperRos * odom_helper_
costmap_2d::Costmap2DROS * costmap_ros_
std::vector< geometry_msgs::PoseStamped > global_plan_
double lookahead_time_
double min_lookahead_dist_
double max_lookahead_dist_
Detailed Description
A class implementing a local planner using the RPP.
Constructor & Destructor Documentation
RPPPlanner() [1/2]
rpp_planner::RPPPlanner::RPPPlanner ()
Construct a new RPP planner object.
                        : initialized_(false), tf_(nullptr), goal_reached_(false)  //, costmap_ros_(nullptr)
 {
 }
RPPPlanner() [2/2]
rpp_planner::RPPPlanner::RPPPlanner (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Construct a new RPP planner object.
                                                                                              : RPPPlanner()
 {
   initialize(name, tf, costmap_ros);
 }
References initialize(), and rviz_generate::name.
~RPPPlanner()
rpp_planner::RPPPlanner::~RPPPlanner ()
Destroy the RPP planner object.
 {
 }
Member Function Documentation
_applyApproachConstraint()
double rpp_planner::RPPPlanner::_applyApproachConstraint (const double raw_linear_vel, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > & prune_plan) private
Applying approach constraints to regularize the speed of robot approaching final goal.
Parameters
raw_linear_vel the raw linear velocity of robot
robot_pose_global the robot's pose [global]
prune_plan the pruned plan
Returns
reg_vel the regulated velocity
 {
   double remain_dist = 0.0;
   for (size_t i = 0; i < prune_plan.size() - 1; i++)
     remain_dist += helper::dist(prune_plan[i], prune_plan[i + 1]);
   double s = remain_dist < approach_dist_ ? helper::dist(prune_plan.back(), robot_pose_global) / approach_dist_ : 1.0;
   return std::min(raw_linear_vel, std::max(approach_min_v_, raw_linear_vel * s));
 }
References approach_dist_, approach_min_v_, and helper::dist().
Referenced by computeVelocityCommands().
_applyCurvatureConstraint()
double rpp_planner::RPPPlanner::_applyCurvatureConstraint (const double raw_linear_vel, const double curvature) private
Applying curvature constraints to regularize the speed of robot turning.
Parameters
raw_linear_vel the raw linear velocity of robot
curvature the tracking curvature
Returns
reg_vel the regulated velocity
 {
   const double radius = std::fabs(1.0 / curvature);
   if (radius < regulated_min_radius_)
     return raw_linear_vel * (radius / regulated_min_radius_);
   else
     return raw_linear_vel;
 }
References regulated_min_radius_.
Referenced by computeVelocityCommands().
_applyObstacleConstraint()
double rpp_planner::RPPPlanner::_applyObstacleConstraint (const double raw_linear_vel) private
Applying obstacle constraints to regularize the speed of robot approaching obstacles.
Parameters
raw_linear_vel the raw linear velocity of robot
Returns
reg_vel the regulated velocity
 {
   int size_x = costmap_ros_->getCostmap()->getSizeInCellsX() / 2;
   int size_y = costmap_ros_->getCostmap()->getSizeInCellsY() / 2;
   double robot_cost = static_cast<double>(costmap_ros_->getCostmap()->getCost(size_x, size_y));
   if (robot_cost != static_cast<double>(costmap_2d::FREE_SPACE) &&
       robot_cost != static_cast<double>(costmap_2d::NO_INFORMATION))
   {
     const double& inscribed_radius = costmap_ros_->getLayeredCostmap()->getInscribedRadius();
     // calculate the minimum distance to obstacles heuristically
     const double obs_dist =
         inscribed_radius -
         (log(robot_cost) - log(static_cast<double>(costmap_2d::INSCRIBED_INFLATED_OBSTACLE))) / inflation_cost_factor_;
     if (obs_dist < scaling_dist_)
       return raw_linear_vel * scaling_gain_ * obs_dist / scaling_dist_;
   }
   return raw_linear_vel;
 }
References local_planner::LocalPlanner::costmap_ros_, inflation_cost_factor_, scaling_dist_, and scaling_gain_.
Referenced by computeVelocityCommands().
_dphi()
double rpp_planner::RPPPlanner::_dphi (geometry_msgs::PointStamped lookahead_pt, geometry_msgs::PoseStamped robot_pose_global) protected
calculate the relative angle between robot' yaw and relative lookahead vector
Parameters
lookahead_pt the lookahead pose [global]
robot_pose_global the robot's pose [global]
Returns
dphi the lookahead angle - robot's yaw
 {
   return atan2(lookahead_pt.point.y - robot_pose_global.pose.position.y,
                lookahead_pt.point.x - robot_pose_global.pose.position.x) -
          tf2::getYaw(robot_pose_global.pose.orientation);
 }
Referenced by computeVelocityCommands().
computeVelocityCommands()
bool rpp_planner::RPPPlanner::computeVelocityCommands (geometry_msgs::Twist & cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Parameters
cmd_vel will be filled with the velocity command to be passed to the robot base
Returns
true if a valid trajectory was found, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("RPP planner has not been initialized");
     return false;
   }
   // odometry observation - getting robot velocities in robot frame
   nav_msgs::Odometry base_odom;
   odom_helper_->getOdom(base_odom);
   // get robot position in global frame
   geometry_msgs::PoseStamped robot_pose_odom, robot_pose_map;
   costmap_ros_->getRobotPose(robot_pose_odom);
   transformPose(tf_, map_frame_, robot_pose_odom, robot_pose_map);
   // transform global plan to robot frame
   std::vector<geometry_msgs::PoseStamped> prune_plan = prune(robot_pose_map);
   // calculate look-ahead distance
   double vt = std::hypot(base_odom.twist.twist.linear.x, base_odom.twist.twist.linear.y);
   double L = getLookAheadDistance(vt);
   // get the particular point on the path at the lookahead distance
   geometry_msgs::PointStamped lookahead_pt;
   double theta, kappa;
   getLookAheadPoint(L, robot_pose_map, prune_plan, lookahead_pt, theta, kappa);
   // get the tracking curvature with goalahead point
   double lookahead_k = 2 * sin(_dphi(lookahead_pt, robot_pose_map)) / L;
   // calculate commands
   if (shouldRotateToGoal(robot_pose_map, global_plan_.back()))
   {
     double e_theta = regularizeAngle(goal_rpy_.z() - tf2::getYaw(robot_pose_map.pose.orientation));
     // orientation reached
     if (!shouldRotateToPath(std::fabs(e_theta)))
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = 0.0;
       goal_reached_ = true;
     }
     // orientation not reached
     else
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = angularRegularization(base_odom, e_theta / d_t_);
     }
   }
   else
   {
     double e_theta = regularizeAngle(_dphi(lookahead_pt, robot_pose_map));
     // large angle, turn first
     if (shouldRotateToPath(std::fabs(e_theta), M_PI_2))
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = angularRegularization(base_odom, e_theta / d_t_);
     }
     // apply constraints
     else
     {
       double curv_vel = _applyCurvatureConstraint(max_v_, lookahead_k);
       double cost_vel = _applyObstacleConstraint(max_v_);
       double v_d = std::min(curv_vel, cost_vel);
       v_d = _applyApproachConstraint(v_d, robot_pose_map, prune_plan);
       cmd_vel.linear.x = linearRegularization(base_odom, v_d);
       cmd_vel.angular.z = angularRegularization(base_odom, v_d * lookahead_k);
     }
   }
   // publish lookahead pose
   target_pt_pub_.publish(lookahead_pt);
   // publish robot pose
   current_pose_pub_.publish(robot_pose_map);
   return true;
 }
References _applyApproachConstraint(), _applyCurvatureConstraint(), _applyObstacleConstraint(), _dphi(), local_planner::LocalPlanner::angularRegularization(), local_planner::LocalPlanner::costmap_ros_, current_pose_pub_, d_t_, local_planner::LocalPlanner::getLookAheadDistance(), local_planner::LocalPlanner::getLookAheadPoint(), local_planner::LocalPlanner::global_plan_, goal_reached_, goal_rpy_, initialized_, local_planner::LocalPlanner::linearRegularization(), local_planner::LocalPlanner::map_frame_, local_planner::LocalPlanner::max_v_, local_planner::LocalPlanner::odom_helper_, local_planner::LocalPlanner::prune(), local_planner::LocalPlanner::regularizeAngle(), local_planner::LocalPlanner::shouldRotateToGoal(), local_planner::LocalPlanner::shouldRotateToPath(), target_pt_pub_, tf_, and local_planner::LocalPlanner::transformPose().
initialize()
void rpp_planner::RPPPlanner::initialize (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Initialization of the local planner.
Parameters
name the name to give this instance of the trajectory planner
tf a pointer to a transform listener
costmap_ros the cost map to use for assigning costs to trajectories
 {
   if (!initialized_)
   {
     initialized_ = true;
     tf_ = tf;
     costmap_ros_ = costmap_ros;
     costmap_2d::Costmap2D* costmap = costmap_ros_->getCostmap();
     // set costmap properties
     setSize(costmap->getSizeInCellsX(), costmap->getSizeInCellsY());
     setOrigin(costmap->getOriginX(), costmap->getOriginY());
     setResolution(costmap->getResolution());
     ros::NodeHandle nh = ros::NodeHandle("~/" + name);
     // base
     nh.param("goal_dist_tolerance", goal_dist_tol_, 0.2);
     nh.param("rotate_tolerance", rotate_tol_, 0.5);
     nh.param("convert_offset", convert_offset_, 0.0);
     nh.param("base_frame", base_frame_, base_frame_);
     nh.param("map_frame", map_frame_, map_frame_);
     // lookahead
     nh.param("lookahead_time", lookahead_time_, 1.5);
     nh.param("min_lookahead_dist", min_lookahead_dist_, 0.3);
     nh.param("max_lookahead_dist", max_lookahead_dist_, 0.9);
     // linear velocity
     nh.param("max_v", max_v_, 0.5);
     nh.param("min_v", min_v_, 0.0);
     nh.param("max_v_inc", max_v_inc_, 0.5);
     // angular velocity
     nh.param("max_w", max_w_, 1.57);
     nh.param("min_w", min_w_, 0.0);
     nh.param("max_w_inc", max_w_inc_, 1.57);
     // constriants
     nh.param("regulated_min_radius", regulated_min_radius_, 0.9);
     nh.param("inflation_cost_factor", inflation_cost_factor_, 3.0);
     nh.param("scaling_dist", scaling_dist_, 0.6);
     nh.param("scaling_gain", scaling_gain_, 1.0);
     nh.param("approach_dist", approach_dist_, 0.8);
     nh.param("approach_min_v", approach_min_v_, 0.1);
     double controller_freqency;
     nh.param("/move_base/controller_frequency", controller_freqency, 10.0);
     d_t_ = 1 / controller_freqency;
     odom_helper_ = new base_local_planner::OdometryHelperRos("/odom");
     target_pt_pub_ = nh.advertise<geometry_msgs::PointStamped>("/target_point", 10);
     current_pose_pub_ = nh.advertise<geometry_msgs::PoseStamped>("/current_pose", 10);
     ROS_INFO("RPP planner initialized!");
   }
   else
     ROS_WARN("RPP planner has already been initialized.");
 }
References approach_dist_, approach_min_v_, local_planner::LocalPlanner::base_frame_, local_planner::LocalPlanner::convert_offset_, local_planner::LocalPlanner::costmap_ros_, current_pose_pub_, d_t_, local_planner::LocalPlanner::goal_dist_tol_, inflation_cost_factor_, initialized_, local_planner::LocalPlanner::lookahead_time_, local_planner::LocalPlanner::map_frame_, local_planner::LocalPlanner::max_lookahead_dist_, local_planner::LocalPlanner::max_v_, local_planner::LocalPlanner::max_v_inc_, local_planner::LocalPlanner::max_w_, local_planner::LocalPlanner::max_w_inc_, local_planner::LocalPlanner::min_lookahead_dist_, local_planner::LocalPlanner::min_v_, local_planner::LocalPlanner::min_w_, rviz_generate::name, local_planner::LocalPlanner::odom_helper_, regulated_min_radius_, local_planner::LocalPlanner::rotate_tol_, scaling_dist_, scaling_gain_, local_planner::LocalPlanner::setOrigin(), local_planner::LocalPlanner::setResolution(), local_planner::LocalPlanner::setSize(), target_pt_pub_, and tf_.
Referenced by RPPPlanner().
isGoalReached()
bool rpp_planner::RPPPlanner::isGoalReached ()
Check if the goal pose has been achieved.
Returns
True if achieved, false otherwise
 {
   if (!initialized_)
   {
     ROS_ERROR("RPP planner has not been initialized");
     return false;
   }
   if (goal_reached_)
   {
     ROS_INFO("GOAL Reached!");
     return true;
   }
   return false;
 }
References goal_reached_, and initialized_.
setPlan()
bool rpp_planner::RPPPlanner::setPlan (const std::vector< geometry_msgs::PoseStamped > & orig_global_plan)
Set the plan that the controller is following.
Parameters
orig_global_plan the plan to pass to the controller
Returns
true if the plan was updated successfully, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   ROS_INFO("Got new plan");
   // set new plan
   global_plan_.clear();
   global_plan_ = orig_global_plan;
   // reset plan parameters
   if (goal_x_ != global_plan_.back().pose.position.x || goal_y_ != global_plan_.back().pose.position.y)
   {
     goal_x_ = global_plan_.back().pose.position.x;
     goal_y_ = global_plan_.back().pose.position.y;
     goal_rpy_ = getEulerAngles(global_plan_.back());
     goal_reached_ = false;
   }
   return true;
 }
References local_planner::LocalPlanner::getEulerAngles(), local_planner::LocalPlanner::global_plan_, goal_reached_, goal_rpy_, goal_x_, goal_y_, and initialized_.
Member Data Documentation
approach_dist_
double rpp_planner::RPPPlanner::approach_dist_ private
Referenced by _applyApproachConstraint(), and initialize().
approach_min_v_
double rpp_planner::RPPPlanner::approach_min_v_ private
Referenced by _applyApproachConstraint(), and initialize().
current_pose_pub_
ros::Publisher rpp_planner::RPPPlanner::current_pose_pub_ private
Referenced by computeVelocityCommands(), and initialize().
d_t_
double rpp_planner::RPPPlanner::d_t_ private
Referenced by computeVelocityCommands(), and initialize().
goal_reached_
bool rpp_planner::RPPPlanner::goal_reached_ private
Referenced by computeVelocityCommands(), isGoalReached(), and setPlan().
goal_rpy_
Eigen::Vector3d rpp_planner::RPPPlanner::goal_rpy_ private
Referenced by computeVelocityCommands(), and setPlan().
goal_x_
double rpp_planner::RPPPlanner::goal_x_ private
Referenced by setPlan().
goal_y_
double rpp_planner::RPPPlanner::goal_y_ private
Referenced by setPlan().
inflation_cost_factor_
double rpp_planner::RPPPlanner::inflation_cost_factor_ private
Referenced by _applyObstacleConstraint(), and initialize().
initialized_
bool rpp_planner::RPPPlanner::initialized_ private
Referenced by computeVelocityCommands(), initialize(), isGoalReached(), and setPlan().
regulated_min_radius_
double rpp_planner::RPPPlanner::regulated_min_radius_ private
Referenced by _applyCurvatureConstraint(), and initialize().
scaling_dist_
double rpp_planner::RPPPlanner::scaling_dist_ private
Referenced by _applyObstacleConstraint(), and initialize().
scaling_gain_
double rpp_planner::RPPPlanner::scaling_gain_ private
Referenced by _applyObstacleConstraint(), and initialize().
target_pt_pub_
ros::Publisher rpp_planner::RPPPlanner::target_pt_pub_ private
Referenced by computeVelocityCommands(), and initialize().
tf_
tf2_ros::Buffer* rpp_planner::RPPPlanner::tf_ private
Referenced by computeVelocityCommands(), and initialize().
The documentation for this class was generated from the following files:
src/core/local_planner/rpp_planner/include/rpp_planner.h
src/core/local_planner/rpp_planner/src/rpp_planner.cpp