ROS Motion Planning: RVO::Vector2 Class Reference
RVO::Vector2 Class Reference
Defines a two-dimensional vector.
#include <Vector2.h>
Public Member Functions
Vector2 ()
Constructs and initializes a two-dimensional vector instance to (0.0, 0.0).
Vector2 (float x, float y)
Constructs and initializes a two-dimensional vector from the specified xy-coordinates.
float x () const
Returns the x-coordinate of this two-dimensional vector.
float y () const
Returns the y-coordinate of this two-dimensional vector.
Vector2 operator- () const
Computes the negation of this two-dimensional vector.
float operator* (const Vector2 &vector) const
Computes the dot product of this two-dimensional vector with the specified two-dimensional vector.
Vector2 operator* (float scalar) const
Computes the scalar multiplication of this two-dimensional vector with the specified scalar value.
Vector2 operator/ (float scalar) const
Computes the scalar division of this two-dimensional vector with the specified scalar value.
Vector2 operator+ (const Vector2 &vector) const
Computes the vector sum of this two-dimensional vector with the specified two-dimensional vector.
Vector2 operator- (const Vector2 &vector) const
Computes the vector difference of this two-dimensional vector with the specified two-dimensional vector.
bool operator== (const Vector2 &vector) const
Tests this two-dimensional vector for equality with the specified two-dimensional vector.
bool operator!= (const Vector2 &vector) const
Tests this two-dimensional vector for inequality with the specified two-dimensional vector.
Vector2 & operator*= (float scalar)
Sets the value of this two-dimensional vector to the scalar multiplication of itself with the specified scalar value.
Vector2 & operator/= (float scalar)
Sets the value of this two-dimensional vector to the scalar division of itself with the specified scalar value.
Vector2 & operator+= (const Vector2 &vector)
Sets the value of this two-dimensional vector to the vector sum of itself with the specified two-dimensional vector.
Vector2 & operator-= (const Vector2 &vector)
Sets the value of this two-dimensional vector to the vector difference of itself with the specified two-dimensional vector.
Private Attributes
float x_
float y_
Related Functions
(Note that these are not member functions.)
Vector2 operator* (float scalar, const Vector2 &vector)
Computes the scalar multiplication of the specified two-dimensional vector with the specified scalar value.
std::ostream & operator<< (std::ostream &stream, const Vector2 &vector)
Inserts the specified two-dimensional vector into the specified output stream.
float abs (const Vector2 &vector)
Computes the length of a specified two-dimensional vector.
float absSq (const Vector2 &vector)
Computes the squared length of a specified two-dimensional vector.
float det (const Vector2 &vector1, const Vector2 &vector2)
Computes the determinant of a two-dimensional square matrix with rows consisting of the specified two-dimensional vectors.
Vector2 normalize (const Vector2 &vector)
Computes the normalization of the specified two-dimensional vector.
Detailed Description
Defines a two-dimensional vector.
Constructor & Destructor Documentation
Vector2() [1/2]
RVO::Vector2::Vector2 ()
Constructs and initializes a two-dimensional vector instance to (0.0, 0.0).
 : x_(0.0F), y_(0.0F) {}
Referenced by operator*(), operator+(), operator-(), and operator/().
Vector2() [2/2]
RVO::Vector2::Vector2 (float x, float y)
Constructs and initializes a two-dimensional vector from the specified xy-coordinates.
Parameters
[in] x The x-coordinate of the two-dimensional vector.
[in] y The y-coordinate of the two-dimensional vector.
 : x_(x), y_(y) {}
Member Function Documentation
operator!=()
bool RVO::Vector2::operator!= (const Vector2 & vector) const
Tests this two-dimensional vector for inequality with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which to test for inequality.
Returns
True if the two-dimensional vectors are not equal.
{
   return x_ != vector.x_ || y_ != vector.y_;
 }
References x_, and y_.
operator*() [1/2]
float RVO::Vector2::operator* (const Vector2 & vector) const
Computes the dot product of this two-dimensional vector with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which the dot product should be computed.
Returns
The dot product of this two-dimensional vector with a specified two-dimensional vector.
{
   return x_ * vector.x_ + y_ * vector.y_;
 }
References x_, and y_.
operator*() [2/2]
Vector2 RVO::Vector2::operator* (float scalar) const
Computes the scalar multiplication of this two-dimensional vector with the specified scalar value.
Parameters
[in] scalar The scalar value with which the scalar multiplication should be computed.
Returns
The scalar multiplication of this two-dimensional vector with a specified scalar value.
{
   return Vector2(x_ * scalar, y_ * scalar);
 }
References Vector2(), x_, and y_.
operator*=()
Vector2 & RVO::Vector2::operator*= (float scalar)
Sets the value of this two-dimensional vector to the scalar multiplication of itself with the specified scalar value.
Parameters
[in] scalar The scalar value with which the scalar multiplication should be computed.
Returns
A reference to this two-dimensional vector.
{
   x_ *= scalar;
   y_ *= scalar;
   return *this;
 }
References x_, and y_.
operator+()
Vector2 RVO::Vector2::operator+ (const Vector2 & vector) const
Computes the vector sum of this two-dimensional vector with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which the vector sum should be computed.
Returns
The vector sum of this two-dimensional vector with a specified two-dimensional vector.
{
   return Vector2(x_ + vector.x_, y_ + vector.y_);
 }
References Vector2(), x_, and y_.
operator+=()
Vector2 & RVO::Vector2::operator+= (const Vector2 & vector)
Sets the value of this two-dimensional vector to the vector sum of itself with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which the vector sum should be computed.
Returns
A reference to this two-dimensional vector.
{
   x_ += vector.x_;
   y_ += vector.y_;
   return *this;
 }
References x_, and y_.
operator-() [1/2]
Vector2 RVO::Vector2::operator- () const
Computes the negation of this two-dimensional vector.
Returns
The negation of this two-dimensional vector.
 { return Vector2(-x_, -y_); }
References Vector2(), x_, and y_.
operator-() [2/2]
Vector2 RVO::Vector2::operator- (const Vector2 & vector) const
Computes the vector difference of this two-dimensional vector with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which the vector difference should be computed.
Returns
The vector difference of this two-dimensional vector with a specified two-dimensional vector.
{
   return Vector2(x_ - vector.x_, y_ - vector.y_);
 }
References Vector2(), x_, and y_.
operator-=()
Vector2 & RVO::Vector2::operator-= (const Vector2 & vector)
Sets the value of this two-dimensional vector to the vector difference of itself with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which the vector difference should be computed.
Returns
A reference to this two-dimensional vector.
{
   x_ -= vector.x_;
   y_ -= vector.y_;
   return *this;
 }
References x_, and y_.
operator/()
Vector2 RVO::Vector2::operator/ (float scalar) const
Computes the scalar division of this two-dimensional vector with the specified scalar value.
Parameters
[in] scalar The scalar value with which the scalar division should be computed.
Returns
The scalar division of this two-dimensional vector with a specified scalar value.
{
   const float invScalar = 1.0F / scalar;
   return Vector2(x_ * invScalar, y_ * invScalar);
 }
References Vector2(), x_, and y_.
operator/=()
Vector2 & RVO::Vector2::operator/= (float scalar)
Sets the value of this two-dimensional vector to the scalar division of itself with the specified scalar value.
Parameters
[in] scalar The scalar value with which the scalar division should be computed.
Returns
A reference to this two-dimensional vector.
{
   const float invScalar = 1.0F / scalar;
   x_ *= invScalar;
   y_ *= invScalar;
   return *this;
 }
References x_, and y_.
operator==()
bool RVO::Vector2::operator== (const Vector2 & vector) const
Tests this two-dimensional vector for equality with the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector with which to test for equality.
Returns
True if the two-dimensional vectors are equal.
{
   return x_ == vector.x_ && y_ == vector.y_;
 }
References x_, and y_.
x()
float RVO::Vector2::x () const inline
Returns the x-coordinate of this two-dimensional vector.
Returns
The x-coordinate of the two-dimensional vector.
 { return x_; }
References x_.
Referenced by RVO::Agent::computeNewVelocity(), orca_planner::OrcaPlanner::computeVelocityCommands(), RVO::det(), RVO::operator*(), RVO::operator<<(), RVO::KdTree::queryAgentTreeRecursive(), and orca_planner::OrcaPlanner::setPlan().
y()
float RVO::Vector2::y () const inline
Returns the y-coordinate of this two-dimensional vector.
Returns
The y-coordinate of the two-dimensional vector.
 { return y_; }
References y_.
Referenced by RVO::Agent::computeNewVelocity(), orca_planner::OrcaPlanner::computeVelocityCommands(), RVO::det(), RVO::operator*(), RVO::operator<<(), RVO::KdTree::queryAgentTreeRecursive(), and orca_planner::OrcaPlanner::setPlan().
Friends And Related Function Documentation
abs()
float abs (const Vector2 & vector) related
Computes the length of a specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector whose length is to be computed.
Returns
The length of the two-dimensional vector.
 { return std::sqrt(vector * vector); }
absSq()
float absSq (const Vector2 & vector) related
Computes the squared length of a specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector whose squared length is to be computed.
Returns
The squared length of the two-dimensional vector.
 { return vector * vector; }
det()
float det (const Vector2 & vector1, const Vector2 & vector2) related
Computes the determinant of a two-dimensional square matrix with rows consisting of the specified two-dimensional vectors.
Parameters
[in] vector1 The top row of the two-dimensional square matrix.
[in] vector2 The bottom row of the two-dimensional square matrix.
Returns
The determinant of the two-dimensional square matrix.
{
   return vector1.x() * vector2.y() - vector1.y() * vector2.x();
 }
normalize()
Vector2 normalize (const Vector2 & vector) related
Computes the normalization of the specified two-dimensional vector.
Parameters
[in] vector The two-dimensional vector whose normalization is to be computed.
Returns
The normalization of the two-dimensional vector.
 { return vector / abs(vector); }
operator*()
Vector2 operator* (float scalar, const Vector2 & vector) related
Computes the scalar multiplication of the specified two-dimensional vector with the specified scalar value.
Parameters
[in] scalar The scalar value with which the scalar multiplication should be computed.
[in] vector The two-dimensional vector with which the scalar multiplication should be computed.
Returns
The scalar multiplication of the two-dimensional vector with the scalar value.
{
   return Vector2(scalar * vector.x(), scalar * vector.y());
 }
operator<<()
std::ostream & operator<< (std::ostream & stream, const Vector2 & vector) related
Inserts the specified two-dimensional vector into the specified output stream.
Parameters
[in,out] stream The output stream into which the two-dimensional vector should be inserted.
[in] vector The two-dimensional vector which to insert into the output stream.
Returns
A reference to the output stream.
{
   stream << "(" << vector.x() << "," << vector.y() << ")";
   return stream;
 }
Member Data Documentation
x_
float RVO::Vector2::x_ private
Referenced by operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), and x().
y_
float RVO::Vector2::y_ private
Referenced by operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), and y().
The documentation for this class was generated from the following files:
src/core/local_planner/orca_planner/include/RVO/Vector2.h
src/core/local_planner/orca_planner/include/RVO/Vector2.cc