ROS Motion Planning: global_planner::VoronoiPlanner Class Reference
global_planner::VoronoiPlanner Class Reference
Class for objects that plan using the Voronoi-based planning algorithm.
#include <voronoi.h>
Public Member Functions
VoronoiPlanner (int nx, int ny, double resolution, double circumscribed_radius)
Construct a new Voronoi-based planning object.
~VoronoiPlanner ()
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Voronoi-based planning implementation.
bool plan (const DynamicVoronoi &voronoi, const Node &start, const Node &goal, std::vector< Node > &path)
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
bool searchPathWithVoronoi (const Node &start, const Node &goal, std::vector< Node > &path, Node *v_goal=nullptr)
search the shortest path from start to VD, or search the shortest path in VD
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Private Attributes
VoronoiData ** voronoi_diagram_
double circumscribed_radius_
Additional Inherited Members
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the Voronoi-based planning algorithm.
Constructor & Destructor Documentation
VoronoiPlanner()
global_planner::VoronoiPlanner::VoronoiPlanner (int nx, int ny, double resolution, double circumscribed_radius)
Construct a new Voronoi-based planning object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
circumscribed_radius the circumscribed radius of robot
   : GlobalPlanner(nx, ny, resolution), circumscribed_radius_(circumscribed_radius)
 {
   voronoi_diagram_ = new VoronoiData*[nx_];
   for (unsigned int i = 0; i < nx_; i++)
     voronoi_diagram_[i] = new VoronoiData[ny_];
 }
References global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, and voronoi_diagram_.
~VoronoiPlanner()
global_planner::VoronoiPlanner::~VoronoiPlanner ()
 {
   for (unsigned int i = 0; i < nx_; i++)
     delete[] voronoi_diagram_[i];
   delete[] voronoi_diagram_;
 }
References global_planner::GlobalPlanner::nx_, and voronoi_diagram_.
Member Function Documentation
plan() [1/2]
bool global_planner::VoronoiPlanner::plan (const DynamicVoronoi & voronoi, const Node & start, const Node & goal, std::vector< Node > & path)
 {
   // update voronoi diagram
   for (unsigned int j = 0; j < ny_; j++)
   {
     for (unsigned int i = 0; i < nx_; i++)
     {
       voronoi_diagram_[i][j].dist = voronoi.getDistance(i, j) * resolution_;
       voronoi_diagram_[i][j].is_voronoi = voronoi.isVoronoi(i, j);
     }
   }
   // clear vector
   path.clear();
   // start/goal to Voronoi Diagram, shortest path in Voronoi Diagram
   std::vector<Node> path_s, path_g, path_v;
   // start/goal point in Voronoi Diagram
   Node v_start, v_goal;
   if (!searchPathWithVoronoi(start, goal, path_s, &v_start))
     return false;
   if (!searchPathWithVoronoi(goal, start, path_g, &v_goal))
     return false;
   std::reverse(path_g.begin(), path_g.end());
   if (!searchPathWithVoronoi(v_start, v_goal, path_v))
     return false;
   path_g.insert(path_g.end(), path_v.begin(), path_v.end());
   path_g.insert(path_g.end(), path_s.begin(), path_s.end());
   path = path_g;
   return true;
 }
References global_planner::VoronoiData::dist, DynamicVoronoi::getDistance(), global_planner::VoronoiData::is_voronoi, DynamicVoronoi::isVoronoi(), global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, global_planner::GlobalPlanner::resolution_, searchPathWithVoronoi(), and voronoi_diagram_.
plan() [2/2]
bool global_planner::VoronoiPlanner::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
Voronoi-based planning implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   return true;
 }
searchPathWithVoronoi()
bool global_planner::VoronoiPlanner::searchPathWithVoronoi (const Node & start, const Node & goal, std::vector< Node > & path, Node * v_goal = nullptr) protected
search the shortest path from start to VD, or search the shortest path in VD
Parameters
start start node
goal goal node
v_goal the voronoi node in VD which is closest to start node
path shortest path from start to VD
Returns
true if path found, else false
 {
   path.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start);
   // get all possible motions
   const std::vector<Node> motion = Node::getMotion();
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id_) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id_, current));
     // goal found
     if ((current == goal) || (v_goal == nullptr ? false : voronoi_diagram_[current.x_][current.y_].is_voronoi))
     {
       path = _convertClosedListToPath(closed_list, start, current);
       if (v_goal != nullptr)
       {
         v_goal->x_ = current.x_;
         v_goal->y_ = current.y_;
         v_goal->id_ = current.id_;
       }
       return true;
     }
     // explore neighbor of current node
     for (const auto& m : motion)
     {
       Node node_new = current + m;
       // current node do not exist in closed list
       if (closed_list.find(node_new.id_) != closed_list.end())
         continue;
       // explore a new node
       node_new.id_ = grid2Index(node_new.x_, node_new.y_);
       node_new.pid_ = current.id_;
       // next node hit the boundary or obstacle
       if ((node_new.id_ < 0) || (node_new.id_ >= ns_) ||
           (voronoi_diagram_[node_new.x_][node_new.y_].dist < circumscribed_radius_))
         continue;
       // search in VD
       if ((v_goal == nullptr) && (!voronoi_diagram_[node_new.x_][node_new.y_].is_voronoi))
         continue;
       node_new.h_ = std::hypot(node_new.x_ - goal.x_, node_new.y_ - goal.y_);
       open_list.push(node_new);
     }
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), circumscribed_radius_, global_planner::VoronoiData::dist, Node::getMotion(), global_planner::GlobalPlanner::grid2Index(), Node::h_, Node::id_, global_planner::VoronoiData::is_voronoi, global_planner::GlobalPlanner::ns_, Node::pid_, voronoi_diagram_, Node::x_, and Node::y_.
Referenced by plan().
Member Data Documentation
circumscribed_radius_
double global_planner::VoronoiPlanner::circumscribed_radius_ private
Referenced by searchPathWithVoronoi().
voronoi_diagram_
VoronoiData** global_planner::VoronoiPlanner::voronoi_diagram_ private
Referenced by plan(), searchPathWithVoronoi(), VoronoiPlanner(), and ~VoronoiPlanner().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/voronoi.h
src/core/global_planner/graph_planner/src/voronoi.cpp