ROS Motion Planning: spencer_tracking_rviz_plugin::DetectedPersonsDisplay Class Reference
spencer_tracking_rviz_plugin::DetectedPersonsDisplay Class Reference
#include <detected_persons_display.h>
Public Member Functions
DetectedPersonsDisplay ()
virtual ~DetectedPersonsDisplay ()
virtual void onInitialize ()
Overrides base class method.
Public Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >
PersonDisplayCommon ()
virtual ~PersonDisplayCommon ()
Public Member Functions inherited from spencer_tracking_rviz_plugin::StylesChangedSubscriber
virtual ~StylesChangedSubscriber ()
virtual void stylesChanged ()
Protected Member Functions
virtual void reset ()
virtual rviz::DisplayContext * getContext ()
Must be implemented by derived classes because MOC doesn't work in templates.
Protected Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >
bool preprocessMessage (const typename spencer_tracking_msgs::DetectedPersons ::ConstPtr &msg)
Common message processing. This method needs to be called by derived classes.
void createPersonVisualIfRequired (Ogre::SceneNode *sceneNode, boost::shared_ptr< PersonVisual > &personVisual)
Create a visual representation of the person itself, if not set yet.
void applyCommonStyles (boost::shared_ptr< PersonVisual > &personVisual)
Applies common styles which apply to person visuals, such as line width etc.
Ogre::Vector3 getVelocityVector (const geometry_msgs::TwistWithCovariance &twist)
bool hasValidOrientation (const geometry_msgs::PoseWithCovariance &pose)
Returns true if all xyz rotation variances are finite.
Ogre::Matrix3 covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance &pose)
void setPoseOrientation (Ogre::SceneNode *sceneNode, const geometry_msgs::PoseWithCovariance &pose, const Ogre::Matrix3 &covXYZinTargetFrame, double personVisualHeight)
Set pose and orientation of person visual.
Ogre::ColourValue getColorFromId (unsigned int object_id)
Get a color based upon track / detection ID.
bool isPersonHidden (person_id personId)
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
Private Slots
void personVisualTypeChanged ()
virtual void stylesChanged ()
Private Member Functions
void processMessage (const spencer_tracking_msgs::DetectedPersons::ConstPtr &msg)
Private Attributes
vector< boost::shared_ptr< DetectedPersonVisual > > m_previousDetections
rviz::BoolProperty * m_render_covariances_property
rviz::BoolProperty * m_render_detection_ids_property
rviz::BoolProperty * m_render_confidences_property
rviz::FloatProperty * m_low_confidence_threshold_property
rviz::FloatProperty * m_low_confidence_alpha_property
rviz::BoolProperty * m_render_orientations_property
rviz::BoolProperty * m_render_modality_text_property
rviz::FloatProperty * m_text_spacing_property
rviz::FloatProperty * m_covariance_line_width_property
Additional Inherited Members
Protected Attributes inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >
PersonDisplayCommonProperties * m_commonProperties
Common properties for the displays in this plugin.
Ogre::Quaternion m_frameOrientation
Ogre::Matrix3 m_frameRotationMatrix
Ogre::Vector3 m_framePosition
const double m_veryLargeVariance
Constructor & Destructor Documentation
DetectedPersonsDisplay()
spencer_tracking_rviz_plugin::DetectedPersonsDisplay::DetectedPersonsDisplay () inline
 {};
~DetectedPersonsDisplay()
spencer_tracking_rviz_plugin::DetectedPersonsDisplay::~DetectedPersonsDisplay () virtual
 {
     m_previousDetections.clear();
 }
References m_previousDetections.
Member Function Documentation
getContext()
virtual rviz::DisplayContext* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::getContext () inline protected virtual
Must be implemented by derived classes because MOC doesn't work in templates.
Implements spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >.
{
             return context_;
         }
onInitialize()
void spencer_tracking_rviz_plugin::DetectedPersonsDisplay::onInitialize () virtual
Overrides base class method.
Reimplemented from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >.
 {
     PersonDisplayCommon::onInitialize();
     QObject::connect(m_commonProperties->style, SIGNAL(changed()), this, SLOT(personVisualTypeChanged()) );
     m_render_covariances_property       = new rviz::BoolProperty( "Render covariances", true, "Render track covariance ellipses", this, SLOT(stylesChanged()) );
     m_render_detection_ids_property     = new rviz::BoolProperty( "Render detection IDs", true, "Render IDs of the detection that a track was matched against, if any", this, SLOT(stylesChanged()));
     m_render_confidences_property       = new rviz::BoolProperty( "Render confidences", false, "Render detection confidences", this, SLOT(stylesChanged()));
     m_render_orientations_property      = new rviz::BoolProperty( "Render orientation arrows", true, "Render orientation arrows (only if orientation covariances are finite!)", this, SLOT(stylesChanged()));
     m_render_modality_text_property     = new rviz::BoolProperty( "Render modality text", false, "Render detection modality as text below detected person", this, SLOT(stylesChanged()));
     m_text_spacing_property = new rviz::FloatProperty( "Text spacing", 1.0, "Factor for vertical spacing betweent texts", this, SLOT(stylesChanged()), this );
     m_low_confidence_threshold_property = new rviz::FloatProperty( "Low-confidence threshold", 0.5, "Detection confidence below which alpha will be reduced", this, SLOT(stylesChanged()));
     m_low_confidence_alpha_property     = new rviz::FloatProperty( "Low-confidence alpha", 0.5, "Alpha multiplier for detections with confidence below low-confidence threshold", this, SLOT(stylesChanged()));
     m_covariance_line_width_property = new rviz::FloatProperty( "Line width", 0.1, "Line width of covariance ellipses", m_render_covariances_property, SLOT(stylesChanged()), this );
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::m_commonProperties, m_covariance_line_width_property, m_low_confidence_alpha_property, m_low_confidence_threshold_property, m_render_confidences_property, m_render_covariances_property, m_render_detection_ids_property, m_render_modality_text_property, m_render_orientations_property, m_text_spacing_property, spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::onInitialize(), personVisualTypeChanged(), spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::style, and stylesChanged().
personVisualTypeChanged
void spencer_tracking_rviz_plugin::DetectedPersonsDisplay::personVisualTypeChanged () private slot
 {
     foreach(boost::shared_ptr<DetectedPersonVisual>& detectedPersonVisual, m_previousDetections)
     {
         detectedPersonVisual->personVisual.reset();
         createPersonVisualIfRequired(detectedPersonVisual->sceneNode.get(), detectedPersonVisual->personVisual);
     }
     stylesChanged();
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::createPersonVisualIfRequired(), m_previousDetections, and stylesChanged().
Referenced by onInitialize().
processMessage()
void spencer_tracking_rviz_plugin::DetectedPersonsDisplay::processMessage (const spencer_tracking_msgs::DetectedPersons::ConstPtr & msg) private
 {
     // Get transforms into fixed frame etc.
     if(!preprocessMessage(msg)) return;
     const Ogre::Quaternion shapeQuaternion( Ogre::Degree(90), Ogre::Vector3(1,0,0) ); // required to fix orientation of any Cylinder shapes
     stringstream ss;
     // Clear previous detections, this will also delete them from the scene graph
     m_previousDetections.clear();
     //
     // Iterate over all detections in this message and create a visual representation
     //
     for (vector<spencer_tracking_msgs::DetectedPerson>::const_iterator detectedPersonIt = msg->detections.begin(); detectedPersonIt != msg->detections.end(); ++detectedPersonIt)
     {
         boost::shared_ptr<DetectedPersonVisual> detectedPersonVisual;
         // Create a new visual representation of the detected person
         detectedPersonVisual = boost::shared_ptr<DetectedPersonVisual>(new DetectedPersonVisual);
         m_previousDetections.push_back(detectedPersonVisual);
         // This scene node is the parent of all visualization elements for the detected person
         detectedPersonVisual->sceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
         detectedPersonVisual->detectionId = detectedPersonIt->detection_id;
         detectedPersonVisual->confidence = detectedPersonIt->confidence;
         Ogre::SceneNode* currentSceneNode = detectedPersonVisual->sceneNode.get();
         //
         // Person visualization
         //
         // Create new visual for the person itself, if needed
         boost::shared_ptr<PersonVisual> &personVisual = detectedPersonVisual->personVisual;
         createPersonVisualIfRequired(currentSceneNode, personVisual);
         const double personHeight = personVisual ? personVisual->getHeight() : 0;
         const double halfPersonHeight = personHeight / 2.0;
         //
         // Position & visibility of entire detection
         //
         const Ogre::Matrix3 covXYZinTargetFrame = covarianceXYZIntoTargetFrame(detectedPersonIt->pose);
         setPoseOrientation(currentSceneNode, detectedPersonIt->pose, covXYZinTargetFrame, personHeight);
         //
         // Texts
         //
         {
             // Detection ID
             if (!detectedPersonVisual->detectionIdText) {
                 detectedPersonVisual->detectionIdText.reset(new TextNode(context_->getSceneManager(), currentSceneNode));
                 detectedPersonVisual->detectionIdText->showOnTop();
             }
             ss.str(""); ss << "det " << detectedPersonIt->detection_id;
             detectedPersonVisual->detectionIdText->setCaption(ss.str());
             // Confidence value
             if (!detectedPersonVisual->confidenceText) {
                 detectedPersonVisual->confidenceText.reset(new TextNode(context_->getSceneManager(), currentSceneNode));
             }
             ss.str(""); ss << fixed << setprecision(2) << detectedPersonIt->confidence;
             detectedPersonVisual->confidenceText->setCaption(ss.str());
             detectedPersonVisual->confidenceText->showOnTop();
             // Modality text
             if (!detectedPersonVisual->modalityText) {
                 detectedPersonVisual->modalityText.reset(new TextNode(context_->getSceneManager(), currentSceneNode));
             }
             ss.str(""); ss << detectedPersonIt->modality;
             detectedPersonVisual->modalityText->setCaption(ss.str());
             detectedPersonVisual->modalityText->showOnTop();
         }
         //
         // Covariance visualization
         //
         if(!detectedPersonVisual->covarianceVisual) {
             detectedPersonVisual->covarianceVisual.reset(new ProbabilityEllipseCovarianceVisual(context_->getSceneManager(), currentSceneNode));
         }
         // Update covariance ellipse
         {
             Ogre::Vector3 covarianceMean(0,0,0); // zero mean because parent node is already centered at pose mean
             detectedPersonVisual->covarianceVisual->setOrientation(currentSceneNode->getOrientation().Inverse());
             detectedPersonVisual->covarianceVisual->setMeanCovariance(covarianceMean, covXYZinTargetFrame);
         }
         //
         // Orientation arrows
         //
         if (!detectedPersonVisual->orientationArrow) {
             detectedPersonVisual->orientationArrow.reset(new rviz::Arrow(context_->getSceneManager(), currentSceneNode));
         }
         // Update orientation arrow
         {
             const Ogre::Vector3 forwardVector(1,0,0);
             const double personRadius = 0.2;
             const Ogre::Vector3 arrowAttachPoint(personRadius, 0, halfPersonHeight); // relative to tracked person's scene node
             detectedPersonVisual->orientationArrow->setPosition(arrowAttachPoint);
             detectedPersonVisual->orientationArrow->setOrientation(Ogre::Vector3::NEGATIVE_UNIT_Z.getRotationTo(forwardVector));
             detectedPersonVisual->hasValidOrientation = hasValidOrientation(detectedPersonIt->pose);
         }
     } // end for loop over all detected persons
     // Set all properties that can dynamically be adjusted in the GUI
     stylesChanged();
     //
     // Update status (shown in property pane)
     //
     ss.str("");
     ss << msg->detections.size() << " detections received";
     setStatusStd(rviz::StatusProperty::Ok, "Tracks", ss.str());
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::covarianceXYZIntoTargetFrame(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::createPersonVisualIfRequired(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::hasValidOrientation(), m_previousDetections, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::preprocessMessage(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::setPoseOrientation(), shapeQuaternion(), and stylesChanged().
reset()
void spencer_tracking_rviz_plugin::DetectedPersonsDisplay::reset () protected virtual
 {
     PersonDisplayCommon::reset();
     m_previousDetections.clear();
 }
References m_previousDetections.
stylesChanged
void spencer_tracking_rviz_plugin::DetectedPersonsDisplay::stylesChanged () private virtual slot
 {
     foreach(boost::shared_ptr<DetectedPersonVisual> detectedPersonVisual, m_previousDetections)
     {
         bool personHidden = isPersonHidden(detectedPersonVisual->detectionId);
         // Update common styles to person visual, such as line width
         applyCommonStyles(detectedPersonVisual->personVisual);
         // Get current detection color
         Ogre::ColourValue detectionColor = getColorFromId(detectedPersonVisual->detectionId);
         detectionColor.a *= m_commonProperties->alpha->getFloat(); // general alpha
         if(personHidden) detectionColor.a = 0.0;
         if(detectedPersonVisual->confidence < m_low_confidence_threshold_property->getFloat()) detectionColor.a *= m_low_confidence_alpha_property->getFloat();
         if(detectedPersonVisual->personVisual) {
             detectedPersonVisual->personVisual->setColor(detectionColor);
         }
         // Update texts
         Ogre::ColourValue fontColor = m_commonProperties->font_color_style->getOptionInt() == FONT_COLOR_CONSTANT ? m_commonProperties->constant_font_color->getOgreColor() : detectionColor;
         fontColor.a = m_commonProperties->alpha->getFloat();
         if(personHidden) fontColor.a = 0.0;
         float textOffset = 0.0f;
         detectedPersonVisual->detectionIdText->setCharacterHeight(0.18 * m_commonProperties->font_scale->getFloat());
         detectedPersonVisual->detectionIdText->setPosition(Ogre::Vector3(0,0, -0.5*detectedPersonVisual->detectionIdText->getCharacterHeight() - textOffset));
         detectedPersonVisual->detectionIdText->setVisible(m_render_detection_ids_property->getBool());
         detectedPersonVisual->detectionIdText->setColor(fontColor);
         if(m_render_detection_ids_property->getBool()) textOffset += m_text_spacing_property->getFloat() * detectedPersonVisual->detectionIdText->getCharacterHeight();
         detectedPersonVisual->modalityText->setCharacterHeight(0.18 * m_commonProperties->font_scale->getFloat());
         detectedPersonVisual->modalityText->setPosition(Ogre::Vector3(textOffset, 0, -0.5*detectedPersonVisual->modalityText->getCharacterHeight() - textOffset));
         detectedPersonVisual->modalityText->setVisible(m_render_modality_text_property->getBool());
         detectedPersonVisual->modalityText->setColor(fontColor);
         if(m_render_modality_text_property->getBool()) textOffset += m_text_spacing_property->getFloat() * detectedPersonVisual->modalityText->getCharacterHeight();
         detectedPersonVisual->confidenceText->setCharacterHeight(0.13 * m_commonProperties->font_scale->getFloat());
         detectedPersonVisual->confidenceText->setPosition(Ogre::Vector3(textOffset, 0, -0.5*detectedPersonVisual->confidenceText->getCharacterHeight() - textOffset));
         detectedPersonVisual->confidenceText->setVisible(m_render_confidences_property->getBool());
         detectedPersonVisual->confidenceText->setColor(fontColor);
         if(m_render_confidences_property->getBool()) textOffset += m_text_spacing_property->getFloat() * detectedPersonVisual->confidenceText->getCharacterHeight();
         // Set color of covariance visualization
         Ogre::ColourValue covarianceColor = detectionColor;
         if(!m_render_covariances_property->getBool()) covarianceColor.a = 0.0;
         detectedPersonVisual->covarianceVisual->setColor(covarianceColor);
         detectedPersonVisual->covarianceVisual->setLineWidth(m_covariance_line_width_property->getFloat());
         // Update orientation arrow
         double arrowAlpha = m_render_orientations_property->getBool() && detectedPersonVisual->hasValidOrientation ? detectionColor.a : 0.0;
         detectedPersonVisual->orientationArrow->setColor(Ogre::ColourValue(detectionColor.r, detectionColor.g, detectionColor.b, arrowAlpha));
         const double shaftLength = 0.5, shaftDiameter = 0.05, headLength = 0.2, headDiameter = 0.2;
         detectedPersonVisual->orientationArrow->set(shaftLength, shaftDiameter, headLength, headDiameter);
     }
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::alpha, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::applyCommonStyles(), spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::constant_font_color, spencer_tracking_rviz_plugin::FONT_COLOR_CONSTANT, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_color_style, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_scale, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::getColorFromId(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::isPersonHidden(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::DetectedPersons >::m_commonProperties, m_covariance_line_width_property, m_low_confidence_alpha_property, m_low_confidence_threshold_property, m_previousDetections, m_render_confidences_property, m_render_covariances_property, m_render_detection_ids_property, m_render_modality_text_property, m_render_orientations_property, and m_text_spacing_property.
Referenced by onInitialize(), personVisualTypeChanged(), and processMessage().
Member Data Documentation
m_covariance_line_width_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_covariance_line_width_property private
Referenced by onInitialize(), and stylesChanged().
m_low_confidence_alpha_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_low_confidence_alpha_property private
Referenced by onInitialize(), and stylesChanged().
m_low_confidence_threshold_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_low_confidence_threshold_property private
Referenced by onInitialize(), and stylesChanged().
m_previousDetections
vector<boost::shared_ptr<DetectedPersonVisual> > spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_previousDetections private
Referenced by personVisualTypeChanged(), processMessage(), reset(), stylesChanged(), and ~DetectedPersonsDisplay().
m_render_confidences_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_render_confidences_property private
Referenced by onInitialize(), and stylesChanged().
m_render_covariances_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_render_covariances_property private
Referenced by onInitialize(), and stylesChanged().
m_render_detection_ids_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_render_detection_ids_property private
Referenced by onInitialize(), and stylesChanged().
m_render_modality_text_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_render_modality_text_property private
Referenced by onInitialize(), and stylesChanged().
m_render_orientations_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_render_orientations_property private
Referenced by onInitialize(), and stylesChanged().
m_text_spacing_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::DetectedPersonsDisplay::m_text_spacing_property private
Referenced by onInitialize(), and stylesChanged().
The documentation for this class was generated from the following files:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/detected_persons_display.h
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/detected_persons_display.cpp