ROS Motion Planning: spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType > Class Template Reference
spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType > Class Template Reference abstract
A display with common properties that are shared by multiple specializations.
#include <person_display_common.h>
Public Member Functions
PersonDisplayCommon ()
virtual ~PersonDisplayCommon ()
virtual void onInitialize ()
Overrides base class method.
Public Member Functions inherited from spencer_tracking_rviz_plugin::StylesChangedSubscriber
virtual ~StylesChangedSubscriber ()
virtual void stylesChanged ()
Protected Member Functions
bool preprocessMessage (const typename MessageType::ConstPtr &msg)
Common message processing. This method needs to be called by derived classes.
void createPersonVisualIfRequired (Ogre::SceneNode *sceneNode, boost::shared_ptr< PersonVisual > &personVisual)
Create a visual representation of the person itself, if not set yet.
void applyCommonStyles (boost::shared_ptr< PersonVisual > &personVisual)
Applies common styles which apply to person visuals, such as line width etc.
Ogre::Vector3 getVelocityVector (const geometry_msgs::TwistWithCovariance &twist)
bool hasValidOrientation (const geometry_msgs::PoseWithCovariance &pose)
Returns true if all xyz rotation variances are finite.
Ogre::Matrix3 covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance &pose)
void setPoseOrientation (Ogre::SceneNode *sceneNode, const geometry_msgs::PoseWithCovariance &pose, const Ogre::Matrix3 &covXYZinTargetFrame, double personVisualHeight)
Set pose and orientation of person visual.
Ogre::ColourValue getColorFromId (unsigned int object_id)
Get a color based upon track / detection ID.
bool isPersonHidden (person_id personId)
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
virtual rviz::DisplayContext * getContext ()=0
Must be implemented by derived classes because MOC doesn't work in templates.
Protected Attributes
PersonDisplayCommonProperties * m_commonProperties
Common properties for the displays in this plugin.
Ogre::Quaternion m_frameOrientation
Ogre::Matrix3 m_frameRotationMatrix
Ogre::Vector3 m_framePosition
const double m_veryLargeVariance
Detailed Description
template<typename MessageType>
class spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >
A display with common properties that are shared by multiple specializations.
Constructor & Destructor Documentation
PersonDisplayCommon()
template<typename MessageType > spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::PersonDisplayCommon () inline
Constructor. pluginlib::ClassLoader creates instances by calling the default constructor, so make sure you have one.
 : m_commonProperties(0), m_veryLargeVariance(99999) {}
~PersonDisplayCommon()
template<typename MessageType > virtual spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::~PersonDisplayCommon () inline virtual
 {}
Member Function Documentation
applyCommonStyles()
template<typename MessageType > void spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::applyCommonStyles (boost::shared_ptr< PersonVisual > & personVisual) inline protected
Applies common styles which apply to person visuals, such as line width etc.
{
             if(!personVisual) return;
             // Set line width of wireframe visualization
             HasLineWidth* hasLineWidth = dynamic_cast<HasLineWidth*>(personVisual.get());
             if(hasLineWidth) {
                 hasLineWidth->setLineWidth(m_commonProperties->line_width->getFloat());
             }
             // Set scaling factor
             personVisual->setScalingFactor(m_commonProperties->scaling_factor->getFloat());
         }
covarianceXYZIntoTargetFrame()
template<typename MessageType > Ogre::Matrix3 spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance & pose) inline protected
Rotate the position (xyz) part of a pose covariance matrix into the fixed frame used for visualization The covariance matrix needs to be transformed from the source (e.g. sensor) into the target (e.g. odometry) frame This is mainly be a problem if the sensor is rotated vertically compared to the odometry frame, so that axes get swapped
{
             Ogre::Matrix3 xyzcov;
             for(int row = 0; row < 3; row++) for(int col = 0; col < 3; col++) xyzcov[row][col] = pose.covariance[row*6 + col]; // 6 = dimension of ROS covariance matrix
             if(!isfinite(xyzcov.Determinant())) ROS_WARN_STREAM("Covariance matrix supplied to covarianceXYZIntoTargetFrame() contains non-finite elements: " << xyzcov);
             return m_frameRotationMatrix * xyzcov * m_frameRotationMatrix.Transpose(); // cov(AX + a) = A cov(X) A^T
         }
createPersonVisualIfRequired()
template<typename MessageType > void spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::createPersonVisualIfRequired (Ogre::SceneNode * sceneNode, boost::shared_ptr< PersonVisual > & personVisual) inline protected
Create a visual representation of the person itself, if not set yet.
         {
             if (!personVisual) {
                 PersonVisualDefaultArgs defaultArgs(getContext()->getSceneManager(), sceneNode);
                 PersonVisual* newPersonVisual = 0;
                 if (m_commonProperties->style->getOptionInt() == STYLE_CYLINDER) newPersonVisual = new CylinderPersonVisual(defaultArgs);
                 if (m_commonProperties->style->getOptionInt() == STYLE_PERSON_MESHES) newPersonVisual = new MeshPersonVisual(defaultArgs);
                 if (m_commonProperties->style->getOptionInt() == STYLE_BOUNDING_BOXES) newPersonVisual = new BoundingBoxPersonVisual(defaultArgs);
                 if (m_commonProperties->style->getOptionInt() == STYLE_CROSSHAIRS) newPersonVisual = new CrosshairPersonVisual(defaultArgs);
                 personVisual.reset(newPersonVisual);
             }
             // Update position of the person visual
             if (personVisual) {
                 personVisual->setPosition(Ogre::Vector3(0,0, personVisual->getHeight() * 0.5));
             }
         }
getColorFromId()
template<typename MessageType > Ogre::ColourValue spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::getColorFromId (unsigned int object_id) inline protected
Get a color based upon track / detection ID.
         {
             Ogre::ColourValue color;
             const int colorScheme = m_commonProperties->color_transform->getOptionInt();
             object_id += max(0, m_commonProperties->color_map_offset->getInt());
             if(colorScheme == COLORS_SRL || colorScheme == COLORS_SRL_ALTERNATIVE)
             {
                 // SRL People Tracker colors
                 const size_t NUM_SRL_COLORS = 6, NUM_SRL_COLOR_SHADES = 4, NUM_SRL_TOTAL_COLORS = NUM_SRL_COLORS * NUM_SRL_COLOR_SHADES;
                 const unsigned int spencer_colors[NUM_SRL_TOTAL_COLORS] = {
                     0xC00000, 0xFF0000, 0xFF5050, 0xFFA0A0, // red
                     0x00C000, 0x00FF00, 0x50FF50, 0xA0FFA0, // green
                     0x0000C0, 0x0000FF, 0x5050FF, 0xA0A0FF, // blue
                     0xF20A86, 0xFF00FF, 0xFF50FF, 0xFFA0FF, // magenta
                     0x00C0C0, 0x00FFFF, 0x50FFFF, 0xA0FFFF, // cyan
                     0xF5A316, 0xFFFF00, 0xFFFF50, 0xFFFFA0  // yellow
                 };
                 unsigned int rgb = 0;
                 const unsigned int tableId = object_id % NUM_SRL_TOTAL_COLORS;
                 if(m_commonProperties->color_transform->getOptionInt() == COLORS_SRL) {
                     // Colors in original order (first vary shade, then vary color)
                     rgb = spencer_colors[tableId];
                 }
                 else if(m_commonProperties->color_transform->getOptionInt() == COLORS_SRL_ALTERNATIVE) {
                     // Colors in alternative order (first vary color, then vary shade)
                     unsigned int shadeIndex = tableId / NUM_SRL_COLORS;
                     unsigned int colorIndex = tableId % NUM_SRL_COLORS;
                     rgb = spencer_colors[colorIndex * NUM_SRL_COLOR_SHADES + shadeIndex];
                 }
                 float r = ((rgb >> 16) & 0xff) / 255.0f,
                        g = ((rgb >> 8)  & 0xff) / 255.0f,
                        b = ((rgb >> 0)  & 0xff) / 255.0f;
                 color = Ogre::ColourValue(r, g, b, 1.0);
             }
             else if(colorScheme == COLORS_RAINBOW || colorScheme == COLORS_RAINBOW_BW)
             {
                 const size_t NUM_COLOR = 10, NUM_BW = 4;
                 const unsigned int rainbow_colors[NUM_COLOR + NUM_BW] = {
                     0xaf1f90, 0x000846, 0x00468a, 0x00953d, 0xb2c908, 0xfcd22a, 0xffa800, 0xff4500, 0xe0000b, 0xb22222,
                     0xffffff, 0xb8b8b8, 0x555555, 0x000000
                 };
                 color.setAsARGB(rainbow_colors[object_id % (colorScheme == COLORS_RAINBOW ? NUM_COLOR : (NUM_COLOR+NUM_BW))]);
             }
             else if(colorScheme == COLORS_FLAT)
             {
                 const size_t NUM_COLOR = 10;
                 const unsigned int flat_colors[NUM_COLOR] = {
                     0x990033, 0xa477c4, 0x3498db, 0x1abc9c, 0x55e08f, 0xfff054, 0xef5523, 0xfe374a, 0xbaa891, 0xad5f43
                 };
                 color.setAsARGB(flat_colors[object_id % NUM_COLOR]);
             }
             else if(colorScheme == COLORS_VINTAGE)
             {
                 const size_t NUM_COLOR = 10;
                 const unsigned int vintage_colors[NUM_COLOR] = {
                     0xd05e56, 0x797d88, 0x448d7a, 0xa5d1cd, 0x88a764, 0xebe18c, 0xd8a027, 0xffcc66, 0xdc3f1c, 0xff9966
                 };
                 color.setAsARGB(vintage_colors[object_id % NUM_COLOR]);
             }
             else
             {
                 // Constant color for all tracks
                 color = m_commonProperties->constant_color->getOgreColor();
             }
             color.a = 1.0f; // force full opacity
             return color;
         }
getContext()
template<typename MessageType > virtual rviz::DisplayContext* spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::getContext () protected pure virtual
Must be implemented by derived classes because MOC doesn't work in templates.
Implemented in spencer_tracking_rviz_plugin::TrackedPersonsDisplay, spencer_tracking_rviz_plugin::TrackedGroupsDisplay, spencer_tracking_rviz_plugin::DetectedPersonsDisplay, spencer_tracking_rviz_plugin::SocialActivitiesDisplay, spencer_tracking_rviz_plugin::HumanAttributesDisplay, and spencer_tracking_rviz_plugin::SocialRelationsDisplay.
getVelocityVector()
template<typename MessageType > Ogre::Vector3 spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::getVelocityVector (const geometry_msgs::TwistWithCovariance & twist) inline protected
{
             const double zVelocityVariance = twist.covariance[2 * 6 + 2];
             const double zVelocity = (isnan(zVelocityVariance) || isinf(zVelocityVariance)) ? 0.0 : twist.twist.linear.z;
             return Ogre::Vector3(twist.twist.linear.x, twist.twist.linear.y, zVelocity);
         }
hasValidOrientation()
template<typename MessageType > bool spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::hasValidOrientation (const geometry_msgs::PoseWithCovariance & pose) inline protected
Returns true if all xyz rotation variances are finite.
         {
             // Check if quaternion has not been initialized, then it's invalid (all-zero elements)
             if(pose.pose.orientation.x == 0 && pose.pose.orientation.y == 0 && pose.pose.orientation.z == 0 && pose.pose.orientation.w == 0) return false;
             // According to ROS conventions, orientation covariance is always fixed-frame
             // so no transform necessary!
             const double xRotVariance = pose.covariance[3 * 6 + 3];
             const double yRotVariance = pose.covariance[4 * 6 + 4];
             const double zRotVariance = pose.covariance[5 * 6 + 5];
             // Using logical OR instead of AND here because the orientation is given as a quaternion, instead of independent
             // RPY angles. We assume if at least one RPY angle is valid (according to its covariance), the other angles are set to a
             // reasonable default (as part of the quaternion) if their variance is non-finite.
             return xRotVariance < m_veryLargeVariance || yRotVariance < m_veryLargeVariance || zRotVariance < m_veryLargeVariance;
         }
isPersonHidden()
template<typename MessageType > bool spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::isPersonHidden (person_id personId) inline protected
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
         {
             bool isIncluded = m_commonProperties->m_includedPersonIDs.find(personId) != m_commonProperties->m_includedPersonIDs.end();
             if(isIncluded) return false;
             if(!m_commonProperties->m_includedPersonIDs.empty()) return true;
             return m_commonProperties->m_excludedPersonIDs.find(personId) != m_commonProperties->m_excludedPersonIDs.end();
         }
onInitialize()
template<typename MessageType > virtual void spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::onInitialize () inline virtual
Overrides base class method.
Reimplemented in spencer_tracking_rviz_plugin::TrackedPersonsDisplay, spencer_tracking_rviz_plugin::DetectedPersonsDisplay, spencer_tracking_rviz_plugin::TrackedGroupsDisplay, spencer_tracking_rviz_plugin::SocialActivitiesDisplay, spencer_tracking_rviz_plugin::HumanAttributesDisplay, and spencer_tracking_rviz_plugin::SocialRelationsDisplay.
         {
             rviz::MessageFilterDisplay<MessageType>::onInitialize();
             m_commonProperties = new PersonDisplayCommonProperties(this, this);
         }
Referenced by spencer_tracking_rviz_plugin::SocialRelationsDisplay::onInitialize(), spencer_tracking_rviz_plugin::HumanAttributesDisplay::onInitialize(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::onInitialize(), spencer_tracking_rviz_plugin::DetectedPersonsDisplay::onInitialize(), spencer_tracking_rviz_plugin::TrackedGroupsDisplay::onInitialize(), and spencer_tracking_rviz_plugin::TrackedPersonsDisplay::onInitialize().
preprocessMessage()
template<typename MessageType > bool spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::preprocessMessage (const typename MessageType::ConstPtr & msg) inline protected
Common message processing. This method needs to be called by derived classes.
         {
             // Here we call the rviz::FrameManager to get the transform from the
             // fixed frame to the frame in the header of this Imu message.  If
             // it fails, we can't do anything else so we return.
             if (!getContext()->getFrameManager()->getTransform(msg->header, m_framePosition, m_frameOrientation)) {
                 ROS_ERROR_THROTTLE(5.0, "Error transforming from frame '%s' into fixed frame!", msg->header.frame_id.c_str());
                 return false;
             }
             m_frameOrientation.ToRotationMatrix(m_frameRotationMatrix);
             return true;
         }
setPoseOrientation()
template<typename MessageType > void spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::setPoseOrientation (Ogre::SceneNode * sceneNode, const geometry_msgs::PoseWithCovariance & pose, const Ogre::Matrix3 & covXYZinTargetFrame, double personVisualHeight) inline protected
Set pose and orientation of person visual.
         {
             const geometry_msgs::Point& position = pose.pose.position;
             const geometry_msgs::Quaternion& orientation = pose.pose.orientation;
             Ogre::Matrix4 transform(m_frameOrientation);
             transform.setTrans(m_framePosition);
             Ogre::Vector3 originalPosition(position.x, position.y, position.z);
             if(!isfinite(originalPosition.x) || !isfinite(originalPosition.y) || !isfinite(originalPosition.z)) {
                 ROS_WARN("Detected or tracked person has non-finite position! Something is wrong!");
                 return;
             }
             Ogre::Vector3 positionInTargetFrame = transform * originalPosition;
             if(hasValidOrientation(pose)) {
                 Ogre::Quaternion detectionOrientation(orientation.w, orientation.x, orientation.y, orientation.z);
                 detectionOrientation.FromAngleAxis(detectionOrientation.getRoll(), Ogre::Vector3(0,0,1)); // only use yaw angle, ignore roll and pitch
                 sceneNode->setOrientation(m_frameOrientation * detectionOrientation);
             }
             else {
                 Ogre::Quaternion rotateTowardsCamera;
                 rotateTowardsCamera.FromAngleAxis(Ogre::Degree(180), Ogre::Vector3(0,0,1));
                 sceneNode->setOrientation(rotateTowardsCamera);
             }
             const double zVariance = covXYZinTargetFrame[2][2];
             bool useActualZPosition = m_commonProperties->use_actual_z_position->getBool() && isfinite(zVariance) && zVariance >= 0 && zVariance < m_veryLargeVariance;
             positionInTargetFrame.z = useActualZPosition ? positionInTargetFrame.z - personVisualHeight/2.0: 0.0;
             positionInTargetFrame.z += m_commonProperties->z_offset->getFloat();
             sceneNode->setPosition(positionInTargetFrame);
         }
Member Data Documentation
m_commonProperties
template<typename MessageType > PersonDisplayCommonProperties* spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::m_commonProperties protected
Common properties for the displays in this plugin.
m_frameOrientation
template<typename MessageType > Ogre::Quaternion spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::m_frameOrientation protected
m_framePosition
template<typename MessageType > Ogre::Vector3 spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::m_framePosition protected
m_frameRotationMatrix
template<typename MessageType > Ogre::Matrix3 spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::m_frameRotationMatrix protected
m_veryLargeVariance
template<typename MessageType > const double spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::m_veryLargeVariance protected
The documentation for this class was generated from the following file:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/person_display_common.h