ROS Motion Planning: global_planner::DStar Class Reference
global_planner::DStar Class Reference
Class for objects that plan using the D* algorithm.
#include <d_star.h>
Public Member Functions
DStar (int nx, int ny, double resolution)
Construct a new DStar object.
void initMap ()
Init map.
void reset ()
Reset the system.
void insert (DNodePtr node_ptr, double h_new)
Insert nodePtr into the open_list with h_new.
bool isCollision (DNodePtr n1, DNodePtr n2)
Check if there is collision between n1 and n2.
void getNeighbours (DNodePtr node_ptr, std::vector< DNodePtr > &neighbours)
Get neighbour DNodePtrs of nodePtr.
double getCost (DNodePtr n1, DNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
double processState ()
Main process of D*.
void extractExpand (std::vector< Node > &expand)
Extract the expanded Nodes (CLOSED)
void extractPath (const Node &start, const Node &goal)
Extract path for map.
Node getState (const Node &current)
Get the closest Node of the path to current state.
void modify (DNodePtr x)
Modify the map when collision occur between x and y in path, and then do processState()
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
D* implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Public Attributes
unsigned char * curr_global_costmap_
unsigned char * last_global_costmap_
DNodePtr ** map_
std::multimap< double, DNodePtr > open_list_
std::vector< Node > path_
std::vector< Node > expand_
Node goal_
Additional Inherited Members
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the D* algorithm.
Constructor & Destructor Documentation
DStar()
global_planner::DStar::DStar (int nx, int ny, double resolution)
Construct a new DStar object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
                                               : GlobalPlanner(nx, ny, resolution)
 {
   curr_global_costmap_ = new unsigned char[ns_];
   last_global_costmap_ = new unsigned char[ns_];
   goal_.x_ = goal_.y_ = INF;
   factor_ = 0.25;
   initMap();
 }
References curr_global_costmap_, global_planner::GlobalPlanner::factor_, goal_, INF, initMap(), last_global_costmap_, global_planner::GlobalPlanner::ns_, Node::x_, and Node::y_.
Member Function Documentation
extractExpand()
void global_planner::DStar::extractExpand (std::vector< Node > & expand)
Extract the expanded Nodes (CLOSED)
Parameters
expand expanded Nodes in vector
 {
   for (int i = 0; i < nx_; ++i)
   {
     for (int j = 0; j < ny_; ++j)
     {
       DNodePtr node_ptr = map_[i][j];
       if (node_ptr->t_ == DNode::CLOSED)
         expand.push_back(*node_ptr);
     }
   }
 }
References DNode::CLOSED, map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, and DNode::t_.
extractPath()
void global_planner::DStar::extractPath (const Node & start, const Node & goal)
Extract path for map.
Parameters
start start node
goal goal node
 {
   DNodePtr node_ptr = map_[start.x_][start.y_];
   while (node_ptr->x_ != goal.x_ || node_ptr->y_ != goal.y_)
   {
     path_.push_back(*node_ptr);
     int x, y;
     index2Grid(node_ptr->pid_, x, y);
     node_ptr = map_[x][y];
   }
   std::reverse(path_.begin(), path_.end());
 }
References global_planner::GlobalPlanner::index2Grid(), map_, path_, Node::pid_, Node::x_, and Node::y_.
Referenced by plan().
getCost()
double global_planner::DStar::getCost (DNodePtr n1, DNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
Parameters
n1 DNode pointer of one DNode
n2 DNode pointer of the other DNode
Returns
cost between n1 and n2
 {
   if (isCollision(n1, n2))
     return INF;
   return std::hypot(n1->x_ - n2->x_, n1->y_ - n2->y_);
 }
References INF, isCollision(), Node::x_, and Node::y_.
Referenced by processState().
getNeighbours()
void global_planner::DStar::getNeighbours (DNodePtr node_ptr, std::vector< DNodePtr > & neighbours)
Get neighbour DNodePtrs of nodePtr.
Get neighbour DNodePtrs of node_ptr.
Parameters
node_ptr DNode to expand
neighbours neigbour DNodePtrs in vector
 {
   int x = node_ptr->x_, y = node_ptr->y_;
   for (int i = -1; i <= 1; ++i)
   {
     for (int j = -1; j <= 1; ++j)
     {
       if (i == 0 && j == 0)
         continue;
       int x_n = x + i, y_n = y + j;
       if (x_n < 0 || x_n > nx_ - 1 || y_n < 0 || y_n > ny_ - 1)
         continue;
       DNodePtr neigbour_ptr = map_[x_n][y_n];
       neighbours.push_back(neigbour_ptr);
     }
   }
 }
References map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, Node::x_, and Node::y_.
Referenced by plan(), and processState().
getState()
Node global_planner::DStar::getState (const Node & current)
Get the closest Node of the path to current state.
Parameters
current current state
Returns
the closest Node
 {
   Node state(path_[0].x_, path_[0].y_);
   double dis_min = std::hypot(state.x_ - current.x_, state.y_ - current.y_);
   int idx_min = 0;
   for (int i = 1; i < path_.size(); i++)
   {
     double dis = std::hypot(path_[i].x_ - current.x_, path_[i].y_ - current.y_);
     if (dis < dis_min)
     {
       dis_min = dis;
       idx_min = i;
     }
   }
   state.x_ = path_[idx_min].x_;
   state.y_ = path_[idx_min].y_;
   return state;
 }
References path_, Node::x_, and Node::y_.
Referenced by plan().
initMap()
void global_planner::DStar::initMap ()
Init map.
 {
   map_ = new DNodePtr*[nx_];
   for (int i = 0; i < nx_; ++i)
   {
     map_[i] = new DNodePtr[ny_];
     for (int j = 0; j < ny_; ++j)
     {
       map_[i][j] = new DNode(i, j, INF, INF, grid2Index(i, j), -1, DNode::NEW, INF);
     }
   }
 }
References global_planner::GlobalPlanner::grid2Index(), INF, map_, DNode::NEW, global_planner::GlobalPlanner::nx_, and global_planner::GlobalPlanner::ny_.
Referenced by DStar(), and reset().
insert()
void global_planner::DStar::insert (DNodePtr node_ptr, double h_new)
Insert nodePtr into the open_list with h_new.
Insert node_ptr into the open_list with h_new.
Parameters
node_ptr DNode pointer of the DNode to be inserted
h_new new h value
 {
   if (node_ptr->t_ == DNode::NEW)
     node_ptr->k_ = h_new;
   else if (node_ptr->t_ == DNode::OPEN)
     node_ptr->k_ = std::min(node_ptr->k_, h_new);
   else if (node_ptr->t_ == DNode::CLOSED)
     node_ptr->k_ = std::min(node_ptr->g_, h_new);
   node_ptr->g_ = h_new;
   node_ptr->t_ = DNode::OPEN;
   open_list_.insert(std::make_pair(node_ptr->k_, node_ptr));
 }
References DNode::CLOSED, Node::g_, DNode::k_, DNode::NEW, DNode::OPEN, open_list_, and DNode::t_.
Referenced by modify(), plan(), and processState().
isCollision()
bool global_planner::DStar::isCollision (DNodePtr n1, DNodePtr n2)
Check if there is collision between n1 and n2.
Parameters
n1 DNode pointer of one DNode
n2 DNode pointer of the other DNode
Returns
true if collision, else false
 {
   return curr_global_costmap_[n1->id_] > lethal_cost_ * factor_ ||
          curr_global_costmap_[n2->id_] > lethal_cost_ * factor_;
 }
References curr_global_costmap_, global_planner::GlobalPlanner::factor_, Node::id_, and global_planner::GlobalPlanner::lethal_cost_.
Referenced by getCost().
modify()
void global_planner::DStar::modify (DNodePtr x)
Modify the map when collision occur between x and y in path, and then do processState()
Parameters
x DNode pointer of one DNode
 {
   if (x->t_ == DNode::CLOSED)
     insert(x, x->g_);
 }
References DNode::CLOSED, Node::g_, insert(), and DNode::t_.
Referenced by plan().
plan()
bool global_planner::DStar::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
D* implementation.
Parameters
costs costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Parameters
global_costmap costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements global_planner::GlobalPlanner.
 {
   // update costmap
   memcpy(last_global_costmap_, curr_global_costmap_, ns_);
   memcpy(curr_global_costmap_, global_costmap, ns_);
   expand_.clear();
   // new goal set
   if (goal_.x_ != goal.x_ || goal_.y_ != goal.y_)
   {
     reset();
     goal_ = goal;
     DNodePtr start_ptr = map_[start.x_][start.y_];
     DNodePtr goal_ptr = map_[goal.x_][goal.y_];
     goal_ptr->g_ = 0;
     insert(goal_ptr, 0);
     while (1)
     {
       double k_min = processState();
       if (k_min == -1 || start_ptr->t_ == DNode::CLOSED)
         break;
     }
     path_.clear();
     extractPath(start, goal);
     expand = expand_;
     path = path_;
     return true;
   }
   else
   {
     // get current state from path, argmin Euler distance
     Node state = getState(start);
     // prepare-repair
     for (int i = -WINDOW_SIZE / 2; i < WINDOW_SIZE / 2; ++i)
     {
       for (int j = -WINDOW_SIZE / 2; j < WINDOW_SIZE / 2; ++j)
       {
         int x_n = state.x_ + i, y_n = state.y_ + j;
         if (x_n < 0 || x_n > nx_ - 1 || y_n < 0 || y_n > ny_ - 1)
           continue;
         DNodePtr x = map_[x_n][y_n];
         std::vector<DNodePtr> neigbours;
         getNeighbours(x, neigbours);
         int idx = grid2Index(x_n, y_n);
         if (curr_global_costmap_[idx] != last_global_costmap_[idx])
         {
           modify(x);
           for (DNodePtr y : neigbours)
           {
             modify(y);
           }
         }
       }
     }
     // repair-replan
     DNodePtr x = map_[state.x_][state.y_];
     while (1)
     {
       double k_min = processState();
       if (k_min >= x->g_ || k_min == -1)
         break;
     }
     path_.clear();
     extractPath(state, goal);
     expand = expand_;
     path = path_;
     return true;
   }
 }
References DNode::CLOSED, curr_global_costmap_, expand_, extractPath(), Node::g_, getNeighbours(), getState(), goal_, global_planner::GlobalPlanner::grid2Index(), insert(), last_global_costmap_, map_, modify(), global_planner::GlobalPlanner::ns_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, path_, processState(), reset(), DNode::t_, WINDOW_SIZE, Node::x_, and Node::y_.
processState()
double global_planner::DStar::processState ()
Main process of D*.
Returns
k_min
 {
   if (open_list_.empty())
     return -1;
   double k_old = open_list_.begin()->first;
   DNodePtr x = open_list_.begin()->second;
   open_list_.erase(open_list_.begin());
   x->t_ = DNode::CLOSED;
   expand_.push_back(*x);
   std::vector<DNodePtr> neigbours;
   getNeighbours(x, neigbours);
   // RAISE state, try to reduce k value by neibhbours
   if (k_old < x->g_)
   {
     for (DNodePtr y : neigbours)
     {
       if (y->t_ != DNode::NEW && y->g_ <= k_old && x->g_ > y->g_ + getCost(y, x))
       {
         x->pid_ = y->id_;
         x->g_ = y->g_ + getCost(y, x);
       }
     }
   }
   // LOWER state, cost reductions
   if (k_old == x->g_)
   {
     for (DNodePtr y : neigbours)
     {
       if (y->t_ == DNode::NEW || ((y->pid_ == x->id_) && (y->g_ != x->g_ + getCost(x, y))) ||
           ((y->pid_ != x->id_) && (y->g_ > x->g_ + getCost(x, y))))
       {
         y->pid_ = x->id_;
         insert(y, x->g_ + getCost(x, y));
       }
     }
   }
   else
   {
     // RAISE state
     for (DNodePtr y : neigbours)
     {
       if (y->t_ == DNode::NEW || ((y->pid_ == x->id_) && (y->g_ != x->g_ + getCost(x, y))))
       {
         y->pid_ = x->id_;
         insert(y, x->g_ + getCost(x, y));
       }
       else if (y->pid_ != x->id_ && (y->g_ > x->g_ + getCost(x, y)))
       {
         insert(x, x->g_);
       }
       else if (y->pid_ != x->id_ && (x->g_ > y->g_ + getCost(y, x)) && y->t_ == DNode::CLOSED && (y->g_ > k_old))
       {
         insert(y, y->g_);
       }
     }
   }
   return open_list_.begin()->first;
 }
References DNode::CLOSED, expand_, Node::g_, getCost(), getNeighbours(), Node::id_, insert(), DNode::NEW, open_list_, Node::pid_, and DNode::t_.
Referenced by plan().
reset()
void global_planner::DStar::reset ()
Reset the system.
 {
   open_list_.clear();
   for (int i = 0; i < nx_; ++i)
     for (int j = 0; j < ny_; ++j)
       delete map_[i][j];
   for (int i = 0; i < nx_; ++i)
     delete[] map_[i];
   delete[] map_;
   initMap();
 }
References initMap(), map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, and open_list_.
Referenced by plan().
Member Data Documentation
curr_global_costmap_
unsigned char* global_planner::DStar::curr_global_costmap_
Referenced by DStar(), isCollision(), and plan().
expand_
std::vector<Node> global_planner::DStar::expand_
Referenced by plan(), and processState().
goal_
Node global_planner::DStar::goal_
Referenced by DStar(), and plan().
last_global_costmap_
unsigned char* global_planner::DStar::last_global_costmap_
Referenced by DStar(), and plan().
map_
DNodePtr** global_planner::DStar::map_
Referenced by extractExpand(), extractPath(), getNeighbours(), initMap(), plan(), and reset().
open_list_
std::multimap<double, DNodePtr> global_planner::DStar::open_list_
Referenced by insert(), processState(), and reset().
path_
std::vector<Node> global_planner::DStar::path_
Referenced by extractPath(), getState(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/d_star.h
src/core/global_planner/graph_planner/src/d_star.cpp