ROS Motion Planning: displays.Displays Class Reference
displays.Displays Class Reference
Public Member Functions
def __init__ (self)
def addDisplay (self, name, class_name, topic=None, color=None, fields={}, enabled=True)
def addMap (self, topic="/map", name="Map", alpha=None, scheme=None)
def addGrid (self)
def addTf (self, scale=None)
def addGroup (self, name, displays)
def addModel (self, parameter="robot_description", tf_prefix=None)
def addLaserscan (self, topic="/base_scan", name=None, color=(46, 255, 0), size=0.1, alpha=None)
def addPoseArray (self, topic="/particlecloud", color=None)
def addFootprint (self, topic, color=(0, 170, 255))
def addPath (self, topic, name, color=None)
def addPose (self, topic, name="Current Goal", color=None, arrow_shape=None)
def addImage (self, topic="/camera/rgb/image_raw", name="Image")
Constructor & Destructor Documentation
__init__()
def displays.Displays.__init__ (self)
     def __init__(self):
         None
Member Function Documentation
addDisplay()
def displays.Displays.addDisplay (self, name, class_name, topic = None, color = None, fields = {}, enabled = True)
     def addDisplay(self, name, class_name, topic=None, color=None, fields={}, enabled=True):
         d = {"Name": name, "Class": class_name, "Enabled": enabled}
         if topic:
             d["Topic"] = topic
         if color:
             d["Color"] = "%d; %d; %d" % color
         d.update(fields)
         self.append(d)
Referenced by displays.Displays.addFootprint(), displays.Displays.addGrid(), displays.Displays.addGroup(), displays.Displays.addImage(), displays.Displays.addLaserscan(), displays.Displays.addMap(), displays.Displays.addModel(), displays.Displays.addPath(), displays.Displays.addPose(), displays.Displays.addPoseArray(), and displays.Displays.addTf().
addFootprint()
def displays.Displays.addFootprint (self, topic, color = (0, 170, 255))
     def addFootprint(self, topic, color=(0, 170, 255)):
         self.addDisplay("Robot Footprint", "rviz/Polygon", topic, color)
References displays.Displays.addDisplay().
addGrid()
def displays.Displays.addGrid (self)
     def addGrid(self):
         self.addDisplay("Grid", "rviz/Grid")
References displays.Displays.addDisplay().
addGroup()
def displays.Displays.addGroup (self, name, displays)
     def addGroup(self, name, displays):
         self.addDisplay(name, "rviz/Group", fields={"Displays": displays})
References displays.Displays.addDisplay().
addImage()
def displays.Displays.addImage (self, topic = "/camera/rgb/image_raw", name = "Image")
     def addImage(self, topic="/camera/rgb/image_raw", name="Image"):
         self.addDisplay(name, "rviz/Image", topic, enabled=False)
References displays.Displays.addDisplay().
addLaserscan()
def displays.Displays.addLaserscan (self, topic = "/base_scan", name = None, color = (46, 255, 0), size = 0.1, alpha = None)
     def addLaserscan(self, topic="/base_scan", name=None, color=(46, 255, 0), size=0.1, alpha=None):
         if name is None:
             name = topic
         fields = {"Size (m)": size, "Style": "Spheres", "Color Transformer": "FlatColor"}
         if alpha:
             fields["Alpha"] = alpha
         self.addDisplay(name, "rviz/LaserScan", topic, color, fields)
References displays.Displays.addDisplay().
addMap()
def displays.Displays.addMap (self, topic = "/map", name = "Map", alpha = None, scheme = None)
     def addMap(self, topic="/map", name="Map", alpha=None, scheme=None):
         fields = {}
         if alpha:
             fields["Alpha"] = alpha
         if scheme:
             fields["Color Scheme"] = scheme
         self.addDisplay(name, "rviz/Map", topic, fields=fields)
References displays.Displays.addDisplay().
addModel()
def displays.Displays.addModel (self, parameter = "robot_description", tf_prefix = None)
     def addModel(self, parameter="robot_description", tf_prefix=None):
         fields = {"Robot Description": parameter}
         if tf_prefix:
             fields["TF Prefix"] = tf_prefix
         self.addDisplay("RobotModel", "rviz/RobotModel", fields=fields)
References displays.Displays.addDisplay().
addPath()
def displays.Displays.addPath (self, topic, name, color = None)
     def addPath(self, topic, name, color=None):
         self.addDisplay(name, "rviz/Path", topic, color)
References displays.Displays.addDisplay().
addPose()
def displays.Displays.addPose (self, topic, name = "Current Goal", color = None, arrow_shape = None)
     def addPose(self, topic, name="Current Goal", color=None, arrow_shape=None):
         fields = {}
         if arrow_shape:
             fields["Head Length"] = arrow_shape[0]
             fields["Head Radius"] = arrow_shape[1]
             fields["Shaft Length"] = arrow_shape[2]
             fields["Shaft Radius"] = arrow_shape[3]
             fields["Shape"] = "Arrow"
         self.addDisplay(name, "rviz/Pose", topic, color, fields)
References displays.Displays.addDisplay().
addPoseArray()
def displays.Displays.addPoseArray (self, topic = "/particlecloud", color = None)
     def addPoseArray(self, topic="/particlecloud", color=None):
         self.addDisplay("AMCL Cloud", "rviz/PoseArray", topic, color)
References displays.Displays.addDisplay().
addTf()
def displays.Displays.addTf (self, scale = None)
     def addTf(self, scale=None):
         fields = {}
         if scale:
             fields["Marker Scale"] = scale
         self.addDisplay("TF", "rviz/TF", fields=fields, enabled=False)
References displays.Displays.addDisplay().
The documentation for this class was generated from the following file:
src/third_party/dynamic_rviz_config/scripts/displays.py