ROS Motion Planning: global_planner::JumpPointSearch Class Reference
global_planner::JumpPointSearch Class Reference
lass for objects that plan using the Jump Point Search(JPS) algorithm
#include <jump_point_search.h>
Public Member Functions
JumpPointSearch (int nx, int ny, double resolution)
Constructor.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Jump Point Search(JPS) implementation.
Node jump (const Node &point, const Node &motion)
Calculate jump node recursively.
bool detectForceNeighbor (const Node &point, const Node &motion)
Detect whether current node has forced neighbor or not.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Private Attributes
Node start_
Node goal_
const unsigned char * costs_
Additional Inherited Members
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
lass for objects that plan using the Jump Point Search(JPS) algorithm
Constructor & Destructor Documentation
JumpPointSearch()
global_planner::JumpPointSearch::JumpPointSearch (int nx, int ny, double resolution)
Constructor.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
                                                                   : GlobalPlanner(nx, ny, resolution)
 {
 }
Member Function Documentation
detectForceNeighbor()
bool global_planner::JumpPointSearch::detectForceNeighbor (const Node & point, const Node & motion)
Detect whether current node has forced neighbor or not.
Detect whether current node has forced neighbors.
Parameters
point current node
motion the motion that current node executes
Returns
true if current node has forced neighbor else false
 {
   int x = point.x_;
   int y = point.y_;
   int x_dir = motion.x_;
   int y_dir = motion.y_;
   // horizontal
   if (x_dir && !y_dir)
   {
     if (costs_[grid2Index(x, y + 1)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x + x_dir, y + 1)] < lethal_cost_ * factor_)
       return true;
     if (costs_[grid2Index(x, y - 1)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x + x_dir, y - 1)] < lethal_cost_ * factor_)
       return true;
   }
   // vertical
   if (!x_dir && y_dir)
   {
     if (costs_[grid2Index(x + 1, y)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x + 1, y + y_dir)] < lethal_cost_ * factor_)
       return true;
     if (costs_[grid2Index(x - 1, y)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x - 1, y + y_dir)] < lethal_cost_ * factor_)
       return true;
   }
   // diagonal
   if (x_dir && y_dir)
   {
     if (costs_[grid2Index(x - x_dir, y)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x - x_dir, y + y_dir)] < lethal_cost_ * factor_)
       return true;
     if (costs_[grid2Index(x, y - y_dir)] >= lethal_cost_ * factor_ &&
         costs_[grid2Index(x + x_dir, y - y_dir)] < lethal_cost_ * factor_)
       return true;
   }
   return false;
 }
References costs_, global_planner::GlobalPlanner::factor_, global_planner::GlobalPlanner::grid2Index(), global_planner::GlobalPlanner::lethal_cost_, Node::x_, and Node::y_.
Referenced by jump().
jump()
Node global_planner::JumpPointSearch::jump (const Node & point, const Node & motion)
Calculate jump node recursively.
Parameters
point current node
motion the motion that current node executes
Returns
jump node
 {
   Node new_point = point + motion;
   new_point.id_ = grid2Index(new_point.x_, new_point.y_);
   new_point.pid_ = point.id_;
   new_point.h_ = std::sqrt(std::pow(new_point.x_ - goal_.x_, 2) + std::pow(new_point.y_ - goal_.y_, 2));
   // next node hit the boundary or obstacle
   if (new_point.id_ < 0 || new_point.id_ >= ns_ || costs_[new_point.id_] >= lethal_cost_ * factor_)
     return Node(-1, -1, -1, -1, -1, -1);
   // goal found
   if (new_point == goal_)
     return new_point;
   // diagonal
   if (motion.x_ && motion.y_)
   {
     // if exists jump point at horizontal or vertical
     Node x_dir = Node(motion.x_, 0, 1, 0, 0, 0);
     Node y_dir = Node(0, motion.y_, 1, 0, 0, 0);
     if (jump(new_point, x_dir).id_ != -1 || jump(new_point, y_dir).id_ != -1)
       return new_point;
   }
   // exists forced neighbor
   if (detectForceNeighbor(new_point, motion))
     return new_point;
   else
     return jump(new_point, motion);
 }
References costs_, detectForceNeighbor(), global_planner::GlobalPlanner::factor_, goal_, global_planner::GlobalPlanner::grid2Index(), Node::h_, Node::id_, global_planner::GlobalPlanner::lethal_cost_, global_planner::GlobalPlanner::ns_, Node::pid_, Node::x_, and Node::y_.
Referenced by plan().
plan()
bool global_planner::JumpPointSearch::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
Jump Point Search(JPS) implementation.
Parameters
costs costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Parameters
global_costmap costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements global_planner::GlobalPlanner.
 {
   // copy
   costs_ = global_costmap;
   start_ = start, goal_ = goal;
   // clear vector
   path.clear();
   expand.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start);
   // get all possible motions
   std::vector<Node> motions = Node::getMotion();
   // main loop
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     // current node do not exist in closed list
     if (closed_list.find(current.id_) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id_, current));
     expand.push_back(current);
     // goal found
     if (current == goal)
     {
       path = _convertClosedListToPath(closed_list, start, goal);
       return true;
     }
     // explore neighbor of current node
     for (const auto& motion : motions)
     {
       Node node_new = jump(current, motion);
       // node_new not exits or in closed list
       if (node_new.id_ == -1 || closed_list.find(node_new.id_) != closed_list.end())
         continue;
       node_new.pid_ = current.id_;
       open_list.push(node_new);
     }
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), costs_, Node::getMotion(), goal_, Node::id_, jump(), Node::pid_, and start_.
Member Data Documentation
costs_
const unsigned char* global_planner::JumpPointSearch::costs_ private
Referenced by detectForceNeighbor(), jump(), and plan().
goal_
Node global_planner::JumpPointSearch::goal_ private
Referenced by jump(), and plan().
start_
Node global_planner::JumpPointSearch::start_ private
Referenced by plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/jump_point_search.h
src/core/global_planner/graph_planner/src/jump_point_search.cpp