ROS Motion Planning: orca_planner::OrcaPlanner Class Reference
orca_planner::OrcaPlanner Class Reference
#include <orca_planner.h>
Public Member Functions
OrcaPlanner ()
OrcaPlanner (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
~OrcaPlanner ()
void initialize (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
bool setPlan (const std::vector< geometry_msgs::PoseStamped > &orig_global_plan)
bool computeVelocityCommands (geometry_msgs::Twist &cmd_vel)
bool isGoalReached ()
Private Member Functions
void odometryCallback (const nav_msgs::OdometryConstPtr &msg, int agent_id)
void initState ()
void updateState ()
Private Member Functions inherited from local_planner::LocalPlanner
LocalPlanner ()
Construct a new Local Planner object.
~LocalPlanner ()
Destroy the Local Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setBaseFrame (std::string base_frame)
Set or reset frame name.
void setMapFrame (std::string map_frame)
double regularizeAngle (double angle)
Regularize angle to [-pi, pi].
Eigen::Vector3d getEulerAngles (geometry_msgs::PoseStamped &ps)
Get the Euler Angles from PoseStamped.
bool shouldRotateToGoal (const geometry_msgs::PoseStamped &cur, const geometry_msgs::PoseStamped &goal)
Whether to reach the target pose through rotation operation.
bool shouldRotateToPath (double angle_to_path, double tolerance=0.0)
Whether to correct the tracking path with rotation operation.
double linearRegularization (nav_msgs::Odometry &base_odometry, double v_d)
linear velocity regularization
double angularRegularization (nav_msgs::Odometry &base_odometry, double w_d)
angular velocity regularization
void transformPose (tf2_ros::Buffer *tf, const std::string out_frame, const geometry_msgs::PoseStamped &in_pose, geometry_msgs::PoseStamped &out_pose) const
Tranform from in_pose to out_pose with out frame using tf.
bool worldToMap (double wx, double wy, int &mx, int &my)
Tranform from world map(x, y) to costmap(x, y)
std::vector< geometry_msgs::PoseStamped > prune (const geometry_msgs::PoseStamped robot_pose_global)
Prune the path, removing the waypoints that the robot has already passed and distant waypoints.
double getLookAheadDistance (double vt)
Calculate the look-ahead distance with current speed dynamically.
void getLookAheadPoint (double lookahead_dist, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > &prune_plan, geometry_msgs::PointStamped &pt, double &theta, double &kappa)
find the point on the path that is exactly the lookahead distance away from the robot
Private Attributes
costmap_2d::Costmap2DROS * costmap_ros_
tf2_ros::Buffer * tf_
bool initialized_
bool odom_flag_
bool goal_reached_
int agent_number_
int agent_id_
double d_t_
double neighbor_dist_
double time_horizon_
double time_horizon_obst_
double radius_
int max_neighbors_
RVO::RVOSimulator * sim_
RVO::Vector2 goal_
std::vector< ros::Subscriber > odom_subs_
std::vector< nav_msgs::Odometry > other_odoms_
Private Attributes inherited from local_planner::LocalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double origin_x_
double origin_y_
double resolution_
double convert_offset_
double factor_
double max_v_
double min_v_
double max_v_inc_
double max_w_
double min_w_
double max_w_inc_
double goal_dist_tol_
double rotate_tol_
std::string base_frame_
std::string map_frame_
std::string odom_frame_
base_local_planner::OdometryHelperRos * odom_helper_
costmap_2d::Costmap2DROS * costmap_ros_
std::vector< geometry_msgs::PoseStamped > global_plan_
double lookahead_time_
double min_lookahead_dist_
double max_lookahead_dist_
Constructor & Destructor Documentation
OrcaPlanner() [1/2]
orca_planner::OrcaPlanner::OrcaPlanner ()
   : initialized_(false), costmap_ros_(nullptr), tf_(nullptr), odom_flag_(false), goal_reached_(false)
 {
 }
OrcaPlanner() [2/2]
orca_planner::OrcaPlanner::OrcaPlanner (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
                                                                                                : OrcaPlanner()
 {
   initialize(name, tf, costmap_ros);
 }
References initialize(), and rviz_generate::name.
~OrcaPlanner()
orca_planner::OrcaPlanner::~OrcaPlanner ()
 {
 }
Member Function Documentation
computeVelocityCommands()
bool orca_planner::OrcaPlanner::computeVelocityCommands (geometry_msgs::Twist & cmd_vel)
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized");
     return false;
   }
   nav_msgs::Odometry agent_odom = other_odoms_[agent_id_ - 1];
   RVO::Vector2 curr_pose(agent_odom.pose.pose.position.x, agent_odom.pose.pose.position.y);
   if (RVO::abs(goal_ - curr_pose) < goal_dist_tol_)
   {
     cmd_vel.linear.x = 0.0;
     cmd_vel.angular.z = 0.0;
     goal_reached_ = true;
   }
   else
   {
     updateState();
     RVO::Vector2 new_speed = sim_->getAgentNewSpeed(agent_id_ - 1);
     // transform from linear.x and linear.y to linear.x and angular.z
     double theta = tf2::getYaw(agent_odom.pose.pose.orientation);
     double v_d = RVO::abs(new_speed);
     double theta_d = std::atan2(new_speed.y(), new_speed.x());
     double e_theta = regularizeAngle(theta_d - theta);
     double w_d = e_theta / d_t_;
     cmd_vel.linear.x = linearRegularization(agent_odom, v_d);
     cmd_vel.angular.z = angularRegularization(agent_odom, w_d);
   }
   return true;
 }
References RVO::abs(), agent_id_, local_planner::LocalPlanner::angularRegularization(), d_t_, RVO::RVOSimulator::getAgentNewSpeed(), goal_, local_planner::LocalPlanner::goal_dist_tol_, goal_reached_, initialized_, local_planner::LocalPlanner::linearRegularization(), other_odoms_, local_planner::LocalPlanner::regularizeAngle(), sim_, updateState(), RVO::Vector2::x(), and RVO::Vector2::y().
initialize()
void orca_planner::OrcaPlanner::initialize (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
 {
   if (!initialized_)
   {
     initialized_ = true;
     tf_ = tf;
     costmap_ros_ = costmap_ros;
     ros::NodeHandle nh = ros::NodeHandle("~/" + name);
     // base
     nh.param("goal_dist_tolerance", goal_dist_tol_, 0.2);
     nh.param("rotate_tolerance", rotate_tol_, 0.5);
     nh.param("base_frame", base_frame_, base_frame_);
     nh.param("map_frame", map_frame_, map_frame_);
     // multi-robot info
     nh.param("agent_number", agent_number_, -1);
     nh.param("agent_id", agent_id_, -1);
     // linear velocity
     nh.param("max_v", max_v_, 0.5);
     nh.param("min_v", min_v_, 0.0);
     nh.param("max_v_inc", max_v_inc_, 0.5);
     // angular velocity
     nh.param("max_w", max_w_, 1.57);
     nh.param("min_w", min_w_, 0.0);
     nh.param("max_w_inc", max_w_inc_, 1.57);
     // orca parameters
     nh.param("neighbor_dist", neighbor_dist_, 3.0);
     nh.param("time_horizon", time_horizon_, 5.0);
     nh.param("time_horizon_obst", time_horizon_obst_, 3.0);
     nh.param("radius", radius_, 0.2);
     nh.param("max_neighbors", max_neighbors_, 10);
     other_odoms_.resize(agent_number_);
     for (int i = 0; i < agent_number_; ++i)
     {
       ros::Subscriber odom_sub = nh.subscribe<nav_msgs::Odometry>(
           "/robot" + std::to_string(i + 1) + "/odom", 1, boost::bind(&OrcaPlanner::odometryCallback, this, _1, i + 1));
       odom_subs_.push_back(odom_sub);
       ROS_INFO("agent %d, subscribe to agent %d.", agent_id_, i + 1);
     }
     int spin_cnt = 5 * agent_number_;
     ros::Rate rate(10);
     ROS_WARN("[ORCA] Waiting for odoms...");
     while (spin_cnt-- > 0)
     {
       ros::spinOnce();
       rate.sleep();
     }
     double controller_freqency;
     nh.param("/move_base/controller_frequency", controller_freqency, 10.0);
     d_t_ = 1 / controller_freqency;
     sim_ = new RVO::RVOSimulator();
     initState();
     ROS_INFO("ORCA planner initialized!");
   }
   else
   {
     ROS_WARN("ORCA planner has already been initialized.");
   }
 }
References agent_id_, agent_number_, local_planner::LocalPlanner::base_frame_, costmap_ros_, d_t_, local_planner::LocalPlanner::goal_dist_tol_, initialized_, initState(), local_planner::LocalPlanner::map_frame_, max_neighbors_, local_planner::LocalPlanner::max_v_, local_planner::LocalPlanner::max_v_inc_, local_planner::LocalPlanner::max_w_, local_planner::LocalPlanner::max_w_inc_, local_planner::LocalPlanner::min_v_, local_planner::LocalPlanner::min_w_, rviz_generate::name, neighbor_dist_, odom_subs_, odometryCallback(), other_odoms_, radius_, send_test_msgs::rate, local_planner::LocalPlanner::rotate_tol_, sim_, tf_, time_horizon_, and time_horizon_obst_.
Referenced by OrcaPlanner().
initState()
void orca_planner::OrcaPlanner::initState () private
 {
   if (!odom_flag_)
   {
     ROS_ERROR("Odom not received!");
     return;
   }
   sim_->setTimeStep(d_t_);
   sim_->setAgentDefaults(neighbor_dist_, max_neighbors_, time_horizon_, time_horizon_obst_, radius_, max_v_);
   for (int i = 0; i < agent_number_; ++i)
   {
     sim_->addAgent(RVO::Vector2(other_odoms_[i].pose.pose.position.x, other_odoms_[i].pose.pose.position.y));
     sim_->setAgentVelocity(i, RVO::Vector2(other_odoms_[i].twist.twist.linear.x, other_odoms_[i].twist.twist.linear.y));
   }
 }
References RVO::RVOSimulator::addAgent(), agent_number_, d_t_, max_neighbors_, local_planner::LocalPlanner::max_v_, neighbor_dist_, odom_flag_, other_odoms_, radius_, RVO::RVOSimulator::setAgentDefaults(), RVO::RVOSimulator::setAgentVelocity(), RVO::RVOSimulator::setTimeStep(), sim_, time_horizon_, and time_horizon_obst_.
Referenced by initialize().
isGoalReached()
bool orca_planner::OrcaPlanner::isGoalReached ()
 {
   if (!initialized_)
   {
     ROS_ERROR("ORCA planner has not been initialized");
     return false;
   }
   if (goal_reached_)
   {
     ROS_INFO("GOAL Reached!");
     return true;
   }
   return false;
 }
References goal_reached_, and initialized_.
odometryCallback()
void orca_planner::OrcaPlanner::odometryCallback (const nav_msgs::OdometryConstPtr & msg, int agent_id) private
 {
   if (!odom_flag_)
     odom_flag_ = true;
   other_odoms_[agent_id - 1] = *msg;
 }
References odom_flag_, and other_odoms_.
Referenced by initialize().
setPlan()
bool orca_planner::OrcaPlanner::setPlan (const std::vector< geometry_msgs::PoseStamped > & orig_global_plan)
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized");
     return false;
   }
   ROS_INFO("Got new plan");
   if (goal_.x() != orig_global_plan.back().pose.position.x || goal_.y() != orig_global_plan.back().pose.position.y)
   {
     goal_ = RVO::Vector2(orig_global_plan.back().pose.position.x, orig_global_plan.back().pose.position.y);
     goal_reached_ = false;
   }
   return true;
 }
References goal_, goal_reached_, initialized_, RVO::Vector2::x(), and RVO::Vector2::y().
updateState()
void orca_planner::OrcaPlanner::updateState () private
 {
   for (int i = 0; i < agent_number_; ++i)
   {
     sim_->setAgentPosition(i, RVO::Vector2(other_odoms_[i].pose.pose.position.x, other_odoms_[i].pose.pose.position.y));
     sim_->setAgentVelocity(i, RVO::Vector2(other_odoms_[i].twist.twist.linear.x, other_odoms_[i].twist.twist.linear.y));
   }
   sim_->setAgentPrefVelocity(agent_id_ - 1, RVO::normalize(goal_ - sim_->getAgentPosition(agent_id_ - 1)) * max_v_);
 }
References agent_id_, agent_number_, RVO::RVOSimulator::getAgentPosition(), goal_, local_planner::LocalPlanner::max_v_, RVO::normalize(), other_odoms_, RVO::RVOSimulator::setAgentPosition(), RVO::RVOSimulator::setAgentPrefVelocity(), RVO::RVOSimulator::setAgentVelocity(), and sim_.
Referenced by computeVelocityCommands().
Member Data Documentation
agent_id_
int orca_planner::OrcaPlanner::agent_id_ private
Referenced by computeVelocityCommands(), initialize(), and updateState().
agent_number_
int orca_planner::OrcaPlanner::agent_number_ private
Referenced by initialize(), initState(), and updateState().
costmap_ros_
costmap_2d::Costmap2DROS* orca_planner::OrcaPlanner::costmap_ros_ private
Referenced by initialize().
d_t_
double orca_planner::OrcaPlanner::d_t_ private
Referenced by computeVelocityCommands(), initialize(), and initState().
goal_
RVO::Vector2 orca_planner::OrcaPlanner::goal_ private
Referenced by computeVelocityCommands(), setPlan(), and updateState().
goal_reached_
bool orca_planner::OrcaPlanner::goal_reached_ private
Referenced by computeVelocityCommands(), isGoalReached(), and setPlan().
initialized_
bool orca_planner::OrcaPlanner::initialized_ private
Referenced by computeVelocityCommands(), initialize(), isGoalReached(), and setPlan().
max_neighbors_
int orca_planner::OrcaPlanner::max_neighbors_ private
Referenced by initialize(), and initState().
neighbor_dist_
double orca_planner::OrcaPlanner::neighbor_dist_ private
Referenced by initialize(), and initState().
odom_flag_
bool orca_planner::OrcaPlanner::odom_flag_ private
Referenced by initState(), and odometryCallback().
odom_subs_
std::vector<ros::Subscriber> orca_planner::OrcaPlanner::odom_subs_ private
Referenced by initialize().
other_odoms_
std::vector<nav_msgs::Odometry> orca_planner::OrcaPlanner::other_odoms_ private
Referenced by computeVelocityCommands(), initialize(), initState(), odometryCallback(), and updateState().
radius_
double orca_planner::OrcaPlanner::radius_ private
Referenced by initialize(), and initState().
sim_
RVO::RVOSimulator* orca_planner::OrcaPlanner::sim_ private
Referenced by computeVelocityCommands(), initialize(), initState(), and updateState().
tf_
tf2_ros::Buffer* orca_planner::OrcaPlanner::tf_ private
Referenced by initialize().
time_horizon_
double orca_planner::OrcaPlanner::time_horizon_ private
Referenced by initialize(), and initState().
time_horizon_obst_
double orca_planner::OrcaPlanner::time_horizon_obst_ private
Referenced by initialize(), and initState().
The documentation for this class was generated from the following files:
src/core/local_planner/orca_planner/include/orca_planner.h
src/core/local_planner/orca_planner/src/orca_planner.cpp