ROS Motion Planning: global_planner::HybridAStar Class Reference
global_planner::HybridAStar Class Reference
Class for objects that plan using the A* algorithm.
#include <hybrid_a_star.h>
Classes
class HybridNode
Public Member Functions
HybridAStar (int nx, int ny, double resolution, bool is_reverse, double max_curv)
Construct a new Hybrid A* object.
~HybridAStar ()
Destory the Hybrid A* object.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Hybrid A* implementation.
bool plan (const unsigned char *global_costmap, HybridNode &start, HybridNode &goal, std::vector< Node > &path, std::vector< Node > &expand)
bool dubinsShot (const HybridNode &start, const HybridNode &goal, std::vector< Node > &path)
Try using Dubins curves to connect the start and goal.
void updateIndex (HybridNode &node)
update index of hybrid node
void updateHeuristic (HybridNode &node)
update the h-value of hybrid node
void genHeurisiticMap (const Node &start)
generate heurisitic map using A* algorithm, each matric of map is the distance between it and start.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
void _worldToGrid (double wx, double wy, int &gx, int &gy)
Tranform from world map(x, y) to grid map(x, y)
int _worldToIndex (double wx, double wy)
Tranform from world map(x, y) to grid index(i)
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, HybridNode > &closed_list, const HybridNode &start, const HybridNode &goal)
Convert closed list to path.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
HybridNode goal_
std::unordered_map< int, Node > h_map_
const unsigned char * costmap_
bool is_reverse_
double max_curv_
trajectory_generation::Dubins dubins_gen_
AStar * a_star_planner_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the A* algorithm.
Constructor & Destructor Documentation
HybridAStar()
global_planner::HybridAStar::HybridAStar (int nx, int ny, double resolution, bool is_reverse, double max_curv)
Construct a new Hybrid A* object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
is_reverse whether reverse operation is allowed
max_curv maximum curvature of model
   : GlobalPlanner(nx, ny, resolution), is_reverse_(is_reverse), max_curv_(max_curv)
 {
   dubins_gen_.setStep(1.5);
   dubins_gen_.setMaxCurv(max_curv_);
   goal_ = HybridNode();
   a_star_planner_ = new AStar(nx, ny, resolution);
 }
References a_star_planner_, dubins_gen_, goal_, max_curv_, trajectory_generation::Dubins::setMaxCurv(), and trajectory_generation::Curve::setStep().
~HybridAStar()
global_planner::HybridAStar::~HybridAStar ()
Destory the Hybrid A* object.
 {
   delete costmap_;
   delete a_star_planner_;
 }
References a_star_planner_, and costmap_.
Member Function Documentation
_convertClosedListToPath()
std::vector< Node > global_planner::HybridAStar::_convertClosedListToPath (std::unordered_map< int, HybridNode > & closed_list, const HybridNode & start, const HybridNode & goal) protected
Convert closed list to path.
Parameters
closed_list closed list
start start node
goal goal node
Returns
vector containing path nodes
 {
   int cur_x, cur_y;
   std::vector<Node> path;
   auto current = closed_list.find(goal.id_);
   while (current->second != start)
   {
     _worldToGrid(current->second.x_, current->second.y_, cur_x, cur_y);
     path.emplace_back(cur_x, cur_y);
     auto it = closed_list.find(current->second.pid_);
     if (it != closed_list.end())
       current = it;
     else
       return {};
   }
   _worldToGrid(start.x_, start.y_, cur_x, cur_y);
   path.emplace_back(cur_x, cur_y);
   return path;
 }
References _worldToGrid(), Node::id_, global_planner::HybridAStar::HybridNode::x_, and global_planner::HybridAStar::HybridNode::y_.
Referenced by plan().
_worldToGrid()
void global_planner::HybridAStar::_worldToGrid (double wx, double wy, int & gx, int & gy) protected
Tranform from world map(x, y) to grid map(x, y)
Parameters
gx grid map x
gy grid map y
wx world map x
wy world map y
 {
   double mx, my;
   world2Map(wx, wy, mx, my);
   map2Grid(mx, my, gx, gy);
 }
References global_planner::GlobalPlanner::map2Grid(), and global_planner::GlobalPlanner::world2Map().
Referenced by _convertClosedListToPath(), and _worldToIndex().
_worldToIndex()
int global_planner::HybridAStar::_worldToIndex (double wx, double wy) protected
Tranform from world map(x, y) to grid index(i)
Parameters
wx world map x
wy world map y
Returns
index
 {
   int gx, gy;
   _worldToGrid(wx, wy, gx, gy);
   return grid2Index(gx, gy);
 }
References _worldToGrid(), and global_planner::GlobalPlanner::grid2Index().
Referenced by plan(), updateHeuristic(), and updateIndex().
dubinsShot()
bool global_planner::HybridAStar::dubinsShot (const HybridNode & start, const HybridNode & goal, std::vector< Node > & path)
Try using Dubins curves to connect the start and goal.
Parameters
start start node
goal goal node
path dubins path between start and goal
Returns
true if shot successfully, else false
 {
   double sx, sy, gx, gy;
   world2Map(start.x_, start.y_, sx, sy);
   world2Map(goal.x_, goal.y_, gx, gy);
   std::vector<std::tuple<double, double, double>> poes = { { sx, sy, start.t_ }, { gx, gy, goal.t_ } };
   std::vector<std::pair<double, double>> path_dubins;
   if (dubins_gen_.run(poes, path_dubins))
   {
     path.clear();
     for (auto const& p : path_dubins)
     {
       if (costmap_[grid2Index(p.first, p.second)] >= lethal_cost_ * factor_)
         return false;
       else
         path.emplace_back(p.first, p.second);
     }
     return true;
   }
   else
     return false;
 }
References costmap_, dubins_gen_, global_planner::GlobalPlanner::factor_, global_planner::GlobalPlanner::grid2Index(), global_planner::GlobalPlanner::lethal_cost_, trajectory_generation::Dubins::run(), global_planner::HybridAStar::HybridNode::t_, global_planner::GlobalPlanner::world2Map(), global_planner::HybridAStar::HybridNode::x_, and global_planner::HybridAStar::HybridNode::y_.
Referenced by plan().
genHeurisiticMap()
void global_planner::HybridAStar::genHeurisiticMap (const Node & start)
generate heurisitic map using A* algorithm, each matric of map is the distance between it and start.
Parameters
start start node
 {
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> open_set;
   open_list.push(start);
   open_set.emplace(start.id_, start);
   // get all possible motions
   const std::vector<Node> motions = Node::getMotion();
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     h_map_.emplace(current.id_, current);
     // explore neighbor of current node
     for (const auto& motion : motions)
     {
       // explore a new node
       Node node_new = current + motion;
       node_new.id_ = grid2Index(node_new.x_, node_new.y_);
       // node_new in closed list
       if (h_map_.find(node_new.id_) != h_map_.end())
         continue;
       // next node hit the boundary or obstacle
       // prevent planning failed when the current within inflation
       if ((node_new.id_ < 0) || (node_new.id_ >= ns_))
         continue;
       if (open_set.find(node_new.id_) != open_set.end())
       {
         if (open_set[node_new.id_].g_ > node_new.g_)
           open_set[node_new.id_].g_ = node_new.g_;
       }
       else
       {
         open_list.push(node_new);
         open_set.emplace(node_new.id_, node_new);
       }
     }
   }
 }
References Node::g_, Node::getMotion(), global_planner::GlobalPlanner::grid2Index(), h_map_, Node::id_, global_planner::GlobalPlanner::ns_, Node::x_, and Node::y_.
Referenced by plan().
plan() [1/2]
bool global_planner::HybridAStar::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
Hybrid A* implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   return false;
 }
plan() [2/2]
bool global_planner::HybridAStar::plan (const unsigned char * global_costmap, HybridNode & start, HybridNode & goal, std::vector< Node > & path, std::vector< Node > & expand)
 {
   // intialization
   path.clear();
   expand.clear();
   costmap_ = global_costmap;
   updateIndex(start);
   updateIndex(goal);
   // update heuristic map
   if (goal_ != goal)
   {
     goal_ = goal;
     double gx, gy;
     world2Map(goal.x_, goal.y_, gx, gy);
     Node h_start(gx, gy, 0, 0, grid2Index(gx, gy), 0);
     genHeurisiticMap(h_start);
   }
   // possible directions and motions
   int dir = is_reverse_ ? 6 : 3;
   const std::vector<HybridNode> motions = HybridNode::getMotion();
   // open list and closed list
   std::priority_queue<HybridNode, std::vector<HybridNode>, HybridNode::compare_cost> open_list;
   std::unordered_map<int, HybridNode> closed_list;
   open_list.push(start);
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     HybridNode current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id_) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id_, current));
     expand.emplace_back(current.x_, current.y_, 0, 0, _worldToIndex(current.x_, current.y_));
     // goal shot
     std::vector<Node> path_dubins;
     if (std::hypot(current.x_ - goal.x_, current.y_ - goal.y_) < 50)
     {
       if (dubinsShot(current, goal, path_dubins))
       {
         path = _convertClosedListToPath(closed_list, start, current);
         std::reverse(path.begin(), path.end());
         path.insert(path.end(), path_dubins.begin(), path_dubins.end());
         std::reverse(path.begin(), path.end());
         return true;
       }
     }
     // explore neighbor of current node
     for (size_t i = 0; i < dir; i++)
     {
       // explore a new node
       HybridNode node_new = current + motions[i];
       updateIndex(node_new);
       // node_new in closed list
       if (closed_list.find(node_new.id_) != closed_list.end())
         continue;
       // next node hit the boundary or obstacle
       // prevent planning failed when the current within inflation
       if ((_worldToIndex(node_new.x_, node_new.y_) < 0) || (_worldToIndex(node_new.x_, node_new.y_) >= ns_) ||
           (node_new.t_ / DELTA_HEADING >= HEADINGS) ||
           (global_costmap[_worldToIndex(node_new.x_, node_new.y_)] >= lethal_cost_ * factor_ &&
            global_costmap[_worldToIndex(node_new.x_, node_new.y_)] >=
                global_costmap[_worldToIndex(current.x_, current.y_)]))
         continue;
       node_new.pid_ = current.id_;
       updateHeuristic(node_new);
       open_list.push(node_new);
     }
   }
   // candidate A* path
   double sx, sy, gx, gy;
   world2Map(start.x_, start.y_, sx, sy);
   world2Map(goal.x_, goal.y_, gx, gy);
   return a_star_planner_->plan(global_costmap, Node(sx, sy, 0, 0, grid2Index(sx, sy)),
                                Node(gx, gy, 0, 0, grid2Index(gx, gy)), path, expand);
 }
References _convertClosedListToPath(), _worldToIndex(), a_star_planner_, costmap_, DELTA_HEADING, dubinsShot(), global_planner::GlobalPlanner::factor_, genHeurisiticMap(), global_planner::HybridAStar::HybridNode::getMotion(), goal_, global_planner::GlobalPlanner::grid2Index(), HEADINGS, Node::id_, is_reverse_, global_planner::GlobalPlanner::lethal_cost_, global_planner::GlobalPlanner::ns_, Node::pid_, global_planner::AStar::plan(), global_planner::HybridAStar::HybridNode::t_, updateHeuristic(), updateIndex(), global_planner::GlobalPlanner::world2Map(), global_planner::HybridAStar::HybridNode::x_, and global_planner::HybridAStar::HybridNode::y_.
updateHeuristic()
void global_planner::HybridAStar::updateHeuristic (HybridNode & node)
update the h-value of hybrid node
Parameters
node hybrid node to update
 {
   // Dubins cost function
   double cost_dubins = 0.0;
   // std::vector<std::tuple<double, double, double>> poes = { { node.x_, node.y_, node.t_ },
   //                                                          { goal_.x_, goal_.y_, goal_.t_ } };
   // std::vector<std::pair<double, double>> path_dubins;
   // if (dubins_gen_.run(poes, path_dubins))
   //   cost_dubins = dubins_gen_.len(path_dubins);
   // 2D search cost function
   double cost_2d = h_map_[_worldToIndex(node.x_, node.y_)].g_ * resolution_;
   node.h_ = std::max(cost_2d, cost_dubins);
 }
References _worldToIndex(), h_map_, tf_map2odom::node, and global_planner::GlobalPlanner::resolution_.
Referenced by plan().
updateIndex()
void global_planner::HybridAStar::updateIndex (HybridNode & node)
update index of hybrid node
Parameters
node hybrid node to update
 {
   node.id_ = static_cast<int>(node.t_ / DELTA_HEADING) + _worldToIndex(node.x_, node.y_);
 }
References _worldToIndex(), DELTA_HEADING, and tf_map2odom::node.
Referenced by plan().
Member Data Documentation
a_star_planner_
AStar* global_planner::HybridAStar::a_star_planner_ protected
Referenced by HybridAStar(), plan(), and ~HybridAStar().
costmap_
const unsigned char* global_planner::HybridAStar::costmap_ protected
Referenced by dubinsShot(), plan(), and ~HybridAStar().
dubins_gen_
trajectory_generation::Dubins global_planner::HybridAStar::dubins_gen_ protected
Referenced by dubinsShot(), and HybridAStar().
goal_
HybridNode global_planner::HybridAStar::goal_ protected
Referenced by HybridAStar(), and plan().
h_map_
std::unordered_map<int, Node> global_planner::HybridAStar::h_map_ protected
Referenced by genHeurisiticMap(), and updateHeuristic().
is_reverse_
bool global_planner::HybridAStar::is_reverse_ protected
Referenced by plan().
max_curv_
double global_planner::HybridAStar::max_curv_ protected
Referenced by HybridAStar().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/hybrid_a_star.h
src/core/global_planner/graph_planner/src/hybrid_a_star.cpp