ROS Motion Planning: DynamicVoronoi Class Reference
DynamicVoronoi Class Reference
A DynamicVoronoi object computes and updates a distance map and Voronoi diagram.
#include <dynamicvoronoi.h>
Classes
struct dataCell
Public Member Functions
DynamicVoronoi ()
~DynamicVoronoi ()
void initializeEmpty (int _sizeX, int _sizeY, bool initGridMap=true)
Initialization with an empty map.
void initializeMap (int _sizeX, int _sizeY, bool **_gridMap)
Initialization with a given binary map (false==free, true==occupied)
void occupyCell (int x, int y)
add an obstacle at the specified cell coordinate
void clearCell (int x, int y)
remove an obstacle at the specified cell coordinate
void exchangeObstacles (std::vector< INTPOINT > &newObstacles)
remove old dynamic obstacles and add the new ones
void update (bool updateRealDist=true)
update distance map and Voronoi diagram to reflect the changes
void prune ()
prune the Voronoi diagram
void updateAlternativePrunedDiagram ()
int ** alternativePrunedDiagram () const
retrieve the alternatively pruned diagram. see updateAlternativePrunedDiagram()
int getNumVoronoiNeighborsAlternative (int x, int y) const
retrieve the number of neighbors that are Voronoi nodes (4-connected)
bool isVoronoiAlternative (int x, int y) const
float getDistance (int x, int y) const
returns the obstacle distance at the specified location
int getObstacleX (int x, int y) const
int getObstacleY (int x, int y) const
bool isVoronoi (int x, int y) const
returns whether the specified cell is part of the (pruned) Voronoi graph
bool isOccupied (int x, int y) const
checks whether the specficied location is occupied
void visualize (const char *filename="result.ppm")
write the current distance map and voronoi diagram as ppm file
unsigned int getSizeX () const
returns the horizontal size of the workspace/map
unsigned int getSizeY () const
returns the vertical size of the workspace/map
Private Types
enum State {
voronoiKeep = -4, freeQueued = -3, voronoiRetry = -2, voronoiPrune = -1,
free = 0, occupied = 1
}
enum QueueingState {
fwNotQueued = 1, fwQueued = 2, fwProcessed = 3, bwQueued = 4,
bwProcessed = 1
}
enum ObstDataState { invalidObstData = SHRT_MAX / 2 }
enum markerMatchResult { pruned, keep, retry }
Private Member Functions
void setObstacle (int x, int y)
void removeObstacle (int x, int y)
void checkVoro (int x, int y, int nx, int ny, dataCell &c, dataCell &nc)
void recheckVoro ()
void commitAndColorize (bool updateRealDist=true)
void reviveVoroNeighbors (int &x, int &y)
bool isOccupied (int &x, int &y, dataCell &c)
markerMatchResult markerMatch (int x, int y)
bool markerMatchAlternative (int x, int y)
int getVoronoiPruneValence (int x, int y)
Private Attributes
BucketPrioQueue< INTPOINT > open
std::queue< INTPOINT > pruneQueue
BucketPrioQueue< INTPOINT > sortedPruneQueue
std::vector< INTPOINT > removeList
std::vector< INTPOINT > addList
std::vector< INTPOINT > lastObstacles
int sizeY
int sizeX
dataCell ** data
bool ** gridMap
bool allocatedGridMap
int padding
double doubleThreshold
double sqrt2
int ** alternativeDiagram
Detailed Description
A DynamicVoronoi object computes and updates a distance map and Voronoi diagram.
Member Enumeration Documentation
markerMatchResult
enum DynamicVoronoi::markerMatchResult private
Enumerator
pruned
keep
retry
   {
     pruned,
     keep,
     retry
   } markerMatchResult;
ObstDataState
enum DynamicVoronoi::ObstDataState private
Enumerator
invalidObstData
   {
     invalidObstData = SHRT_MAX / 2
   } ObstDataState;
QueueingState
enum DynamicVoronoi::QueueingState private
Enumerator
fwNotQueued
fwQueued
fwProcessed
bwQueued
bwProcessed
   {
     fwNotQueued = 1,
     fwQueued = 2,
     fwProcessed = 3,
     bwQueued = 4,
     bwProcessed = 1
   } QueueingState;
State
enum DynamicVoronoi::State private
Enumerator
voronoiKeep
freeQueued
voronoiRetry
voronoiPrune
free
occupied
   {
     voronoiKeep = -4,
     freeQueued = -3,
     voronoiRetry = -2,
     voronoiPrune = -1,
     free = 0,
     occupied = 1
   } State;
Constructor & Destructor Documentation
DynamicVoronoi()
DynamicVoronoi::DynamicVoronoi ()
 {
   sqrt2 = sqrt(2.0);
   data = NULL;
   gridMap = NULL;
   alternativeDiagram = NULL;
   allocatedGridMap = false;
 }
References allocatedGridMap, alternativeDiagram, data, gridMap, and sqrt2.
~DynamicVoronoi()
DynamicVoronoi::~DynamicVoronoi ()
 {
   if (data)
   {
     for (int x = 0; x < sizeX; x++)
       delete[] data[x];
     delete[] data;
   }
   if (allocatedGridMap && gridMap)
   {
     for (int x = 0; x < sizeX; x++)
       delete[] gridMap[x];
     delete[] gridMap;
   }
 }
References allocatedGridMap, data, gridMap, and sizeX.
Member Function Documentation
alternativePrunedDiagram()
int** DynamicVoronoi::alternativePrunedDiagram () const inline
retrieve the alternatively pruned diagram. see updateAlternativePrunedDiagram()
   {
     return alternativeDiagram;
   };
References alternativeDiagram.
checkVoro()
void DynamicVoronoi::checkVoro (int x, int y, int nx, int ny, dataCell & c, dataCell & nc) inline private
 {
   if ((c.sqdist > 1 || nc.sqdist > 1) && nc.obstX != invalidObstData)
   {
     if (abs(c.obstX - nc.obstX) > 1 || abs(c.obstY - nc.obstY) > 1)
     {
       // compute dist from x,y to obstacle of nx,ny
       int dxy_x = x - nc.obstX;
       int dxy_y = y - nc.obstY;
       int sqdxy = dxy_x * dxy_x + dxy_y * dxy_y;
       int stability_xy = sqdxy - c.sqdist;
       if (sqdxy - c.sqdist < 0)
         return;
       // compute dist from nx,ny to obstacle of x,y
       int dnxy_x = nx - c.obstX;
       int dnxy_y = ny - c.obstY;
       int sqdnxy = dnxy_x * dnxy_x + dnxy_y * dnxy_y;
       int stability_nxy = sqdnxy - nc.sqdist;
       if (sqdnxy - nc.sqdist < 0)
         return;
       // which cell is added to the Voronoi diagram?
       if (stability_xy <= stability_nxy && c.sqdist > 2)
       {
         if (c.voronoi != free)
         {
           c.voronoi = free;
           reviveVoroNeighbors(x, y);
           pruneQueue.push(INTPOINT(x, y));
         }
       }
       if (stability_nxy <= stability_xy && nc.sqdist > 2)
       {
         if (nc.voronoi != free)
         {
           nc.voronoi = free;
           reviveVoroNeighbors(nx, ny);
           pruneQueue.push(INTPOINT(nx, ny));
         }
       }
     }
   }
 }
References RVO::abs(), free, INTPOINT, invalidObstData, DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, pruneQueue, reviveVoroNeighbors(), DynamicVoronoi::dataCell::sqdist, and DynamicVoronoi::dataCell::voronoi.
Referenced by update().
clearCell()
void DynamicVoronoi::clearCell (int x, int y)
remove an obstacle at the specified cell coordinate
 {
   gridMap[x][y] = 0;
   removeObstacle(x, y);
 }
References gridMap, and removeObstacle().
commitAndColorize()
void DynamicVoronoi::commitAndColorize (bool updateRealDist = true) private
 {
   // ADD NEW OBSTACLES
   for (unsigned int i = 0; i < addList.size(); i++)
   {
     INTPOINT p = addList[i];
     int x = p.x;
     int y = p.y;
     dataCell c = data[x][y];
     if (c.queueing != fwQueued)
     {
       if (updateRealDist)
         c.dist = 0;
       c.sqdist = 0;
       c.obstX = x;
       c.obstY = y;
       c.queueing = fwQueued;
       c.voronoi = occupied;
       data[x][y] = c;
       open.push(0, INTPOINT(x, y));
     }
   }
   // REMOVE OLD OBSTACLES
   for (unsigned int i = 0; i < removeList.size(); i++)
   {
     INTPOINT p = removeList[i];
     int x = p.x;
     int y = p.y;
     dataCell c = data[x][y];
     if (isOccupied(x, y, c) == true)
       continue;  // obstacle was removed and reinserted
     open.push(0, INTPOINT(x, y));
     if (updateRealDist)
       c.dist = INFINITY;
     c.sqdist = INT_MAX;
     c.needsRaise = true;
     data[x][y] = c;
   }
   removeList.clear();
   addList.clear();
 }
References addList, data, DynamicVoronoi::dataCell::dist, fwQueued, INTPOINT, isOccupied(), DynamicVoronoi::dataCell::needsRaise, DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, occupied, open, BucketPrioQueue< T >::push(), DynamicVoronoi::dataCell::queueing, removeList, DynamicVoronoi::dataCell::sqdist, and DynamicVoronoi::dataCell::voronoi.
Referenced by update().
exchangeObstacles()
void DynamicVoronoi::exchangeObstacles (std::vector< INTPOINT > & newObstacles)
remove old dynamic obstacles and add the new ones
 {
   for (unsigned int i = 0; i < lastObstacles.size(); i++)
   {
     int x = lastObstacles[i].x;
     int y = lastObstacles[i].y;
     bool v = gridMap[x][y];
     if (v)
       continue;
     removeObstacle(x, y);
   }
   lastObstacles.clear();
   for (unsigned int i = 0; i < points.size(); i++)
   {
     int x = points[i].x;
     int y = points[i].y;
     bool v = gridMap[x][y];
     if (v)
       continue;
     setObstacle(x, y);
     lastObstacles.push_back(points[i]);
   }
 }
References gridMap, lastObstacles, removeObstacle(), and setObstacle().
getDistance()
float DynamicVoronoi::getDistance (int x, int y) const
returns the obstacle distance at the specified location
 {
   if ((x > 0) && (x < sizeX) && (y > 0) && (y < sizeY))
     return data[x][y].dist;
   else
     return -INFINITY;
 }
References data, DynamicVoronoi::dataCell::dist, sizeX, and sizeY.
Referenced by global_planner::VoronoiPlanner::plan().
getNumVoronoiNeighborsAlternative()
int DynamicVoronoi::getNumVoronoiNeighborsAlternative (int x, int y) const
retrieve the number of neighbors that are Voronoi nodes (4-connected)
 {
   int count = 0;
   for (int dx = -1; dx <= 1; dx++)
   {
     for (int dy = -1; dy <= 1; dy++)
     {
       if ((dx == 0 && dy == 0) || (dx != 0 && dy != 0))
       {
         continue;
       }
       int nx = x + dx;
       int ny = y + dy;
       if (nx < 0 || nx >= sizeX || ny < 0 || ny >= sizeY)
       {
         continue;
       }
       if (alternativeDiagram[nx][ny] == free || alternativeDiagram[nx][ny] == voronoiKeep)
       {
         count++;
       }
     }
   }
   return count;
 }
References alternativeDiagram, free, sizeX, sizeY, and voronoiKeep.
Referenced by updateAlternativePrunedDiagram().
getObstacleX()
int DynamicVoronoi::getObstacleX (int x, int y) const
 {
   if ((x > 0) && (x < sizeX) && (y > 0) && (y < sizeY))
     return data[x][y].obstX;
   else
     return -1;
 }
References data, DynamicVoronoi::dataCell::obstX, sizeX, and sizeY.
getObstacleY()
int DynamicVoronoi::getObstacleY (int x, int y) const
 {
   if ((x > 0) && (x < sizeX) && (y > 0) && (y < sizeY))
     return data[x][y].obstY;
   else
     return -1;
 }
References data, DynamicVoronoi::dataCell::obstY, sizeX, and sizeY.
getSizeX()
unsigned int DynamicVoronoi::getSizeX () const inline
returns the horizontal size of the workspace/map
   {
     return sizeX;
   }
References sizeX.
getSizeY()
unsigned int DynamicVoronoi::getSizeY () const inline
returns the vertical size of the workspace/map
   {
     return sizeY;
   }
References sizeY.
getVoronoiPruneValence()
int DynamicVoronoi::getVoronoiPruneValence (int x, int y) inline private
initializeEmpty()
void DynamicVoronoi::initializeEmpty (int _sizeX, int _sizeY, bool initGridMap = true)
Initialization with an empty map.
 {
   if (data)
   {
     for (int x = 0; x < sizeX; x++)
       delete[] data[x];
     delete[] data;
     data = NULL;
   }
   if (alternativeDiagram)
   {
     for (int x = 0; x < sizeX; x++)
       delete[] alternativeDiagram[x];
     delete[] alternativeDiagram;
     alternativeDiagram = NULL;
   }
   if (initGridMap)
   {
     if (allocatedGridMap && gridMap)
     {
       for (int x = 0; x < sizeX; x++)
         delete[] gridMap[x];
       delete[] gridMap;
       gridMap = NULL;
       allocatedGridMap = false;
     }
   }
   sizeX = _sizeX;
   sizeY = _sizeY;
   data = new dataCell*[sizeX];
   for (int x = 0; x < sizeX; x++)
     data[x] = new dataCell[sizeY];
   if (initGridMap)
   {
     gridMap = new bool*[sizeX];
     for (int x = 0; x < sizeX; x++)
       gridMap[x] = new bool[sizeY];
     allocatedGridMap = true;
   }
   dataCell c;
   c.dist = INFINITY;
   c.sqdist = INT_MAX;
   c.obstX = invalidObstData;
   c.obstY = invalidObstData;
   c.voronoi = free;
   c.queueing = fwNotQueued;
   c.needsRaise = false;
   for (int x = 0; x < sizeX; x++)
     for (int y = 0; y < sizeY; y++)
       data[x][y] = c;
   if (initGridMap)
   {
     for (int x = 0; x < sizeX; x++)
       for (int y = 0; y < sizeY; y++)
         gridMap[x][y] = 0;
   }
 }
References allocatedGridMap, alternativeDiagram, data, DynamicVoronoi::dataCell::dist, free, fwNotQueued, gridMap, invalidObstData, DynamicVoronoi::dataCell::needsRaise, DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, DynamicVoronoi::dataCell::queueing, sizeX, sizeY, DynamicVoronoi::dataCell::sqdist, and DynamicVoronoi::dataCell::voronoi.
Referenced by initializeMap().
initializeMap()
void DynamicVoronoi::initializeMap (int _sizeX, int _sizeY, bool ** _gridMap)
Initialization with a given binary map (false==free, true==occupied)
 {
   gridMap = _gridMap;
   initializeEmpty(_sizeX, _sizeY, false);
   for (int x = 0; x < sizeX; x++)
   {
     for (int y = 0; y < sizeY; y++)
     {
       if (gridMap[x][y])
       {
         dataCell c = data[x][y];
         if (!isOccupied(x, y, c))
         {
           bool isSurrounded = true;
           for (int dx = -1; dx <= 1; dx++)
           {
             int nx = x + dx;
             if (nx <= 0 || nx >= sizeX - 1)
               continue;
             for (int dy = -1; dy <= 1; dy++)
             {
               if (dx == 0 && dy == 0)
                 continue;
               int ny = y + dy;
               if (ny <= 0 || ny >= sizeY - 1)
                 continue;
               if (!gridMap[nx][ny])
               {
                 isSurrounded = false;
                 break;
               }
             }
           }
           if (isSurrounded)
           {
             c.obstX = x;
             c.obstY = y;
             c.sqdist = 0;
             c.dist = 0;
             c.voronoi = occupied;
             c.queueing = fwProcessed;
             data[x][y] = c;
           }
           else
             setObstacle(x, y);
         }
       }
     }
   }
 }
References data, DynamicVoronoi::dataCell::dist, fwProcessed, gridMap, initializeEmpty(), isOccupied(), DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, occupied, DynamicVoronoi::dataCell::queueing, setObstacle(), sizeX, sizeY, DynamicVoronoi::dataCell::sqdist, and DynamicVoronoi::dataCell::voronoi.
isOccupied() [1/2]
bool DynamicVoronoi::isOccupied (int & x, int & y, dataCell & c) inline private
 {
   return (c.obstX == x && c.obstY == y);
 }
References DynamicVoronoi::dataCell::obstX, and DynamicVoronoi::dataCell::obstY.
isOccupied() [2/2]
bool DynamicVoronoi::isOccupied (int x, int y) const
checks whether the specficied location is occupied
 {
   dataCell c = data[x][y];
   return (c.obstX == x && c.obstY == y);
 }
References data, DynamicVoronoi::dataCell::obstX, and DynamicVoronoi::dataCell::obstY.
Referenced by commitAndColorize(), initializeMap(), removeObstacle(), setObstacle(), and update().
isVoronoi()
bool DynamicVoronoi::isVoronoi (int x, int y) const
returns whether the specified cell is part of the (pruned) Voronoi graph
 {
   dataCell c = data[x][y];
   return (c.voronoi == free || c.voronoi == voronoiKeep);
 }
References data, free, DynamicVoronoi::dataCell::voronoi, and voronoiKeep.
Referenced by global_planner::VoronoiPlanner::plan(), and visualize().
isVoronoiAlternative()
bool DynamicVoronoi::isVoronoiAlternative (int x, int y) const
returns whether the specified cell is part of the alternatively pruned diagram. See updateAlternativePrunedDiagram.
 {
   int v = alternativeDiagram[x][y];
   return (v == free || v == voronoiKeep);
 }
References alternativeDiagram, free, and voronoiKeep.
Referenced by updateAlternativePrunedDiagram().
markerMatch()
DynamicVoronoi::markerMatchResult DynamicVoronoi::markerMatch (int x, int y) inline private
 {
   // implementation of connectivity patterns
   bool f[8];
   int nx, ny;
   int dx, dy;
   int i = 0;
   int count = 0;
   //  int obstacleCount=0;
   int voroCount = 0;
   int voroCountFour = 0;
   for (dy = 1; dy >= -1; dy--)
   {
     ny = y + dy;
     for (dx = -1; dx <= 1; dx++)
     {
       if (dx || dy)
       {
         nx = x + dx;
         dataCell nc = data[nx][ny];
         int v = nc.voronoi;
         bool b = (v <= free && v != voronoiPrune);
         //  if (v==occupied) obstacleCount++;
         f[i] = b;
         if (b)
         {
           voroCount++;
           if (!(dx && dy))
             voroCountFour++;
         }
         if (b && !(dx && dy))
           count++;
         //  if (v<=free && !(dx && dy)) voroCount++;
         i++;
       }
     }
   }
   if (voroCount < 3 && voroCountFour == 1 && (f[1] || f[3] || f[4] || f[6]))
   {
     //    assert(voroCount<2);
     //    if (voroCount>=2) printf("voro>2 %d %d\n", x, y);
     return keep;
   }
   // 4-connected
   if ((!f[0] && f[1] && f[3]) || (!f[2] && f[1] && f[4]) || (!f[5] && f[3] && f[6]) || (!f[7] && f[6] && f[4]))
     return keep;
   if ((f[3] && f[4] && !f[1] && !f[6]) || (f[1] && f[6] && !f[3] && !f[4]))
     return keep;
   // keep voro cells inside of blocks and retry later
   if (voroCount >= 5 && voroCountFour >= 3 && data[x][y].voronoi != voronoiRetry)
   {
     return retry;
   }
   return pruned;
 }
References data, free, keep, pruned, retry, DynamicVoronoi::dataCell::voronoi, voronoiPrune, and voronoiRetry.
Referenced by prune().
markerMatchAlternative()
bool DynamicVoronoi::markerMatchAlternative (int x, int y) inline private
 {
   // prune if this returns true
   bool f[8];
   int nx, ny;
   int dx, dy;
   int i = 0;
   //  int obstacleCount=0;
   int voroCount = 0;
   for (dy = 1; dy >= -1; dy--)
   {
     ny = y + dy;
     for (dx = -1; dx <= 1; dx++)
     {
       if (dx || dy)
       {
         nx = x + dx;
         int v = alternativeDiagram[nx][ny];
         bool b = (v <= free && v != voronoiPrune);
         //  if (v==occupied) obstacleCount++;
         f[i] = b;
         if (v <= free && !(dx && dy))
           voroCount++;
         i++;
       }
     }
   }
   /*
    * 5 6 7
    * 3   4
    * 0 1 2
    */
   {
     // connected horizontal or vertically to only one cell
     if (voroCount == 1 && (f[1] || f[3] || f[4] || f[6]))
     {
       return false;
     }
     // 4-connected
     if ((!f[0] && f[1] && f[3]) || (!f[2] && f[1] && f[4]) || (!f[5] && f[3] && f[6]) || (!f[7] && f[6] && f[4]))
       return false;
     if ((f[3] && f[4] && !f[1] && !f[6]) || (f[1] && f[6] && !f[3] && !f[4]))
       return false;
   }
   return true;
 }
References alternativeDiagram, free, and voronoiPrune.
Referenced by updateAlternativePrunedDiagram().
occupyCell()
void DynamicVoronoi::occupyCell (int x, int y)
add an obstacle at the specified cell coordinate
 {
   gridMap[x][y] = 1;
   setObstacle(x, y);
 }
References gridMap, and setObstacle().
prune()
void DynamicVoronoi::prune ()
prune the Voronoi diagram
 {
   // filler
   while (!pruneQueue.empty())
   {
     INTPOINT p = pruneQueue.front();
     pruneQueue.pop();
     int x = p.x;
     int y = p.y;
     if (data[x][y].voronoi == occupied)
       continue;
     if (data[x][y].voronoi == freeQueued)
       continue;
     data[x][y].voronoi = freeQueued;
     sortedPruneQueue.push(data[x][y].sqdist, p);
     /* tl t tr
        l c r
        bl b br */
     dataCell tr, tl, br, bl;
     tr = data[x + 1][y + 1];
     tl = data[x - 1][y + 1];
     br = data[x + 1][y - 1];
     bl = data[x - 1][y - 1];
     dataCell r, b, t, l;
     r = data[x + 1][y];
     l = data[x - 1][y];
     t = data[x][y + 1];
     b = data[x][y - 1];
     if (x + 2 < sizeX && r.voronoi == occupied)
     {
       // fill to the right
       if (tr.voronoi != occupied && br.voronoi != occupied && data[x + 2][y].voronoi != occupied)
       {
         r.voronoi = freeQueued;
         sortedPruneQueue.push(r.sqdist, INTPOINT(x + 1, y));
         data[x + 1][y] = r;
       }
     }
     if (x - 2 >= 0 && l.voronoi == occupied)
     {
       // fill to the left
       if (tl.voronoi != occupied && bl.voronoi != occupied && data[x - 2][y].voronoi != occupied)
       {
         l.voronoi = freeQueued;
         sortedPruneQueue.push(l.sqdist, INTPOINT(x - 1, y));
         data[x - 1][y] = l;
       }
     }
     if (y + 2 < sizeY && t.voronoi == occupied)
     {
       // fill to the top
       if (tr.voronoi != occupied && tl.voronoi != occupied && data[x][y + 2].voronoi != occupied)
       {
         t.voronoi = freeQueued;
         sortedPruneQueue.push(t.sqdist, INTPOINT(x, y + 1));
         data[x][y + 1] = t;
       }
     }
     if (y - 2 >= 0 && b.voronoi == occupied)
     {
       // fill to the bottom
       if (br.voronoi != occupied && bl.voronoi != occupied && data[x][y - 2].voronoi != occupied)
       {
         b.voronoi = freeQueued;
         sortedPruneQueue.push(b.sqdist, INTPOINT(x, y - 1));
         data[x][y - 1] = b;
       }
     }
   }
   while (!sortedPruneQueue.empty())
   {
     INTPOINT p = sortedPruneQueue.pop();
     dataCell c = data[p.x][p.y];
     int v = c.voronoi;
     if (v != freeQueued && v != voronoiRetry)
     {  // || v>free || v==voronoiPrune || v==voronoiKeep) {
       //      assert(v!=retry);
       continue;
     }
     markerMatchResult r = markerMatch(p.x, p.y);
     if (r == pruned)
       c.voronoi = voronoiPrune;
     else if (r == keep)
       c.voronoi = voronoiKeep;
     else
     {  // r==retry
       c.voronoi = voronoiRetry;
       //      printf("RETRY %d %d\n", x, sizeY-1-y);
       pruneQueue.push(p);
     }
     data[p.x][p.y] = c;
     if (sortedPruneQueue.empty())
     {
       while (!pruneQueue.empty())
       {
         INTPOINT p = pruneQueue.front();
         pruneQueue.pop();
         sortedPruneQueue.push(data[p.x][p.y].sqdist, p);
       }
     }
   }
   //  printf("match: %d\nnomat: %d\n", matchCount, noMatchCount);
 }
References send_test_msgs::br, data, BucketPrioQueue< T >::empty(), freeQueued, INTPOINT, keep, markerMatch(), occupied, BucketPrioQueue< T >::pop(), pruned, pruneQueue, BucketPrioQueue< T >::push(), rviz_generate::r, sizeX, sizeY, sortedPruneQueue, DynamicVoronoi::dataCell::sqdist, DynamicVoronoi::dataCell::voronoi, voronoiKeep, voronoiPrune, and voronoiRetry.
recheckVoro()
void DynamicVoronoi::recheckVoro () private
removeObstacle()
void DynamicVoronoi::removeObstacle (int x, int y) private
 {
   dataCell c = data[x][y];
   if (isOccupied(x, y, c) == false)
     return;
   removeList.push_back(INTPOINT(x, y));
   c.obstX = invalidObstData;
   c.obstY = invalidObstData;
   c.queueing = bwQueued;
   data[x][y] = c;
 }
References bwQueued, data, INTPOINT, invalidObstData, isOccupied(), DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, DynamicVoronoi::dataCell::queueing, and removeList.
Referenced by clearCell(), and exchangeObstacles().
reviveVoroNeighbors()
void DynamicVoronoi::reviveVoroNeighbors (int & x, int & y) inline private
 {
   for (int dx = -1; dx <= 1; dx++)
   {
     int nx = x + dx;
     if (nx <= 0 || nx >= sizeX - 1)
       continue;
     for (int dy = -1; dy <= 1; dy++)
     {
       if (dx == 0 && dy == 0)
         continue;
       int ny = y + dy;
       if (ny <= 0 || ny >= sizeY - 1)
         continue;
       dataCell nc = data[nx][ny];
       if (nc.sqdist != INT_MAX && !nc.needsRaise && (nc.voronoi == voronoiKeep || nc.voronoi == voronoiPrune))
       {
         nc.voronoi = free;
         data[nx][ny] = nc;
         pruneQueue.push(INTPOINT(nx, ny));
       }
     }
   }
 }
References data, free, INTPOINT, DynamicVoronoi::dataCell::needsRaise, pruneQueue, sizeX, sizeY, DynamicVoronoi::dataCell::sqdist, DynamicVoronoi::dataCell::voronoi, voronoiKeep, and voronoiPrune.
Referenced by checkVoro().
setObstacle()
void DynamicVoronoi::setObstacle (int x, int y) private
 {
   dataCell c = data[x][y];
   if (isOccupied(x, y, c))
     return;
   addList.push_back(INTPOINT(x, y));
   c.obstX = x;
   c.obstY = y;
   data[x][y] = c;
 }
References addList, data, INTPOINT, isOccupied(), DynamicVoronoi::dataCell::obstX, and DynamicVoronoi::dataCell::obstY.
Referenced by exchangeObstacles(), initializeMap(), and occupyCell().
update()
void DynamicVoronoi::update (bool updateRealDist = true)
update distance map and Voronoi diagram to reflect the changes
 {
   commitAndColorize(updateRealDist);
   while (!open.empty())
   {
     INTPOINT p = open.pop();
     int x = p.x;
     int y = p.y;
     dataCell c = data[x][y];
     if (c.queueing == fwProcessed)
       continue;
     if (c.needsRaise)
     {
       // RAISE
       for (int dx = -1; dx <= 1; dx++)
       {
         int nx = x + dx;
         if (nx <= 0 || nx >= sizeX - 1)
           continue;
         for (int dy = -1; dy <= 1; dy++)
         {
           if (dx == 0 && dy == 0)
             continue;
           int ny = y + dy;
           if (ny <= 0 || ny >= sizeY - 1)
             continue;
           dataCell nc = data[nx][ny];
           if (nc.obstX != invalidObstData && !nc.needsRaise)
           {
             if (!isOccupied(nc.obstX, nc.obstY, data[nc.obstX][nc.obstY]))
             {
               open.push(nc.sqdist, INTPOINT(nx, ny));
               nc.queueing = fwQueued;
               nc.needsRaise = true;
               nc.obstX = invalidObstData;
               nc.obstY = invalidObstData;
               if (updateRealDist)
                 nc.dist = INFINITY;
               nc.sqdist = INT_MAX;
               data[nx][ny] = nc;
             }
             else
             {
               if (nc.queueing != fwQueued)
               {
                 open.push(nc.sqdist, INTPOINT(nx, ny));
                 nc.queueing = fwQueued;
                 data[nx][ny] = nc;
               }
             }
           }
         }
       }
       c.needsRaise = false;
       c.queueing = bwProcessed;
       data[x][y] = c;
     }
     else if (c.obstX != invalidObstData && isOccupied(c.obstX, c.obstY, data[c.obstX][c.obstY]))
     {
       // LOWER
       c.queueing = fwProcessed;
       c.voronoi = occupied;
       for (int dx = -1; dx <= 1; dx++)
       {
         int nx = x + dx;
         if (nx <= 0 || nx >= sizeX - 1)
           continue;
         for (int dy = -1; dy <= 1; dy++)
         {
           if (dx == 0 && dy == 0)
             continue;
           int ny = y + dy;
           if (ny <= 0 || ny >= sizeY - 1)
             continue;
           dataCell nc = data[nx][ny];
           if (!nc.needsRaise)
           {
             int distx = nx - c.obstX;
             int disty = ny - c.obstY;
             int newSqDistance = distx * distx + disty * disty;
             bool overwrite = (newSqDistance < nc.sqdist);
             if (!overwrite && newSqDistance == nc.sqdist)
             {
               if (nc.obstX == invalidObstData || isOccupied(nc.obstX, nc.obstY, data[nc.obstX][nc.obstY]) == false)
                 overwrite = true;
             }
             if (overwrite)
             {
               open.push(newSqDistance, INTPOINT(nx, ny));
               nc.queueing = fwQueued;
               if (updateRealDist)
               {
                 nc.dist = sqrt((double)newSqDistance);
               }
               nc.sqdist = newSqDistance;
               nc.obstX = c.obstX;
               nc.obstY = c.obstY;
             }
             else
             {
               checkVoro(x, y, nx, ny, c, nc);
             }
             data[nx][ny] = nc;
           }
         }
       }
     }
     data[x][y] = c;
   }
 }
References bwProcessed, checkVoro(), commitAndColorize(), data, DynamicVoronoi::dataCell::dist, BucketPrioQueue< T >::empty(), fwProcessed, fwQueued, INTPOINT, invalidObstData, isOccupied(), DynamicVoronoi::dataCell::needsRaise, DynamicVoronoi::dataCell::obstX, DynamicVoronoi::dataCell::obstY, occupied, open, BucketPrioQueue< T >::pop(), BucketPrioQueue< T >::push(), DynamicVoronoi::dataCell::queueing, sizeX, sizeY, DynamicVoronoi::dataCell::sqdist, and DynamicVoronoi::dataCell::voronoi.
updateAlternativePrunedDiagram()
void DynamicVoronoi::updateAlternativePrunedDiagram ()
prune the Voronoi diagram by globally revisiting all Voronoi nodes. Takes more time but gives a more sparsely pruned Voronoi graph. You need to call this after every call to udpate()
 {
   if (alternativeDiagram == NULL)
   {
     alternativeDiagram = new int*[sizeX];
     for (int x = 0; x < sizeX; x++)
     {
       alternativeDiagram[x] = new int[sizeY];
     }
   }
   std::queue<INTPOINT> end_cells;
   BucketPrioQueue<INTPOINT> sortedPruneQueue;
   for (int x = 1; x < sizeX - 1; x++)
   {
     for (int y = 1; y < sizeY - 1; y++)
     {
       dataCell& c = data[x][y];
       alternativeDiagram[x][y] = c.voronoi;
       if (c.voronoi <= free)
       {
         sortedPruneQueue.push(c.sqdist, INTPOINT(x, y));
         end_cells.push(INTPOINT(x, y));
       }
     }
   }
   for (int x = 1; x < sizeX - 1; x++)
   {
     for (int y = 1; y < sizeY - 1; y++)
     {
       if (getNumVoronoiNeighborsAlternative(x, y) >= 3)
       {
         alternativeDiagram[x][y] = voronoiKeep;
         sortedPruneQueue.push(data[x][y].sqdist, INTPOINT(x, y));
         end_cells.push(INTPOINT(x, y));
       }
     }
   }
   for (int x = 1; x < sizeX - 1; x++)
   {
     for (int y = 1; y < sizeY - 1; y++)
     {
       if (getNumVoronoiNeighborsAlternative(x, y) >= 3)
       {
         alternativeDiagram[x][y] = voronoiKeep;
         sortedPruneQueue.push(data[x][y].sqdist, INTPOINT(x, y));
         end_cells.push(INTPOINT(x, y));
       }
     }
   }
   while (!sortedPruneQueue.empty())
   {
     INTPOINT p = sortedPruneQueue.pop();
     if (markerMatchAlternative(p.x, p.y))
     {
       alternativeDiagram[p.x][p.y] = voronoiPrune;
     }
     else
     {
       alternativeDiagram[p.x][p.y] = voronoiKeep;
     }
   }
   // //delete worms
   while (!end_cells.empty())
   {
     INTPOINT p = end_cells.front();
     end_cells.pop();
     if (isVoronoiAlternative(p.x, p.y) && getNumVoronoiNeighborsAlternative(p.x, p.y) == 1)
     {
       alternativeDiagram[p.x][p.y] = voronoiPrune;
       for (int dx = -1; dx <= 1; ++dx)
       {
         for (int dy = -1; dy <= 1; ++dy)
         {
           if (!(dx || dy) || (dx && dy))
           {
             continue;
           }
           int nx = p.x + dx;
           int ny = p.y + dy;
           if (nx < 0 || nx >= sizeX || ny < 0 || ny >= sizeY)
           {
             continue;
           }
           if (isVoronoiAlternative(nx, ny))
           {
             if (getNumVoronoiNeighborsAlternative(nx, ny) == 1)
             {
               end_cells.push(INTPOINT(nx, ny));
             }
           }
         }
       }
     }
   }
 }
References alternativeDiagram, data, BucketPrioQueue< T >::empty(), free, getNumVoronoiNeighborsAlternative(), INTPOINT, isVoronoiAlternative(), markerMatchAlternative(), BucketPrioQueue< T >::pop(), BucketPrioQueue< T >::push(), sizeX, sizeY, sortedPruneQueue, DynamicVoronoi::dataCell::sqdist, DynamicVoronoi::dataCell::voronoi, voronoiKeep, and voronoiPrune.
visualize()
void DynamicVoronoi::visualize (const char * filename = "result.ppm")
write the current distance map and voronoi diagram as ppm file
 {
   // write ppm files
   FILE* F = fopen(filename, "w");
   if (!F)
   {
     std::cerr << "could not open 'result.pgm' for writing!\n";
     return;
   }
   fprintf(F, "P6\n#\n");
   fprintf(F, "%d %d\n255\n", sizeX, sizeY);
   for (int y = sizeY - 1; y >= 0; y--)
   {
     for (int x = 0; x < sizeX; x++)
     {
       unsigned char c = 0;
       if (alternativeDiagram != NULL && (alternativeDiagram[x][y] == free || alternativeDiagram[x][y] == voronoiKeep))
       {
         fputc(255, F);
         fputc(0, F);
         fputc(0, F);
       }
       else if (isVoronoi(x, y))
       {
         fputc(0, F);
         fputc(0, F);
         fputc(255, F);
       }
       else if (data[x][y].sqdist == 0)
       {
         fputc(0, F);
         fputc(0, F);
         fputc(0, F);
       }
       else
       {
         float f = 80 + (sqrt(data[x][y].sqdist) * 10);
         if (f > 255)
           f = 255;
         if (f < 0)
           f = 0;
         c = (unsigned char)f;
         fputc(c, F);
         fputc(c, F);
         fputc(c, F);
       }
     }
   }
   fclose(F);
 }
References alternativeDiagram, data, free, isVoronoi(), sizeX, sizeY, and voronoiKeep.
Member Data Documentation
addList
std::vector<INTPOINT> DynamicVoronoi::addList private
Referenced by commitAndColorize(), and setObstacle().
allocatedGridMap
bool DynamicVoronoi::allocatedGridMap private
Referenced by DynamicVoronoi(), initializeEmpty(), and ~DynamicVoronoi().
alternativeDiagram
int** DynamicVoronoi::alternativeDiagram private
Referenced by alternativePrunedDiagram(), DynamicVoronoi(), getNumVoronoiNeighborsAlternative(), initializeEmpty(), isVoronoiAlternative(), markerMatchAlternative(), updateAlternativePrunedDiagram(), and visualize().
data
dataCell** DynamicVoronoi::data private
Referenced by commitAndColorize(), DynamicVoronoi(), getDistance(), getObstacleX(), getObstacleY(), initializeEmpty(), initializeMap(), isOccupied(), isVoronoi(), markerMatch(), prune(), removeObstacle(), reviveVoroNeighbors(), setObstacle(), update(), updateAlternativePrunedDiagram(), visualize(), and ~DynamicVoronoi().
doubleThreshold
double DynamicVoronoi::doubleThreshold private
gridMap
bool** DynamicVoronoi::gridMap private
Referenced by clearCell(), DynamicVoronoi(), exchangeObstacles(), initializeEmpty(), initializeMap(), occupyCell(), and ~DynamicVoronoi().
lastObstacles
std::vector<INTPOINT> DynamicVoronoi::lastObstacles private
Referenced by exchangeObstacles().
open
BucketPrioQueue<INTPOINT> DynamicVoronoi::open private
Referenced by commitAndColorize(), and update().
padding
int DynamicVoronoi::padding private
pruneQueue
std::queue<INTPOINT> DynamicVoronoi::pruneQueue private
Referenced by checkVoro(), prune(), and reviveVoroNeighbors().
removeList
std::vector<INTPOINT> DynamicVoronoi::removeList private
Referenced by commitAndColorize(), and removeObstacle().
sizeX
int DynamicVoronoi::sizeX private
Referenced by getDistance(), getNumVoronoiNeighborsAlternative(), getObstacleX(), getObstacleY(), getSizeX(), initializeEmpty(), initializeMap(), prune(), reviveVoroNeighbors(), update(), updateAlternativePrunedDiagram(), visualize(), and ~DynamicVoronoi().
sizeY
int DynamicVoronoi::sizeY private
Referenced by getDistance(), getNumVoronoiNeighborsAlternative(), getObstacleX(), getObstacleY(), getSizeY(), initializeEmpty(), initializeMap(), prune(), reviveVoroNeighbors(), update(), updateAlternativePrunedDiagram(), and visualize().
sortedPruneQueue
BucketPrioQueue<INTPOINT> DynamicVoronoi::sortedPruneQueue private
Referenced by prune(), and updateAlternativePrunedDiagram().
sqrt2
double DynamicVoronoi::sqrt2 private
Referenced by DynamicVoronoi().
The documentation for this class was generated from the following files:
src/third_party/map_plugins/voronoi_layer/include/dynamicvoronoi.h
src/third_party/map_plugins/voronoi_layer/src/dynamicvoronoi.cpp