ROS Motion Planning: kd_tree::KDTree< PointT > Class Template Reference
kd_tree::KDTree< PointT > Class Template Reference
k-d tree class
#include <kd_tree.h>
Classes
class BoundedPriorityQueue
Bounded priority queue.
class Exception
k-d tree exception.
struct KDNode
k-d tree node.
Public Member Functions
KDTree ()
Construct a new KDTree object.
KDTree (const std::vector< PointT > &points)
Construct a new KDTree object.
~KDTree ()
Destroy the KDTree object.
void build (const std::vector< PointT > &points)
Re-builds k-d tree.
void clear ()
Clear k-d tree.
bool validate () const
Validates k-d tree.
int nnSearch (const PointT &query, double *min_dist=nullptr) const
Searches the nearest neighbor.
std::vector< int > knnSearch (const PointT &query, int k) const
Searches k-nearest neighbors.
std::vector< int > radiusSearch (const PointT &query, double radius) const
Searches neighbors within radius.
Private Types
using KnnQueue = BoundedPriorityQueue< std::pair< double, int > >
KNN Priority queue of <distance, index> pair.
Private Member Functions
KDNode * _buildRecursive (int *indices, int npoints, int depth)
Builds k-d tree recursively.
void _clearRecursive (KDNode *node)
Clears k-d tree recursively.
void _validateRecursive (const KDNode *node, int depth) const
Validates k-d tree recursively.
void _nnSearchRecursive (const PointT &query, const KDNode *node, int *guess, double *min_dist) const
Searches the nearest neighbor recursively.
void _knnSearchRecursive (const PointT &query, const KDNode *node, KnnQueue &queue, int k) const
Searches k-nearest neighbors recursively.
void _radiusSearchRecursive (const PointT &query, const KDNode *node, std::vector< int > &indices, double radius) const
Searches neighbors within radius.
Static Private Member Functions
static double _distance (const PointT &p, const PointT &q)
Calculate the distance between kd node p and q.
Private Attributes
KDNode * root_
std::vector< PointT > points_
Detailed Description
template<class PointT>
class kd_tree::KDTree< PointT >
k-d tree class
Member Typedef Documentation
KnnQueue
template<class PointT > using kd_tree::KDTree< PointT >::KnnQueue = BoundedPriorityQueue<std::pair<double, int> > private
KNN Priority queue of <distance, index> pair.
Constructor & Destructor Documentation
KDTree() [1/2]
template<class PointT > kd_tree::KDTree< PointT >::KDTree () inline
Construct a new KDTree object.
 : root_(nullptr){};
KDTree() [2/2]
template<class PointT > kd_tree::KDTree< PointT >::KDTree (const std::vector< PointT > & points) inline
Construct a new KDTree object.
Parameters
points set of points
                                           : root_(nullptr)
   {
     build(points);
   }
References kd_tree::KDTree< PointT >::build().
~KDTree()
template<class PointT > kd_tree::KDTree< PointT >::~KDTree () inline
Destroy the KDTree object.
   {
     clear();
   }
References kd_tree::KDTree< PointT >::clear().
Member Function Documentation
_buildRecursive()
template<class PointT > KDNode* kd_tree::KDTree< PointT >::_buildRecursive (int * indices, int npoints, int depth) inline private
Builds k-d tree recursively.
Parameters
indices
npoints
depth
Returns
KDNode*
   {
     if (npoints <= 0)
       return nullptr;
     const int axis = depth % PointT::dim;
     const int mid = (npoints - 1) / 2;
     std::nth_element(indices, indices + mid, indices + npoints,
                      [&](int lhs, int rhs) { return points_[lhs][axis] < points_[rhs][axis]; });
     KDNode* node = new KDNode();
     node->idx = indices[mid];
     node->axis = axis;
     node->next[0] = _buildRecursive(indices, mid, depth + 1);
     node->next[1] = _buildRecursive(indices + mid + 1, npoints - mid - 1, depth + 1);
     return node;
   }
References tf_map2odom::node, and kd_tree::KDTree< PointT >::points_.
Referenced by kd_tree::KDTree< PointT >::build().
_clearRecursive()
template<class PointT > void kd_tree::KDTree< PointT >::_clearRecursive (KDNode * node) inline private
Clears k-d tree recursively.
Parameters
node
   {
     if (node == nullptr)
       return;
     if (node->next[0])
       _clearRecursive(node->next[0]);
     if (node->next[1])
       _clearRecursive(node->next[1]);
     delete node;
   }
References tf_map2odom::node.
Referenced by kd_tree::KDTree< PointT >::clear().
_distance()
template<class PointT > static double kd_tree::KDTree< PointT >::_distance (const PointT & p, const PointT & q) inline static private
Calculate the distance between kd node p and q.
Parameters
p KD Node p
q KD Node q
Returns
distance between kd node p and q
   {
     double dist = 0;
     for (size_t i = 0; i < PointT::dim; i++)
       dist += (p[i] - q[i]) * (p[i] - q[i]);
     return std::sqrt(dist);
   }
References helper::dist().
Referenced by kd_tree::KDTree< PointT >::_knnSearchRecursive(), and kd_tree::KDTree< PointT >::_nnSearchRecursive().
_knnSearchRecursive()
template<class PointT > void kd_tree::KDTree< PointT >::_knnSearchRecursive (const PointT & query, const KDNode * node, KnnQueue & queue, int k) const inline private
Searches k-nearest neighbors recursively.
Parameters
query the point in the KD Tree
node root node of KD Tree of its child tree
queue the priority queue of size k
k k-nearest neighbors
   {
     if (node == nullptr)
       return;
     const PointT& train = points_[node->idx];
     const double dist = _distance(query, train);
     queue.push(std::make_pair(dist, node->idx));
     const int axis = node->axis;
     const int dir = query[axis] < train[axis] ? 0 : 1;
     _knnSearchRecursive(query, node->next[dir], queue, k);
     const double diff = fabs(query[axis] - train[axis]);
     if ((int)queue.size() < k || diff < queue.back().first)
       _knnSearchRecursive(query, node->next[!dir], queue, k);
   }
References kd_tree::KDTree< PointT >::_distance(), kd_tree::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::back(), helper::dist(), tf_map2odom::node, kd_tree::KDTree< PointT >::points_, kd_tree::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::push(), and kd_tree::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::size().
Referenced by kd_tree::KDTree< PointT >::knnSearch().
_nnSearchRecursive()
template<class PointT > void kd_tree::KDTree< PointT >::_nnSearchRecursive (const PointT & query, const KDNode * node, int * guess, double * min_dist) const inline private
Searches the nearest neighbor recursively.
Parameters
query the point in the KD Tree
node root node of KD Tree of its child tree
guess the possible nearest neighbor of query
minDist the min distance between query and its nearest neighbor
   {
     if (node == nullptr)
       return;
     const PointT& train = points_[node->idx];
     const double dist = _distance(query, train);
     if (dist < *min_dist)
     {
       *min_dist = dist;
       *guess = node->idx;
     }
     const int axis = node->axis;
     const int dir = query[axis] < train[axis] ? 0 : 1;
     _nnSearchRecursive(query, node->next[dir], guess, min_dist);
     // if the min distance crosses the axis, the nearest neighbor maybe exist
     // in the other side of axis, therefore another direction should be searched
     const double diff = fabs(query[axis] - train[axis]);
     if (diff < *min_dist)
       _nnSearchRecursive(query, node->next[!dir], guess, min_dist);
   }
References kd_tree::KDTree< PointT >::_distance(), helper::dist(), tf_map2odom::node, and kd_tree::KDTree< PointT >::points_.
Referenced by kd_tree::KDTree< PointT >::nnSearch().
_radiusSearchRecursive()
template<class PointT > void kd_tree::KDTree< PointT >::_radiusSearchRecursive (const PointT & query, const KDNode * node, std::vector< int > & indices, double radius) const inline private
Searches neighbors within radius.
Parameters
query the point in the KD Tree
node root node of KD Tree of its child tree
indices neighbors inside the radius range of query
radius radius neighbors
   {
     if (node == nullptr)
       return;
     const PointT& train = points_[node->idx];
     const double dist = distance(query, train);
     if (dist < radius)
       indices.push_back(node->idx);
     const int axis = node->axis;
     const int dir = query[axis] < train[axis] ? 0 : 1;
     _radiusSearchRecursive(query, node->next[dir], indices, radius);
     const double diff = fabs(query[axis] - train[axis]);
     if (diff < radius)
       _radiusSearchRecursive(query, node->next[!dir], indices, radius);
   }
References helper::dist(), tf_map2odom::node, and kd_tree::KDTree< PointT >::points_.
Referenced by kd_tree::KDTree< PointT >::radiusSearch().
_validateRecursive()
template<class PointT > void kd_tree::KDTree< PointT >::_validateRecursive (const KDNode * node, int depth) const inline private
Validates k-d tree recursively.
Parameters
node a KD Tree node
depth KD tree depth
   {
     if (node == nullptr)
       return;
     const int axis = node->axis;
     const KDNode* node0 = node->next[0];
     const KDNode* node1 = node->next[1];
     if (node0 && node1)
     {
       if (points_[node->idx][axis] < points_[node0->idx][axis])
         throw Exception();
       if (points_[node->idx][axis] > points_[node1->idx][axis])
         throw Exception();
     }
     if (node0)
       validateRecursive(node0, depth + 1);
     if (node1)
       validateRecursive(node1, depth + 1);
   }
References kd_tree::KDTree< PointT >::KDNode::idx, tf_map2odom::node, and kd_tree::KDTree< PointT >::points_.
Referenced by kd_tree::KDTree< PointT >::validate().
build()
template<class PointT > void kd_tree::KDTree< PointT >::build (const std::vector< PointT > & points) inline
Re-builds k-d tree.
Parameters
points set of points
   {
     clear();
     points_ = points;
     // creat indices
     std::vector<int> indices(points.size());
     std::iota(std::begin(indices), std::end(indices), 0);
     root_ = _buildRecursive(indices.data(), (int)points.size(), 0);
   }
References kd_tree::KDTree< PointT >::_buildRecursive(), kd_tree::KDTree< PointT >::clear(), kd_tree::KDTree< PointT >::points_, and kd_tree::KDTree< PointT >::root_.
Referenced by kd_tree::KDTree< PointT >::KDTree().
clear()
template<class PointT > void kd_tree::KDTree< PointT >::clear () inline
Clear k-d tree.
   {
     _clearRecursive(root_);
     root_ = nullptr;
     points_.clear();
   }
References kd_tree::KDTree< PointT >::_clearRecursive(), kd_tree::KDTree< PointT >::points_, and kd_tree::KDTree< PointT >::root_.
Referenced by kd_tree::KDTree< PointT >::build(), and kd_tree::KDTree< PointT >::~KDTree().
knnSearch()
template<class PointT > std::vector<int> kd_tree::KDTree< PointT >::knnSearch (const PointT & query, int k) const inline
Searches k-nearest neighbors.
Parameters
query the point in the KD Tree
k k nearest neighbors
Returns
k-nearest neighbors indices vector
   {
     KnnQueue queue(k);
     _knnSearchRecursive(query, root_, queue, k);
     std::vector<int> indices(queue.size());
     for (size_t i = 0; i < queue.size(); i++)
       indices[i] = queue[i].second;
     return indices;
   }
References kd_tree::KDTree< PointT >::_knnSearchRecursive(), kd_tree::KDTree< PointT >::root_, and kd_tree::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::size().
nnSearch()
template<class PointT > int kd_tree::KDTree< PointT >::nnSearch (const PointT & query, double * min_dist = nullptr) const inline
Searches the nearest neighbor.
Parameters
query the point in the KD Tree
min_dist the min distance between query and its nearest neighbor
Returns
the nearest neighbor index of query
   {
     int guess;
     double _min_dist = std::numeric_limits<double>::max();
     _nnSearchRecursive(query, root_, &guess, &_min_dist);
     if (min_dist)
       *min_dist = _min_dist;
     return guess;
   }
References kd_tree::KDTree< PointT >::_nnSearchRecursive(), and kd_tree::KDTree< PointT >::root_.
radiusSearch()
template<class PointT > std::vector<int> kd_tree::KDTree< PointT >::radiusSearch (const PointT & query, double radius) const inline
Searches neighbors within radius.
Parameters
query the point in the KD Tree
radius radius neighbors
Returns
neighbors inside the radius range of query
   {
     std::vector<int> indices;
     _radiusSearchRecursive(query, root_, indices, radius);
     return indices;
   }
References kd_tree::KDTree< PointT >::_radiusSearchRecursive(), and kd_tree::KDTree< PointT >::root_.
validate()
template<class PointT > bool kd_tree::KDTree< PointT >::validate () const inline
Validates k-d tree.
   {
     try
     {
       _validateRecursive(root_, 0);
     }
     catch (const Exception&)
     {
       return false;
     }
     return true;
   }
References kd_tree::KDTree< PointT >::_validateRecursive(), and kd_tree::KDTree< PointT >::root_.
Member Data Documentation
points_
template<class PointT > std::vector<PointT> kd_tree::KDTree< PointT >::points_ private
Referenced by kd_tree::KDTree< PointT >::_buildRecursive(), kd_tree::KDTree< PointT >::_knnSearchRecursive(), kd_tree::KDTree< PointT >::_nnSearchRecursive(), kd_tree::KDTree< PointT >::_radiusSearchRecursive(), kd_tree::KDTree< PointT >::_validateRecursive(), kd_tree::KDTree< PointT >::build(), and kd_tree::KDTree< PointT >::clear().
root_
template<class PointT > KDNode* kd_tree::KDTree< PointT >::root_ private
Referenced by kd_tree::KDTree< PointT >::build(), kd_tree::KDTree< PointT >::clear(), kd_tree::KDTree< PointT >::knnSearch(), kd_tree::KDTree< PointT >::nnSearch(), kd_tree::KDTree< PointT >::radiusSearch(), and kd_tree::KDTree< PointT >::validate().
The documentation for this class was generated from the following file:
src/core/utils/include/kd_tree.h