ROS Motion Planning: mpc_planner::MPCPlanner Class Reference
mpc_planner::MPCPlanner Class Reference
A class implementing a local planner using the MPC.
#include <mpc_planner.h>
Public Member Functions
MPCPlanner ()
Construct a new MPC planner object.
MPCPlanner (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Construct a new MPC planner object.
~MPCPlanner ()
Destroy the MPC planner object.
void initialize (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Initialization of the local planner.
bool setPlan (const std::vector< geometry_msgs::PoseStamped > &orig_global_plan)
Set the plan that the controller is following.
bool isGoalReached ()
Check if the goal pose has been achieved.
bool computeVelocityCommands (geometry_msgs::Twist &cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Private Member Functions
Eigen::Vector2d _mpcControl (Eigen::Vector3d s, Eigen::Vector3d s_d, Eigen::Vector2d u_r, Eigen::Vector2d du_p)
Execute MPC control process.
Eigen::SparseMatrix< double > _convertToSparseMatrix (Eigen::MatrixXd A)
convert matrix A to its sparse view
Private Member Functions inherited from local_planner::LocalPlanner
LocalPlanner ()
Construct a new Local Planner object.
~LocalPlanner ()
Destroy the Local Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setBaseFrame (std::string base_frame)
Set or reset frame name.
void setMapFrame (std::string map_frame)
double regularizeAngle (double angle)
Regularize angle to [-pi, pi].
Eigen::Vector3d getEulerAngles (geometry_msgs::PoseStamped &ps)
Get the Euler Angles from PoseStamped.
bool shouldRotateToGoal (const geometry_msgs::PoseStamped &cur, const geometry_msgs::PoseStamped &goal)
Whether to reach the target pose through rotation operation.
bool shouldRotateToPath (double angle_to_path, double tolerance=0.0)
Whether to correct the tracking path with rotation operation.
double linearRegularization (nav_msgs::Odometry &base_odometry, double v_d)
linear velocity regularization
double angularRegularization (nav_msgs::Odometry &base_odometry, double w_d)
angular velocity regularization
void transformPose (tf2_ros::Buffer *tf, const std::string out_frame, const geometry_msgs::PoseStamped &in_pose, geometry_msgs::PoseStamped &out_pose) const
Tranform from in_pose to out_pose with out frame using tf.
bool worldToMap (double wx, double wy, int &mx, int &my)
Tranform from world map(x, y) to costmap(x, y)
std::vector< geometry_msgs::PoseStamped > prune (const geometry_msgs::PoseStamped robot_pose_global)
Prune the path, removing the waypoints that the robot has already passed and distant waypoints.
double getLookAheadDistance (double vt)
Calculate the look-ahead distance with current speed dynamically.
void getLookAheadPoint (double lookahead_dist, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > &prune_plan, geometry_msgs::PointStamped &pt, double &theta, double &kappa)
find the point on the path that is exactly the lookahead distance away from the robot
Private Attributes
bool initialized_
bool goal_reached_
tf2_ros::Buffer * tf_
double d_t_
Eigen::Matrix3d Q_
Eigen::Matrix2d R_
int p_
int m_
Eigen::Vector2d du_p_
ros::Publisher target_pt_pub_
ros::Publisher current_pose_pub_
double goal_x_
double goal_y_
Eigen::Vector3d goal_rpy_
Private Attributes inherited from local_planner::LocalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double origin_x_
double origin_y_
double resolution_
double convert_offset_
double factor_
double max_v_
double min_v_
double max_v_inc_
double max_w_
double min_w_
double max_w_inc_
double goal_dist_tol_
double rotate_tol_
std::string base_frame_
std::string map_frame_
std::string odom_frame_
base_local_planner::OdometryHelperRos * odom_helper_
costmap_2d::Costmap2DROS * costmap_ros_
std::vector< geometry_msgs::PoseStamped > global_plan_
double lookahead_time_
double min_lookahead_dist_
double max_lookahead_dist_
Detailed Description
A class implementing a local planner using the MPC.
Constructor & Destructor Documentation
MPCPlanner() [1/2]
mpc_planner::MPCPlanner::MPCPlanner ()
Construct a new MPC planner object.
                        : initialized_(false), goal_reached_(false), tf_(nullptr)  //, costmap_ros_(nullptr)
 {
 }
MPCPlanner() [2/2]
mpc_planner::MPCPlanner::MPCPlanner (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Construct a new MPC planner object.
                                                                                              : MPCPlanner()
 {
   initialize(name, tf, costmap_ros);
 }
References initialize(), and rviz_generate::name.
~MPCPlanner()
mpc_planner::MPCPlanner::~MPCPlanner ()
Destroy the MPC planner object.
 {
 }
Member Function Documentation
_convertToSparseMatrix()
Eigen::SparseMatrix< double > mpc_planner::MPCPlanner::_convertToSparseMatrix (Eigen::MatrixXd A) private
convert matrix A to its sparse view
Parameters
A dense matrix
Returns
A_s sparse matrix
 {
   int row = A.rows();
   int col = A.cols();
   Eigen::SparseMatrix<double> A_s(row, col);
   for (int i = 0; i < row; i++)
     for (int j = 0; j < col; j++)
       A_s.insert(i, j) = A(i, j);
   return A_s;
 }
Referenced by _mpcControl().
_mpcControl()
Eigen::Vector2d mpc_planner::MPCPlanner::_mpcControl (Eigen::Vector3d s, Eigen::Vector3d s_d, Eigen::Vector2d u_r, Eigen::Vector2d du_p) private
Execute MPC control process.
Parameters
s current state
s_d desired state
u_r refered control
du_p previous control error
Returns
u control vector
 {
   int dim_u = 2;
   int dim_x = 3;
   // state vector (5 x 1)
   Eigen::VectorXd x = Eigen::VectorXd(dim_x + dim_u);
   x.topLeftCorner(dim_x, 1) = s - s_d;
   x[2] = regularizeAngle(x[2]);
   x.bottomLeftCorner(dim_u, 1) = du_p;
   // original state matrix
   Eigen::Matrix3d A_o = Eigen::Matrix3d::Identity();
   A_o(0, 2) = -u_r[0] * sin(s_d[2]) * d_t_;
   A_o(1, 2) = u_r[0] * cos(s_d[2]) * d_t_;
   // original control matrix
   Eigen::MatrixXd B_o = Eigen::MatrixXd::Zero(dim_x, dim_u);
   B_o(0, 0) = cos(s_d[2]) * d_t_;
   B_o(1, 0) = sin(s_d[2]) * d_t_;
   B_o(2, 1) = d_t_;
   // state matrix (5 x 5)
   Eigen::MatrixXd A = Eigen::MatrixXd::Zero(dim_x + dim_u, dim_x + dim_u);
   A.topLeftCorner(dim_x, dim_x) = A_o;
   A.topRightCorner(dim_x, dim_u) = B_o;
   A.bottomLeftCorner(dim_u, dim_x) = Eigen::MatrixXd::Zero(dim_u, dim_x);
   A.bottomRightCorner(dim_u, dim_u) = Eigen::Matrix2d::Identity();
   // control matrix (5 x 2)
   Eigen::MatrixXd B = Eigen::MatrixXd::Zero(dim_x + dim_u, dim_u);
   B.topLeftCorner(dim_x, dim_u) = B_o;
   B.bottomLeftCorner(dim_u, dim_u) = Eigen::Matrix2d::Identity();
   // output matrix(3 x 5)
   Eigen::MatrixXd C = Eigen::MatrixXd::Zero(dim_x, dim_x + dim_u);
   C.topLeftCorner(dim_x, dim_x) = Eigen::Matrix3d::Identity();
   C.topRightCorner(dim_x, dim_u) = Eigen::MatrixXd::Zero(dim_x, dim_u);
   // mpc state matrix(3p x 5)
   Eigen::MatrixPower<Eigen::MatrixXd> A_pow(A);
   Eigen::MatrixXd S_x = Eigen::MatrixXd::Zero(dim_x * p_, dim_x + dim_u);
   for (int i = 0; i < p_; i++)
     S_x.middleRows(dim_x * i, dim_x) = C * A_pow(i + 1);
   // mpc control matrix(3p x 2m)
   Eigen::MatrixXd S_u = Eigen::MatrixXd::Zero(dim_x * p_, dim_u * m_);
   for (int i = 0; i < p_; i++)
   {
     for (int j = 0; j < m_; j++)
     {
       if (j <= i)
         S_u.block(dim_x * i, dim_u * j, dim_x, dim_u) = C * A_pow(i - j) * B;
       else
         S_u.block(dim_x * i, dim_u * j, dim_x, dim_u) = Eigen::MatrixXd::Zero(dim_x, dim_u);
     }
   }
   // optimization
   // min 1/2 * x.T * H * x + g.T * x
   // s.t. l <= Px <= u
   Eigen::VectorXd Yr = Eigen::VectorXd::Zero(dim_x * p_);                              // (3p x 1)
   Eigen::MatrixXd Q = Eigen::kroneckerProduct(Eigen::MatrixXd::Identity(p_, p_), Q_);  // (3p x 3p)
   Eigen::MatrixXd R = Eigen::kroneckerProduct(Eigen::MatrixXd::Identity(m_, m_), R_);  // (2m x 2m)
   Eigen::MatrixXd H = S_u.transpose() * Q * S_u + R;                                   // (2m x 2m)
   Eigen::VectorXd g = S_u.transpose() * Q * (S_x * x - Yr);                            // (2m x 1)
   // boundary
   Eigen::Vector2d u_min(min_v_, -max_w_);
   Eigen::Vector2d u_max(max_v_, max_w_);
   Eigen::Vector2d u_k_1(du_p[0], du_p[1]);
   Eigen::Vector2d du_min(-0.2, -0.2);
   Eigen::Vector2d du_max(0.2, M_PI);
   Eigen::VectorXd U_min = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_min);    // (2m x 1)
   Eigen::VectorXd U_max = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_max);    // (2m x 1)
   Eigen::VectorXd U_r = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_r);        // (2m x 1)
   Eigen::VectorXd U_k_1 = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_k_1);    // (2m x 1)
   Eigen::VectorXd dU_min = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), du_min);  // (2m x 1)
   Eigen::VectorXd dU_max = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), du_max);  // (2m x 1)
   // constriants
   Eigen::MatrixXd temp = Eigen::MatrixXd::Ones(m_, m_).triangularView<Eigen::Lower>();
   Eigen::MatrixXd A_I = Eigen::kroneckerProduct(temp, Eigen::MatrixXd::Identity(dim_u, dim_u));  // (2m x 2m)
   Eigen::MatrixXd P = Eigen::MatrixXd::Zero(2 * dim_u * m_, dim_u * m_);  // (4m x 2m)
   P.topRows(dim_u * m_) = A_I;
   P.bottomRows(dim_u * m_) = Eigen::MatrixXd::Identity(dim_u * m_, dim_u * m_);
   Eigen::VectorXd lower = Eigen::VectorXd::Zero(2 * dim_u * m_);  // (4m x 1)
   Eigen::VectorXd upper = Eigen::VectorXd::Zero(2 * dim_u * m_);  // (4m x 1)
   lower.topRows(dim_u * m_) = U_min - U_k_1 - U_r;
   lower.bottomRows(dim_u * m_) = dU_min;
   upper.topRows(dim_u * m_) = U_max - U_k_1 - U_r;
   upper.bottomRows(dim_u * m_) = dU_max;
   // solve
   OsqpEigen::Solver solver;
   solver.settings()->setVerbosity(false);
   solver.settings()->setWarmStart(true);
   solver.data()->setNumberOfVariables(dim_u * m_);
   solver.data()->setNumberOfConstraints(2 * dim_u * m_);
   solver.data()->setHessianMatrix(_convertToSparseMatrix(H));
   solver.data()->setGradient(g);
   solver.data()->setLinearConstraintsMatrix(_convertToSparseMatrix(P));
   solver.data()->setLowerBound(lower);
   solver.data()->setUpperBound(upper);
   solver.initSolver();
   solver.solveProblem();
   Eigen::VectorXd solution = solver.getSolution();
   // real control
   Eigen::Vector2d u(solution[0] + du_p[0] + u_r[0], regularizeAngle(solution[1] + du_p[1] + u_r[1]));
   return u;
 }
References _convertToSparseMatrix(), d_t_, m_, local_planner::LocalPlanner::max_v_, local_planner::LocalPlanner::max_w_, local_planner::LocalPlanner::min_v_, p_, Q_, R_, and local_planner::LocalPlanner::regularizeAngle().
Referenced by computeVelocityCommands().
computeVelocityCommands()
bool mpc_planner::MPCPlanner::computeVelocityCommands (geometry_msgs::Twist & cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Parameters
cmd_vel will be filled with the velocity command to be passed to the robot base
Returns
true if a valid trajectory was found, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("MPC planner has not been initialized");
     return false;
   }
   // odometry observation - getting robot velocities in robot frame
   nav_msgs::Odometry base_odom;
   odom_helper_->getOdom(base_odom);
   // get robot position in global frame
   geometry_msgs::PoseStamped robot_pose_odom, robot_pose_map;
   costmap_ros_->getRobotPose(robot_pose_odom);
   transformPose(tf_, map_frame_, robot_pose_odom, robot_pose_map);
   // transform global plan to robot frame
   std::vector<geometry_msgs::PoseStamped> prune_plan = prune(robot_pose_map);
   // calculate look-ahead distance
   double vt = std::hypot(base_odom.twist.twist.linear.x, base_odom.twist.twist.linear.y);
   double wt = base_odom.twist.twist.angular.z;
   double L = getLookAheadDistance(vt);
   // get the particular point on the path at the lookahead distance
   geometry_msgs::PointStamped lookahead_pt;
   double theta_trj, kappa;
   getLookAheadPoint(L, robot_pose_map, prune_plan, lookahead_pt, theta_trj, kappa);
   // current angle
   double theta = tf2::getYaw(robot_pose_map.pose.orientation);  // [-pi, pi]
   // calculate commands
   if (shouldRotateToGoal(robot_pose_map, global_plan_.back()))
   {
     du_p_ = Eigen::Vector2d(0, 0);
     double e_theta = regularizeAngle(goal_rpy_.z() - theta);
     // orientation reached
     if (!shouldRotateToPath(std::fabs(e_theta)))
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = 0.0;
       goal_reached_ = true;
     }
     // orientation not reached
     else
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = angularRegularization(base_odom, e_theta / d_t_);
     }
   }
   else
   {
     Eigen::Vector3d s(robot_pose_map.pose.position.x, robot_pose_map.pose.position.y, theta);  // current state
     Eigen::Vector3d s_d(lookahead_pt.point.x, lookahead_pt.point.y, theta_trj);                // desired state
     Eigen::Vector2d u_r(vt, regularizeAngle(vt * kappa));                                      // refered input
     Eigen::Vector2d u = _mpcControl(s, s_d, u_r, du_p_);
     double u_v = linearRegularization(base_odom, u[0]);
     double u_w = angularRegularization(base_odom, u[1]);
     du_p_ = Eigen::Vector2d(u_v - u_r[0], regularizeAngle(u_w - u_r[1]));
     cmd_vel.linear.x = u_v;
     cmd_vel.angular.z = u_w;
   }
   // publish lookahead pose
   target_pt_pub_.publish(lookahead_pt);
   // publish robot pose
   current_pose_pub_.publish(robot_pose_map);
   return true;
 }
References _mpcControl(), local_planner::LocalPlanner::angularRegularization(), local_planner::LocalPlanner::costmap_ros_, current_pose_pub_, d_t_, du_p_, local_planner::LocalPlanner::getLookAheadDistance(), local_planner::LocalPlanner::getLookAheadPoint(), local_planner::LocalPlanner::global_plan_, goal_reached_, goal_rpy_, initialized_, local_planner::LocalPlanner::linearRegularization(), local_planner::LocalPlanner::map_frame_, local_planner::LocalPlanner::odom_helper_, local_planner::LocalPlanner::prune(), local_planner::LocalPlanner::regularizeAngle(), local_planner::LocalPlanner::shouldRotateToGoal(), local_planner::LocalPlanner::shouldRotateToPath(), target_pt_pub_, tf_, and local_planner::LocalPlanner::transformPose().
initialize()
void mpc_planner::MPCPlanner::initialize (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Initialization of the local planner.
Parameters
name the name to give this instance of the trajectory planner
tf a pointer to a transform listener
costmap_ros the cost map to use for assigning costs to trajectories
 {
   if (!initialized_)
   {
     initialized_ = true;
     tf_ = tf;
     costmap_ros_ = costmap_ros;
     costmap_2d::Costmap2D* costmap = costmap_ros_->getCostmap();
     // set costmap properties
     setSize(costmap->getSizeInCellsX(), costmap->getSizeInCellsY());
     setOrigin(costmap->getOriginX(), costmap->getOriginY());
     setResolution(costmap->getResolution());
     ros::NodeHandle nh = ros::NodeHandle("~/" + name);
     // base
     nh.param("goal_dist_tolerance", goal_dist_tol_, 0.2);
     nh.param("rotate_tolerance", rotate_tol_, 0.5);
     nh.param("convert_offset", convert_offset_, 0.0);
     nh.param("base_frame", base_frame_, base_frame_);
     nh.param("map_frame", map_frame_, map_frame_);
     // lookahead
     nh.param("lookahead_time", lookahead_time_, 1.5);
     nh.param("min_lookahead_dist", min_lookahead_dist_, 0.3);
     nh.param("max_lookahead_dist", max_lookahead_dist_, 0.9);
     // linear velocity
     nh.param("max_v", max_v_, 0.5);
     nh.param("min_v", min_v_, 0.0);
     nh.param("max_v_inc", max_v_inc_, 0.5);
     // angular velocity
     nh.param("max_w", max_w_, 1.57);
     nh.param("min_w", min_w_, 0.0);
     nh.param("max_w_inc", max_w_inc_, 1.57);
     // iteration for ricatti solution
     nh.param("predicting_time_domain", p_, 4);
     nh.param("control_time_domain", m_, 4);
     // weight matrix for penalizing state error while tracking [x,y,theta]
     std::vector<double> diag_vec;
     nh.getParam("Q_matrix_diag", diag_vec);
     for (size_t i = 0; i < diag_vec.size(); ++i)
       Q_(i, i) = diag_vec[i];
     // weight matrix for penalizing input error while tracking[v, w]
     nh.getParam("R_matrix_diag", diag_vec);
     for (size_t i = 0; i < diag_vec.size(); ++i)
       R_(i, i) = diag_vec[i];
     double controller_freqency;
     nh.param("/move_base/controller_frequency", controller_freqency, 10.0);
     d_t_ = 1 / controller_freqency;
     target_pt_pub_ = nh.advertise<geometry_msgs::PointStamped>("/target_point", 10);
     current_pose_pub_ = nh.advertise<geometry_msgs::PoseStamped>("/current_pose", 10);
     ROS_INFO("MPC planner initialized!");
   }
   else
   {
     ROS_WARN("MPC planner has already been initialized.");
   }
 }
References local_planner::LocalPlanner::base_frame_, local_planner::LocalPlanner::convert_offset_, local_planner::LocalPlanner::costmap_ros_, current_pose_pub_, d_t_, local_planner::LocalPlanner::goal_dist_tol_, initialized_, local_planner::LocalPlanner::lookahead_time_, m_, local_planner::LocalPlanner::map_frame_, local_planner::LocalPlanner::max_lookahead_dist_, local_planner::LocalPlanner::max_v_, local_planner::LocalPlanner::max_v_inc_, local_planner::LocalPlanner::max_w_, local_planner::LocalPlanner::max_w_inc_, local_planner::LocalPlanner::min_lookahead_dist_, local_planner::LocalPlanner::min_v_, local_planner::LocalPlanner::min_w_, rviz_generate::name, p_, Q_, R_, local_planner::LocalPlanner::rotate_tol_, local_planner::LocalPlanner::setOrigin(), local_planner::LocalPlanner::setResolution(), local_planner::LocalPlanner::setSize(), target_pt_pub_, and tf_.
Referenced by MPCPlanner().
isGoalReached()
bool mpc_planner::MPCPlanner::isGoalReached ()
Check if the goal pose has been achieved.
Returns
true if achieved, false otherwise
 {
   if (!initialized_)
   {
     ROS_ERROR("MPC planner has not been initialized");
     return false;
   }
   if (goal_reached_)
   {
     ROS_INFO("GOAL Reached!");
     return true;
   }
   return false;
 }
References goal_reached_, and initialized_.
setPlan()
bool mpc_planner::MPCPlanner::setPlan (const std::vector< geometry_msgs::PoseStamped > & orig_global_plan)
Set the plan that the controller is following.
Parameters
orig_global_plan the plan to pass to the controller
Returns
true if the plan was updated successfully, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   ROS_INFO("Got new plan");
   // set new plan
   global_plan_.clear();
   global_plan_ = orig_global_plan;
   // reset plan parameters
   if (goal_x_ != global_plan_.back().pose.position.x || goal_y_ != global_plan_.back().pose.position.y)
   {
     goal_x_ = global_plan_.back().pose.position.x;
     goal_y_ = global_plan_.back().pose.position.y;
     goal_rpy_ = getEulerAngles(global_plan_.back());
     goal_reached_ = false;
   }
   return true;
 }
References local_planner::LocalPlanner::getEulerAngles(), local_planner::LocalPlanner::global_plan_, goal_reached_, goal_rpy_, goal_x_, goal_y_, and initialized_.
Member Data Documentation
current_pose_pub_
ros::Publisher mpc_planner::MPCPlanner::current_pose_pub_ private
Referenced by computeVelocityCommands(), and initialize().
d_t_
double mpc_planner::MPCPlanner::d_t_ private
Referenced by _mpcControl(), computeVelocityCommands(), and initialize().
du_p_
Eigen::Vector2d mpc_planner::MPCPlanner::du_p_ private
Referenced by computeVelocityCommands().
goal_reached_
bool mpc_planner::MPCPlanner::goal_reached_ private
Referenced by computeVelocityCommands(), isGoalReached(), and setPlan().
goal_rpy_
Eigen::Vector3d mpc_planner::MPCPlanner::goal_rpy_ private
Referenced by computeVelocityCommands(), and setPlan().
goal_x_
double mpc_planner::MPCPlanner::goal_x_ private
Referenced by setPlan().
goal_y_
double mpc_planner::MPCPlanner::goal_y_ private
Referenced by setPlan().
initialized_
bool mpc_planner::MPCPlanner::initialized_ private
Referenced by computeVelocityCommands(), initialize(), isGoalReached(), and setPlan().
m_
int mpc_planner::MPCPlanner::m_ private
Referenced by _mpcControl(), and initialize().
p_
int mpc_planner::MPCPlanner::p_ private
Referenced by _mpcControl(), and initialize().
Q_
Eigen::Matrix3d mpc_planner::MPCPlanner::Q_ private
Referenced by _mpcControl(), and initialize().
R_
Eigen::Matrix2d mpc_planner::MPCPlanner::R_ private
Referenced by _mpcControl(), and initialize().
target_pt_pub_
ros::Publisher mpc_planner::MPCPlanner::target_pt_pub_ private
Referenced by computeVelocityCommands(), and initialize().
tf_
tf2_ros::Buffer* mpc_planner::MPCPlanner::tf_ private
Referenced by computeVelocityCommands(), and initialize().
The documentation for this class was generated from the following files:
src/core/local_planner/mpc_planner/include/mpc_planner.h
src/core/local_planner/mpc_planner/src/mpc_planner.cpp