ROS Motion Planning: trajectory_generation::Curve Class Reference
trajectory_generation::Curve Class Reference abstract
#include <curve.h>
Public Member Functions
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
virtual bool run (const Points2d points, Points2d &path)=0
Running trajectory generation.
virtual bool run (const Poses2d points, Points2d &path)=0
Running trajectory generation.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Attributes
double step_
Constructor & Destructor Documentation
Curve()
trajectory_generation::Curve::Curve (double step)
Construct a new Curve object.
Parameters
step Simulation or interpolation size
                         : step_(step)
 {
 }
~Curve()
virtual trajectory_generation::Curve::~Curve () virtual default
Destroy the curve generation object.
Member Function Documentation
len()
double trajectory_generation::Curve::len (Points2d path)
Calculate length of given path.
Parameters
path the trajectory
Returns
length the length of path
 {
   double length = 0.0;
   for (size_t i = 1; i < path.size(); ++i)
     length += helper::dist(path[i - 1], path[i]);
   return length;
 }
References helper::dist().
Referenced by global_planner::ACO::calFitnessValue(), global_planner::GA::calFitnessValue(), and global_planner::PSO::calFitnessValue().
run() [1/2]
virtual bool trajectory_generation::Curve::run (const Points2d points, Points2d & path) pure virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implemented in trajectory_generation::Polynomial, trajectory_generation::ReedsShepp, trajectory_generation::Dubins, trajectory_generation::BSpline, trajectory_generation::Bezier, and trajectory_generation::CubicSpline.
run() [2/2]
virtual bool trajectory_generation::Curve::run (const Poses2d points, Points2d & path) pure virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implemented in trajectory_generation::Polynomial, trajectory_generation::ReedsShepp, trajectory_generation::Dubins, trajectory_generation::BSpline, trajectory_generation::Bezier, and trajectory_generation::CubicSpline.
setStep()
void trajectory_generation::Curve::setStep (double step)
Configure the simulation step.
Parameters
step Simulation or interpolation size
 {
   assert(step > 0);
   step_ = step;
 }
References step_.
Referenced by global_planner::HybridAStar::HybridAStar().
Member Data Documentation
step_
double trajectory_generation::Curve::step_ protected
Referenced by trajectory_generation::Bezier::generation(), trajectory_generation::BSpline::generation(), trajectory_generation::Polynomial::generation(), trajectory_generation::Dubins::generation(), trajectory_generation::ReedsShepp::generation(), trajectory_generation::CubicSpline::run(), and setStep().
The documentation for this class was generated from the following files:
src/core/curve_generation/include/curve.h
src/core/curve_generation/src/curve.cpp