ROS Motion Planning: spencer_tracking_rviz_plugin::TextNode Class Reference
spencer_tracking_rviz_plugin::TextNode Class Reference
#include <text_node.h>
Public Member Functions
TextNode (Ogre::SceneManager *sceneManager, Ogre::SceneNode *parentNode, Ogre::Vector3 position=Ogre::Vector3::ZERO)
virtual ~TextNode ()
void setCharacterHeight (double characterHeight)
double getCharacterHeight ()
void setCaption (const std::string &caption)
void setPosition (const Ogre::Vector3 &position)
void setVisible (bool visible)
void setColor (const Ogre::ColourValue &c)
void showOnTop (bool onTop=true)
Private Attributes
Ogre::SceneManager * m_sceneManager
Ogre::SceneNode * m_sceneNode
rviz::MovableText * m_text
Constructor & Destructor Documentation
TextNode()
spencer_tracking_rviz_plugin::TextNode::TextNode (Ogre::SceneManager * sceneManager, Ogre::SceneNode * parentNode, Ogre::Vector3 position = Ogre::Vector3::ZERO) inline
                                                                                                                     : m_sceneManager(sceneManager)
         {
             m_sceneNode = parentNode->createChildSceneNode();
             m_text = new rviz::MovableText("text");
             m_text->setTextAlignment(rviz::MovableText::H_CENTER, rviz::MovableText::V_BELOW);
             m_sceneNode->attachObject(m_text);
             setCharacterHeight(1.0);
             setPosition(position);
             setVisible(true);
         }
References m_sceneNode, m_text, setCharacterHeight(), setPosition(), and setVisible().
~TextNode()
virtual spencer_tracking_rviz_plugin::TextNode::~TextNode () inline virtual
{
             m_sceneManager->destroySceneNode(m_sceneNode->getName());
             delete m_text;
         };
References m_sceneManager, m_sceneNode, and m_text.
Member Function Documentation
getCharacterHeight()
double spencer_tracking_rviz_plugin::TextNode::getCharacterHeight () inline
{
             return m_text->getCharacterHeight();
         }
References m_text.
setCaption()
void spencer_tracking_rviz_plugin::TextNode::setCaption (const std::string & caption) inline
{
             m_text->setCaption(caption);
         }
References m_text.
setCharacterHeight()
void spencer_tracking_rviz_plugin::TextNode::setCharacterHeight (double characterHeight) inline
{
             m_text->setCharacterHeight(characterHeight);
             m_text->setSpaceWidth(0.3 * characterHeight);
         }
References m_text.
Referenced by TextNode().
setColor()
void spencer_tracking_rviz_plugin::TextNode::setColor (const Ogre::ColourValue & c) inline
{
             m_text->setColor(c);
         }
References m_text.
setPosition()
void spencer_tracking_rviz_plugin::TextNode::setPosition (const Ogre::Vector3 & position) inline
{
             m_sceneNode->setPosition(position);
         }
References m_sceneNode.
Referenced by TextNode().
setVisible()
void spencer_tracking_rviz_plugin::TextNode::setVisible (bool visible) inline
{
             m_sceneNode->setVisible(visible, true);
         }
References m_sceneNode.
Referenced by TextNode().
showOnTop()
void spencer_tracking_rviz_plugin::TextNode::showOnTop (bool onTop = true) inline
{
             m_text->showOnTop(onTop);
         }
References m_text.
Member Data Documentation
m_sceneManager
Ogre::SceneManager* spencer_tracking_rviz_plugin::TextNode::m_sceneManager private
Referenced by ~TextNode().
m_sceneNode
Ogre::SceneNode* spencer_tracking_rviz_plugin::TextNode::m_sceneNode private
Referenced by setPosition(), setVisible(), TextNode(), and ~TextNode().
m_text
rviz::MovableText* spencer_tracking_rviz_plugin::TextNode::m_text private
Referenced by getCharacterHeight(), setCaption(), setCharacterHeight(), setColor(), showOnTop(), TextNode(), and ~TextNode().
The documentation for this class was generated from the following file:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/visuals/text_node.h