ROS Motion Planning: global_planner::AStar Class Reference
global_planner::AStar Class Reference
Class for objects that plan using the A* algorithm.
#include <a_star.h>
Public Member Functions
AStar (int nx, int ny, double resolution, bool dijkstra=false, bool gbfs=false)
Construct a new AStar object.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
A* implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Private Attributes
bool is_dijkstra_
bool is_gbfs_
Additional Inherited Members
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the A* algorithm.
Constructor & Destructor Documentation
AStar()
global_planner::AStar::AStar (int nx, int ny, double resolution, bool dijkstra = false, bool gbfs = false)
Construct a new AStar object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
dijkstra using diksktra implementation
gbfs using gbfs implementation
                                                                         : GlobalPlanner(nx, ny, resolution)
 {
   // can not using both dijkstra and GBFS at the same time
   if (!(dijkstra && gbfs))
   {
     is_dijkstra_ = dijkstra;
     is_gbfs_ = gbfs;
   }
   else
   {
     is_dijkstra_ = false;
     is_gbfs_ = false;
   }
   factor_ = 0.25;
 };
References global_planner::GlobalPlanner::factor_, is_dijkstra_, and is_gbfs_.
Member Function Documentation
plan()
bool global_planner::AStar::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
A* implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   // clear vector
   path.clear();
   expand.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start);
   // get all possible motions
   const std::vector<Node> motions = Node::getMotion();
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id_) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id_, current));
     expand.push_back(current);
     // goal found
     if (current == goal)
     {
       path = _convertClosedListToPath(closed_list, start, goal);
       return true;
     }
     // explore neighbor of current node
     for (const auto& motion : motions)
     {
       // explore a new node
       Node node_new = current + motion;
       node_new.id_ = grid2Index(node_new.x_, node_new.y_);
       // node_new in closed list
       if (closed_list.find(node_new.id_) != closed_list.end())
         continue;
       node_new.pid_ = current.id_;
       // next node hit the boundary or obstacle
       // prevent planning failed when the current within inflation
       if ((node_new.id_ < 0) || (node_new.id_ >= ns_) ||
           (global_costmap[node_new.id_] >= lethal_cost_ * factor_ &&
            global_costmap[node_new.id_] >= global_costmap[current.id_]))
         continue;
       // if using dijkstra implementation, do not consider heuristics cost
       if (!is_dijkstra_)
         node_new.h_ = helper::dist(node_new, goal);
       // if using GBFS implementation, only consider heuristics cost
       if (is_gbfs_)
         node_new.g_ = 0.0;
       // else, g will be calculate through node_new = current + m
       open_list.push(node_new);
     }
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), helper::dist(), global_planner::GlobalPlanner::factor_, Node::g_, Node::getMotion(), global_planner::GlobalPlanner::grid2Index(), Node::h_, Node::id_, is_dijkstra_, is_gbfs_, global_planner::GlobalPlanner::lethal_cost_, global_planner::GlobalPlanner::ns_, Node::pid_, Node::x_, and Node::y_.
Referenced by global_planner::HybridAStar::plan().
Member Data Documentation
is_dijkstra_
bool global_planner::AStar::is_dijkstra_ private
Referenced by AStar(), and plan().
is_gbfs_
bool global_planner::AStar::is_gbfs_ private
Referenced by AStar(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/a_star.h
src/core/global_planner/graph_planner/src/a_star.cpp