ROS Motion Planning: sfm::SocialForceModel Class Reference
sfm::SocialForceModel Class Reference
#include <sfm.hpp>
Public Member Functions
SocialForceModel (SocialForceModel const &)=delete
void operator= (SocialForceModel const &)=delete
~SocialForceModel ()
std::vector< Agent > & computeForces (std::vector< Agent > &agents, Map *map=NULL) const
void computeForces (Agent &me, std::vector< Agent > &agents, Map *map=NULL)
std::vector< Agent > & updatePosition (std::vector< Agent > &agents, double dt) const
void updatePosition (Agent &me, double dt) const
Static Public Member Functions
static SocialForceModel & getInstance ()
Private Member Functions
SocialForceModel ()
utils::Vector2d computeDesiredForce (Agent &agent) const
void computeObstacleForce (Agent &agent, Map *map) const
void computeSocialForce (unsigned index, std::vector< Agent > &agents) const
void computeSocialForce (Agent &agent, std::vector< Agent > &agents) const
void computeGroupForce (unsigned index, const utils::Vector2d &desiredDirection, std::vector< Agent > &agents, const std::unordered_map< int, Group > &groups) const
void computeGroupForce (Agent &me, const utils::Vector2d &desiredDirection, std::vector< Agent > &agents, Group &group) const
Constructor & Destructor Documentation
SocialForceModel() [1/2]
sfm::SocialForceModel::SocialForceModel (SocialForceModel const &) delete
~SocialForceModel()
sfm::SocialForceModel::~SocialForceModel () inline
   {
   }
SocialForceModel() [2/2]
sfm::SocialForceModel::SocialForceModel () inline private
   {
   }
Member Function Documentation
computeDesiredForce()
utils::Vector2d sfm::SocialForceModel::computeDesiredForce (Agent & agent) const inline private
 {
   utils::Vector2d desiredDirection;
   if (!agent.goals.empty() && (agent.goals.front().center - agent.position).norm() > agent.goals.front().radius)
   {
     utils::Vector2d diff = agent.goals.front().center - agent.position;
     desiredDirection = diff.normalized();
     agent.forces.desiredForce = agent.params.forceFactorDesired *
                                 (desiredDirection * agent.desiredVelocity - agent.velocity) /
                                 agent.params.relaxationTime;
     agent.antimove = false;
   }
   else
   {
     agent.forces.desiredForce = -agent.velocity / agent.params.relaxationTime;
     agent.antimove = true;
   }
   return desiredDirection;
 }
References sfm::Agent::antimove, sfm::Forces::desiredForce, sfm::Agent::desiredVelocity, sfm::Parameters::forceFactorDesired, sfm::Agent::forces, sfm::Agent::goals, utils::Vector2d::normalized(), sfm::Agent::params, sfm::Agent::position, sfm::Parameters::relaxationTime, and sfm::Agent::velocity.
Referenced by computeForces().
computeForces() [1/2]
void sfm::SocialForceModel::computeForces (Agent & me, std::vector< Agent > & agents, Map * map = NULL) inline
 {
   // form the group
   Group mygroup;
   if (me.groupId != -1)
   {
     mygroup.agents.push_back(me.id);
     mygroup.center = me.position;
     for (unsigned i = 0; i < agents.size(); i++)
     {
       if (agents[i].id == me.id)
       {
         continue;
       }
       if (agents[i].groupId == me.groupId)
       {
         mygroup.agents.push_back(i);
         mygroup.center += agents[i].position;
       }
     }
     mygroup.center /= (double)mygroup.agents.size();
   }
   // Compute agent's forces
   utils::Vector2d desiredDirection = computeDesiredForce(me);
   computeObstacleForce(me, map);
   computeSocialForce(me, agents);
   computeGroupForce(me, desiredDirection, agents, mygroup);
   me.forces.globalForce =
       me.forces.desiredForce + me.forces.socialForce + me.forces.obstacleForce + me.forces.groupForce;
 }
References sfm::Group::agents, sfm::Group::center, computeDesiredForce(), computeGroupForce(), computeObstacleForce(), computeSocialForce(), sfm::Forces::desiredForce, sfm::Agent::forces, sfm::Forces::globalForce, sfm::Forces::groupForce, sfm::Agent::groupId, sfm::Agent::id, sfm::Forces::obstacleForce, sfm::Agent::position, and sfm::Forces::socialForce.
computeForces() [2/2]
std::vector< Agent > & sfm::SocialForceModel::computeForces (std::vector< Agent > & agents, Map * map = NULL) const inline
 {
   std::unordered_map<int, Group> groups;
   for (unsigned i = 0; i < agents.size(); i++)
   {
     if (agents[i].groupId < 0)
     {
       continue;
     }
     groups[agents[i].groupId].agents.push_back(i);
     groups[agents[i].groupId].center += agents[i].position;
   }
   for (auto it = groups.begin(); it != groups.end(); ++it)
   {
     it->second.center /= (double)(it->second.agents.size());
   }
   for (unsigned i = 0; i < agents.size(); i++)
   {
     utils::Vector2d desiredDirection = computeDesiredForce(agents[i]);
     computeObstacleForce(agents[i], map);
     computeSocialForce(i, agents);
     computeGroupForce(i, desiredDirection, agents, groups);
     agents[i].forces.globalForce = agents[i].forces.desiredForce + agents[i].forces.socialForce +
                                    agents[i].forces.obstacleForce + agents[i].forces.groupForce;
   }
   return agents;
 }
References computeDesiredForce(), computeGroupForce(), computeObstacleForce(), and computeSocialForce().
computeGroupForce() [1/2]
void sfm::SocialForceModel::computeGroupForce (Agent & me, const utils::Vector2d & desiredDirection, std::vector< Agent > & agents, Group & group) const inline private
 {
   // Agent& agent = agents[index];
   me.forces.groupForce.set(0, 0);
   me.forces.groupGazeForce.set(0, 0);
   me.forces.groupCoherenceForce.set(0, 0);
   me.forces.groupRepulsionForce.set(0, 0);
   if (group.agents.size() < 2)
   {
     return;
   }
   // Gaze force
   utils::Vector2d com = group.center;
   com = (1 / (double)(group.agents.size() - 1)) * (group.agents.size() * com - me.position);
   utils::Vector2d relativeCom = com - me.position;
   utils::Angle visionAngle = utils::Angle::fromDegree(90);
   double elementProduct = desiredDirection.dot(relativeCom);
   utils::Angle comAngle =
       utils::Angle::fromRadian(std::acos(elementProduct / (desiredDirection.norm() * relativeCom.norm())));
   if (comAngle > visionAngle)
   {
 #ifdef _PAPER_VERSION_
     utils::Angle necessaryRotation = comAngle - visionAngle;
     me.forces.groupGazeForce = -necessaryRotation.toRadian() * desiredDirection;
 #else
     double desiredDirectionSquared = desiredDirection.squaredNorm();
     double desiredDirectionDistance = elementProduct / desiredDirectionSquared;
     me.forces.groupGazeForce = desiredDirectionDistance * desiredDirection;
 #endif
     me.forces.groupGazeForce *= me.params.forceFactorGroupGaze;
   }
   // Coherence force
   com = group.center;
   relativeCom = com - me.position;
   double distance = relativeCom.norm();
   double maxDistance = ((double)group.agents.size() - 1) / 2;
 #ifdef _PAPER_VERSION_
   if (distance >= maxDistance)
   {
     me.forces.groupCoherenceForce = relativeCom.normalized();
     me.forces.groupCoherenceForce *= me.params.forceFactorGroupCoherence;
   }
 #else
   me.forces.groupCoherenceForce = relativeCom;
   double softenedFactor = me.params.forceFactorGroupCoherence * (std::tanh(distance - maxDistance) + 1) / 2;
   me.forces.groupCoherenceForce *= softenedFactor;
 #endif
   // Repulsion Force
   // Index 0 -> me
   for (unsigned i = 1; i < group.agents.size(); i++)
   {
     utils::Vector2d diff = me.position - agents.at(group.agents[i]).position;
     if (diff.norm() < me.radius + agents.at(group.agents[i]).radius)
     {
       me.forces.groupRepulsionForce += diff;
     }
   }
   me.forces.groupRepulsionForce *= me.params.forceFactorGroupRepulsion;
   // Group Force
   me.forces.groupForce = me.forces.groupGazeForce + me.forces.groupCoherenceForce + me.forces.groupRepulsionForce;
 }
References sfm::Group::agents, sfm::Group::center, utils::Vector2d::dot(), sfm::Parameters::forceFactorGroupCoherence, sfm::Parameters::forceFactorGroupGaze, sfm::Parameters::forceFactorGroupRepulsion, sfm::Agent::forces, utils::Angle::fromDegree(), utils::Angle::fromRadian(), sfm::Forces::groupCoherenceForce, sfm::Forces::groupForce, sfm::Forces::groupGazeForce, sfm::Forces::groupRepulsionForce, utils::Vector2d::norm(), utils::Vector2d::normalized(), sfm::Agent::params, sfm::Agent::position, sfm::Agent::radius, utils::Vector2d::set(), utils::Vector2d::squaredNorm(), and utils::Angle::toRadian().
computeGroupForce() [2/2]
void sfm::SocialForceModel::computeGroupForce (unsigned index, const utils::Vector2d & desiredDirection, std::vector< Agent > & agents, const std::unordered_map< int, Group > & groups) const inline private
 {
   Agent& agent = agents[index];
   agent.forces.groupForce.set(0, 0);
   agent.forces.groupGazeForce.set(0, 0);
   agent.forces.groupCoherenceForce.set(0, 0);
   agent.forces.groupRepulsionForce.set(0, 0);
   if (groups.count(agent.groupId) == 0 || groups.at(agent.groupId).agents.size() < 2)
   {
     return;
   }
   const Group& group = groups.at(agent.groupId);
   // Gaze force
   utils::Vector2d com = group.center;
   com = (1 / (double)(group.agents.size() - 1)) * (group.agents.size() * com - agent.position);
   utils::Vector2d relativeCom = com - agent.position;
   utils::Angle visionAngle = utils::Angle::fromDegree(90);
   double elementProduct = desiredDirection.dot(relativeCom);
   utils::Angle comAngle =
       utils::Angle::fromRadian(std::acos(elementProduct / (desiredDirection.norm() * relativeCom.norm())));
   if (comAngle > visionAngle)
   {
 #ifdef _PAPER_VERSION_
     utils::Angle necessaryRotation = comAngle - visionAngle;
     agent.forces.groupGazeForce = -necessaryRotation.toRadian() * desiredDirection;
 #else
     double desiredDirectionSquared = desiredDirection.squaredNorm();
     double desiredDirectionDistance = elementProduct / desiredDirectionSquared;
     agent.forces.groupGazeForce = desiredDirectionDistance * desiredDirection;
 #endif
     agent.forces.groupGazeForce *= agent.params.forceFactorGroupGaze;
   }
   // Coherence force
   com = group.center;
   relativeCom = com - agent.position;
   double distance = relativeCom.norm();
   double maxDistance = ((double)group.agents.size() - 1) / 2;
 #ifdef _PAPER_VERSION_
   if (distance >= maxDistance)
   {
     agent.forces.groupCoherenceForce = relativeCom.normalized();
     agent.forces.groupCoherenceForce *= agent.params.forceFactorGroupCoherence;
   }
 #else
   agent.forces.groupCoherenceForce = relativeCom;
   double softenedFactor = agent.params.forceFactorGroupCoherence * (std::tanh(distance - maxDistance) + 1) / 2;
   agent.forces.groupCoherenceForce *= softenedFactor;
 #endif
   // Repulsion Force
   for (unsigned i = 0; i < group.agents.size(); i++)
   {
     if (index == group.agents[i])
     {
       continue;
     }
     utils::Vector2d diff = agent.position - agents.at(group.agents[i]).position;
     if (diff.norm() < agent.radius + agents.at(group.agents[i]).radius)
     {
       agent.forces.groupRepulsionForce += diff;
     }
   }
   agent.forces.groupRepulsionForce *= agent.params.forceFactorGroupRepulsion;
   // Group Force
   agent.forces.groupForce =
       agent.forces.groupGazeForce + agent.forces.groupCoherenceForce + agent.forces.groupRepulsionForce;
 }
References sfm::Group::agents, sfm::Group::center, utils::Vector2d::dot(), sfm::Parameters::forceFactorGroupCoherence, sfm::Parameters::forceFactorGroupGaze, sfm::Parameters::forceFactorGroupRepulsion, sfm::Agent::forces, utils::Angle::fromDegree(), utils::Angle::fromRadian(), sfm::Forces::groupCoherenceForce, sfm::Forces::groupForce, sfm::Forces::groupGazeForce, sfm::Agent::groupId, sfm::Forces::groupRepulsionForce, utils::Vector2d::norm(), utils::Vector2d::normalized(), sfm::Agent::params, sfm::Agent::position, sfm::Agent::radius, utils::Vector2d::set(), utils::Vector2d::squaredNorm(), and utils::Angle::toRadian().
Referenced by computeForces().
computeObstacleForce()
void sfm::SocialForceModel::computeObstacleForce (Agent & agent, Map * map) const inline private
 {
   // Initially, the obstacles were expected to be in robot local frame. We have
   // replaced it to work in the same frame of the other forces.
   //   if (agent.obstacles1.size() > 0 || agent.obstacles2.size() > 0) {
   //     agent.forces.obstacleForce.set(0, 0);
   //     for (unsigned i = 0; i < agent.obstacles1.size(); i++) {
   //       double distance = agent.obstacles1[i].norm() - agent.radius;
   //       agent.forces.obstacleForce +=
   //           agent.params.forceFactorObstacle *
   //           std::exp(-distance / agent.params.forceSigmaObstacle) *
   //           (-agent.obstacles1[i]).normalized();
   //     }
   //     for (unsigned i = 0; i < agent.obstacles2.size(); i++) {
   //       double distance = agent.obstacles2[i].norm() - agent.radius;
   //       agent.forces.obstacleForce +=
   //           agent.params.forceFactorObstacle *
   //           std::exp(-distance / agent.params.forceSigmaObstacle) *
   //           (-agent.obstacles2[i]).normalized();
   //     }
   //     agent.forces.obstacleForce /=
   //         (double)(agent.obstacles1.size() + agent.obstacles2.size());
   if (agent.obstacles1.size() > 0 || agent.obstacles2.size() > 0)
   {
     agent.forces.obstacleForce.set(0, 0);
     for (unsigned i = 0; i < agent.obstacles1.size(); i++)
     {
       utils::Vector2d minDiff = agent.position - agent.obstacles1[i];
       double distance = minDiff.norm() - agent.radius;
       agent.forces.obstacleForce += agent.params.forceFactorObstacle *
                                     std::exp(-distance / agent.params.forceSigmaObstacle) * minDiff.normalized();
     }
     for (unsigned i = 0; i < agent.obstacles2.size(); i++)
     {
       utils::Vector2d minDiff = agent.position - agent.obstacles2[i];
       double distance = minDiff.norm() - agent.radius;
       agent.forces.obstacleForce += agent.params.forceFactorObstacle *
                                     std::exp(-distance / agent.params.forceSigmaObstacle) * minDiff.normalized();
     }
     agent.forces.obstacleForce /= (double)(agent.obstacles1.size() + agent.obstacles2.size());
   }
   else if (map != NULL)
   {
     const Map::Obstacle& obs = map->getNearestObstacle(agent.position);
     utils::Vector2d minDiff = agent.position - obs.position;
     double distance = minDiff.norm() - agent.radius;
     agent.forces.obstacleForce =
         agent.params.forceFactorObstacle * std::exp(-distance / agent.params.forceSigmaObstacle) * minDiff.normalized();
   }
   else
   {
     agent.forces.obstacleForce.set(0, 0);
   }
 }
References sfm::Parameters::forceFactorObstacle, sfm::Agent::forces, sfm::Parameters::forceSigmaObstacle, sfm::Map::getNearestObstacle(), utils::Vector2d::norm(), utils::Vector2d::normalized(), sfm::Forces::obstacleForce, sfm::Agent::obstacles1, sfm::Agent::obstacles2, sfm::Agent::params, sfm::Map::Obstacle::position, sfm::Agent::position, sfm::Agent::radius, and utils::Vector2d::set().
Referenced by computeForces().
computeSocialForce() [1/2]
void sfm::SocialForceModel::computeSocialForce (Agent & agent, std::vector< Agent > & agents) const inline private
 {
   // Agent& agent = agents[index];
   me.forces.socialForce.set(0, 0);
   for (unsigned i = 0; i < agents.size(); i++)
   {
     if (agents[i].id == me.id)
     {
       continue;
     }
     utils::Vector2d diff = agents[i].position - me.position;
     utils::Vector2d diffDirection = diff.normalized();
     utils::Vector2d velDiff = me.velocity - agents[i].velocity;
     utils::Vector2d interactionVector = me.params.lambda * velDiff + diffDirection;
     double interactionLength = interactionVector.norm();
     utils::Vector2d interactionDirection = interactionVector / interactionLength;
     utils::Angle theta = interactionDirection.angleTo(diffDirection);
     double B = me.params.gamma * interactionLength;
     double thetaRad = theta.toRadian();
     double forceVelocityAmount = -std::exp(-diff.norm() / B - PW(me.params.nPrime * B * thetaRad));
     double forceAngleAmount = -theta.sign() * std::exp(-diff.norm() / B - PW(me.params.n * B * thetaRad));
     utils::Vector2d forceVelocity = forceVelocityAmount * interactionDirection;
     utils::Vector2d forceAngle = forceAngleAmount * interactionDirection.leftNormalVector();
     me.forces.socialForce += me.params.forceFactorSocial * (forceVelocity + forceAngle);
     // if (i == 0)
     //{
     //  agent.forces.robotSocialForce =
     //      agent.params.forceFactorSocial * (forceVelocity + forceAngle);
     //}
   }
 }
References utils::Vector2d::angleTo(), sfm::Parameters::forceFactorSocial, sfm::Agent::forces, sfm::Parameters::gamma, sfm::Agent::id, sfm::Parameters::lambda, utils::Vector2d::leftNormalVector(), sfm::Parameters::n, utils::Vector2d::norm(), utils::Vector2d::normalized(), sfm::Parameters::nPrime, sfm::Agent::params, sfm::Agent::position, PW, utils::Vector2d::set(), utils::Angle::sign(), sfm::Forces::socialForce, utils::Angle::toRadian(), and sfm::Agent::velocity.
computeSocialForce() [2/2]
void sfm::SocialForceModel::computeSocialForce (unsigned index, std::vector< Agent > & agents) const inline private
 {
   Agent& agent = agents[index];
   agent.forces.socialForce.set(0, 0);
   for (unsigned i = 0; i < agents.size(); i++)
   {
     if (i == index)
     {
       continue;
     }
     utils::Vector2d diff = agents[i].position - agent.position;
     utils::Vector2d diffDirection = diff.normalized();
     utils::Vector2d velDiff = agent.velocity - agents[i].velocity;
     utils::Vector2d interactionVector = agent.params.lambda * velDiff + diffDirection;
     double interactionLength = interactionVector.norm();
     utils::Vector2d interactionDirection = interactionVector / interactionLength;
     utils::Angle theta = interactionDirection.angleTo(diffDirection);
     double B = agent.params.gamma * interactionLength;
     double thetaRad = theta.toRadian();
     double forceVelocityAmount = -std::exp(-diff.norm() / B - PW(agent.params.nPrime * B * thetaRad));
     double forceAngleAmount = -theta.sign() * std::exp(-diff.norm() / B - PW(agent.params.n * B * thetaRad));
     utils::Vector2d forceVelocity = forceVelocityAmount * interactionDirection;
     utils::Vector2d forceAngle = forceAngleAmount * interactionDirection.leftNormalVector();
     agent.forces.socialForce += agent.params.forceFactorSocial * (forceVelocity + forceAngle);
     if (i == 0)
     {
       agent.forces.robotSocialForce = agent.params.forceFactorSocial * (forceVelocity + forceAngle);
     }
   }
 }
References utils::Vector2d::angleTo(), sfm::Parameters::forceFactorSocial, sfm::Agent::forces, sfm::Parameters::gamma, sfm::Parameters::lambda, utils::Vector2d::leftNormalVector(), sfm::Parameters::n, utils::Vector2d::norm(), utils::Vector2d::normalized(), sfm::Parameters::nPrime, sfm::Agent::params, sfm::Agent::position, PW, sfm::Forces::robotSocialForce, utils::Vector2d::set(), utils::Angle::sign(), sfm::Forces::socialForce, utils::Angle::toRadian(), and sfm::Agent::velocity.
Referenced by computeForces().
getInstance()
static SocialForceModel& sfm::SocialForceModel::getInstance () inline static
   {
     static SocialForceModel singleton;
     return singleton;
   }
operator=()
void sfm::SocialForceModel::operator= (SocialForceModel const &) delete
updatePosition() [1/2]
void sfm::SocialForceModel::updatePosition (Agent & me, double dt) const inline
 {
   utils::Vector2d initPos = agent.position;
   utils::Angle initYaw = agent.yaw;
   agent.velocity += agent.forces.globalForce * dt;
   if (agent.velocity.norm() > agent.desiredVelocity)
   {
     agent.velocity.normalize();
     agent.velocity *= agent.desiredVelocity;
   }
   agent.yaw = agent.velocity.angle();
   agent.position += agent.velocity * dt;
   agent.linearVelocity = agent.velocity.norm();
   agent.angularVelocity = (agent.yaw - initYaw).toRadian() / dt;
   agent.movement = agent.position - initPos;
   if (!agent.goals.empty() && (agent.goals.front().center - agent.position).norm() <= agent.goals.front().radius)
   {
     Goal g = agent.goals.front();
     agent.goals.pop_front();
     if (agent.cyclicGoals)
     {
       agent.goals.push_back(g);
     }
   }
 }
References utils::Vector2d::angle(), sfm::Agent::angularVelocity, sfm::Agent::cyclicGoals, sfm::Agent::desiredVelocity, sfm::Agent::forces, sfm::Forces::globalForce, sfm::Agent::goals, sfm::Agent::linearVelocity, sfm::Agent::movement, utils::Vector2d::norm(), utils::Vector2d::normalize(), sfm::Agent::position, sfm::Agent::velocity, and sfm::Agent::yaw.
updatePosition() [2/2]
std::vector< Agent > & sfm::SocialForceModel::updatePosition (std::vector< Agent > & agents, double dt) const inline
 {
   for (unsigned i = 0; i < agents.size(); i++)
   {
     utils::Vector2d initPos = agents[i].position;
     if (agents[i].teleoperated)
     {
       double imd = agents[i].linearVelocity * dt;
       utils::Vector2d inc(imd * std::cos(agents[i].yaw.toRadian() + agents[i].angularVelocity * dt * 0.5),
                           imd * std::sin(agents[i].yaw.toRadian() + agents[i].angularVelocity * dt * 0.5));
       agents[i].yaw += utils::Angle::fromRadian(agents[i].angularVelocity * dt);
       agents[i].position += inc;
       agents[i].velocity.set(agents[i].linearVelocity * agents[i].yaw.cos(),
                              agents[i].linearVelocity * agents[i].yaw.sin());
     }
     else
     {
       agents[i].velocity += agents[i].forces.globalForce * dt;
       if (agents[i].velocity.norm() > agents[i].desiredVelocity)
       {
         agents[i].velocity.normalize();
         agents[i].velocity *= agents[i].desiredVelocity;
       }
       agents[i].yaw = agents[i].velocity.angle();
       agents[i].position += agents[i].velocity * dt;
     }
     agents[i].movement = agents[i].position - initPos;
     if (!agents[i].goals.empty() &&
         (agents[i].goals.front().center - agents[i].position).norm() <= agents[i].goals.front().radius)
     {
       Goal g = agents[i].goals.front();
       agents[i].goals.pop_front();
       if (agents[i].cyclicGoals)
       {
         agents[i].goals.push_back(g);
       }
     }
   }
   return agents;
 }
References utils::Vector2d::angle(), utils::Angle::fromRadian(), utils::Vector2d::normalize(), and utils::Vector2d::set().
The documentation for this class was generated from the following file:
src/third_party/gazebo_plugins/pedestrian_sfm_plugin/include/lightsfm/sfm.hpp