ROS Motion Planning: global_planner::RRT Class Reference
global_planner::RRT Class Reference
Class for objects that plan using the RRT algorithm.
#include <rrt.h>
Public Member Functions
RRT (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
RRT implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
Node _findNearestPoint (std::unordered_map< int, Node > list, const Node &node)
Regular the sample node by the nearest node in the sample list.
bool _isAnyObstacleInPath (const Node &n1, const Node &n2)
Check if there is any obstacle between the 2 nodes.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
const unsigned char * costs_
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the RRT algorithm.
Constructor & Destructor Documentation
RRT()
global_planner::RRT::RRT (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
sample_num andom sample points
max_dist max distance between sample points
nx pixel number in costmap x direction
ny pixel number in costmap y direction
sample_num andom sample points
max_dist max distance between sample points
   : GlobalPlanner(nx, ny, resolution), sample_num_(sample_num), max_dist_(max_dist)
 {
 }
Member Function Documentation
_checkGoal()
bool global_planner::RRT::_checkGoal (const Node & new_node) protected
Check if goal is reachable from current node.
Parameters
new_node Current node
Returns
bool value of whether goal is reachable from current node
 {
   auto dist_ = helper::dist(new_node, goal_);
   if (dist_ > max_dist_)
     return false;
   if (!_isAnyObstacleInPath(new_node, goal_))
   {
     Node goal(goal_.x_, goal_.y_, dist_ + new_node.g_, 0, grid2Index(goal_.x_, goal_.y_), new_node.id_);
     sample_list_.insert(std::make_pair(goal.id_, goal));
     return true;
   }
   return false;
 }
References _isAnyObstacleInPath(), helper::dist(), Node::g_, goal_, global_planner::GlobalPlanner::grid2Index(), Node::id_, max_dist_, sample_list_, Node::x_, and Node::y_.
Referenced by global_planner::RRTStar::plan(), and plan().
_findNearestPoint()
Node global_planner::RRT::_findNearestPoint (std::unordered_map< int, Node > list, const Node & node) protected
Regular the sample node by the nearest node in the sample list.
Parameters
list samplee list
node sample node
Returns
nearest node
 {
   Node nearest_node, new_node(node);
   double min_dist = std::numeric_limits<double>::max();
   for (const auto & p : list)
   {
     // calculate distance
     double new_dist = helper::dist(p.second, new_node);
     // update nearest node
     if (new_dist < min_dist)
     {
       nearest_node = p.second;
       new_node.pid_ = nearest_node.id_;
       new_node.g_ = new_dist + p.second.g_;
       min_dist = new_dist;
     }
   }
   // distance longer than the threshold
   if (min_dist > max_dist_)
   {
     // connect sample node and nearest node, then move the nearest node
     // forward to sample node with `max_distance` as result
     double theta = helper::angle(nearest_node, new_node);
     new_node.x_ = nearest_node.x_ + (int)(max_dist_ * cos(theta));
     new_node.y_ = nearest_node.y_ + (int)(max_dist_ * sin(theta));
     new_node.id_ = grid2Index(new_node.x_, new_node.y_);
     new_node.g_ = max_dist_ + nearest_node.g_;
   }
   // obstacle check
   if (_isAnyObstacleInPath(new_node, nearest_node))
     new_node.id_ = -1;
   return new_node;
 }
References _isAnyObstacleInPath(), helper::angle(), helper::dist(), Node::g_, global_planner::GlobalPlanner::grid2Index(), Node::id_, max_dist_, tf_map2odom::node, Node::pid_, Node::x_, and Node::y_.
Referenced by global_planner::RRTConnect::plan(), and plan().
_generateRandomNode()
Node global_planner::RRT::_generateRandomNode () protected
Generates a random node.
Returns
Generated node
 {
   // obtain a random number from hardware
   std::random_device rd;
   // seed the generator
   std::mt19937 eng(rd());
   // define the range
   std::uniform_real_distribution<float> p(0, 1);
   // heuristic
   if (p(eng) > 0.05)
   {
     // generate node
     std::uniform_int_distribution<int> distr(0, ns_ - 1);
     const int id = distr(eng);
     int x, y;
     index2Grid(id, x, y);
     return Node(x, y, 0, 0, id, 0);
   }
   else
     return Node(goal_.x_, goal_.y_, 0, 0, goal_.id_, 0);
 }
References goal_, Node::id_, global_planner::GlobalPlanner::index2Grid(), global_planner::GlobalPlanner::ns_, Node::x_, and Node::y_.
Referenced by global_planner::InformedRRT::_generateRandomNode(), global_planner::RRTStar::plan(), global_planner::RRTConnect::plan(), and plan().
_isAnyObstacleInPath()
bool global_planner::RRT::_isAnyObstacleInPath (const Node & n1, const Node & n2) protected
Check if there is any obstacle between the 2 nodes.
Parameters
n1 Node 1
n2 Node 2
Returns
bool value of whether obstacle exists between nodes
 {
   double theta = helper::angle(n1, n2);
   double dist_ = helper::dist(n1, n2);
   // distance longer than the threshold
   if (dist_ > max_dist_)
     return true;
   // sample the line between two nodes and check obstacle
   int n_step = (int)(dist_ / resolution_);
   for (int i = 0; i < n_step; i++)
   {
     float line_x = (float)n1.x_ + (float)(i * resolution_ * cos(theta));
     float line_y = (float)n1.y_ + (float)(i * resolution_ * sin(theta));
     if (costs_[grid2Index((int)line_x, (int)line_y)] >= lethal_cost_ * factor_)
       return true;
   }
   return false;
 }
References helper::angle(), costs_, helper::dist(), global_planner::GlobalPlanner::factor_, global_planner::GlobalPlanner::grid2Index(), global_planner::GlobalPlanner::lethal_cost_, max_dist_, global_planner::GlobalPlanner::resolution_, Node::x_, and Node::y_.
Referenced by _checkGoal(), global_planner::RRTStar::_findNearestPoint(), _findNearestPoint(), global_planner::RRTConnect::plan(), and global_planner::InformedRRT::plan().
plan()
bool global_planner::RRT::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
RRT implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
Reimplemented in global_planner::RRTConnect, and global_planner::RRTStar.
 {
   path.clear();
   expand.clear();
   sample_list_.clear();
   // copy
   start_ = start, goal_ = goal;
   costs_ = global_costmap;
   sample_list_.insert(std::make_pair(start.id_, start));
   expand.push_back(start);
   // main loop
   int iteration = 0;
   while (iteration < sample_num_)
   {
     // generate a random node in the map
     Node sample_node = _generateRandomNode();
     // obstacle
     if (global_costmap[sample_node.id_] >= lethal_cost_ * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id_) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_, sample_node);
     if (new_node.id_ == -1)
       continue;
     else
     {
       sample_list_.insert(std::make_pair(new_node.id_, new_node));
       expand.push_back(new_node);
     }
     // goal found
     if (_checkGoal(new_node))
     {
       path = _convertClosedListToPath(sample_list_, start, goal);
       return true;
     }
     iteration++;
   }
   return false;
 }
References _checkGoal(), global_planner::GlobalPlanner::_convertClosedListToPath(), _findNearestPoint(), _generateRandomNode(), costs_, global_planner::GlobalPlanner::factor_, goal_, Node::id_, global_planner::GlobalPlanner::lethal_cost_, sample_list_, sample_num_, and start_.
Member Data Documentation
costs_
const unsigned char* global_planner::RRT::costs_ protected
Referenced by _isAnyObstacleInPath(), global_planner::RRTStar::plan(), global_planner::RRTConnect::plan(), global_planner::InformedRRT::plan(), and plan().
goal_
Node global_planner::RRT::goal_ protected
Referenced by _checkGoal(), global_planner::RRTConnect::_convertClosedListToPath(), _generateRandomNode(), global_planner::InformedRRT::_transform(), global_planner::RRTStar::plan(), global_planner::RRTConnect::plan(), global_planner::InformedRRT::plan(), and plan().
max_dist_
double global_planner::RRT::max_dist_ protected
Referenced by _checkGoal(), global_planner::RRTStar::_findNearestPoint(), _findNearestPoint(), _isAnyObstacleInPath(), global_planner::RRTConnect::plan(), and global_planner::InformedRRT::plan().
sample_list_
std::unordered_map<int, Node> global_planner::RRT::sample_list_ protected
Referenced by _checkGoal(), global_planner::RRTConnect::_convertClosedListToPath(), global_planner::RRTStar::_findNearestPoint(), global_planner::RRTConnect::plan(), global_planner::RRTStar::plan(), global_planner::InformedRRT::plan(), and plan().
sample_num_
int global_planner::RRT::sample_num_ protected
Referenced by global_planner::RRTConnect::plan(), global_planner::RRTStar::plan(), global_planner::InformedRRT::plan(), and plan().
start_
Node global_planner::RRT::start_ protected
Referenced by global_planner::RRTConnect::_convertClosedListToPath(), global_planner::InformedRRT::_transform(), global_planner::RRTConnect::plan(), global_planner::RRTStar::plan(), global_planner::InformedRRT::plan(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/sample_planner/include/rrt.h
src/core/global_planner/sample_planner/src/rrt.cpp