ROS Motion Planning: RVO::KdTree Class Reference
RVO::KdTree Class Reference
Defines k-D trees for agents and static obstacles in the simulation.
#include <KdTree.h>
Classes
class AgentTreeNode
Defines an agent k-D tree node.
class ObstacleTreeNode
Defines an obstacle k-D tree node.
Private Member Functions
KdTree (RVOSimulator *simulator)
Constructs a k-D tree instance.
~KdTree ()
Destroys this k-D tree instance.
void buildAgentTree ()
Builds an agent k-D tree.
void buildAgentTreeRecursive (std::size_t begin, std::size_t end, std::size_t node)
Recursive function to build an agent k-D tree.
void buildObstacleTree ()
Builds an obstacle k-D tree.
ObstacleTreeNode * buildObstacleTreeRecursive (const std::vector< Obstacle * > &obstacles)
Recursive function to build an obstacle k-D tree.
void computeAgentNeighbors (Agent *agent, float &rangeSq) const
Computes the agent neighbors of the specified agent.
void computeObstacleNeighbors (Agent *agent, float rangeSq) const
Computes the obstacle neighbors of the specified agent.
void deleteObstacleTree (ObstacleTreeNode *node)
Deletes the specified obstacle tree node.
void queryAgentTreeRecursive (Agent *agent, float &rangeSq, std::size_t node) const
Recursive function to compute the neighbors of the specified agent.
void queryObstacleTreeRecursive (Agent *agent, float rangeSq, const ObstacleTreeNode *node) const
Recursive function to compute the neighbors of the specified obstacle.
bool queryVisibility (const Vector2 &vector1, const Vector2 &vector2, float radius) const
Queries the visibility between two points within a specified radius.
bool queryVisibilityRecursive (const Vector2 &vector1, const Vector2 &vector2, float radius, const ObstacleTreeNode *node) const
Recursive function to query the visibility between two points within a specified radius.
KdTree (const KdTree &other)
KdTree & operator= (const KdTree &other)
Private Attributes
std::vector< Agent * > agents_
std::vector< AgentTreeNode > agentTree_
ObstacleTreeNode * obstacleTree_
RVOSimulator * simulator_
Friends
class Agent
class RVOSimulator
Detailed Description
Defines k-D trees for agents and static obstacles in the simulation.
Constructor & Destructor Documentation
KdTree() [1/2]
RVO::KdTree::KdTree (RVOSimulator * simulator) explicit private
Constructs a k-D tree instance.
Parameters
[in] simulator The simulator instance.
     : obstacleTree_(NULL), simulator_(simulator) {}
~KdTree()
RVO::KdTree::~KdTree () private
Destroys this k-D tree instance.
 { deleteObstacleTree(obstacleTree_); }
References deleteObstacleTree(), and obstacleTree_.
KdTree() [2/2]
RVO::KdTree::KdTree (const KdTree & other) private
Member Function Documentation
buildAgentTree()
void RVO::KdTree::buildAgentTree () private
Builds an agent k-D tree.
{
   if (agents_.size() < simulator_->agents_.size()) {
     agents_.insert(agents_.end(),
                    simulator_->agents_.begin() +
                        static_cast<std::ptrdiff_t>(agents_.size()),
                    simulator_->agents_.end());
     agentTree_.resize(2U * agents_.size() - 1U);
   }
   if (!agents_.empty()) {
     buildAgentTreeRecursive(0U, agents_.size(), 0U);
   }
 }
References agents_, RVO::RVOSimulator::agents_, agentTree_, buildAgentTreeRecursive(), and simulator_.
Referenced by RVO::RVOSimulator::doStep(), and RVO::RVOSimulator::getAgentNewSpeed().
buildAgentTreeRecursive()
void RVO::KdTree::buildAgentTreeRecursive (std::size_t begin, std::size_t end, std::size_t node) private
Recursive function to build an agent k-D tree.
Parameters
[in] begin The beginning agent k-D tree node.
[in] end The ending agent k-D tree node.
[in] node The current agent k-D tree node.
{
   agentTree_[node].begin = begin;
   agentTree_[node].end = end;
   agentTree_[node].minX = agentTree_[node].maxX = agents_[begin]->position_.x();
   agentTree_[node].minY = agentTree_[node].maxY = agents_[begin]->position_.y();
   for (std::size_t i = begin + 1U; i < end; ++i) {
     agentTree_[node].maxX =
         std::max(agentTree_[node].maxX, agents_[i]->position_.x());
     agentTree_[node].minX =
         std::min(agentTree_[node].minX, agents_[i]->position_.x());
     agentTree_[node].maxY =
         std::max(agentTree_[node].maxY, agents_[i]->position_.y());
     agentTree_[node].minY =
         std::min(agentTree_[node].minY, agents_[i]->position_.y());
   }
   if (end - begin > RVO_MAX_LEAF_SIZE) {
     /* No leaf node. */
     const bool isVertical = agentTree_[node].maxX - agentTree_[node].minX >
                             agentTree_[node].maxY - agentTree_[node].minY;
     const float splitValue =
         0.5F * (isVertical ? agentTree_[node].maxX + agentTree_[node].minX
                            : agentTree_[node].maxY + agentTree_[node].minY);
     std::size_t left = begin;
     std::size_t right = end;
     while (left < right) {
       while (left < right &&
              (isVertical ? agents_[left]->position_.x()
                          : agents_[left]->position_.y()) < splitValue) {
         ++left;
       }
       while (right > left &&
              (isVertical ? agents_[right - 1U]->position_.x()
                          : agents_[right - 1U]->position_.y()) >= splitValue) {
         --right;
       }
       if (left < right) {
         std::swap(agents_[left], agents_[right - 1U]);
         ++left;
         --right;
       }
     }
     if (left == begin) {
       ++left;
       ++right;
     }
     agentTree_[node].left = node + 1U;
     agentTree_[node].right = node + 2U * (left - begin);
     buildAgentTreeRecursive(begin, left, agentTree_[node].left);
     buildAgentTreeRecursive(left, end, agentTree_[node].right);
   }
 }
References agents_, agentTree_, tf_map2odom::node, and RVO_MAX_LEAF_SIZE.
Referenced by buildAgentTree().
buildObstacleTree()
void RVO::KdTree::buildObstacleTree () private
Builds an obstacle k-D tree.
{
   deleteObstacleTree(obstacleTree_);
   const std::vector<Obstacle *> obstacles(simulator_->obstacles_);
   obstacleTree_ = buildObstacleTreeRecursive(obstacles);
 }
References buildObstacleTreeRecursive(), deleteObstacleTree(), plugins.obstacles_generate_ros::obstacles, RVO::RVOSimulator::obstacles_, obstacleTree_, and simulator_.
Referenced by RVO::RVOSimulator::processObstacles().
buildObstacleTreeRecursive()
KdTree::ObstacleTreeNode * RVO::KdTree::buildObstacleTreeRecursive (const std::vector< Obstacle * > & obstacles) private
Recursive function to build an obstacle k-D tree.
Parameters
[in] obstacles List of obstacles from which to build the obstacle k-D tree.
{
   if (!obstacles.empty()) {
     ObstacleTreeNode *const node = new ObstacleTreeNode();
     std::size_t optimalSplit = 0U;
     std::size_t minLeft = obstacles.size();
     std::size_t minRight = obstacles.size();
     for (std::size_t i = 0U; i < obstacles.size(); ++i) {
       std::size_t leftSize = 0U;
       std::size_t rightSize = 0U;
       const Obstacle *const obstacleI1 = obstacles[i];
       const Obstacle *const obstacleI2 = obstacleI1->next_;
       /* Compute optimal split node. */
       for (std::size_t j = 0U; j < obstacles.size(); ++j) {
         if (i != j) {
           const Obstacle *const obstacleJ1 = obstacles[j];
           const Obstacle *const obstacleJ2 = obstacleJ1->next_;
           const float j1LeftOfI = leftOf(obstacleI1->point_, obstacleI2->point_,
                                          obstacleJ1->point_);
           const float j2LeftOfI = leftOf(obstacleI1->point_, obstacleI2->point_,
                                          obstacleJ2->point_);
           if (j1LeftOfI >= -RVO_EPSILON && j2LeftOfI >= -RVO_EPSILON) {
             ++leftSize;
           } else if (j1LeftOfI <= RVO_EPSILON && j2LeftOfI <= RVO_EPSILON) {
             ++rightSize;
           } else {
             ++leftSize;
             ++rightSize;
           }
           if (std::make_pair(std::max(leftSize, rightSize),
                              std::min(leftSize, rightSize)) >=
               std::make_pair(std::max(minLeft, minRight),
                              std::min(minLeft, minRight))) {
             break;
           }
         }
       }
       if (std::make_pair(std::max(leftSize, rightSize),
                          std::min(leftSize, rightSize)) <
           std::make_pair(std::max(minLeft, minRight),
                          std::min(minLeft, minRight))) {
         minLeft = leftSize;
         minRight = rightSize;
         optimalSplit = i;
       }
     }
     /* Build split node. */
     std::vector<Obstacle *> leftObstacles(minLeft);
     std::vector<Obstacle *> rightObstacles(minRight);
     std::size_t leftCounter = 0U;
     std::size_t rightCounter = 0U;
     const std::size_t i = optimalSplit;
     const Obstacle *const obstacleI1 = obstacles[i];
     const Obstacle *const obstacleI2 = obstacleI1->next_;
     for (std::size_t j = 0U; j < obstacles.size(); ++j) {
       if (i != j) {
         Obstacle *const obstacleJ1 = obstacles[j];
         Obstacle *const obstacleJ2 = obstacleJ1->next_;
         const float j1LeftOfI =
             leftOf(obstacleI1->point_, obstacleI2->point_, obstacleJ1->point_);
         const float j2LeftOfI =
             leftOf(obstacleI1->point_, obstacleI2->point_, obstacleJ2->point_);
         if (j1LeftOfI >= -RVO_EPSILON && j2LeftOfI >= -RVO_EPSILON) {
           leftObstacles[leftCounter++] = obstacles[j];
         } else if (j1LeftOfI <= RVO_EPSILON && j2LeftOfI <= RVO_EPSILON) {
           rightObstacles[rightCounter++] = obstacles[j];
         } else {
           /* Split obstacle j. */
           const float t = det(obstacleI2->point_ - obstacleI1->point_,
                               obstacleJ1->point_ - obstacleI1->point_) /
                           det(obstacleI2->point_ - obstacleI1->point_,
                               obstacleJ1->point_ - obstacleJ2->point_);
           const Vector2 splitPoint =
               obstacleJ1->point_ +
               t * (obstacleJ2->point_ - obstacleJ1->point_);
           Obstacle *const newObstacle = new Obstacle();
           newObstacle->direction_ = obstacleJ1->direction_;
           newObstacle->point_ = splitPoint;
           newObstacle->next_ = obstacleJ2;
           newObstacle->previous_ = obstacleJ1;
           newObstacle->id_ = simulator_->obstacles_.size();
           newObstacle->isConvex_ = true;
           simulator_->obstacles_.push_back(newObstacle);
           obstacleJ1->next_ = newObstacle;
           obstacleJ2->previous_ = newObstacle;
           if (j1LeftOfI > 0.0F) {
             leftObstacles[leftCounter++] = obstacleJ1;
             rightObstacles[rightCounter++] = newObstacle;
           } else {
             rightObstacles[rightCounter++] = obstacleJ1;
             leftObstacles[leftCounter++] = newObstacle;
           }
         }
       }
     }
     node->obstacle = obstacleI1;
     node->left = buildObstacleTreeRecursive(leftObstacles);
     node->right = buildObstacleTreeRecursive(rightObstacles);
     return node;
   }
   return NULL;
 }
References RVO::det(), RVO::Obstacle::direction_, RVO::Obstacle::id_, RVO::leftOf(), RVO::Obstacle::next_, tf_map2odom::node, plugins.obstacles_generate_ros::obstacles, RVO::RVOSimulator::obstacles_, RVO::Obstacle::point_, RVO::Obstacle::previous_, RVO::RVO_EPSILON, and simulator_.
Referenced by buildObstacleTree().
computeAgentNeighbors()
void RVO::KdTree::computeAgentNeighbors (Agent * agent, float & rangeSq) const private
Computes the agent neighbors of the specified agent.
Parameters
[in] agent A pointer to the agent for which agent neighbors are to be computed.
[in,out] rangeSq The squared range around the agent.
{
   queryAgentTreeRecursive(agent, rangeSq, 0U);
 }
References queryAgentTreeRecursive().
Referenced by RVO::Agent::computeNeighbors().
computeObstacleNeighbors()
void RVO::KdTree::computeObstacleNeighbors (Agent * agent, float rangeSq) const private
Computes the obstacle neighbors of the specified agent.
Parameters
[in] agent A pointer to the agent for which obstacle neighbors are to be computed.
[in] rangeSq The squared range around the agent.
{
   queryObstacleTreeRecursive(agent, rangeSq, obstacleTree_);
 }
References obstacleTree_, and queryObstacleTreeRecursive().
Referenced by RVO::Agent::computeNeighbors().
deleteObstacleTree()
void RVO::KdTree::deleteObstacleTree (ObstacleTreeNode * node) private
Deletes the specified obstacle tree node.
Parameters
[in] node A pointer to the obstacle tree node to be deleted.
{
   if (node != NULL) {
     deleteObstacleTree(node->left);
     deleteObstacleTree(node->right);
     delete node;
   }
 }
References tf_map2odom::node.
Referenced by buildObstacleTree(), and ~KdTree().
operator=()
KdTree& RVO::KdTree::operator= (const KdTree & other) private
queryAgentTreeRecursive()
void RVO::KdTree::queryAgentTreeRecursive (Agent * agent, float & rangeSq, std::size_t node) const private
Recursive function to compute the neighbors of the specified agent.
Parameters
[in] agent A pointer to the agent for which neighbors are to be computed.
[in,out] rangeSq The squared range around the agent.
[in] node The current agent k-D tree node.
{
   if (agentTree_[node].end - agentTree_[node].begin <= RVO_MAX_LEAF_SIZE) {
     for (std::size_t i = agentTree_[node].begin; i < agentTree_[node].end;
          ++i) {
       agent->insertAgentNeighbor(agents_[i], rangeSq);
     }
   } else {
     const float distLeftMinX = std::max(
         0.0F, agentTree_[agentTree_[node].left].minX - agent->position_.x());
     const float distLeftMaxX = std::max(
         0.0F, agent->position_.x() - agentTree_[agentTree_[node].left].maxX);
     const float distLeftMinY = std::max(
         0.0F, agentTree_[agentTree_[node].left].minY - agent->position_.y());
     const float distLeftMaxY = std::max(
         0.0F, agent->position_.y() - agentTree_[agentTree_[node].left].maxY);
     const float distSqLeft =
         distLeftMinX * distLeftMinX + distLeftMaxX * distLeftMaxX +
         distLeftMinY * distLeftMinY + distLeftMaxY * distLeftMaxY;
     const float distRightMinX = std::max(
         0.0F, agentTree_[agentTree_[node].right].minX - agent->position_.x());
     const float distRightMaxX = std::max(
         0.0F, agent->position_.x() - agentTree_[agentTree_[node].right].maxX);
     const float distRightMinY = std::max(
         0.0F, agentTree_[agentTree_[node].right].minY - agent->position_.y());
     const float distRightMaxY = std::max(
         0.0F, agent->position_.y() - agentTree_[agentTree_[node].right].maxY);
     const float distSqRight =
         distRightMinX * distRightMinX + distRightMaxX * distRightMaxX +
         distRightMinY * distRightMinY + distRightMaxY * distRightMaxY;
     if (distSqLeft < distSqRight) {
       if (distSqLeft < rangeSq) {
         queryAgentTreeRecursive(agent, rangeSq, agentTree_[node].left);
         if (distSqRight < rangeSq) {
           queryAgentTreeRecursive(agent, rangeSq, agentTree_[node].right);
         }
       }
     } else if (distSqRight < rangeSq) {
       queryAgentTreeRecursive(agent, rangeSq, agentTree_[node].right);
       if (distSqLeft < rangeSq) {
         queryAgentTreeRecursive(agent, rangeSq, agentTree_[node].left);
       }
     }
   }
 }
References agents_, agentTree_, RVO::Agent::insertAgentNeighbor(), tf_map2odom::node, RVO::Agent::position_, RVO_MAX_LEAF_SIZE, RVO::Vector2::x(), and RVO::Vector2::y().
Referenced by computeAgentNeighbors().
queryObstacleTreeRecursive()
void RVO::KdTree::queryObstacleTreeRecursive (Agent * agent, float rangeSq, const ObstacleTreeNode * node) const private
Recursive function to compute the neighbors of the specified obstacle.
Parameters
[in] agent A pointer to the agent for which neighbors are to be computed.
[in,out] rangeSq The squared range around the agent.
[in] node The current obstacle k-D tree node.
{
   if (node != NULL) {
     const Obstacle *const obstacle1 = node->obstacle;
     const Obstacle *const obstacle2 = obstacle1->next_;
     const float agentLeftOfLine =
         leftOf(obstacle1->point_, obstacle2->point_, agent->position_);
     queryObstacleTreeRecursive(
         agent, rangeSq, agentLeftOfLine >= 0.0F ? node->left : node->right);
     const float distSqLine = agentLeftOfLine * agentLeftOfLine /
                              absSq(obstacle2->point_ - obstacle1->point_);
     if (distSqLine < rangeSq) {
       if (agentLeftOfLine < 0.0F) {
         /* Try obstacle at this node only if agent is on right side of obstacle
          * and can see obstacle. */
         agent->insertObstacleNeighbor(node->obstacle, rangeSq);
       }
       /* Try other side of line. */
       queryObstacleTreeRecursive(
           agent, rangeSq, agentLeftOfLine >= 0.0F ? node->right : node->left);
     }
   }
 }
References RVO::absSq(), RVO::Agent::insertObstacleNeighbor(), RVO::leftOf(), RVO::Obstacle::next_, tf_map2odom::node, RVO::Obstacle::point_, and RVO::Agent::position_.
Referenced by computeObstacleNeighbors().
queryVisibility()
bool RVO::KdTree::queryVisibility (const Vector2 & vector1, const Vector2 & vector2, float radius) const private
Queries the visibility between two points within a specified radius.
Parameters
[in] vector1 The first point between which visibility is to be tested.
[in] vector2 The second point between which visibility is to be tested.
[in] radius The radius within which visibility is to be tested.
Returns
True if q1 and q2 are mutually visible within the radius; false otherwise.
{
   return queryVisibilityRecursive(vector1, vector2, radius, obstacleTree_);
 }
References obstacleTree_, and queryVisibilityRecursive().
Referenced by RVO::RVOSimulator::queryVisibility().
queryVisibilityRecursive()
bool RVO::KdTree::queryVisibilityRecursive (const Vector2 & vector1, const Vector2 & vector2, float radius, const ObstacleTreeNode * node) const private
Recursive function to query the visibility between two points within a specified radius.
Parameters
[in] vector1 The first point between which visibility is to be tested.
[in] vector2 The second point between which visibility is to be tested.
[in] radius The radius within which visibility is to be tested.
[in] node The current obstacle k-D tree node.
Returns
True if q1 and q2 are mutually visible within the radius; false otherwise.
{
   if (node != NULL) {
     const Obstacle *const obstacle1 = node->obstacle;
     const Obstacle *const obstacle2 = obstacle1->next_;
     const float q1LeftOfI =
         leftOf(obstacle1->point_, obstacle2->point_, vector1);
     const float q2LeftOfI =
         leftOf(obstacle1->point_, obstacle2->point_, vector2);
     const float invLengthI =
         1.0F / absSq(obstacle2->point_ - obstacle1->point_);
     if (q1LeftOfI >= 0.0F && q2LeftOfI >= 0.0F) {
       return queryVisibilityRecursive(vector1, vector2, radius, node->left) &&
              ((q1LeftOfI * q1LeftOfI * invLengthI >= radius * radius &&
                q2LeftOfI * q2LeftOfI * invLengthI >= radius * radius) ||
               queryVisibilityRecursive(vector1, vector2, radius, node->right));
     }
     if (q1LeftOfI <= 0.0F && q2LeftOfI <= 0.0F) {
       return queryVisibilityRecursive(vector1, vector2, radius, node->right) &&
              ((q1LeftOfI * q1LeftOfI * invLengthI >= radius * radius &&
                q2LeftOfI * q2LeftOfI * invLengthI >= radius * radius) ||
               queryVisibilityRecursive(vector1, vector2, radius, node->left));
     }
     if (q1LeftOfI >= 0.0F && q2LeftOfI <= 0.0F) {
       /* One can see through obstacle from left to right. */
       return queryVisibilityRecursive(vector1, vector2, radius, node->left) &&
              queryVisibilityRecursive(vector1, vector2, radius, node->right);
     }
     const float point1LeftOfQ = leftOf(vector1, vector2, obstacle1->point_);
     const float point2LeftOfQ = leftOf(vector1, vector2, obstacle2->point_);
     const float invLengthQ = 1.0F / absSq(vector2 - vector1);
     return point1LeftOfQ * point2LeftOfQ >= 0.0F &&
            point1LeftOfQ * point1LeftOfQ * invLengthQ > radius * radius &&
            point2LeftOfQ * point2LeftOfQ * invLengthQ > radius * radius &&
            queryVisibilityRecursive(vector1, vector2, radius, node->left) &&
            queryVisibilityRecursive(vector1, vector2, radius, node->right);
   }
   return true;
 }
References RVO::absSq(), RVO::leftOf(), RVO::Obstacle::next_, tf_map2odom::node, and RVO::Obstacle::point_.
Referenced by queryVisibility().
Friends And Related Function Documentation
Agent
friend class Agent friend
RVOSimulator
friend class RVOSimulator friend
Member Data Documentation
agents_
std::vector<Agent *> RVO::KdTree::agents_ private
Referenced by buildAgentTree(), buildAgentTreeRecursive(), and queryAgentTreeRecursive().
agentTree_
std::vector<AgentTreeNode> RVO::KdTree::agentTree_ private
Referenced by buildAgentTree(), buildAgentTreeRecursive(), and queryAgentTreeRecursive().
obstacleTree_
ObstacleTreeNode* RVO::KdTree::obstacleTree_ private
Referenced by buildObstacleTree(), computeObstacleNeighbors(), queryVisibility(), and ~KdTree().
simulator_
RVOSimulator* RVO::KdTree::simulator_ private
Referenced by buildAgentTree(), buildObstacleTree(), and buildObstacleTreeRecursive().
The documentation for this class was generated from the following files:
src/core/local_planner/orca_planner/include/RVO/KdTree.h
src/core/local_planner/orca_planner/include/RVO/KdTree.cc