ROS Motion Planning: spencer_tracking_rviz_plugin::TrackedPersonsCache Class Reference
spencer_tracking_rviz_plugin::TrackedPersonsCache Class Reference
#include <tracked_persons_cache.h>
Public Types
typedef std::map< track_id, boost::shared_ptr< CachedTrackedPerson > > CachedTrackedPersonsMap
Public Member Functions
~TrackedPersonsCache ()
void initialize (rviz::Display *display, rviz::DisplayContext *context, ros::NodeHandle update_nh)
Create TrackedPersons subscriber and setup RViz properties.
void reset ()
Clear internal state, including all cached track positions.
const boost::shared_ptr< CachedTrackedPerson > lookup (track_id trackId)
Lookup information for the given tracked person ID. Returns a null pointer if no information is available.
const CachedTrackedPersonsMap & getMap ()
Return internal map.
Private Member Functions
void processTrackedPersonsMessage (const spencer_tracking_msgs::TrackedPersons::ConstPtr &msg)
Private Attributes
rviz::AdditionalTopicSubscriber< spencer_tracking_msgs::TrackedPersons > * m_tracked_person_subscriber
rviz::Display * m_display
rviz::DisplayContext * m_context
CachedTrackedPersonsMap m_cachedTrackedPersons
Detailed Description
Subscribes to a TrackedPersons topic and caches all TrackedPersons of the current cycle, so that the owning rviz::Display can look up track positions etc for visualization.
Member Typedef Documentation
CachedTrackedPersonsMap
typedef std::map<track_id, boost::shared_ptr<CachedTrackedPerson> > spencer_tracking_rviz_plugin::TrackedPersonsCache::CachedTrackedPersonsMap
Constructor & Destructor Documentation
~TrackedPersonsCache()
spencer_tracking_rviz_plugin::TrackedPersonsCache::~TrackedPersonsCache ()
 {
     m_cachedTrackedPersons.clear();
     delete m_tracked_person_subscriber;
 }
References m_cachedTrackedPersons, and m_tracked_person_subscriber.
Member Function Documentation
getMap()
const CachedTrackedPersonsMap& spencer_tracking_rviz_plugin::TrackedPersonsCache::getMap () inline
Return internal map.
{
             return m_cachedTrackedPersons;
         }
References m_cachedTrackedPersons.
Referenced by spencer_tracking_rviz_plugin::SocialActivitiesDisplay::processMessage().
initialize()
void spencer_tracking_rviz_plugin::TrackedPersonsCache::initialize (rviz::Display * display, rviz::DisplayContext * context, ros::NodeHandle update_nh)
Create TrackedPersons subscriber and setup RViz properties.
 {
     m_display = display;
     m_context = context;
     m_tracked_person_subscriber = new rviz::AdditionalTopicSubscriber<spencer_tracking_msgs::TrackedPersons>("Tracked persons topic", display, context, update_nh,
         boost::bind(&TrackedPersonsCache::processTrackedPersonsMessage, this, _1));
 }
References m_context, m_display, m_tracked_person_subscriber, and processTrackedPersonsMessage().
Referenced by spencer_tracking_rviz_plugin::SocialRelationsDisplay::onInitialize(), spencer_tracking_rviz_plugin::HumanAttributesDisplay::onInitialize(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::onInitialize(), and spencer_tracking_rviz_plugin::TrackedGroupsDisplay::onInitialize().
lookup()
const boost::shared_ptr< CachedTrackedPerson > spencer_tracking_rviz_plugin::TrackedPersonsCache::lookup (track_id trackId)
Lookup information for the given tracked person ID. Returns a null pointer if no information is available.
 {
     CachedTrackedPersonsMap::const_iterator entry = m_cachedTrackedPersons.find(trackId);
     if(entry == m_cachedTrackedPersons.end()) return boost::shared_ptr<CachedTrackedPerson>();
     else return entry->second;
 }
References m_cachedTrackedPersons.
Referenced by spencer_tracking_rviz_plugin::SocialRelationsDisplay::processMessage(), spencer_tracking_rviz_plugin::HumanAttributesDisplay::processMessage(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::processMessage(), spencer_tracking_rviz_plugin::TrackedGroupsDisplay::processMessage(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::updateSocialActivityVisualStyles(), and spencer_tracking_rviz_plugin::HumanAttributesDisplay::updateVisualStyles().
processTrackedPersonsMessage()
void spencer_tracking_rviz_plugin::TrackedPersonsCache::processTrackedPersonsMessage (const spencer_tracking_msgs::TrackedPersons::ConstPtr & msg) private
 {
     // Get transform of person tracks into fixed frame
     Ogre::Vector3 frameOrigin; Ogre::Quaternion frameOrientation;
     m_context->getFrameManager()->getTransform(msg->header, frameOrigin, frameOrientation);
     Ogre::Matrix4 transform(frameOrientation);
     transform.setTrans(frameOrigin);
     // Now iterate over all tracks and store their positions
     m_cachedTrackedPersons.clear();
     foreach(spencer_tracking_msgs::TrackedPerson trackedPerson, msg->tracks)
     {
         m_cachedTrackedPersons[trackedPerson.track_id] = boost::shared_ptr<CachedTrackedPerson>(new CachedTrackedPerson);
         CachedTrackedPerson& cachedTrackedPerson = *m_cachedTrackedPersons[trackedPerson.track_id];
         const geometry_msgs::Point& position = trackedPerson.pose.pose.position;
         cachedTrackedPerson.center = transform * Ogre::Vector3(position.x, position.y, position.z);
         cachedTrackedPerson.pose = trackedPerson.pose;
         cachedTrackedPerson.twist = trackedPerson.twist;
         cachedTrackedPerson.isOccluded = trackedPerson.is_occluded;
     }
     std::stringstream ss;
     ss << msg->tracks.size() << " track(s)";
     m_display->setStatusStd(rviz::StatusProperty::Ok, "Tracks", ss.str());
 }
References spencer_tracking_rviz_plugin::CachedTrackedPerson::center, send_test_msgs::frameOrientation, spencer_tracking_rviz_plugin::CachedTrackedPerson::isOccluded, m_cachedTrackedPersons, m_context, m_display, spencer_tracking_rviz_plugin::CachedTrackedPerson::pose, and spencer_tracking_rviz_plugin::CachedTrackedPerson::twist.
Referenced by initialize().
reset()
void spencer_tracking_rviz_plugin::TrackedPersonsCache::reset ()
Clear internal state, including all cached track positions.
 {
     m_cachedTrackedPersons.clear();
 }
References m_cachedTrackedPersons.
Referenced by spencer_tracking_rviz_plugin::SocialRelationsDisplay::reset(), spencer_tracking_rviz_plugin::HumanAttributesDisplay::reset(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::reset(), and spencer_tracking_rviz_plugin::TrackedGroupsDisplay::reset().
Member Data Documentation
m_cachedTrackedPersons
CachedTrackedPersonsMap spencer_tracking_rviz_plugin::TrackedPersonsCache::m_cachedTrackedPersons private
Referenced by getMap(), lookup(), processTrackedPersonsMessage(), reset(), and ~TrackedPersonsCache().
m_context
rviz::DisplayContext* spencer_tracking_rviz_plugin::TrackedPersonsCache::m_context private
Referenced by initialize(), and processTrackedPersonsMessage().
m_display
rviz::Display* spencer_tracking_rviz_plugin::TrackedPersonsCache::m_display private
Referenced by initialize(), and processTrackedPersonsMessage().
m_tracked_person_subscriber
rviz::AdditionalTopicSubscriber<spencer_tracking_msgs::TrackedPersons>* spencer_tracking_rviz_plugin::TrackedPersonsCache::m_tracked_person_subscriber private
Referenced by initialize(), and ~TrackedPersonsCache().
The documentation for this class was generated from the following files:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/tracked_persons_cache.h
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/tracked_persons_cache.cpp