ROS Motion Planning: global_planner::InformedRRT Class Reference
global_planner::InformedRRT Class Reference
Class for objects that plan using the RRT* algorithm.
#include <informed_rrt.h>
Public Member Functions
InformedRRT (int nx, int ny, double resolution, int sample_num, double max_dist, double r)
Constructor.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
RRT implementation.
Public Member Functions inherited from global_planner::RRTStar
RRTStar (int nx, int ny, double resolution, int sample_num, double max_dist, double r)
Constructor.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
RRT implementation.
Public Member Functions inherited from global_planner::RRT
RRT (int nx, int ny, double resolution, int sample_num, double max_dist)
Constructor.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
Node _transform (double x, double y)
Sample in ellipse.
Node _generateRandomNode ()
Generates a random node.
Protected Member Functions inherited from global_planner::RRTStar
Node _findNearestPoint (std::unordered_map< int, Node > list, Node &node)
Regular the new node by the nearest node in the sample list.
Protected Member Functions inherited from global_planner::RRT
Node _findNearestPoint (std::unordered_map< int, Node > list, const Node &node)
Regular the sample node by the nearest node in the sample list.
bool _isAnyObstacleInPath (const Node &n1, const Node &n2)
Check if there is any obstacle between the 2 nodes.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
double c_best_
double c_min_
Protected Attributes inherited from global_planner::RRTStar
double r_
Protected Attributes inherited from global_planner::RRT
const unsigned char * costs_
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the RRT* algorithm.
Constructor & Destructor Documentation
InformedRRT()
global_planner::InformedRRT::InformedRRT (int nx, int ny, double resolution, int sample_num, double max_dist, double r)
Constructor.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
sample_num andom sample points
max_dist max distance between sample points
r optimization radius
nx pixel number in costmap x direction
ny pixel number in costmap y direction
sample_num andom sample points
max_dist max distance between sample points
   : RRTStar(nx, ny, resolution, sample_num, max_dist, r)
 {
 }
Member Function Documentation
_generateRandomNode()
Node global_planner::InformedRRT::_generateRandomNode () protected
Generates a random node.
Returns
Generated node
 {
   // ellipse sample
   if (c_best_ < std::numeric_limits<double>::max())
   {
     while (true)
     {
       // unit ball sample
       double x, y;
       std::random_device rd;
       std::mt19937 eng(rd());
       std::uniform_real_distribution<float> p(-1, 1);
       while (true)
       {
         x = p(eng);
         y = p(eng);
         if (x * x + y * y < 1)
           break;
       }
       // transform to ellipse
       Node temp = _transform(x, y);
       if (temp.id_ < ns_ - 1)
         return temp;
     }
   }
   else
     return RRTStar::_generateRandomNode();
 }
References global_planner::RRT::_generateRandomNode(), _transform(), c_best_, Node::id_, and global_planner::GlobalPlanner::ns_.
Referenced by plan().
_transform()
Node global_planner::InformedRRT::_transform (double x, double y) protected
Sample in ellipse.
Parameters
x random sampling x
y random sampling y
Returns
ellipse node
 {
   // center
   double center_x = (start_.x_ + goal_.x_) / 2;
   double center_y = (start_.y_ + goal_.y_) / 2;
   // rotation
   double theta = -helper::angle(start_, goal_);
   // ellipse
   double a = c_best_ / 2.0;
   double c = c_min_ / 2.0;
   double b = std::sqrt(a * a - c * c);
   // transform
   int tx = (int)(a * cos(theta) * x + b * sin(theta) * y + center_x);
   int ty = (int)(-a * sin(theta) * x + b * cos(theta) * y + center_y);
   int id = grid2Index(tx, ty);
   return Node(tx, ty, 0, 0, id, 0);
 }
References helper::angle(), c_best_, c_min_, global_planner::RRT::goal_, global_planner::GlobalPlanner::grid2Index(), global_planner::RRT::start_, Node::x_, and Node::y_.
Referenced by _generateRandomNode().
plan()
bool global_planner::InformedRRT::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
RRT implementation.
Informed RRT* implementation.
Parameters
costs costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Parameters
global_costmap costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements global_planner::GlobalPlanner.
 {
   // initialization
   c_best_ = std::numeric_limits<double>::max();
   c_min_ = helper::dist(start, goal);
   int best_parent = -1;
   sample_list_.clear();
   // copy
   start_ = start, goal_ = goal;
   costs_ = global_costmap;
   sample_list_.insert(std::make_pair(start.id_, start));
   expand.push_back(start);
   // main loop
   int iteration = 0;
   while (iteration < sample_num_)
   {
     iteration++;
     // generate a random node in the map
     Node sample_node = _generateRandomNode();
     // obstacle
     if (global_costmap[sample_node.id_] >= lethal_cost_ * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id_) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_, sample_node);
     if (new_node.id_ == -1)
       continue;
     else
     {
       sample_list_.insert(std::make_pair(new_node.id_, new_node));
       expand.push_back(new_node);
     }
     // goal found
     auto dist_ = helper::dist(new_node, goal_);
     if (dist_ <= max_dist_ && !_isAnyObstacleInPath(new_node, goal_))
     {
       double cost = dist_ + new_node.g_;
       if (cost < c_best_)
       {
         best_parent = new_node.id_;
         c_best_ = cost;
       }
     }
   }
   if (best_parent != -1)
   {
     Node goal_star(goal_.x_, goal_.y_, c_best_, 0, grid2Index(goal_.x_, goal_.y_), best_parent);
     sample_list_.insert(std::make_pair(goal_star.id_, goal_star));
     path = _convertClosedListToPath(sample_list_, start, goal);
     return true;
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), global_planner::RRTStar::_findNearestPoint(), _generateRandomNode(), global_planner::RRT::_isAnyObstacleInPath(), c_best_, c_min_, global_planner::RRT::costs_, helper::dist(), global_planner::GlobalPlanner::factor_, Node::g_, global_planner::RRT::goal_, global_planner::GlobalPlanner::grid2Index(), Node::id_, global_planner::GlobalPlanner::lethal_cost_, global_planner::RRT::max_dist_, global_planner::RRT::sample_list_, global_planner::RRT::sample_num_, global_planner::RRT::start_, Node::x_, and Node::y_.
Member Data Documentation
c_best_
double global_planner::InformedRRT::c_best_ protected
Referenced by _generateRandomNode(), _transform(), and plan().
c_min_
double global_planner::InformedRRT::c_min_ protected
Referenced by _transform(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/sample_planner/include/informed_rrt.h
src/core/global_planner/sample_planner/src/informed_rrt.cpp