ROS Motion Planning: global_planner::DStarLite Class Reference
global_planner::DStarLite Class Reference
Class for objects that plan using the LPA* algorithm.
#include <d_star_lite.h>
Public Member Functions
DStarLite (int nx, int ny, double resolution)
Construct a new DStarLite object.
void initMap ()
Init map.
void reset ()
Reset the system.
double getH (LNodePtr n1, LNodePtr n2)
Get heuristics between n1 and n2.
double calculateKey (LNodePtr s)
Calculate the key of s.
bool isCollision (LNodePtr n1, LNodePtr n2)
Check if there is collision between n1 and n2.
void getNeighbours (LNodePtr u, std::vector< LNodePtr > &neighbours)
Get neighbour LNodePtrs of nodePtr.
double getCost (LNodePtr n1, LNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
void updateVertex (LNodePtr u)
Update vertex u.
void computeShortestPath ()
Main process of D* lite.
bool extractPath (const Node &start, const Node &goal)
Extract path for map.
Node getState (const Node &current)
Get the closest Node of the path to current state.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
D* lite implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Public Attributes
unsigned char * curr_global_costmap_
unsigned char * last_global_costmap_
LNodePtr ** map_
std::multimap< double, LNodePtr > open_list_
std::vector< Node > path_
std::vector< Node > expand_
Node start_
Node goal_
LNodePtr start_ptr_
LNodePtr goal_ptr_
LNodePtr last_ptr_
double km_
Additional Inherited Members
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the LPA* algorithm.
Constructor & Destructor Documentation
DStarLite()
global_planner::DStarLite::DStarLite (int nx, int ny, double resolution)
Construct a new DStarLite object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
                                                       : GlobalPlanner(nx, ny, resolution)
 {
   curr_global_costmap_ = new unsigned char[ns_];
   last_global_costmap_ = new unsigned char[ns_];
   start_.x_ = start_.y_ = goal_.x_ = goal_.y_ = INF;
   factor_ = 0.4;
   initMap();
 }
References curr_global_costmap_, global_planner::GlobalPlanner::factor_, goal_, INF, initMap(), last_global_costmap_, global_planner::GlobalPlanner::ns_, start_, Node::x_, and Node::y_.
Member Function Documentation
calculateKey()
double global_planner::DStarLite::calculateKey (LNodePtr s)
Calculate the key of s.
Parameters
s LNode pointer
Returns
the key value
 {
   return std::min(s->g_, s->rhs) + 0.9 * (getH(s, start_ptr_) + km_);
 }
References Node::g_, getH(), km_, LNode::rhs, and start_ptr_.
Referenced by computeShortestPath(), plan(), and updateVertex().
computeShortestPath()
void global_planner::DStarLite::computeShortestPath ()
Main process of D* lite.
 {
   while (1)
   {
     if (open_list_.empty())
       break;
     double k_old = open_list_.begin()->first;
     LNodePtr u = open_list_.begin()->second;
     open_list_.erase(open_list_.begin());
     u->open_it = open_list_.end();
     expand_.push_back(*u);
     // start reached
     if (u->key >= calculateKey(start_ptr_) && start_ptr_->rhs == start_ptr_->g_)
       break;
     // affected by obstacles
     if (k_old < calculateKey(u))
     {
       u->key = calculateKey(u);
       u->open_it = open_list_.insert(std::make_pair(u->key, u));
     }
     // Locally over-consistent -> Locally consistent
     else if (u->g_ > u->rhs)
     {
       u->g_ = u->rhs;
     }
     // Locally under-consistent -> Locally over-consistent
     else
     {
       u->g_ = INF;
       updateVertex(u);
     }
     std::vector<LNodePtr> neigbours;
     getNeighbours(u, neigbours);
     for (LNodePtr s : neigbours)
       updateVertex(s);
   }
 }
References calculateKey(), expand_, Node::g_, getNeighbours(), INF, LNode::key, LNode::open_it, open_list_, LNode::rhs, start_ptr_, and updateVertex().
Referenced by plan().
extractPath()
bool global_planner::DStarLite::extractPath (const Node & start, const Node & goal)
Extract path for map.
Parameters
start start node
goal goal node
Returns
flag true if extract successfully else do not
 {
   std::vector<Node> path_temp;
   LNodePtr node_ptr = map_[start.x_][start.y_];
   int count = 0;
   while (node_ptr->x_ != goal.x_ || node_ptr->y_ != goal.y_)
   {
     path_temp.push_back(*node_ptr);
     // argmin_{s\in pred(u)}
     std::vector<LNodePtr> neigbours;
     getNeighbours(node_ptr, neigbours);
     double min_cost = INF;
     LNodePtr next_node_ptr;
     for (LNodePtr node_n_ptr : neigbours)
     {
       if (node_n_ptr->g_ < min_cost)
       {
         min_cost = node_n_ptr->g_;
         next_node_ptr = node_n_ptr;
       }
     }
     node_ptr = next_node_ptr;
     // TODO: it happens to cannnot find a path to start sometimes...
     // use counter to solve it templately
     if (count++ > 1000)
       return false;
   }
   std::reverse(path_temp.begin(), path_temp.end());
   path_ = path_temp;
   return true;
 }
References Node::g_, getNeighbours(), INF, map_, path_, Node::x_, and Node::y_.
Referenced by plan().
getCost()
double global_planner::DStarLite::getCost (LNodePtr n1, LNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
Parameters
n1 LNode pointer of one LNode
n2 LNode pointer of the other LNode
Returns
cost between n1 and n2
 {
   if (isCollision(n1, n2))
     return INF;
   return std::hypot(n1->x_ - n2->x_, n1->y_ - n2->y_);
 }
References INF, isCollision(), Node::x_, and Node::y_.
Referenced by updateVertex().
getH()
double global_planner::DStarLite::getH (LNodePtr n1, LNodePtr n2)
Get heuristics between n1 and n2.
Parameters
n1 LNode pointer of on LNode
n2 LNode pointer of the other LNode
Returns
heuristics between n1 and n2
 {
   return std::hypot(n1->x_ - n2->x_, n1->y_ - n2->y_);
 }
References Node::x_, and Node::y_.
Referenced by calculateKey(), and plan().
getNeighbours()
void global_planner::DStarLite::getNeighbours (LNodePtr u, std::vector< LNodePtr > & neighbours)
Get neighbour LNodePtrs of nodePtr.
Parameters
node_ptr DNode to expand
neighbours neigbour LNodePtrs in vector
 {
   int x = u->x_, y = u->y_;
   for (int i = -1; i <= 1; i++)
   {
     for (int j = -1; j <= 1; j++)
     {
       if (i == 0 && j == 0)
         continue;
       int x_n = x + i, y_n = y + j;
       if (x_n < 0 || x_n > nx_ - 1 || y_n < 0 || y_n > ny_ - 1)
         continue;
       LNodePtr neigbour_ptr = map_[x_n][y_n];
       if (isCollision(u, neigbour_ptr))
         continue;
       neighbours.push_back(neigbour_ptr);
     }
   }
 }
References isCollision(), map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, Node::x_, and Node::y_.
Referenced by computeShortestPath(), extractPath(), plan(), and updateVertex().
getState()
Node global_planner::DStarLite::getState (const Node & current)
Get the closest Node of the path to current state.
Parameters
current current state
Returns
the closest Node
 {
   Node state(path_[0].x_, path_[0].y_);
   double dis_min = std::hypot(state.x_ - current.x_, state.y_ - current.y_);
   int idx_min = 0;
   for (int i = 1; i < path_.size(); i++)
   {
     double dis = std::hypot(path_[i].x_ - current.x_, path_[i].y_ - current.y_);
     if (dis < dis_min)
     {
       dis_min = dis;
       idx_min = i;
     }
   }
   state.x_ = path_[idx_min].x_;
   state.y_ = path_[idx_min].y_;
   return state;
 }
References path_, Node::x_, and Node::y_.
initMap()
void global_planner::DStarLite::initMap ()
Init map.
 {
   map_ = new LNodePtr*[nx_];
   for (int i = 0; i < nx_; i++)
   {
     map_[i] = new LNodePtr[ny_];
     for (int j = 0; j < ny_; j++)
     {
       map_[i][j] = new LNode(i, j, INF, INF, grid2Index(i, j), -1, INF, INF);
       map_[i][j]->open_it = open_list_.end();  // allocate empty memory
     }
   }
 }
References global_planner::GlobalPlanner::grid2Index(), INF, map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, LNode::open_it, and open_list_.
Referenced by DStarLite(), and reset().
isCollision()
bool global_planner::DStarLite::isCollision (LNodePtr n1, LNodePtr n2)
Check if there is collision between n1 and n2.
Parameters
n1 DNode pointer of one DNode
n2 DNode pointer of the other DNode
Returns
true if collision, else false
 {
   return (curr_global_costmap_[n1->id_] > lethal_cost_ * factor_) ||
          (curr_global_costmap_[n2->id_] > lethal_cost_ * factor_);
 }
References curr_global_costmap_, global_planner::GlobalPlanner::factor_, Node::id_, and global_planner::GlobalPlanner::lethal_cost_.
Referenced by getCost(), and getNeighbours().
plan()
bool global_planner::DStarLite::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
D* lite implementation.
Parameters
costs costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Parameters
global_costmap costmap
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements global_planner::GlobalPlanner.
 {
   // update costmap
   memcpy(last_global_costmap_, curr_global_costmap_, ns_);
   memcpy(curr_global_costmap_, global_costmap, ns_);
   expand_.clear();
   // new goal set
   if (goal_.x_ != goal.x_ || goal_.y_ != goal.y_)
   {
     reset();
     goal_ = goal;
     start_ = start;
     start_ptr_ = map_[start.x_][start.y_];
     goal_ptr_ = map_[goal.x_][goal.y_];
     last_ptr_ = start_ptr_;
     goal_ptr_->rhs = 0.0;
     goal_ptr_->key = calculateKey(goal_ptr_);
     goal_ptr_->open_it = open_list_.insert(std::make_pair(goal_ptr_->key, goal_ptr_));
     computeShortestPath();
     // path_.clear();
     extractPath(start, goal);
     expand = expand_;
     path = path_;
     return true;
   }
   else
   {
     start_ = start;
     start_ptr_ = map_[start.x_][start.y_];
     for (int i = -WINDOW_SIZE / 2; i < WINDOW_SIZE / 2; i++)
     {
       for (int j = -WINDOW_SIZE / 2; j < WINDOW_SIZE / 2; j++)
       {
         int x_n = start.x_ + i, y_n = start.y_ + j;
         if (x_n < 0 || x_n > nx_ - 1 || y_n < 0 || y_n > ny_ - 1)
           continue;
         int idx = grid2Index(x_n, y_n);
         if (curr_global_costmap_[idx] != last_global_costmap_[idx])
         {
           km_ = km_ + getH(last_ptr_, start_ptr_);
           last_ptr_ = start_ptr_;
           LNodePtr u = map_[x_n][y_n];
           std::vector<LNodePtr> neigbours;
           getNeighbours(u, neigbours);
           updateVertex(u);
           for (LNodePtr s : neigbours)
           {
             updateVertex(s);
           }
         }
       }
     }
     computeShortestPath();
     path_.clear();
     extractPath(start, goal);
     expand = expand_;
     path = path_;
     return true;
   }
 }
References calculateKey(), computeShortestPath(), curr_global_costmap_, expand_, extractPath(), getH(), getNeighbours(), goal_, goal_ptr_, global_planner::GlobalPlanner::grid2Index(), LNode::key, km_, last_global_costmap_, last_ptr_, map_, global_planner::GlobalPlanner::ns_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, LNode::open_it, open_list_, path_, reset(), LNode::rhs, start_, start_ptr_, updateVertex(), WINDOW_SIZE, Node::x_, and Node::y_.
reset()
void global_planner::DStarLite::reset ()
Reset the system.
 {
   open_list_.clear();
   km_ = 0.0;
   for (int i = 0; i < nx_; i++)
     for (int j = 0; j < ny_; j++)
       delete map_[i][j];
   for (int i = 0; i < nx_; i++)
     delete[] map_[i];
   delete[] map_;
   initMap();
 }
References initMap(), km_, map_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, and open_list_.
Referenced by plan().
updateVertex()
void global_planner::DStarLite::updateVertex (LNodePtr u)
Update vertex u.
Parameters
u LNode pointer to update
 {
   // u != goal
   if (u->x_ != goal_.x_ || u->y_ != goal_.y_)
   {
     std::vector<LNodePtr> neigbours;
     getNeighbours(u, neigbours);
     // min_{s\in pred(u)}(g(s) + c(s, u))
     u->rhs = INF;
     for (LNodePtr s : neigbours)
     {
       if (s->g_ + getCost(s, u) < u->rhs)
       {
         u->rhs = s->g_ + getCost(s, u);
       }
     }
   }
   // u in openlist, remove u
   if (u->open_it != open_list_.end())
   {
     open_list_.erase(u->open_it);
     u->open_it = open_list_.end();
   }
   // g(u) != rhs(u)
   if (u->g_ != u->rhs)
   {
     u->key = calculateKey(u);
     u->open_it = open_list_.insert(std::make_pair(u->key, u));
   }
 }
References calculateKey(), Node::g_, getCost(), getNeighbours(), goal_, INF, LNode::key, LNode::open_it, open_list_, LNode::rhs, Node::x_, and Node::y_.
Referenced by computeShortestPath(), and plan().
Member Data Documentation
curr_global_costmap_
unsigned char* global_planner::DStarLite::curr_global_costmap_
Referenced by DStarLite(), isCollision(), and plan().
expand_
std::vector<Node> global_planner::DStarLite::expand_
Referenced by computeShortestPath(), and plan().
goal_
Node global_planner::DStarLite::goal_
Referenced by DStarLite(), plan(), and updateVertex().
goal_ptr_
LNodePtr global_planner::DStarLite::goal_ptr_
Referenced by plan().
km_
double global_planner::DStarLite::km_
Referenced by calculateKey(), plan(), and reset().
last_global_costmap_
unsigned char* global_planner::DStarLite::last_global_costmap_
Referenced by DStarLite(), and plan().
last_ptr_
LNodePtr global_planner::DStarLite::last_ptr_
Referenced by plan().
map_
LNodePtr** global_planner::DStarLite::map_
Referenced by extractPath(), getNeighbours(), initMap(), plan(), and reset().
open_list_
std::multimap<double, LNodePtr> global_planner::DStarLite::open_list_
Referenced by computeShortestPath(), initMap(), plan(), reset(), and updateVertex().
path_
std::vector<Node> global_planner::DStarLite::path_
Referenced by extractPath(), getState(), and plan().
start_
Node global_planner::DStarLite::start_
Referenced by DStarLite(), and plan().
start_ptr_
LNodePtr global_planner::DStarLite::start_ptr_
Referenced by calculateKey(), computeShortestPath(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/d_star_lite.h
src/core/global_planner/graph_planner/src/d_star_lite.cpp