ROS Motion Planning: config.RVizConfig Class Reference
config.RVizConfig Class Reference
Public Member Functions
def __init__ (self, rviz_name, path, base_file=None)
def __repr__ (self)
def setFileCache (self, path)
def getVisualization (self)
def setDisplays (self, displays)
def delDisplays (self)
def setStdTools (self)
def delStdTools (self)
def setStdPanels (self)
def delStdPanels (self)
def setFixedFrame (self, frame="map")
def setToolTopic (self, name, topic)
def appendToolGoal (self, topic)
def appendToolInit (self, topic)
def run (self)
Public Attributes
VIZ_MAN
STD_TOOLS
STD_PANELS
file_name
cache_path
data
Constructor & Destructor Documentation
__init__()
def config.RVizConfig.__init__ (self, rviz_name, path, base_file = None)
     def __init__(self, rviz_name, path, base_file=None):
         # Rviz visualization manager
         self.VIZ_MAN = "Visualization Manager"
         # Rviz standard tools
         self.STD_TOOLS = ["rviz/Interact", "rviz/MoveCamera", "rviz/Select", "rviz/FocusCamera", "rviz/Measure", "rviz/PublishPoint"]
         # Rviz standard panels
         self.STD_PANELS = ["rviz/Displays", "rviz/Tool Properties"]
         # Rviz file name
         self.file_name = rviz_name
         # Rviz cache
         self.cache_path = path
         # Rviz pre-configure
         self.data = yaml.load(base_file) if base_file else {}
Member Function Documentation
__repr__()
def config.RVizConfig.__repr__ (self)
     def __repr__(self):
         return yaml.dump(self.data, default_flow_style=False)
References config.RVizConfig.data.
appendToolGoal()
def config.RVizConfig.appendToolGoal (self, topic)
     def appendToolGoal(self, topic):
         v = self.getVisualization()
         if "Tools" not in v:
             v["Tools"] = []
         v["Tools"].append({"Class": "rviz/SetGoal", "Topic": topic})
References config.RVizConfig.getVisualization().
appendToolInit()
def config.RVizConfig.appendToolInit (self, topic)
     def appendToolInit(self, topic):
         v = self.getVisualization()
         if "Tools" not in v:
             v["Tools"] = []
         v["Tools"].append({"Class": "rviz/SetInitialPose", "Topic": topic})
References config.RVizConfig.getVisualization().
delDisplays()
def config.RVizConfig.delDisplays (self)
     def delDisplays(self):
         if "Displays" in self.getVisualization():
             del self.data[self.VIZ_MAN]["Displays"]
             print("Displays have been deleted successfully!")
             return True
         print("Displays delete failed! please call displays setting first!")
         return False
References config.RVizConfig.data, config.RVizConfig.getVisualization(), and config.RVizConfig.VIZ_MAN.
delStdPanels()
def config.RVizConfig.delStdPanels (self)
     def delStdPanels(self):
         if "Panels" in self.data:
             del self.data["Panels"]
             print("standard panels have been deleted successfully!")
             return True
         print("standard panels delete failed! please call standard panels setting first!")
         return False
References config.RVizConfig.data.
delStdTools()
def config.RVizConfig.delStdTools (self)
     def delStdTools(self):
         if "Tools" in self.getVisualization():
             del self.data[self.VIZ_MAN]["Tools"]
             print("standard tools have been deleted successfully!")
             return True
         print("standard tools delete failed! please call standard tools setting first!")
         return False
References config.RVizConfig.data, config.RVizConfig.getVisualization(), and config.RVizConfig.VIZ_MAN.
getVisualization()
def config.RVizConfig.getVisualization (self)
     def getVisualization(self):
         if self.VIZ_MAN not in self.data:
             self.data[self.VIZ_MAN] = {}
         return self.data[self.VIZ_MAN]
References config.RVizConfig.data, and config.RVizConfig.VIZ_MAN.
Referenced by config.RVizConfig.appendToolGoal(), config.RVizConfig.appendToolInit(), config.RVizConfig.delDisplays(), config.RVizConfig.delStdTools(), config.RVizConfig.setDisplays(), config.RVizConfig.setFixedFrame(), and config.RVizConfig.setStdTools().
run()
def config.RVizConfig.run (self)
     def run(self):
         with open(self.cache_path + self.file_name + ".rviz", "w") as fp:
             fp.write(str(self))
         import subprocess
         subprocess.call(["rosrun", "rviz", "rviz", "-d", self.cache_path + self.file_name + ".rviz"])
References config.RVizConfig.cache_path, and config.RVizConfig.file_name.
setDisplays()
def config.RVizConfig.setDisplays (self, displays)
     def setDisplays(self, displays):
         if "Displays" not in self.getVisualization():
             self.data[self.VIZ_MAN]["Displays"] = displays
             print("Displays have been set successfully!")
             return True
         print("Displays setting failed! please call displays delete first!")
         return False
References config.RVizConfig.data, config.RVizConfig.getVisualization(), and config.RVizConfig.VIZ_MAN.
setFileCache()
def config.RVizConfig.setFileCache (self, path)
     def setFileCache(self, path):
         self.cache_path = path
References config.RVizConfig.cache_path.
setFixedFrame()
def config.RVizConfig.setFixedFrame (self, frame = "map")
     def setFixedFrame(self, frame="map"):
         v = self.getVisualization()
         if "Global Options" not in v:
             v["Global Options"] = {"Fixed Frame": frame}
         else:
             v["Global Options"]["Fixed Frame"] = frame
References config.RVizConfig.getVisualization().
setStdPanels()
def config.RVizConfig.setStdPanels (self)
     def setStdPanels(self):
         if "Panels" not in self.data:
             self.data["Panels"] = []
             for tool in self.STD_PANELS:
                 self.data["Panels"].append({"Class": tool, "Name": tool.split("/")[-1]})
                 print("standard panels have been set successfully!")
             return True
         print("standard panels setting failed! please call standard panels delete first!")
         return False
References config.RVizConfig.data, and config.RVizConfig.STD_PANELS.
setStdTools()
def config.RVizConfig.setStdTools (self)
     def setStdTools(self):
         v = self.getVisualization()
         if "Tools" not in v:
             v["Tools"] = []
             for tool in self.STD_TOOLS:
                 v["Tools"].append({"Class": tool})
             print("standard tools have been set successfully!")
             return True
         print("standard tools setting failed! please call standard tools delete first!")
         return False
References config.RVizConfig.getVisualization(), and config.RVizConfig.STD_TOOLS.
setToolTopic()
def config.RVizConfig.setToolTopic (self, name, topic)
     def setToolTopic(self, name, topic):
         for m in self.data[self.VIZ_MAN]["Tools"]:
             if m.get("Class", "") == name:
                 m["Topic"] = topic
References config.RVizConfig.data, and config.RVizConfig.VIZ_MAN.
Member Data Documentation
cache_path
config.RVizConfig.cache_path
Referenced by config.RVizConfig.run(), and config.RVizConfig.setFileCache().
data
config.RVizConfig.data
Referenced by config.RVizConfig.__repr__(), config.RVizConfig.delDisplays(), config.RVizConfig.delStdPanels(), config.RVizConfig.delStdTools(), config.RVizConfig.getVisualization(), config.RVizConfig.setDisplays(), config.RVizConfig.setStdPanels(), and config.RVizConfig.setToolTopic().
file_name
config.RVizConfig.file_name
Referenced by config.RVizConfig.run().
STD_PANELS
config.RVizConfig.STD_PANELS
Referenced by config.RVizConfig.setStdPanels().
STD_TOOLS
config.RVizConfig.STD_TOOLS
Referenced by config.RVizConfig.setStdTools().
VIZ_MAN
config.RVizConfig.VIZ_MAN
Referenced by config.RVizConfig.delDisplays(), config.RVizConfig.delStdTools(), config.RVizConfig.getVisualization(), config.RVizConfig.setDisplays(), and config.RVizConfig.setToolTopic().
The documentation for this class was generated from the following file:
src/third_party/dynamic_rviz_config/scripts/config.py