ROS Motion Planning: trajectory_generation::RSPath Class Reference
trajectory_generation::RSPath Class Reference
#include <reeds_shepp_curve.h>
Public Member Functions
RSPath (std::vector< double > lengths, std::vector< int > ctypes)
Construct a new Reeds-Shepp Path object.
~RSPath ()
Destroy the Reeds-Shepp Path object.
double len ()
Calculate the length of the generated trajectory.
bool valid ()
Determine whether the generated trajectory is valid.
size_t size ()
Calculate the number of segments for generating trajectories.
void get (int i, double &length, int &ctype)
Obtain segment i with its motion pattern.
Private Attributes
std::vector< double > lengths_
std::vector< int > ctypes_
Constructor & Destructor Documentation
RSPath()
trajectory_generation::RSPath::RSPath (std::vector< double > lengths, std::vector< int > ctypes)
Construct a new Reeds-Shepp Path object.
Parameters
lengths the length of segments
ctypes the motion patterns of segments
 {
   lengths_ = lengths;
   ctypes_ = ctypes;
 }
References ctypes_, and lengths_.
~RSPath()
trajectory_generation::RSPath::~RSPath ()
Destroy the Reeds-Shepp Path object.
 {
 }
Member Function Documentation
get()
void trajectory_generation::RSPath::get (int i, double & length, int & ctype)
Obtain segment i with its motion pattern.
Parameters
i index
length the length of segment i
ctype the motion of segment i
 {
   assert(valid());
   length = lengths_[i];
   ctype = ctypes_[i];
 }
References ctypes_, lengths_, and valid().
len()
double trajectory_generation::RSPath::len ()
Calculate the length of the generated trajectory.
Returns
length the length of the generated trajectory
 {
   double path_length = 0.0;
   for (const auto& l : lengths_)
     path_length += fabs(l);
   return path_length;
 }
References lengths_.
Referenced by trajectory_generation::ReedsShepp::_update().
size()
size_t trajectory_generation::RSPath::size ()
Calculate the number of segments for generating trajectories.
Returns
number the number of segments for generating trajectories
 {
   assert(valid());
   return lengths_.size();
 }
References lengths_, and valid().
valid()
bool trajectory_generation::RSPath::valid ()
Determine whether the generated trajectory is valid.
Returns
flag true is valid else invalid
 {
   return ((lengths_.size() > 0) && (lengths_.size() == ctypes_.size()));
 }
References ctypes_, and lengths_.
Referenced by get(), and size().
Member Data Documentation
ctypes_
std::vector<int> trajectory_generation::RSPath::ctypes_ private
Referenced by get(), RSPath(), and valid().
lengths_
std::vector<double> trajectory_generation::RSPath::lengths_ private
Referenced by get(), len(), RSPath(), size(), and valid().
The documentation for this class was generated from the following files:
src/core/curve_generation/include/reeds_shepp_curve.h
src/core/curve_generation/src/reeds_shepp_curve.cpp