ROS Motion Planning: spencer_tracking_rviz_plugin::SocialRelationsDisplay Class Reference
spencer_tracking_rviz_plugin::SocialRelationsDisplay Class Reference
The display which can be added in RViz to display social relations.
#include <social_relations_display.h>
Classes
struct RelationVisual
Public Member Functions
SocialRelationsDisplay ()
virtual ~SocialRelationsDisplay ()
virtual void onInitialize ()
Overrides base class method.
Public Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >
PersonDisplayCommon ()
virtual ~PersonDisplayCommon ()
Public Member Functions inherited from spencer_tracking_rviz_plugin::StylesChangedSubscriber
virtual ~StylesChangedSubscriber ()
virtual void stylesChanged ()
Protected Member Functions
virtual void reset ()
virtual rviz::DisplayContext * getContext ()
Must be implemented by derived classes because MOC doesn't work in templates.
Protected Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >
bool preprocessMessage (const typename spencer_social_relation_msgs::SocialRelations ::ConstPtr &msg)
Common message processing. This method needs to be called by derived classes.
void createPersonVisualIfRequired (Ogre::SceneNode *sceneNode, boost::shared_ptr< PersonVisual > &personVisual)
Create a visual representation of the person itself, if not set yet.
void applyCommonStyles (boost::shared_ptr< PersonVisual > &personVisual)
Applies common styles which apply to person visuals, such as line width etc.
Ogre::Vector3 getVelocityVector (const geometry_msgs::TwistWithCovariance &twist)
bool hasValidOrientation (const geometry_msgs::PoseWithCovariance &pose)
Returns true if all xyz rotation variances are finite.
Ogre::Matrix3 covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance &pose)
void setPoseOrientation (Ogre::SceneNode *sceneNode, const geometry_msgs::PoseWithCovariance &pose, const Ogre::Matrix3 &covXYZinTargetFrame, double personVisualHeight)
Set pose and orientation of person visual.
Ogre::ColourValue getColorFromId (unsigned int object_id)
Get a color based upon track / detection ID.
bool isPersonHidden (person_id personId)
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
Private Slots
virtual void stylesChanged ()
Private Member Functions
void processMessage (const spencer_social_relation_msgs::SocialRelations::ConstPtr &msg)
void updateRelationVisualStyles (boost::shared_ptr< RelationVisual > &relationVisual)
Private Attributes
boost::shared_ptr< Ogre::SceneNode > m_socialRelationsSceneNode
rviz::StringProperty * m_relation_type_filter_property
rviz::BoolProperty * m_render_positive_person_relations_property
rviz::BoolProperty * m_render_negative_person_relations_property
rviz::FloatProperty * m_positive_person_relation_threshold
rviz::ColorProperty * m_positive_person_relations_color
rviz::ColorProperty * m_negative_person_relations_color
vector< boost::shared_ptr< RelationVisual > > m_relationVisuals
TrackedPersonsCache m_trackedPersonsCache
Additional Inherited Members
Protected Attributes inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >
PersonDisplayCommonProperties * m_commonProperties
Common properties for the displays in this plugin.
Ogre::Quaternion m_frameOrientation
Ogre::Matrix3 m_frameRotationMatrix
Ogre::Vector3 m_framePosition
const double m_veryLargeVariance
Detailed Description
The display which can be added in RViz to display social relations.
Constructor & Destructor Documentation
SocialRelationsDisplay()
spencer_tracking_rviz_plugin::SocialRelationsDisplay::SocialRelationsDisplay () inline
 {};
~SocialRelationsDisplay()
spencer_tracking_rviz_plugin::SocialRelationsDisplay::~SocialRelationsDisplay () virtual
 {
 }
Member Function Documentation
getContext()
virtual rviz::DisplayContext* spencer_tracking_rviz_plugin::SocialRelationsDisplay::getContext () inline protected virtual
Must be implemented by derived classes because MOC doesn't work in templates.
Implements spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >.
{
             return context_;
         }
onInitialize()
void spencer_tracking_rviz_plugin::SocialRelationsDisplay::onInitialize () virtual
Overrides base class method.
Reimplemented from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >.
 {
     m_trackedPersonsCache.initialize(this, context_, update_nh_);
     PersonDisplayCommon::onInitialize();
     m_relation_type_filter_property = new rviz::StringProperty( "Relation type filter", "", "Type of social relations to display (see \"type\" field in message). No wildcards allowed. Leave empty to allow any type of relation.", this, SLOT(stylesChanged()));
     m_positive_person_relation_threshold = new rviz::FloatProperty( "Positive relation threshold", 0.5, "Above which probability threshold a social relation between tracks is considered as positive", this, SLOT(stylesChanged()));
     m_positive_person_relations_color = new rviz::ColorProperty( "Positive relation color", QColor(0,255,0), "Color for positive track relations", this, SLOT(stylesChanged()));
     m_negative_person_relations_color = new rviz::ColorProperty( "Negative relation color", QColor(255,0,0), "Color for negative track relations", this, SLOT(stylesChanged()));
     m_render_positive_person_relations_property = new rviz::BoolProperty( "Render positive relations", true,  "Render positive person relations", this, SLOT(stylesChanged()));
     m_render_negative_person_relations_property = new rviz::BoolProperty( "Render negative relations", false, "Render negative person relations", this, SLOT(stylesChanged()));
     // Create a scene node for visualizing social relations
     m_socialRelationsSceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
 }
References spencer_tracking_rviz_plugin::TrackedPersonsCache::initialize(), m_negative_person_relations_color, m_positive_person_relation_threshold, m_positive_person_relations_color, m_relation_type_filter_property, m_render_negative_person_relations_property, m_render_positive_person_relations_property, m_socialRelationsSceneNode, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::onInitialize(), and stylesChanged().
processMessage()
void spencer_tracking_rviz_plugin::SocialRelationsDisplay::processMessage (const spencer_social_relation_msgs::SocialRelations::ConstPtr & msg) private
 {
     // Get transforms into fixed frame etc.
     if(!preprocessMessage(msg)) return;
     // Loop over all social relations between tracks
     m_relationVisuals.clear();
     m_socialRelationsSceneNode->removeAndDestroyAllChildren();
     foreach(const spencer_social_relation_msgs::SocialRelation& socialRelation, msg->elements)
     {
         boost::shared_ptr<CachedTrackedPerson> personTrack1 = m_trackedPersonsCache.lookup(socialRelation.track1_id);
         boost::shared_ptr<CachedTrackedPerson> personTrack2 = m_trackedPersonsCache.lookup(socialRelation.track2_id);
         // Cannot draw relations for tracks with unknown position
         if(!personTrack1 || !personTrack2) continue;
         // Create a new visual representation of the tracked person
         boost::shared_ptr<RelationVisual> relationVisual = boost::shared_ptr<RelationVisual>(new RelationVisual);
         relationVisual->type = socialRelation.type;
         relationVisual->relationStrength = socialRelation.strength;
         m_relationVisuals.push_back(relationVisual);
         // Get positions. These are already in fixed frame coordinates!
         const Ogre::Vector3 verticalShift(0,0, 1.0 + m_commonProperties->z_offset->getFloat()), textShift(0,0, 0.3);
         const Ogre::Vector3& position1 = verticalShift + personTrack1->center;
         const Ogre::Vector3& position2 = verticalShift + personTrack2->center;
         const Ogre::Vector3& centerPosition = (position1 + position2) / 2.0;
         // Add line connecting the two tracks
         boost::shared_ptr<rviz::BillboardLine> relationLine(new rviz::BillboardLine(context_->getSceneManager(), m_socialRelationsSceneNode.get()));
         relationLine->setMaxPointsPerLine(2);
         relationLine->addPoint(position1);
         relationLine->addPoint(position2);
         relationVisual->relationLine = relationLine;
         // Add relationship strength text
         stringstream ss;
         boost::shared_ptr<TextNode> relationText(new TextNode(context_->getSceneManager(), m_socialRelationsSceneNode.get()));
         ss.str(""); ss << std::fixed << std::setprecision(0) << socialRelation.strength * 100 << "%";
         relationText->setCaption(ss.str());
         relationText->setPosition(centerPosition + textShift);
         relationText->showOnTop();
         relationVisual->relationText = relationText;
         // Remember to which groups the tracks belong, to be able to hide certain groups and their track-to-track relations
         relationVisual->trackId1 = socialRelation.track1_id;
         relationVisual->trackId2 = socialRelation.track2_id;
         // Update adjustable styles
         updateRelationVisualStyles(relationVisual);
     }
 }
References spencer_tracking_rviz_plugin::TrackedPersonsCache::lookup(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >::m_commonProperties, m_relationVisuals, m_socialRelationsSceneNode, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >::preprocessMessage(), updateRelationVisualStyles(), and spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::z_offset.
reset()
void spencer_tracking_rviz_plugin::SocialRelationsDisplay::reset () protected virtual
 {
     PersonDisplayCommon::reset();
     m_trackedPersonsCache.reset();
     m_relationVisuals.clear();
 }
References m_relationVisuals, m_trackedPersonsCache, and spencer_tracking_rviz_plugin::TrackedPersonsCache::reset().
stylesChanged
void spencer_tracking_rviz_plugin::SocialRelationsDisplay::stylesChanged () private virtual slot
 {
     foreach(boost::shared_ptr<RelationVisual> relationVisual, m_relationVisuals) {
         updateRelationVisualStyles(relationVisual);
     }
 }
References m_relationVisuals, and updateRelationVisualStyles().
Referenced by onInitialize().
updateRelationVisualStyles()
void spencer_tracking_rviz_plugin::SocialRelationsDisplay::updateRelationVisualStyles (boost::shared_ptr< RelationVisual > & relationVisual) private
 {
     std::string typeFilter = m_relation_type_filter_property->getStdString();
     bool validRelationType = relationVisual->type.find(typeFilter) != std::string::npos;
     bool hideRelation = !validRelationType || isPersonHidden(relationVisual->trackId1) || isPersonHidden(relationVisual->trackId2);
     // Determine type of the relationship
     bool isPositiveRelation = relationVisual->relationStrength > m_positive_person_relation_threshold->getFloat();
     // Get color
     Ogre::ColourValue relationColor = isPositiveRelation ? m_positive_person_relations_color->getOgreColor() : m_negative_person_relations_color->getOgreColor();
     relationColor.a *= m_commonProperties->alpha->getFloat(); // general alpha
     if(hideRelation) relationColor.a = 0;
     if(isPositiveRelation && !m_render_positive_person_relations_property->getBool()) relationColor.a = 0;
     if(!isPositiveRelation && !m_render_negative_person_relations_property->getBool()) relationColor.a = 0;
     relationVisual->relationLine->setLineWidth(0.03 * (isPositiveRelation ? 1.0 : 0.3));
     relationVisual->relationLine->setColor(relationColor.r, relationColor.g, relationColor.b, relationColor.a);
     relationVisual->relationText->setCharacterHeight(0.15 * m_commonProperties->font_scale->getFloat());
     relationVisual->relationText->setColor(relationColor);
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::alpha, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_scale, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >::isPersonHidden(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_social_relation_msgs::SocialRelations >::m_commonProperties, m_negative_person_relations_color, m_positive_person_relation_threshold, m_positive_person_relations_color, m_relation_type_filter_property, m_render_negative_person_relations_property, and m_render_positive_person_relations_property.
Referenced by processMessage(), and stylesChanged().
Member Data Documentation
m_negative_person_relations_color
rviz::ColorProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_negative_person_relations_color private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_positive_person_relation_threshold
rviz::FloatProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_positive_person_relation_threshold private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_positive_person_relations_color
rviz::ColorProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_positive_person_relations_color private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_relation_type_filter_property
rviz::StringProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_relation_type_filter_property private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_relationVisuals
vector<boost::shared_ptr<RelationVisual> > spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_relationVisuals private
Referenced by processMessage(), reset(), and stylesChanged().
m_render_negative_person_relations_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_render_negative_person_relations_property private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_render_positive_person_relations_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_render_positive_person_relations_property private
Referenced by onInitialize(), and updateRelationVisualStyles().
m_socialRelationsSceneNode
boost::shared_ptr<Ogre::SceneNode> spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_socialRelationsSceneNode private
Referenced by onInitialize(), and processMessage().
m_trackedPersonsCache
TrackedPersonsCache spencer_tracking_rviz_plugin::SocialRelationsDisplay::m_trackedPersonsCache private
Referenced by onInitialize(), processMessage(), and reset().
The documentation for this class was generated from the following files:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/social_relations_display.h
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/social_relations_display.cpp