ROS Motion Planning: global_planner::LazyThetaStar Class Reference
global_planner::LazyThetaStar Class Reference
Class for objects that plan using the lazy Theta* algorithm.
#include <lazy_theta_star.h>
Public Member Functions
LazyThetaStar (int nx, int ny, double resolution)
Construct a new LaztThetaStar object.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Lazy Theta* implementation.
Public Member Functions inherited from global_planner::ThetaStar
ThetaStar (int nx, int ny, double resolution)
Construct a new ThetaStar object.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Theta* implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
void _updateVertex (const Node &parent, Node &child)
update the g value of child node
void _setVertex (Node &node)
check if the parent of vertex need to be updated. if so, update it
Protected Member Functions inherited from global_planner::ThetaStar
void _updateVertex (const Node &parent, Node &child)
update the g value of child node
bool _lineOfSight (const Node &parent, const Node &child)
Bresenham algorithm to check if there is any obstacle between parent and child.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Private Attributes
std::unordered_map< int, Node > closed_list_
std::vector< Node > motion_
Additional Inherited Members
Protected Attributes inherited from global_planner::ThetaStar
const unsigned char * costs_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the lazy Theta* algorithm.
Constructor & Destructor Documentation
LazyThetaStar()
global_planner::LazyThetaStar::LazyThetaStar (int nx, int ny, double resolution)
Construct a new LaztThetaStar object.
Construct a new LazyThetaStar object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
                                                               : ThetaStar(nx, ny, resolution)
 {
   factor_ = 0.35;
 };
References global_planner::GlobalPlanner::factor_.
Member Function Documentation
_setVertex()
void global_planner::LazyThetaStar::_setVertex (Node & node) protected
check if the parent of vertex need to be updated. if so, update it
Parameters
node
 {
   // get the coordinate of parent node
   Node parent;
   parent.id_ = node.pid_;
   index2Grid(parent.id_, parent.x_, parent.y_);
   // if no parent, no need to check the line of sight
   auto find_parent = closed_list_.find(parent.id_);
   if (find_parent == closed_list_.end())
     return;
   parent = find_parent->second;
   if (!_lineOfSight(parent, node))
   {
     // path 1
     node.g_ = INFINITE_COST;
     for (const auto& m : motion_)
     {
       Node parent_new = node + m;
       parent_new.id_ = grid2Index(parent_new.x_, parent_new.y_);
       auto find_parent_new = closed_list_.find(parent_new.id_);
       if (find_parent_new != closed_list_.end())
       {
         // parent_new exists in closed list
         parent_new = find_parent_new->second;
         if (parent_new.g_ + helper::dist(parent_new, node) < node.g_)
         {
           node.g_ = parent_new.g_ + helper::dist(parent_new, node);
           node.pid_ = parent_new.id_;
         }
       }
     }
   }
 }
References global_planner::ThetaStar::_lineOfSight(), closed_list_, helper::dist(), Node::g_, global_planner::GlobalPlanner::grid2Index(), Node::id_, global_planner::GlobalPlanner::index2Grid(), INFINITE_COST, motion_, tf_map2odom::node, Node::x_, and Node::y_.
Referenced by plan().
_updateVertex()
void global_planner::LazyThetaStar::_updateVertex (const Node & parent, Node & child) protected
update the g value of child node
Parameters
parent
child
 {
   // path 2
   if (parent.g_ + helper::dist(parent, child) < child.g_)
   {
     child.g_ = parent.g_ + helper::dist(parent, child);
     child.pid_ = parent.id_;
   }
 }
References helper::dist(), Node::g_, Node::id_, and Node::pid_.
Referenced by plan().
plan()
bool global_planner::LazyThetaStar::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
Lazy Theta* implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   // initialize
   costs_ = global_costmap;
   closed_list_.clear();
   path.clear();
   expand.clear();
   motion_ = Node::getMotion();
   // push the start node into open list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   open_list.push(start);
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     _setVertex(current);
     if (current.g_ >= INFINITE_COST)
       continue;
     // current node does not exist in closed list
     if (closed_list_.find(current.id_) != closed_list_.end())
       continue;
     closed_list_.insert(std::make_pair(current.id_, current));
     expand.push_back(current);
     // goal found
     if (current == goal)
     {
       path = _convertClosedListToPath(closed_list_, start, goal);
       return true;
     }
     // explore neighbor of current node
     for (const auto& m : motion_)
     {
       // explore a new node
       // path 1
       Node node_new = current + m;  // add the x_, y_, g_
       node_new.h_ = helper::dist(node_new, goal);
       node_new.id_ = grid2Index(node_new.x_, node_new.y_);
       node_new.pid_ = current.id_;
       // current node do not exist in closed list
       if (closed_list_.find(node_new.id_) != closed_list_.end())
         continue;
       // next node hit the boundary or obstacle
       if ((node_new.id_ < 0) || (node_new.id_ >= ns_) ||
           (costs_[node_new.id_] >= lethal_cost_ * factor_ && costs_[node_new.id_] >= costs_[current.id_]))
         continue;
       // get parent node
       Node parent;
       parent.id_ = current.pid_;
       index2Grid(parent.id_, parent.x_, parent.y_);
       auto find_parent = closed_list_.find(parent.id_);
       if (find_parent != closed_list_.end())
       {
         parent = find_parent->second;
         // path 2
         _updateVertex(parent, node_new);
       }
       open_list.push(node_new);
     }
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), _setVertex(), _updateVertex(), closed_list_, global_planner::ThetaStar::costs_, helper::dist(), global_planner::GlobalPlanner::factor_, Node::g_, Node::getMotion(), global_planner::GlobalPlanner::grid2Index(), Node::h_, Node::id_, global_planner::GlobalPlanner::index2Grid(), INFINITE_COST, global_planner::GlobalPlanner::lethal_cost_, motion_, global_planner::GlobalPlanner::ns_, Node::pid_, Node::x_, and Node::y_.
Member Data Documentation
closed_list_
std::unordered_map<int, Node> global_planner::LazyThetaStar::closed_list_ private
Referenced by _setVertex(), and plan().
motion_
std::vector<Node> global_planner::LazyThetaStar::motion_ private
Referenced by _setVertex(), and plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/lazy_theta_star.h
src/core/global_planner/graph_planner/src/lazy_theta_star.cpp