ROS Motion Planning: spencer_tracking_rviz_plugin::HumanAttributesDisplay Class Reference
spencer_tracking_rviz_plugin::HumanAttributesDisplay Class Reference
The display which can be added in RViz to display human attributes.
#include <human_attributes_display.h>
Classes
struct HumanAttributeVisual
Public Member Functions
HumanAttributesDisplay ()
virtual ~HumanAttributesDisplay ()
virtual void onInitialize ()
Overrides base class method.
virtual void update (float wall_dt, float ros_dt)
Public Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >
PersonDisplayCommon ()
virtual ~PersonDisplayCommon ()
Public Member Functions inherited from spencer_tracking_rviz_plugin::StylesChangedSubscriber
virtual ~StylesChangedSubscriber ()
virtual void stylesChanged ()
Protected Member Functions
virtual void reset ()
virtual rviz::DisplayContext * getContext ()
Must be implemented by derived classes because MOC doesn't work in templates.
Protected Member Functions inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >
bool preprocessMessage (const typename spencer_human_attribute_msgs::HumanAttributes ::ConstPtr &msg)
Common message processing. This method needs to be called by derived classes.
void createPersonVisualIfRequired (Ogre::SceneNode *sceneNode, boost::shared_ptr< PersonVisual > &personVisual)
Create a visual representation of the person itself, if not set yet.
void applyCommonStyles (boost::shared_ptr< PersonVisual > &personVisual)
Applies common styles which apply to person visuals, such as line width etc.
Ogre::Vector3 getVelocityVector (const geometry_msgs::TwistWithCovariance &twist)
bool hasValidOrientation (const geometry_msgs::PoseWithCovariance &pose)
Returns true if all xyz rotation variances are finite.
Ogre::Matrix3 covarianceXYZIntoTargetFrame (const geometry_msgs::PoseWithCovariance &pose)
void setPoseOrientation (Ogre::SceneNode *sceneNode, const geometry_msgs::PoseWithCovariance &pose, const Ogre::Matrix3 &covXYZinTargetFrame, double personVisualHeight)
Set pose and orientation of person visual.
Ogre::ColourValue getColorFromId (unsigned int object_id)
Get a color based upon track / detection ID.
bool isPersonHidden (person_id personId)
Checks if a person shall be hidden (can be set using include/exclude person ID properties in GUI)
Private Slots
virtual void stylesChanged ()
Private Member Functions
void processMessage (const spencer_human_attribute_msgs::HumanAttributes::ConstPtr &msg)
void updateVisualStyles (boost::shared_ptr< HumanAttributeVisual > &humanAttributeVisual)
boost::shared_ptr< HumanAttributeVisual > createVisualIfNotExists (track_id trackId)
Private Attributes
rviz::BoolProperty * m_render_gender_property
rviz::BoolProperty * m_render_person_height_property
rviz::BoolProperty * m_render_age_group_property
rviz::FloatProperty * m_occlusion_alpha_property
map< track_id, boost::shared_ptr< HumanAttributeVisual > > m_humanAttributeVisuals
Ogre::Matrix4 m_frameTransform
TrackedPersonsCache m_trackedPersonsCache
Additional Inherited Members
Protected Attributes inherited from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >
PersonDisplayCommonProperties * m_commonProperties
Common properties for the displays in this plugin.
Ogre::Quaternion m_frameOrientation
Ogre::Matrix3 m_frameRotationMatrix
Ogre::Vector3 m_framePosition
const double m_veryLargeVariance
Detailed Description
The display which can be added in RViz to display human attributes.
Constructor & Destructor Documentation
HumanAttributesDisplay()
spencer_tracking_rviz_plugin::HumanAttributesDisplay::HumanAttributesDisplay () inline
 {};
~HumanAttributesDisplay()
spencer_tracking_rviz_plugin::HumanAttributesDisplay::~HumanAttributesDisplay () virtual
 {
 }
Member Function Documentation
createVisualIfNotExists()
boost::shared_ptr< HumanAttributesDisplay::HumanAttributeVisual > spencer_tracking_rviz_plugin::HumanAttributesDisplay::createVisualIfNotExists (track_id trackId) private
 {
     if(m_humanAttributeVisuals.find(trackId) == m_humanAttributeVisuals.end()) {
         boost::shared_ptr<HumanAttributeVisual> humanAttributeVisual = boost::shared_ptr<HumanAttributeVisual>(new HumanAttributeVisual);
         humanAttributeVisual->sceneNode = boost::shared_ptr<Ogre::SceneNode>(scene_node_->createChildSceneNode());
         humanAttributeVisual->ageGroupText = boost::shared_ptr<TextNode>(new TextNode(context_->getSceneManager(), humanAttributeVisual->sceneNode.get()));
         humanAttributeVisual->ageGroupText->showOnTop();
         humanAttributeVisual->ageGroupText->setCaption(" ");
         humanAttributeVisual->personHeightText = boost::shared_ptr<TextNode>(new TextNode(context_->getSceneManager(), humanAttributeVisual->sceneNode.get()));
         humanAttributeVisual->personHeightText->showOnTop();
         humanAttributeVisual->personHeightText->setCaption(" ");
         humanAttributeVisual->trackId = trackId;
         m_humanAttributeVisuals[trackId] = humanAttributeVisual;
     }
     return m_humanAttributeVisuals[trackId];
 }
References m_humanAttributeVisuals.
Referenced by processMessage().
getContext()
virtual rviz::DisplayContext* spencer_tracking_rviz_plugin::HumanAttributesDisplay::getContext () inline protected virtual
Must be implemented by derived classes because MOC doesn't work in templates.
Implements spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >.
{
             return context_;
         }
onInitialize()
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::onInitialize () virtual
Overrides base class method.
Reimplemented from spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >.
 {
     m_trackedPersonsCache.initialize(this, context_, update_nh_);
     PersonDisplayCommon::onInitialize();
     m_render_gender_property = new rviz::BoolProperty( "Render gender", true, "Render gender visual", this, SLOT(stylesChanged()));
     m_render_age_group_property = new rviz::BoolProperty( "Render age group", true, "Render age group visual", this, SLOT(stylesChanged()));
     m_render_person_height_property = new rviz::BoolProperty( "Render person height", true, "Render person height", this, SLOT(stylesChanged()));
     m_occlusion_alpha_property = new rviz::FloatProperty( "Occlusion alpha", 0.5, "Alpha multiplier for occluded tracks", this, SLOT(stylesChanged()) );
     m_occlusion_alpha_property->setMin( 0.0 );
     m_commonProperties->z_offset->setFloat(2.7f);
     m_commonProperties->style->setHidden(true);
 }
References spencer_tracking_rviz_plugin::TrackedPersonsCache::initialize(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::m_commonProperties, m_occlusion_alpha_property, m_render_age_group_property, m_render_gender_property, m_render_person_height_property, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< MessageType >::onInitialize(), spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::style, stylesChanged(), and spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::z_offset.
processMessage()
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::processMessage (const spencer_human_attribute_msgs::HumanAttributes::ConstPtr & msg) private
 {
     // Get transforms into fixed frame etc.
     if(!preprocessMessage(msg)) return;
     // Transform into Rviz fixed frame
     m_frameTransform = Ogre::Matrix4(m_frameOrientation);
     m_frameTransform.setTrans(m_framePosition);
     const Ogre::Quaternion shapeQuaternion( Ogre::Degree(90), Ogre::Vector3(1,0,0) ); // required to fix orientation of any Cylinder shapes
     stringstream ss;
     //
     // Iterate over all categorical attributes in this message
     //
     foreach (const spencer_human_attribute_msgs::CategoricalAttribute& categoricalAttribute, msg->categoricalAttributes)
     {
         // Check if there is already a visual for this particular track
         track_id trackId = categoricalAttribute.subject_id; // assumes subject_id is a track_id (not detection_id)
         boost::shared_ptr<HumanAttributeVisual> humanAttributeVisual = createVisualIfNotExists(trackId);
         if(categoricalAttribute.values.empty()) {
             ROS_ERROR_STREAM("categoricalAttribute.values.empty() for track ID " << trackId << ", attribute " << categoricalAttribute.type);
             continue;
         }
         if(categoricalAttribute.confidences.size() != categoricalAttribute.values.size()) {
             ROS_WARN_STREAM("categoricalAttribute.confidences.size() != categoricalAttribute.values.size() for track ID " << trackId << ", attribute " << categoricalAttribute.type);
         }
         // Find highest-ranking attribute
         size_t highestRankingIndex = 0; float highestConfidence = -999999;
         for(size_t i = 0; i < categoricalAttribute.confidences.size(); i++) {
             if(categoricalAttribute.confidences[i] > highestConfidence) {
                 highestConfidence = categoricalAttribute.confidences[i];
                 highestRankingIndex = i;
             }
         }
         std::string valueWithHighestConfidence = categoricalAttribute.values[highestRankingIndex];
         // Age group
         if(categoricalAttribute.type == spencer_human_attribute_msgs::CategoricalAttribute::AGE_GROUP) {
             ss.str(""); ss << valueWithHighestConfidence << "yrs";
             humanAttributeVisual->ageGroupText->setCaption(ss.str());
         }
         // Gender
         else if(categoricalAttribute.type == spencer_human_attribute_msgs::CategoricalAttribute::GENDER) {
             ss.str(""); ss << "package://" ROS_PACKAGE_NAME "/media/" << valueWithHighestConfidence << "_symbol.dae";
             std::string meshResource = ss.str();
             humanAttributeVisual->genderMesh = boost::shared_ptr<MeshNode>(new MeshNode(context_, humanAttributeVisual->sceneNode.get(), meshResource));
             Ogre::ColourValue meshColor(1, 1, 1, 1);
             if(valueWithHighestConfidence == spencer_human_attribute_msgs::CategoricalAttribute::GENDER_MALE) meshColor = Ogre::ColourValue(0, 1, 1, 1);
             if(valueWithHighestConfidence == spencer_human_attribute_msgs::CategoricalAttribute::GENDER_FEMALE) meshColor = Ogre::ColourValue(1, 0, 1, 1);
             humanAttributeVisual->genderMesh->setColor(meshColor);
             humanAttributeVisual->genderMesh->setScale(0.5);
             humanAttributeVisual->genderMesh->setCameraFacing(true);
         }
     }
     //
     // Iterate over all scalar attributes in this message
     //
     foreach (const spencer_human_attribute_msgs::ScalarAttribute& scalarAttribute, msg->scalarAttributes)
     {
         // Check if there is already a visual for this particular track
         track_id trackId = scalarAttribute.subject_id; // assumes subject_id is a track_id (not detection_id)
         boost::shared_ptr<HumanAttributeVisual> humanAttributeVisual = createVisualIfNotExists(trackId);
         if(scalarAttribute.values.empty()) {
             ROS_ERROR_STREAM("scalarAttribute.values.empty() for track ID " << trackId << ", attribute " << scalarAttribute.type);
             continue;
         }
         if(scalarAttribute.confidences.size() != scalarAttribute.values.size()) {
             ROS_WARN_STREAM("scalarAttribute.confidences.size() != scalarAttribute.values.size() for track ID " << trackId << ", attribute " << scalarAttribute.type);
         }
         // Find highest-ranking attribute
         size_t highestRankingIndex = 0; float highestConfidence = -999999;
         for(size_t i = 0; i < scalarAttribute.confidences.size(); i++) {
             if(scalarAttribute.confidences[i] > highestConfidence) {
                 highestConfidence = scalarAttribute.confidences[i];
                 highestRankingIndex = i;
             }
         }
         float valueWithHighestConfidence = scalarAttribute.values[highestRankingIndex];
         // Person height
         if(scalarAttribute.type == spencer_human_attribute_msgs::ScalarAttribute::PERSON_HEIGHT) {
             ss.str(""); ss << std::fixed << std::setprecision(2) << valueWithHighestConfidence << "m";
             humanAttributeVisual->personHeightText->setCaption(ss.str());
         }
     }
     //
     // Update position and style of all existing person visuals
     //
     set<track_id> tracksWithUnknownPosition;
     foreach(boost::shared_ptr<HumanAttributeVisual> humanAttributeVisual, m_humanAttributeVisuals | boost::adaptors::map_values)
     {
         boost::shared_ptr<CachedTrackedPerson> trackedPerson = m_trackedPersonsCache.lookup(humanAttributeVisual->trackId);
         // Get current track position
         if(!trackedPerson) {
             tracksWithUnknownPosition.insert(humanAttributeVisual->trackId);
         }
         else
         {   // Track position is known
             humanAttributeVisual->sceneNode->setPosition(trackedPerson->center + Ogre::Vector3(0, 0, m_commonProperties->z_offset->getFloat()));
             // Update styles
             updateVisualStyles(humanAttributeVisual);
         }
     }
     // Remove visuals for tracks with unknown position
     foreach(track_id trackId, tracksWithUnknownPosition) {
         m_humanAttributeVisuals.erase(trackId);
     }
     //
     // Update display status (shown in property pane)
     //
     ss.str("");
     ss << msg->categoricalAttributes.size() << " categorical attribute(s)";
     setStatusStd(rviz::StatusProperty::Ok, "Categorical attributes", ss.str());
     ss.str("");
     ss << msg->scalarAttributes.size() << " scalar attribute(s)";
     setStatusStd(rviz::StatusProperty::Ok, "Scalar attributes", ss.str());
     ss.str("");
     ss << tracksWithUnknownPosition.size() << " track(s) with unknown position";
     setStatusStd(0 == tracksWithUnknownPosition.size() ? rviz::StatusProperty::Ok : rviz::StatusProperty::Warn, "Attribute-to-track assignment", ss.str());
 }
References createVisualIfNotExists(), spencer_tracking_rviz_plugin::TrackedPersonsCache::lookup(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::m_commonProperties, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::m_frameOrientation, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::m_framePosition, m_frameTransform, m_humanAttributeVisuals, m_trackedPersonsCache, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::preprocessMessage(), shapeQuaternion(), updateVisualStyles(), and spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::z_offset.
reset()
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::reset () protected virtual
 {
     PersonDisplayCommon::reset();
     m_trackedPersonsCache.reset();
     m_humanAttributeVisuals.clear();
     scene_node_->removeAndDestroyAllChildren(); // not sure if required?
 }
References m_humanAttributeVisuals, m_trackedPersonsCache, and spencer_tracking_rviz_plugin::TrackedPersonsCache::reset().
stylesChanged
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::stylesChanged () private virtual slot
 {
     foreach(boost::shared_ptr<HumanAttributeVisual> humanAttributeVisual, m_humanAttributeVisuals | boost::adaptors::map_values) {
         updateVisualStyles(humanAttributeVisual);
     }
 }
References m_humanAttributeVisuals, and updateVisualStyles().
Referenced by onInitialize().
update()
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::update (float wall_dt, float ros_dt) virtual
 {}
updateVisualStyles()
void spencer_tracking_rviz_plugin::HumanAttributesDisplay::updateVisualStyles (boost::shared_ptr< HumanAttributeVisual > & humanAttributeVisual) private
 {
     track_id trackId = humanAttributeVisual->trackId;
     bool personHidden = isPersonHidden(trackId);
     boost::shared_ptr<CachedTrackedPerson> trackedPerson = m_trackedPersonsCache.lookup(trackId);
     float occlusionAlpha = trackedPerson->isOccluded ? m_occlusion_alpha_property->getFloat() : 1.0;
     // Update text colors, size and visibility
     Ogre::ColourValue fontColor = m_commonProperties->font_color_style->getOptionInt() == FONT_COLOR_CONSTANT ? m_commonProperties->constant_font_color->getOgreColor() : getColorFromId(trackId);
     fontColor.a = m_commonProperties->alpha->getFloat() * occlusionAlpha;
     if(personHidden) fontColor.a = 0;
     humanAttributeVisual->ageGroupText->setVisible(m_render_age_group_property->getBool());
     humanAttributeVisual->ageGroupText->setCharacterHeight(0.17 * m_commonProperties->font_scale->getFloat());
     humanAttributeVisual->ageGroupText->setColor(fontColor);
     humanAttributeVisual->ageGroupText->setPosition(Ogre::Vector3(0, 0, 0.17 * m_commonProperties->font_scale->getFloat()) );
     humanAttributeVisual->personHeightText->setVisible(m_render_person_height_property->getBool());
     humanAttributeVisual->personHeightText->setCharacterHeight(0.17 * m_commonProperties->font_scale->getFloat());
     humanAttributeVisual->personHeightText->setColor(fontColor);
     humanAttributeVisual->personHeightText->setPosition(Ogre::Vector3(0, 0, 0) );
     if(humanAttributeVisual->genderMesh) {
         humanAttributeVisual->genderMesh->setPosition(Ogre::Vector3(0, 0, 0.17 * 2 * m_commonProperties->font_scale->getFloat() + 0.3));
         humanAttributeVisual->genderMesh->setVisible(m_render_gender_property->getBool());
     }
 }
References spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::alpha, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::constant_font_color, spencer_tracking_rviz_plugin::FONT_COLOR_CONSTANT, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_color_style, spencer_tracking_rviz_plugin::PersonDisplayCommonProperties::font_scale, spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::getColorFromId(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::isPersonHidden(), spencer_tracking_rviz_plugin::TrackedPersonsCache::lookup(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_human_attribute_msgs::HumanAttributes >::m_commonProperties, m_occlusion_alpha_property, m_render_age_group_property, m_render_gender_property, m_render_person_height_property, and m_trackedPersonsCache.
Referenced by processMessage(), and stylesChanged().
Member Data Documentation
m_frameTransform
Ogre::Matrix4 spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_frameTransform private
Referenced by processMessage().
m_humanAttributeVisuals
map<track_id, boost::shared_ptr<HumanAttributeVisual> > spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_humanAttributeVisuals private
Referenced by createVisualIfNotExists(), processMessage(), reset(), and stylesChanged().
m_occlusion_alpha_property
rviz::FloatProperty* spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_occlusion_alpha_property private
Referenced by onInitialize(), and updateVisualStyles().
m_render_age_group_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_render_age_group_property private
Referenced by onInitialize(), and updateVisualStyles().
m_render_gender_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_render_gender_property private
Referenced by onInitialize(), and updateVisualStyles().
m_render_person_height_property
rviz::BoolProperty* spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_render_person_height_property private
Referenced by onInitialize(), and updateVisualStyles().
m_trackedPersonsCache
TrackedPersonsCache spencer_tracking_rviz_plugin::HumanAttributesDisplay::m_trackedPersonsCache private
Referenced by onInitialize(), processMessage(), reset(), and updateVisualStyles().
The documentation for this class was generated from the following files:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/human_attributes_display.h
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/human_attributes_display.cpp