ROS Motion Planning: sample_planner::SamplePlanner Class Reference
sample_planner::SamplePlanner Class Reference
#include <sample_planner.h>
Public Member Functions
SamplePlanner ()
Constructor(default)
SamplePlanner (std::string name, costmap_2d::Costmap2D *costmap, std::string frame_id)
Constructor.
~SamplePlanner ()
Destructor.
void initialize (std::string name, costmap_2d::Costmap2DROS *costmapRos)
Planner initialization.
void initialize (std::string name, costmap_2d::Costmap2D *costmap, std::string frame_id)
Planner initialization.
bool makePlan (const geometry_msgs::PoseStamped &start, const geometry_msgs::PoseStamped &goal, std::vector< geometry_msgs::PoseStamped > &plan)
plan a path given start and goal in world map
bool makePlan (const geometry_msgs::PoseStamped &start, const geometry_msgs::PoseStamped &goal, double tolerance, std::vector< geometry_msgs::PoseStamped > &plan)
void publishPlan (const std::vector< geometry_msgs::PoseStamped > &plan)
publish planning path
bool makePlanService (nav_msgs::GetPlan::Request &req, nav_msgs::GetPlan::Response &resp)
regeister planning service
Protected Member Functions
void _publishExpand (std::vector< Node > &expand)
publish expand zone
bool _getPlanFromPath (std::vector< Node > path, std::vector< geometry_msgs::PoseStamped > &plan)
calculate plan from planning path
void _pubLine (visualization_msgs::Marker *line_msg, ros::Publisher *line_pub, int id, int pid)
Publishes a Marker msg with two points in Rviz.
Protected Attributes
costmap_2d::Costmap2D * costmap_
unsigned int nx_
unsigned int ny_
double resolution_
std::string frame_id_
ros::Publisher plan_pub_
bool initialized_
global_planner::GlobalPlanner * g_planner_
ros::Publisher expand_pub_
ros::ServiceServer make_plan_srv_
Private Attributes
boost::mutex mutex_
double convert_offset_
double tolerance_
bool is_outline_
double factor_
bool is_expand_
int sample_points_
double sample_max_d_
double opt_r_
Constructor & Destructor Documentation
SamplePlanner() [1/2]
sample_planner::SamplePlanner::SamplePlanner ()
Constructor(default)
                              : costmap_(NULL), initialized_(false), g_planner_(NULL)
 {
 }
SamplePlanner() [2/2]
sample_planner::SamplePlanner::SamplePlanner (std::string name, costmap_2d::Costmap2D * costmap, std::string frame_id)
Constructor.
Parameters
name planner name
costmap costmap pointer
frame_id costmap frame ID
                                                                                              : SamplePlanner()
 {
   initialize(name, costmap, frame_id);
 }
References send_test_msgs::frame_id, initialize(), and rviz_generate::name.
~SamplePlanner()
sample_planner::SamplePlanner::~SamplePlanner ()
Destructor.
Returns
No return value
default
 {
   if (g_planner_)
     delete g_planner_;
 }
References g_planner_.
Member Function Documentation
_getPlanFromPath()
bool sample_planner::SamplePlanner::_getPlanFromPath (std::vector< Node > path, std::vector< geometry_msgs::PoseStamped > & plan) protected
calculate plan from planning path
Parameters
path path generated by global planner
plan plan transfromed from path
Returns
bool true if successful else false
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized yet, but it is being used, please call initialize() before use");
     return false;
   }
   std::string globalFrame = frame_id_;
   ros::Time planTime = ros::Time::now();
   plan.clear();
   for (int i = path.size() - 1; i >= 0; i--)
   {
     double wx, wy;
     g_planner_->map2World((double)path[i].x_, (double)path[i].y_, wx, wy);
     // coding as message type
     geometry_msgs::PoseStamped pose;
     pose.header.stamp = ros::Time::now();
     pose.header.frame_id = frame_id_;
     pose.pose.position.x = wx;
     pose.pose.position.y = wy;
     pose.pose.position.z = 0.0;
     pose.pose.orientation.x = 0.0;
     pose.pose.orientation.y = 0.0;
     pose.pose.orientation.z = 0.0;
     pose.pose.orientation.w = 1.0;
     plan.push_back(pose);
   }
   return !plan.empty();
 }
References frame_id_, g_planner_, initialized_, and global_planner::GlobalPlanner::map2World().
Referenced by makePlan().
_pubLine()
void sample_planner::SamplePlanner::_pubLine (visualization_msgs::Marker * line_msg, ros::Publisher * line_pub, int id, int pid) protected
Publishes a Marker msg with two points in Rviz.
Parameters
line_msg Pointer to existing marker object.
line_pub Pointer to existing marker Publisher.
id first marker id
pid second marker id
 {
   // Update line_msg header
   line_msg->header.stamp = ros::Time::now();
   // Build msg
   geometry_msgs::Point p1, p2;
   std_msgs::ColorRGBA c1, c2;
   int p1x, p1y, p2x, p2y;
   g_planner_->index2Grid(id, p1x, p1y);
   g_planner_->grid2Map(p1x, p1y, p1.x, p1.y);
   p1.x = (p1.x + convert_offset_) + costmap_->getOriginX();
   p1.y = (p1.y + convert_offset_) + costmap_->getOriginY();
   p1.z = 1.0;
   g_planner_->index2Grid(pid, p2x, p2y);
   g_planner_->grid2Map(p2x, p2y, p2.x, p2.y);
   p2.x = (p2.x + convert_offset_) + costmap_->getOriginX();
   p2.y = (p2.y + convert_offset_) + costmap_->getOriginY();
   p2.z = 1.0;
   c1.r = 0.43;
   c1.g = 0.54;
   c1.b = 0.24;
   c1.a = 0.5;
   c2.r = 0.43;
   c2.g = 0.54;
   c2.b = 0.24;
   c2.a = 0.5;
   line_msg->points.push_back(p1);
   line_msg->points.push_back(p2);
   line_msg->colors.push_back(c1);
   line_msg->colors.push_back(c2);
   // Publish line_msg
   line_pub->publish(*line_msg);
 }
References convert_offset_, costmap_, g_planner_, global_planner::GlobalPlanner::grid2Map(), and global_planner::GlobalPlanner::index2Grid().
Referenced by _publishExpand().
_publishExpand()
void sample_planner::SamplePlanner::_publishExpand (std::vector< Node > & expand) protected
publish expand zone
Parameters
expand set of expand nodes
 {
   ROS_DEBUG("Expand Zone Size:%ld", expand.size());
   // Initializes a Marker msg for a LINE_LIST
   visualization_msgs::Marker tree_msg;
   tree_msg.header.frame_id = "map";
   tree_msg.id = 0;
   tree_msg.ns = "tree";
   tree_msg.type = visualization_msgs::Marker::LINE_LIST;
   tree_msg.action = visualization_msgs::Marker::ADD;
   tree_msg.pose.orientation.w = 1.0;
   tree_msg.scale.x = 0.05;
   // Publish all edges
   for (auto node : expand)
     if (node.pid_ != 0)
       _pubLine(&tree_msg, &expand_pub_, node.id_, node.pid_);
 }
References _pubLine(), expand_pub_, and tf_map2odom::node.
Referenced by makePlan().
initialize() [1/2]
void sample_planner::SamplePlanner::initialize (std::string name, costmap_2d::Costmap2D * costmap, std::string frame_id)
Planner initialization.
Parameters
name planner name
costmap costmap pointer
frame_id costmap frame ID
 {
   if (!initialized_)
   {
     // initialize ROS node
     ros::NodeHandle private_nh("~/" + name);
     // initialize costmap
     costmap_ = costmap;
     // costmap frame ID
     frame_id_ = frame_id;
     // get costmap properties
     nx_ = costmap->getSizeInCellsX(), ny_ = costmap->getSizeInCellsY();
     resolution_ = costmap->getResolution();
     /*======================= static parameters loading ==========================*/
     private_nh.param("convert_offset", convert_offset_, 0.0);  // offset of transform from world(x,y) to grid map(x,y)
     private_nh.param("default_tolerance", tolerance_, 0.0);    // error tolerance
     private_nh.param("outline_map", is_outline_, false);       // whether outline the map or not
     private_nh.param("obstacle_factor", factor_, 0.5);         // obstacle inflation factor
     private_nh.param("expand_zone", is_expand_, false);        // whether publish expand zone or not
     private_nh.param("sample_points", sample_points_, 500);    // random sample points
     private_nh.param("sample_max_d", sample_max_d_, 5.0);      // max distance between sample points
     private_nh.param("optimization_r", opt_r_, 10.0);          // optimization radius
     // planner name
     std::string planner_name;
     private_nh.param("planner_name", planner_name, (std::string) "rrt");
     if (planner_name == "rrt")
       g_planner_ = new global_planner::RRT(nx_, ny_, resolution_, sample_points_, sample_max_d_);
     else if (planner_name == "rrt_star")
       g_planner_ = new global_planner::RRTStar(nx_, ny_, resolution_, sample_points_, sample_max_d_, opt_r_);
     else if (planner_name == "rrt_connect")
       g_planner_ = new global_planner::RRTConnect(nx_, ny_, resolution_, sample_points_, sample_max_d_);
     else if (planner_name == "informed_rrt")
       g_planner_ = new global_planner::InformedRRT(nx_, ny_, resolution_, sample_points_, sample_max_d_, opt_r_);
     // pass costmap information to planner (required)
     g_planner_->setOrigin(costmap_->getOriginX(), costmap_->getOriginY());
     g_planner_->setConvertOffset(convert_offset_);
     ROS_INFO("Using global sample planner: %s", planner_name.c_str());
     /*====================== register topics and services =======================*/
     // register planning publisher
     plan_pub_ = private_nh.advertise<nav_msgs::Path>("plan", 1);
     // register explorer visualization publisher
     expand_pub_ = private_nh.advertise<visualization_msgs::Marker>("tree", 1);
     // register planning service
     make_plan_srv_ = private_nh.advertiseService("make_plan", &SamplePlanner::makePlanService, this);
     // set initialization flag
     initialized_ = true;
   }
   else
     ROS_WARN("This planner has already been initialized, you can't call it twice, doing nothing");
 }
References convert_offset_, costmap_, expand_pub_, factor_, send_test_msgs::frame_id, frame_id_, g_planner_, initialized_, is_expand_, is_outline_, make_plan_srv_, makePlanService(), rviz_generate::name, nx_, ny_, opt_r_, plan_pub_, resolution_, sample_max_d_, sample_points_, global_planner::GlobalPlanner::setConvertOffset(), global_planner::GlobalPlanner::setOrigin(), and tolerance_.
initialize() [2/2]
void sample_planner::SamplePlanner::initialize (std::string name, costmap_2d::Costmap2DROS * costmapRos)
Planner initialization.
Parameters
name planner name
costmapRos costmap ROS wrapper
 {
   initialize(name, costmapRos->getCostmap(), costmapRos->getGlobalFrameID());
 }
References rviz_generate::name.
Referenced by SamplePlanner().
makePlan() [1/2]
bool sample_planner::SamplePlanner::makePlan (const geometry_msgs::PoseStamped & start, const geometry_msgs::PoseStamped & goal, double tolerance, std::vector< geometry_msgs::PoseStamped > & plan)
 {
   // start thread mutex
   boost::mutex::scoped_lock lock(mutex_);
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized yet, but it is being used, please call initialize() before use");
     return false;
   }
   // clear existing plan
   plan.clear();
   // judege whether goal and start node in costmap frame or not
   if (goal.header.frame_id != frame_id_)
   {
     ROS_ERROR("The goal pose passed to this planner must be in the %s frame.  It is instead in the %s frame.",
               frame_id_.c_str(), goal.header.frame_id.c_str());
     return false;
   }
   if (start.header.frame_id != frame_id_)
   {
     ROS_ERROR("The start pose passed to this planner must be in the %s frame.  It is instead in the %s frame.",
               frame_id_.c_str(), start.header.frame_id.c_str());
     return false;
   }
   // get goal and strat node coordinate
   // tranform from world to costmap
   double wx = start.pose.position.x, wy = start.pose.position.y;
   double m_start_x, m_start_y, m_goal_x, m_goal_y;
   if (!g_planner_->world2Map(wx, wy, m_start_x, m_start_y))
   {
     ROS_WARN(
         "The robot's start position is off the global costmap. Planning will always fail, are you sure the robot has "
         "been properly localized?");
     return false;
   }
   wx = goal.pose.position.x, wy = goal.pose.position.y;
   if (!g_planner_->world2Map(wx, wy, m_goal_x, m_goal_y))
   {
     ROS_WARN_THROTTLE(1.0,
                       "The goal sent to the global planner is off the global costmap. Planning will always fail to "
                       "this goal.");
     return false;
   }
   // tranform from costmap to grid map
   int g_start_x, g_start_y, g_goal_x, g_goal_y;
   g_planner_->map2Grid(m_start_x, m_start_y, g_start_x, g_start_y);
   g_planner_->map2Grid(m_goal_x, m_goal_y, g_goal_x, g_goal_y);
   Node n_start(g_start_x, g_start_y, 0, 0, g_planner_->grid2Index(g_start_x, g_start_y), 0);
   Node n_goal(g_goal_x, g_goal_y, 0, 0, g_planner_->grid2Index(g_goal_x, g_goal_y), 0);
   // clear the cost of robot location
   costmap_->setCost(g_start_x, g_start_y, costmap_2d::FREE_SPACE);
   // outline the map
   if (is_outline_)
     g_planner_->outlineMap(costmap_->getCharMap());
   // calculate path
   std::vector<Node> path;
   std::vector<Node> expand;
   bool path_found = g_planner_->plan(costmap_->getCharMap(), n_start, n_goal, path, expand);
   if (path_found)
   {
     if (_getPlanFromPath(path, plan))
     {
       geometry_msgs::PoseStamped goalCopy = goal;
       goalCopy.header.stamp = ros::Time::now();
       plan.push_back(goalCopy);
     }
     else
       ROS_ERROR("Failed to get a plan from path when a legal path was found. This shouldn't happen.");
   }
   else
     ROS_ERROR("Failed to get a path.");
   // publish expand zone
   if (is_expand_)
     _publishExpand(expand);
   // publish visulization plan
   publishPlan(plan);
   return !plan.empty();
 }
References _getPlanFromPath(), _publishExpand(), costmap_, frame_id_, g_planner_, global_planner::GlobalPlanner::grid2Index(), initialized_, is_expand_, is_outline_, global_planner::GlobalPlanner::map2Grid(), mutex_, global_planner::GlobalPlanner::outlineMap(), global_planner::GlobalPlanner::plan(), publishPlan(), and global_planner::GlobalPlanner::world2Map().
makePlan() [2/2]
bool sample_planner::SamplePlanner::makePlan (const geometry_msgs::PoseStamped & start, const geometry_msgs::PoseStamped & goal, std::vector< geometry_msgs::PoseStamped > & plan)
plan a path given start and goal in world map
Parameters
start start in world map
goal goal in world map
plan plan
tolerance error tolerance
Returns
true if find a path successfully else false
 {
   return makePlan(start, goal, tolerance_, plan);
 }
References tolerance_.
Referenced by makePlanService().
makePlanService()
bool sample_planner::SamplePlanner::makePlanService (nav_msgs::GetPlan::Request & req, nav_msgs::GetPlan::Response & resp)
regeister planning service
Parameters
req request from client
resp response from server
 {
   makePlan(req.start, req.goal, resp.plan.poses);
   resp.plan.header.stamp = ros::Time::now();
   resp.plan.header.frame_id = frame_id_;
   return true;
 }
References frame_id_, and makePlan().
Referenced by initialize().
publishPlan()
void sample_planner::SamplePlanner::publishPlan (const std::vector< geometry_msgs::PoseStamped > & plan)
publish planning path
Parameters
path planning path
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized yet, but it is being used, please call initialize() before use");
     return;
   }
   // creat visulized path plan
   nav_msgs::Path gui_plan;
   gui_plan.poses.resize(plan.size());
   gui_plan.header.frame_id = frame_id_;
   gui_plan.header.stamp = ros::Time::now();
   for (unsigned int i = 0; i < plan.size(); i++)
     gui_plan.poses[i] = plan[i];
   // publish plan to rviz
   plan_pub_.publish(gui_plan);
 }
References frame_id_, initialized_, and plan_pub_.
Referenced by makePlan().
Member Data Documentation
convert_offset_
double sample_planner::SamplePlanner::convert_offset_ private
Referenced by _pubLine(), and initialize().
costmap_
costmap_2d::Costmap2D* sample_planner::SamplePlanner::costmap_ protected
Referenced by _pubLine(), initialize(), and makePlan().
expand_pub_
ros::Publisher sample_planner::SamplePlanner::expand_pub_ protected
Referenced by _publishExpand(), and initialize().
factor_
double sample_planner::SamplePlanner::factor_ private
Referenced by initialize().
frame_id_
std::string sample_planner::SamplePlanner::frame_id_ protected
Referenced by _getPlanFromPath(), initialize(), makePlan(), makePlanService(), and publishPlan().
g_planner_
global_planner::GlobalPlanner* sample_planner::SamplePlanner::g_planner_ protected
Referenced by _getPlanFromPath(), _pubLine(), initialize(), makePlan(), and ~SamplePlanner().
initialized_
bool sample_planner::SamplePlanner::initialized_ protected
Referenced by _getPlanFromPath(), initialize(), makePlan(), and publishPlan().
is_expand_
bool sample_planner::SamplePlanner::is_expand_ private
Referenced by initialize(), and makePlan().
is_outline_
bool sample_planner::SamplePlanner::is_outline_ private
Referenced by initialize(), and makePlan().
make_plan_srv_
ros::ServiceServer sample_planner::SamplePlanner::make_plan_srv_ protected
Referenced by initialize().
mutex_
boost::mutex sample_planner::SamplePlanner::mutex_ private
Referenced by makePlan().
nx_
unsigned int sample_planner::SamplePlanner::nx_ protected
Referenced by initialize().
ny_
unsigned int sample_planner::SamplePlanner::ny_ protected
Referenced by initialize().
opt_r_
double sample_planner::SamplePlanner::opt_r_ private
Referenced by initialize().
plan_pub_
ros::Publisher sample_planner::SamplePlanner::plan_pub_ protected
Referenced by initialize(), and publishPlan().
resolution_
double sample_planner::SamplePlanner::resolution_ protected
Referenced by initialize().
sample_max_d_
double sample_planner::SamplePlanner::sample_max_d_ private
Referenced by initialize().
sample_points_
int sample_planner::SamplePlanner::sample_points_ private
Referenced by initialize().
tolerance_
double sample_planner::SamplePlanner::tolerance_ private
Referenced by initialize(), and makePlan().
The documentation for this class was generated from the following files:
src/core/global_planner/sample_planner/include/sample_planner.h
src/core/global_planner/sample_planner/src/sample_planner.cpp