ROS Motion Planning: spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual Class Reference
spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual Class Reference
#include <covariance_visual.h>
Public Member Functions
ProbabilityEllipseCovarianceVisual (Ogre::SceneManager *sceneManager, Ogre::SceneNode *parentNode)
virtual ~ProbabilityEllipseCovarianceVisual ()
virtual void setLineWidth (float lineWidth)
virtual void setColor (const Ogre::ColourValue &c)
virtual void setMeanCovariance (const Ogre::Vector3 &mean, const Ogre::Matrix3 &cov)
NOTE: It is assumed that the covariance matrix is already rotated into the target frame of the sceneNode!
Public Member Functions inherited from spencer_tracking_rviz_plugin::CovarianceVisual
CovarianceVisual (Ogre::SceneManager *sceneManager, Ogre::SceneNode *parentNode)
virtual ~CovarianceVisual ()
void setPosition (const Ogre::Vector3 &position)
void setOrientation (const Ogre::Quaternion &orientation)
void setVisible (bool visible)
Private Member Functions
double set_angle_to_range (double alpha, double min)
void calc_ellipse (double xc, double yc, double a, double b, double phi, int &np, double *&xvec, double *&yvec)
void calc_prob_elli_95 (double xc, double yc, double sxx, double syy, double sxy, int &np, double *&x, double *&y)
void calc_prob_elli_99 (double xc, double yc, double sxx, double syy, double sxy, int &np, double *&x, double *&y)
Private Attributes
rviz::BillboardLine * m_line
Additional Inherited Members
Protected Attributes inherited from spencer_tracking_rviz_plugin::CovarianceVisual
Ogre::SceneManager * m_sceneManager
Ogre::SceneNode * m_sceneNode
Constructor & Destructor Documentation
ProbabilityEllipseCovarianceVisual()
spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::ProbabilityEllipseCovarianceVisual (Ogre::SceneManager * sceneManager, Ogre::SceneNode * parentNode) inline
     : CovarianceVisual(sceneManager, parentNode)
   {
     m_line = new rviz::BillboardLine(m_sceneManager, m_sceneNode);
   }
References m_line, spencer_tracking_rviz_plugin::CovarianceVisual::m_sceneManager, and spencer_tracking_rviz_plugin::CovarianceVisual::m_sceneNode.
~ProbabilityEllipseCovarianceVisual()
virtual spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::~ProbabilityEllipseCovarianceVisual () inline virtual
   {
     delete m_line;
   }
References m_line.
Member Function Documentation
calc_ellipse()
void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::calc_ellipse (double xc, double yc, double a, double b, double phi, int & np, double *& xvec, double *& yvec) inline private
   {
     const int N_ELLI_POINTS = 40;
     int i, offset;
     double t, cr, sr, ca, sa, xi, yi, reso;
     static double x[N_ELLI_POINTS + 1];
     static double y[N_ELLI_POINTS + 1];
     reso = 2 * M_PI / N_ELLI_POINTS;
     offset = N_ELLI_POINTS / 2;
     ca = cos(phi);
     sa = sin(phi);
     i = 0;
     t = 0;
     while (t < M_PI)
     {
       cr = cos(t);
       sr = sin(t);
       xi = a * cr * ca - b * sr * sa;
       yi = a * cr * sa + b * sr * ca;
       x[i] = xi + xc;
       y[i] = yi + yc;
       x[offset + i] = -xi + xc;
       y[offset + i] = -yi + yc;
       t = t + reso;
       i++;
     }
     x[N_ELLI_POINTS] = x[0];  // Close contour
     y[N_ELLI_POINTS] = y[0];  // Close contour
     np = N_ELLI_POINTS + 1;
     xvec = x;
     yvec = y;
   }
Referenced by calc_prob_elli_95(), and calc_prob_elli_99().
calc_prob_elli_95()
void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::calc_prob_elli_95 (double xc, double yc, double sxx, double syy, double sxy, int & np, double *& x, double *& y) inline private
   {
     double la, lb, a, b, phi;
     la = (sxx + syy + sqrt((sxx - syy) * (sxx - syy) + 4 * sxy * sxy)) / 2;
     lb = (sxx + syy - sqrt((sxx - syy) * (sxx - syy) + 4 * sxy * sxy)) / 2;
     a = sqrt(5.991464 * la);
     b = sqrt(5.991464 * lb);
     phi = set_angle_to_range(atan2(2 * sxy, sxx - syy) / 2, 0);
     calc_ellipse(xc, yc, a, b, phi, np, x, y);
   }
References calc_ellipse(), and set_angle_to_range().
calc_prob_elli_99()
void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::calc_prob_elli_99 (double xc, double yc, double sxx, double syy, double sxy, int & np, double *& x, double *& y) inline private
   {
     double la, lb, a, b, phi;
     la = (sxx + syy + sqrt((sxx - syy) * (sxx - syy) + 4 * sxy * sxy)) / 2;
     lb = (sxx + syy - sqrt((sxx - syy) * (sxx - syy) + 4 * sxy * sxy)) / 2;
     a = sqrt(9.210340 * la);
     b = sqrt(9.210340 * lb);
     phi = set_angle_to_range(atan2(2 * sxy, sxx - syy) / 2, 0);
     calc_ellipse(xc, yc, a, b, phi, np, x, y);
   }
References calc_ellipse(), and set_angle_to_range().
Referenced by setMeanCovariance().
set_angle_to_range()
double spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::set_angle_to_range (double alpha, double min) inline private
   {
     while (alpha >= min + 2.0 * M_PI)
     {
       alpha -= 2.0 * M_PI;
     }
     while (alpha < min)
     {
       alpha += 2.0 * M_PI;
     }
     return alpha;
   }
References rviz_generate::alpha.
Referenced by calc_prob_elli_95(), and calc_prob_elli_99().
setColor()
virtual void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::setColor (const Ogre::ColourValue & c) inline virtual
Implements spencer_tracking_rviz_plugin::CovarianceVisual.
   {
     m_line->setColor(c.r, c.g, c.b, c.a);
   }
References m_line.
setLineWidth()
virtual void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::setLineWidth (float lineWidth) inline virtual
Implements spencer_tracking_rviz_plugin::CovarianceVisual.
   {
     m_line->setLineWidth(lineWidth);
   }
References m_line.
setMeanCovariance()
virtual void spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::setMeanCovariance (const Ogre::Vector3 & mean, const Ogre::Matrix3 & cov) inline virtual
NOTE: It is assumed that the covariance matrix is already rotated into the target frame of the sceneNode!
Implements spencer_tracking_rviz_plugin::CovarianceVisual.
   {
     int numberOfPoints;
     double *xs, *ys;
     double determinant = cov[0][0] * cov[1][1] - cov[1][0] * cov[0][1];
     m_line->clear();
     if (!std::isfinite(determinant))
     {
       ROS_WARN_STREAM_THROTTLE(
           5.0, "Covariance matrix has non-finite values in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): "
                    << cov);
       return;
     }
     if (std::abs(cov[0][1] - cov[1][0]) > 0.00001)
     {
       ROS_WARN_STREAM_THROTTLE(
           5.0,
           "Covariance matrix is not symmetric in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): " << cov);
       return;
     }
     if (determinant > 0 && cov[0][0] > 0 /* positive definite? */ ||
         std::abs(determinant - 0.00001) == 0.0 && (cov[0][0] > 0 || cov[1][1] > 0) /* positive semidefinite? */)
     {
       calc_prob_elli_99(mean.x, mean.y, cov[0][0], cov[1][1], cov[0][1], numberOfPoints, xs, ys);
       m_line->setMaxPointsPerLine(numberOfPoints);
       for (int i = 0; i < numberOfPoints; i++)
       {
         Ogre::Vector3 vertex(xs[i], ys[i], mean.z);
         m_line->addPoint(vertex);
       }
     }
     else
     {
       if (cov[0][0] != 0 || cov[0][1] != 0 || cov[0][2] != 0 || cov[1][0] != 0 || cov[1][1] != 0 || cov[1][2] != 0 ||
           cov[2][0] != 0 || cov[2][1] != 0 || cov[2][2] != 0)
         ROS_WARN_STREAM_THROTTLE(5.0,
                                  "Covariance matrix is not positive (semi-)definite in "
                                  "ProbabilityEllipseCovarianceVisual::setMeanCovariance(): "
                                      << cov);
     }
   }
References RVO::abs(), calc_prob_elli_99(), and m_line.
Member Data Documentation
m_line
rviz::BillboardLine* spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::m_line private
Referenced by ProbabilityEllipseCovarianceVisual(), setColor(), setLineWidth(), setMeanCovariance(), and ~ProbabilityEllipseCovarianceVisual().
The documentation for this class was generated from the following file:
src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/visuals/covariance_visual.h