ROS Motion Planning: trajectory_generation::Bezier Class Reference
trajectory_generation::Bezier Class Reference
#include <bezier_curve.h>
Public Member Functions
Bezier ()
Construct a new Bezier generation object.
Bezier (double step, double offset)
Construct a new Bezier generation object.
~Bezier ()
Destroy the Bezier generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Poses2d points, Points2d &path)
Running trajectory generation.
Point2d bezier (double t, Points2d control_pts)
Calculate the Bezier curve point.
Points2d getControlPoints (Pose2d start, Pose2d goal)
Calculate control points heuristically.
Points2d generation (Pose2d start, Pose2d goal)
Generate the path.
void setOffset (double offset)
Configure the offset of control points.
Public Member Functions inherited from trajectory_generation::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Attributes
double offset_
Protected Attributes inherited from trajectory_generation::Curve
double step_
Private Member Functions
int _comb (int n, int r)
Constructor & Destructor Documentation
Bezier() [1/2]
trajectory_generation::Bezier::Bezier ()
Construct a new Bezier generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
offset The offset of control points (default: 3.0)
                : Curve(0.1), offset_(3)
 {
 }
Bezier() [2/2]
trajectory_generation::Bezier::Bezier (double step, double offset)
Construct a new Bezier generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
offset The offset of control points (default: 3.0)
                                          : Curve(step), offset_(offset)
 {
 }
~Bezier()
trajectory_generation::Bezier::~Bezier ()
Destroy the Bezier generation object.
 {
 }
Member Function Documentation
_comb()
int trajectory_generation::Bezier::_comb (int n, int r) private
 {
   if ((r == 0) || (r == n))
     return 1;
   else
     return _comb(n - 1, r - 1) + _comb(n - 1, r);
 }
References rviz_generate::r.
Referenced by bezier().
bezier()
Point2d trajectory_generation::Bezier::bezier (double t, Points2d control_pts)
Calculate the Bezier curve point.
Parameters
t scale factor
control_pts control points
Returns
point point in Bezier curve with t
 {
   size_t n = control_pts.size() - 1;
   Point2d pt(0, 0);
   for (size_t i = 0; i < n + 1; i++)
   {
     pt.first += _comb(n, i) * std::pow(t, i) * std::pow(1 - t, n - i) * control_pts[i].first;
     pt.second += _comb(n, i) * std::pow(t, i) * std::pow(1 - t, n - i) * control_pts[i].second;
   }
   return pt;
 }
References _comb().
Referenced by generation().
generation()
Points2d trajectory_generation::Bezier::generation (Pose2d start, Pose2d goal)
Generate the path.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
path The smoothed trajectory points
 {
   double sx, sy, syaw;
   double gx, gy, gyaw;
   std::tie(sx, sy, syaw) = start;
   std::tie(gx, gy, gyaw) = goal;
   int n_points = (int)(helper::dist(Point2d(sx, sy), Point2d(gx, gy)) / step_);
   Points2d control_pts = getControlPoints(start, goal);
   Points2d points;
   for (size_t i = 0; i < n_points; i++)
   {
     double t = (double)(i) / (double)(n_points - 1);
     points.push_back(bezier(t, control_pts));
   }
   return points;
 }
References bezier(), helper::dist(), getControlPoints(), and trajectory_generation::Curve::step_.
Referenced by run().
getControlPoints()
Points2d trajectory_generation::Bezier::getControlPoints (Pose2d start, Pose2d goal)
Calculate control points heuristically.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
control_pts control points
 {
   double sx, sy, syaw;
   double gx, gy, gyaw;
   std::tie(sx, sy, syaw) = start;
   std::tie(gx, gy, gyaw) = goal;
   double d = helper::dist(Point2d(sx, sy), Point2d(gx, gy)) / offset_;
   Points2d control_pts;
   control_pts.emplace_back(sx, sy);
   control_pts.emplace_back(sx + d * cos(syaw), sy + d * sin(syaw));
   control_pts.emplace_back(gx - d * cos(gyaw), gy - d * sin(gyaw));
   control_pts.emplace_back(gx, gy);
   return control_pts;
 }
References rviz_generate::d, helper::dist(), and offset_.
Referenced by generation().
run() [1/2]
bool trajectory_generation::Bezier::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     Poses2d poses;
     poses.emplace_back(points.begin()->first, points.begin()->second, 0);
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = helper::angle(points[i - 1], points[i]);
       double theta2 = helper::angle(points[i], points[i + 1]);
       poses.emplace_back(points[i].first, points[i].second, (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().first, points.back().second, 0);
     return run(poses, path);
   }
 }
References helper::angle().
run() [2/2]
bool trajectory_generation::Bezier::run (const Poses2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     path.clear();
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       Points2d path_i = generation(points[i], points[i + 1]);
       path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation().
setOffset()
void trajectory_generation::Bezier::setOffset (double offset)
Configure the offset of control points.
Parameters
offset The offset of control points
 {
   assert(offset > 0);
   offset_ = offset;
 }
References offset_.
Member Data Documentation
offset_
double trajectory_generation::Bezier::offset_ protected
Referenced by getControlPoints(), and setOffset().
The documentation for this class was generated from the following files:
src/core/curve_generation/include/bezier_curve.h
src/core/curve_generation/src/bezier_curve.cpp