ROS Motion Planning: trajectory_generation::Dubins Class Reference
trajectory_generation::Dubins Class Reference
#include <dubins_curve.h>
Public Member Functions
Dubins ()
Construct a new Dubins generation object.
Dubins (double step, double max_curv)
Construct a new Dubins generation object.
~Dubins ()
Destroy the Dubins generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Poses2d points, Points2d &path)
Running trajectory generation.
void LSL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Straight-Left generation mode.
void RSR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Straight-Right generation mode.
void LSR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Straight-Right generation mode.
void RSL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Straight-Left generation mode.
void RLR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Left-Right generation mode.
void LRL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Right-Left generation mode.
Pose2d interpolate (int mode, double length, Pose2d init_pose)
Planning path interpolation.
Points2d generation (Pose2d start, Pose2d goal)
Generate the path.
void setMaxCurv (double max_curv)
Configure the maximum curvature.
Public Member Functions inherited from trajectory_generation::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Member Functions
void _update (DubinsLength length, DubinsMode mode, DubinsLength &best_length, DubinsMode &best_mode, double &best_cost)
Update the best motion mode.
Protected Attributes
double max_curv_
Protected Attributes inherited from trajectory_generation::Curve
double step_
Constructor & Destructor Documentation
Dubins() [1/2]
trajectory_generation::Dubins::Dubins ()
Construct a new Dubins generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                : Curve(0.1), max_curv_(0.25)
 {
 }
Dubins() [2/2]
trajectory_generation::Dubins::Dubins (double step, double max_curv)
Construct a new Dubins generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                                            : Curve(step), max_curv_(max_curv)
 {
 }
~Dubins()
trajectory_generation::Dubins::~Dubins ()
Destroy the Dubins generation object.
 {
 }
Member Function Documentation
_update()
void trajectory_generation::Dubins::_update (DubinsLength length, DubinsMode mode, DubinsLength & best_length, DubinsMode & best_mode, double & best_cost) protected
Update the best motion mode.
Parameters
length the current motion length
mode the current motion mode
best_length the best motion length so far
best_mode the best motion mode so far
best_cost the best motion cost so far
 {
   if (std::get<0>(length) != DUBINS_NONE)
   {
     double t, p, q;
     std::tie(t, p, q) = length;
     double cost = fabs(t) + fabs(p) + fabs(q);
     if (best_cost > cost)
     {
       best_length = length;
       best_mode = mode;
       best_cost = cost;
     }
   }
 }
References DUBINS_NONE.
Referenced by generation().
generation()
Points2d trajectory_generation::Dubins::generation (Pose2d start, Pose2d goal)
Generate the path.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
path The smoothed trajectory points
 {
   Points2d path;
   double sx, sy, syaw;
   double gx, gy, gyaw;
   std::tie(sx, sy, syaw) = start;
   std::tie(gx, gy, gyaw) = goal;
   // coordinate transformation
   gx -= sx;
   gy -= sy;
   double theta = helper::mod2pi(atan2(gy, gx));
   double dist = hypot(gx, gy) * max_curv_;
   double alpha = helper::mod2pi(syaw - theta);
   double beta = helper::mod2pi(gyaw - theta);
   // select the best motion
   DubinsMode best_mode;
   double best_cost = DUBINS_MAX;
   DubinsLength length;
   DubinsLength best_length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
   DubinsMode mode;
   for (const auto solver : dubins_solvers)
   {
     (this->*solver)(alpha, beta, dist, length, mode);
     _update(length, mode, best_length, best_mode, best_cost);
   }
   if (best_cost == DUBINS_MAX)
     return path;
   // interpolation
   int points_num = int(best_cost / step_) + 6;
   std::vector<double> path_x(points_num);
   std::vector<double> path_y(points_num);
   std::vector<double> path_yaw(points_num, alpha);
   std::vector<int> mode_v = { std::get<0>(best_mode), std::get<1>(best_mode), std::get<2>(best_mode) };
   std::vector<double> length_v = { std::get<0>(best_length), std::get<1>(best_length), std::get<2>(best_length) };
   int i = 0;
   for (int j = 0; j < 3; j++)
   {
     int m = mode_v[j];
     double seg_length = length_v[j];
     // path increment
     double d_l = seg_length > 0.0 ? step_ : -step_;
     double x = path_x[i];
     double y = path_y[i];
     double yaw = path_yaw[i];
     // current path length
     double l = d_l;
     while (fabs(l) <= fabs(seg_length))
     {
       i += 1;
       std::tie(path_x[i], path_y[i], path_yaw[i]) = interpolate(m, l, { x, y, yaw });
       l += d_l;
     }
     i += 1;
     std::tie(path_x[i], path_y[i], path_yaw[i]) = interpolate(m, seg_length, { x, y, yaw });
   }
   // remove unused data
   while ((path_x.size() >= 1) && (path_x.back() == 0.0))
   {
     path_x.pop_back();
     path_y.pop_back();
     path_yaw.pop_back();
   }
   // coordinate transformation
   Eigen::AngleAxisd r_vec(theta, Eigen::Vector3d(0, 0, 1));
   Eigen::Matrix3d R = r_vec.toRotationMatrix();
   Eigen::MatrixXd P = Eigen::MatrixXd::Ones(3, path_x.size());
   for (size_t i = 0; i < path_x.size(); i++)
   {
     P(0, i) = path_x[i];
     P(1, i) = path_y[i];
   }
   P = R * P;
   for (size_t i = 0; i < path_x.size(); i++)
     path.push_back({ P(0, i) + sx, P(1, i) + sy });
   return path;
 }
References _update(), rviz_generate::alpha, helper::dist(), DUBINS_MAX, DUBINS_NONE, trajectory_generation::dubins_solvers, interpolate(), max_curv_, helper::mod2pi(), and trajectory_generation::Curve::step_.
Referenced by run().
interpolate()
Pose2d trajectory_generation::Dubins::interpolate (int mode, double length, Pose2d init_pose)
Planning path interpolation.
Parameters
mode motion, i.e., DUBINS_L, DUBINS_S, DUBINS_R
length Single step motion path length
init_pose Initial pose (x, y, yaw)
Returns
new_pose New pose (new_x, new_y, new_yaw) after moving
 {
   double x, y, yaw;
   double new_x, new_y, new_yaw;
   std::tie(x, y, yaw) = init_pose;
   if (mode == DUBINS_S)
   {
     new_x = x + length / max_curv_ * cos(yaw);
     new_y = y + length / max_curv_ * sin(yaw);
     new_yaw = yaw;
   }
   else if (mode == DUBINS_L)
   {
     new_x = x + (sin(yaw + length) - sin(yaw)) / max_curv_;
     new_y = y - (cos(yaw + length) - cos(yaw)) / max_curv_;
     new_yaw = yaw + length;
   }
   else if (mode == DUBINS_R)
   {
     new_x = x - (sin(yaw - length) - sin(yaw)) / max_curv_;
     new_y = y + (cos(yaw - length) - cos(yaw)) / max_curv_;
     new_yaw = yaw - length;
   }
   else
     std::cerr << "Error mode" << std::endl;
   return { new_x, new_y, new_yaw };
 }
References DUBINS_L, DUBINS_R, DUBINS_S, and max_curv_.
Referenced by generation().
LRL()
void trajectory_generation::Dubins::LRL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Right-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lrl = (6.0 - std::pow(dist, 2) + 2.0 * cos_a_b + 2.0 * dist * (sin_a - sin_b)) / 8.0;
   if (fabs(p_lrl) > 1.0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_R, DUBINS_L };
   }
   else
   {
     p_lrl = helper::mod2pi(2 * M_PI - acos(p_lrl));
     double t_lrl = helper::mod2pi(-alpha + atan2(-cos_a + cos_b, dist + sin_a - sin_b) + p_lrl / 2.0);
     double q_lrl = helper::mod2pi(beta - alpha - t_lrl + p_lrl);
     length = { t_lrl, p_lrl, q_lrl };
     mode = { DUBINS_L, DUBINS_R, DUBINS_L };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_L, DUBINS_NONE, DUBINS_R, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
LSL()
void trajectory_generation::Dubins::LSL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Straight-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lsl = 2 + std::pow(dist, 2) - 2 * cos_a_b + 2 * dist * (sin_a - sin_b);
   if (p_lsl < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_S, DUBINS_L };
   }
   else
   {
     p_lsl = sqrt(p_lsl);
     double t_lsl = helper::mod2pi(-alpha + atan2(cos_b - cos_a, dist + sin_a - sin_b));
     double q_lsl = helper::mod2pi(beta - atan2(cos_b - cos_a, dist + sin_a - sin_b));
     length = { t_lsl, p_lsl, q_lsl };
     mode = { DUBINS_L, DUBINS_S, DUBINS_L };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_L, DUBINS_NONE, DUBINS_S, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
LSR()
void trajectory_generation::Dubins::LSR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Straight-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lsr = -2 + std::pow(dist, 2) + 2 * cos_a_b + 2 * dist * (sin_a + sin_b);
   if (p_lsr < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_S, DUBINS_R };
   }
   else
   {
     p_lsr = sqrt(p_lsr);
     double t_lsr = helper::mod2pi(-alpha + atan2(-cos_a - cos_b, dist + sin_a + sin_b) - atan2(-2.0, p_lsr));
     double q_lsr = helper::mod2pi(-beta + atan2(-cos_a - cos_b, dist + sin_a + sin_b) - atan2(-2.0, p_lsr));
     length = { t_lsr, p_lsr, q_lsr };
     mode = { DUBINS_L, DUBINS_S, DUBINS_R };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_L, DUBINS_NONE, DUBINS_R, DUBINS_S, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
RLR()
void trajectory_generation::Dubins::RLR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Left-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rlr = (6.0 - std::pow(dist, 2) + 2.0 * cos_a_b + 2.0 * dist * (sin_a - sin_b)) / 8.0;
   if (fabs(p_rlr) > 1.0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_L, DUBINS_R };
   }
   else
   {
     p_rlr = helper::mod2pi(2 * M_PI - acos(p_rlr));
     double t_rlr = helper::mod2pi(alpha - atan2(cos_a - cos_b, dist - sin_a + sin_b) + p_rlr / 2.0);
     double q_rlr = helper::mod2pi(alpha - beta - t_rlr + p_rlr);
     length = { t_rlr, p_rlr, q_rlr };
     mode = { DUBINS_R, DUBINS_L, DUBINS_R };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_L, DUBINS_NONE, DUBINS_R, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
RSL()
void trajectory_generation::Dubins::RSL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Straight-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rsl = -2 + std::pow(dist, 2) + 2 * cos_a_b - 2 * dist * (sin_a + sin_b);
   if (p_rsl < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_S, DUBINS_L };
   }
   else
   {
     p_rsl = sqrt(p_rsl);
     double t_rsl = helper::mod2pi(alpha - atan2(cos_a + cos_b, dist - sin_a - sin_b) + atan2(2.0, p_rsl));
     double q_rsl = helper::mod2pi(beta - atan2(cos_a + cos_b, dist - sin_a - sin_b) + atan2(2.0, p_rsl));
     length = { t_rsl, p_rsl, q_rsl };
     mode = { DUBINS_R, DUBINS_S, DUBINS_L };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_L, DUBINS_NONE, DUBINS_R, DUBINS_S, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
RSR()
void trajectory_generation::Dubins::RSR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Straight-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rsr = 2 + std::pow(dist, 2) - 2 * cos_a_b + 2 * dist * (sin_b - sin_a);
   if (p_rsr < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_S, DUBINS_R };
   }
   else
   {
     p_rsr = sqrt(p_rsr);
     double t_rsr = helper::mod2pi(alpha - atan2(cos_a - cos_b, dist - sin_a + sin_b));
     double q_rsr = helper::mod2pi(-beta + atan2(cos_a - cos_b, dist - sin_a + sin_b));
     length = { t_rsr, p_rsr, q_rsr };
     mode = { DUBINS_R, DUBINS_S, DUBINS_R };
   }
 }
References rviz_generate::alpha, helper::dist(), DUBINS_NONE, DUBINS_R, DUBINS_S, helper::mod2pi(), and UNPACK_DUBINS_INPUTS.
run() [1/2]
bool trajectory_generation::Dubins::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 2)
     return false;
   else
   {
     Poses2d poses;
     poses.emplace_back(points.begin()->first, points.begin()->second, 0);
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = helper::angle(points[i - 1], points[i]);
       double theta2 = helper::angle(points[i], points[i + 1]);
       poses.emplace_back(points[i].first, points[i].second, (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().first, points.back().second, 0);
     return run(poses, path);
   }
 }
References helper::angle().
Referenced by global_planner::HybridAStar::dubinsShot().
run() [2/2]
bool trajectory_generation::Dubins::run (const Poses2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 2)
     return false;
   else
   {
     path.clear();
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       Points2d path_i = generation(points[i], points[i + 1]);
       if (!path_i.empty())
         path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation().
setMaxCurv()
void trajectory_generation::Dubins::setMaxCurv (double max_curv)
Configure the maximum curvature.
Parameters
max_curv the maximum curvature
 {
   assert(max_curv > 0);
   max_curv_ = max_curv;
 }
References max_curv_.
Referenced by global_planner::HybridAStar::HybridAStar().
Member Data Documentation
max_curv_
double trajectory_generation::Dubins::max_curv_ protected
Referenced by generation(), interpolate(), and setMaxCurv().
The documentation for this class was generated from the following files:
src/core/curve_generation/include/dubins_curve.h
src/core/curve_generation/src/dubins_curve.cpp