ROS Motion Planning: trajectory_generation::Polynomial Class Reference
trajectory_generation::Polynomial Class Reference
#include <polynomial_curve.h>
Public Member Functions
Polynomial ()
Construct a new Polynomial generation object.
Polynomial (double step, double max_acc, double max_jerk)
Construct a new Polynomial generation object.
~Polynomial ()
Destroy the Polynomial generation object.
void generation (PolyState start_state, PolyState goal_state, PolyTrajectory &traj)
Generate a valid trajectory from start state to goal state.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Poses2d points, Points2d &path)
Running trajectory generation.
void setMaxAcceleration (double max_acc)
Configure the maximum acceleration.
void setMaxJerk (double max_jerk)
Configure the maximum jerk.
Public Member Functions inherited from trajectory_generation::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Attributes
double max_acc_
double max_jerk_
Protected Attributes inherited from trajectory_generation::Curve
double step_
Constructor & Destructor Documentation
Polynomial() [1/2]
trajectory_generation::Polynomial::Polynomial ()
Construct a new Polynomial generation object.
Parameters
max_acc Maximum acceleration (default: 1.0)
max_jerk Maximum jerk (default: 0.5)
                        : Curve(2.0), max_acc_(3.0), max_jerk_(1.0)
 {
 }
Polynomial() [2/2]
trajectory_generation::Polynomial::Polynomial (double step, double max_acc, double max_jerk)
Construct a new Polynomial generation object.
Parameters
max_acc Maximum acceleration (default: 1.0)
max_jerk Maximum jerk (default: 0.5)
   : Curve(step), max_acc_(max_acc), max_jerk_(max_jerk)
 {
 }
~Polynomial()
trajectory_generation::Polynomial::~Polynomial ()
Destroy the Polynomial generation object.
 {
 }
Member Function Documentation
generation()
void trajectory_generation::Polynomial::generation (PolyState start_state, PolyState goal_state, PolyTrajectory & traj)
Generate a valid trajectory from start state to goal state.
Parameters
start_state start state
goal_state goal state
traj the trajectory
 {
   //  simulation parameters
   double t_min = 1.0;
   double t_max = 30.0;
   double dt = 0.5;
   double sx, sy, syaw, sv, sa;
   double gx, gy, gyaw, gv, ga;
   std::tie(sx, sy, syaw, sv, sa) = start_state;
   std::tie(gx, gy, gyaw, gv, ga) = goal_state;
   double sv_x = sv * cos(syaw);
   double sv_y = sv * sin(syaw);
   double gv_x = gv * cos(gyaw);
   double gv_y = gv * sin(gyaw);
   double sa_x = sa * cos(syaw);
   double sa_y = sa * sin(syaw);
   double ga_x = ga * cos(gyaw);
   double ga_y = ga * sin(gyaw);
   traj.clear();
   double T = t_min;
   while (T < t_max)
   {
     Poly x_psolver({ sx, sv_x, sa_x }, { gx, gv_x, ga_x }, T);
     Poly y_psolver({ sy, sv_y, sa_y }, { gy, gv_y, ga_y }, T);
     double t = 0.0;
     while (t < T + dt)
     {
       double vx = x_psolver.dx(t);
       double vy = y_psolver.dx(t);
       double v = hypot(vx, vy);
       double yaw = atan2(vy, vx);
       double ax = x_psolver.ddx(t);
       double ay = y_psolver.ddx(t);
       double a = hypot(ax, ay);
       a = traj.dir(POLY_DIR_ACC) ? a * traj.dir(POLY_DIR_ACC) : a;
       double jx = x_psolver.dddx(t);
       double jy = y_psolver.dddx(t);
       double j = hypot(jx, jy);
       j = traj.dir(POLY_DIR_JERK) ? j * traj.dir(POLY_DIR_JERK) : j;
       traj.append(t, x_psolver.x(t), y_psolver.x(t), v, yaw, a, j);
       t += dt;
     }
     if (traj.valid(max_acc_, max_jerk_))
       break;
     else
       traj.clear();
     T += step_;
   }
 }
References trajectory_generation::PolyTrajectory::append(), trajectory_generation::PolyTrajectory::clear(), trajectory_generation::PolyTrajectory::dir(), trajectory_generation::Poly::dx(), max_acc_, max_jerk_, POLY_DIR_ACC, POLY_DIR_JERK, trajectory_generation::Curve::step_, and trajectory_generation::PolyTrajectory::valid().
Referenced by run().
run() [1/2]
bool trajectory_generation::Polynomial::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     Poses2d poses;
     poses.emplace_back(points.begin()->first, points.begin()->second, 0);
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = helper::angle(points[i - 1], points[i]);
       double theta2 = helper::angle(points[i], points[i + 1]);
       poses.emplace_back(points[i].first, points[i].second, (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().first, points.back().second, 0);
     return run(poses, path);
   }
 }
References helper::angle().
run() [2/2]
bool trajectory_generation::Polynomial::run (const Poses2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements trajectory_generation::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     path.clear();
     // generate velocity and acceleration constraints heuristically
     std::vector<double> v(points.size(), 1.0);
     v[0] = 0.0;
     std::vector<double> a;
     for (size_t i = 0; i < points.size() - 1; i++)
       a.push_back((v[i + 1] - v[i]) / 5);
     a.push_back(0.0);
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       PolyTrajectory traj;
       PolyState start(std::get<0>(points[i]), std::get<1>(points[i]), std::get<2>(points[i]), v[i], a[i]);
       PolyState goal(std::get<0>(points[i + 1]), std::get<1>(points[i + 1]), std::get<2>(points[i + 1]), v[i + 1],
                      a[i + 1]);
       generation(start, goal, traj);
       Points2d path_i = traj.toPath();
       path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation(), and trajectory_generation::PolyTrajectory::toPath().
setMaxAcceleration()
void trajectory_generation::Polynomial::setMaxAcceleration (double max_acc)
Configure the maximum acceleration.
Parameters
max_acc The maximum acceleration
 {
   assert(max_acc > 0);
   max_acc_ = max_acc;
 }
References max_acc_.
setMaxJerk()
void trajectory_generation::Polynomial::setMaxJerk (double max_jerk)
Configure the maximum jerk.
Parameters
max_jerk The maximum jerk
 {
   assert(max_jerk > 0);
   max_jerk_ = max_jerk;
 }
References max_jerk_.
Member Data Documentation
max_acc_
double trajectory_generation::Polynomial::max_acc_ protected
Referenced by generation(), and setMaxAcceleration().
max_jerk_
double trajectory_generation::Polynomial::max_jerk_ protected
Referenced by generation(), and setMaxJerk().
The documentation for this class was generated from the following files:
src/core/curve_generation/include/polynomial_curve.h
src/core/curve_generation/src/polynomial_curve.cpp