ROS Motion Planning: global_planner::PSO Class Reference
global_planner::PSO Class Reference
Class for objects that plan using the PSO algorithm.
#include <pso.h>
Public Member Functions
PSO (int nx, int ny, double resolution, int n_particles, int n_inherited, int point_num, double w_inertial, double w_social, double w_cognitive, int max_speed, int init_mode, int max_iter)
Construct a new PSO object.
~PSO ()
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
PSO implementation.
void initializePositions (PositionSequence &initial_positions, const Node &start, const Node &goal, int gen_mode=GEN_MODE_CIRCLE)
Generate n particles with pointNum_ positions each within the map range.
double calFitnessValue (std::vector< std::pair< int, int >> position)
Calculate the value of fitness function.
void updateParticleVelocity (Particle &particle, const Particle &global_best, std::mt19937 &gen)
A function to update the particle velocity.
void updateParticlePosition (Particle &particle)
A function to update the particle position.
void optimizeParticle (Particle &particle, Particle &best_particle, std::mt19937 &gen, std::vector< Node > &expand)
Particle update optimization iteration.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Attributes
int max_iter_
int n_particles_
int n_inherited_
int point_num_
double w_inertial_
double w_social_
double w_cognitive_
int max_speed_
int init_mode_
std::pair< double, double > start_
std::pair< double, double > goal_
const unsigned char * costmap_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Private Attributes
std::mutex particles_lock_
std::vector< Particle > inherited_particles_
trajectory_generation::BSpline bspline_gen_
Additional Inherited Members
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Detailed Description
Class for objects that plan using the PSO algorithm.
Constructor & Destructor Documentation
PSO()
global_planner::PSO::PSO (int nx, int ny, double resolution, int n_particles, int n_inherited, int point_num, double w_inertial, double w_social, double w_cognitive, int max_speed, int init_mode, int max_iter)
Construct a new PSO object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
n_particles number of particles
n_inherited number of inherited particles
point_num number of position points contained in each particle
w_inertial inertia weight
w_social social weight
w_cognitive cognitive weight
max_speed The maximum movement speed of particles
init_mode Set the generation mode for the initial position points of the particle swarm
max_iter maximum iterations
   : GlobalPlanner(nx, ny, resolution)
   , n_particles_(n_particles)
   , n_inherited_(n_inherited)
   , point_num_(point_num)
   , w_inertial_(w_inertial)
   , w_social_(w_social)
   , w_cognitive_(w_cognitive)
   , max_speed_(max_speed)
   , init_mode_(init_mode)
   , max_iter_(max_iter)
 {
   inherited_particles_.emplace_back(std::vector<std::pair<int, int>>(point_num, std::make_pair(1, 1)),
                                     std::vector<std::pair<int, int>>(point_num, std::make_pair(0, 0)), 0.0);
 }
References inherited_particles_.
~PSO()
global_planner::PSO::~PSO ()
 {
 }
Member Function Documentation
calFitnessValue()
double global_planner::PSO::calFitnessValue (std::vector< std::pair< int, int >> position)
Calculate the value of fitness function.
Parameters
position the control points calculated by PSO
Returns
fitness the value of fitness function
 {
   std::vector<std::pair<double, double>> points, b_path;
   points.push_back(start_);
   for (const auto& pos : position)
     points.emplace_back(static_cast<double>(pos.first), static_cast<double>(pos.second));
   points.push_back(goal_);
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_.run(points, b_path);
   // collision detection
   int point_index;
   double obs_cost = 1;
   for (size_t i = 1; i < b_path.size(); ++i)
   {
     point_index = grid2Index(static_cast<int>(b_path[i].first), static_cast<int>(b_path[i].second));
     // next node hit the boundary or obstacle
     if ((point_index < 0) || (point_index >= ns_) || (costmap_[point_index] >= lethal_cost_ * factor_))
       obs_cost++;
   }
   // Calculate particle fitness
   return 100000.0 / (bspline_gen_.len(b_path) + 1000 * obs_cost);
 }
References bspline_gen_, costmap_, global_planner::GlobalPlanner::factor_, goal_, global_planner::GlobalPlanner::grid2Index(), trajectory_generation::Curve::len(), global_planner::GlobalPlanner::lethal_cost_, global_planner::GlobalPlanner::ns_, trajectory_generation::BSpline::run(), and start_.
Referenced by optimizeParticle(), and plan().
initializePositions()
void global_planner::PSO::initializePositions (PositionSequence & initial_positions, const Node & start, const Node & goal, int gen_mode = GEN_MODE_CIRCLE)
Generate n particles with pointNum_ positions each within the map range.
Parameters
initial_positions The initial position sequence of particle swarm
start start node
goal goal node
gen_mode generation mode
 {
   // Use a random device and engine to generate random numbers
   std::random_device rd;
   std::mt19937 gen(rd());
   int x[point_num_], y[point_num_];
   int point_id, pos_id;
   // Calculate sequence direction
   bool x_order = (goal.x_ > start.x_);
   bool y_order = (goal.y_ > start.y_);
   // circle generation
   int center_x, center_y;
   double radius;
   if (gen_mode == GEN_MODE_CIRCLE)
   {
     // Calculate the center and the radius of the circle (midpoint between start and goal)
     center_x = (start.x_ + goal.x_) / 2;
     center_y = (start.y_ + goal.y_) / 2;
     radius = helper::dist(start, goal) / 2.0 < 5 ? 5 : helper::dist(start, goal) / 2.0;
   }
   // initialize n_particles positions
   for (int i = 0; i < n_particles_; ++i)
   {
     std::unordered_set<int> visited;
     std::vector<std::pair<int, int>> particle_positions;
     point_id = 0;
     // Generate point_num_ unique coordinates
     while (point_id < point_num_)
     {
       if (gen_mode == GEN_MODE_RANDOM)
       {
         x[point_id] = std::uniform_int_distribution<int>(0, nx_ - 1)(gen);
         y[point_id] = std::uniform_int_distribution<int>(0, ny_ - 1)(gen);
         pos_id = grid2Index(x[point_id], y[point_id]);
       }
       else
       {
         // Generate random angle in radians
         double angle = std::uniform_real_distribution<double>(0, 2 * M_PI)(gen);
         // Generate random distance from the center within the circle
         double r = std::sqrt(std::uniform_real_distribution<double>(0, 1)(gen)) * radius;
         // Convert polar coordinates to Cartesian coordinates
         x[point_id] = static_cast<int>(std::round(center_x + r * std::cos(angle)));
         y[point_id] = static_cast<int>(std::round(center_y + r * std::sin(angle)));
         // Check if the coordinates are within the map range
         if (x[point_id] >= 0 && x[point_id] < nx_ && y[point_id] >= 0 && y[point_id] < ny_)
           pos_id = grid2Index(x[point_id], y[point_id]);
         else
           continue;
       }
       // Check if the coordinates have already been used
       if (visited.find(pos_id) == visited.end())
       {
         point_id++;
         visited.insert(pos_id);
       }
     }
     // sort
     if (x_order)
       std::sort(x, x + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(x, x + point_num_, [](int a, int b) { return a > b; });
     if (y_order)
       std::sort(y, y + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(y, y + point_num_, [](int a, int b) { return a > b; });
     // Store elements from x and y in particle_positions
     for (int j = 0; j < point_num_; ++j)
       particle_positions.emplace_back(x[j], y[j]);
     initial_positions.push_back(particle_positions);
   }
 }
References helper::angle(), helper::dist(), GEN_MODE_CIRCLE, GEN_MODE_RANDOM, global_planner::GlobalPlanner::grid2Index(), n_particles_, global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, point_num_, rviz_generate::r, Node::x_, and Node::y_.
Referenced by plan().
optimizeParticle()
void global_planner::PSO::optimizeParticle (Particle & particle, Particle & best_particle, std::mt19937 & gen, std::vector< Node > & expand)
Particle update optimization iteration.
Parameters
particle Particles to be updated for velocity
best_particle Global optimal particle
gen randomizer
expand containing the node been search during the process
 {
   // update speed
   updateParticleVelocity(particle, best_particle, gen);
   // update position
   updateParticlePosition(particle);
   // Calculate fitness
   particle.fitness = calFitnessValue(particle.position);
   // Update individual optima
   if (particle.fitness > particle.best_fitness)
   {
     particle.best_fitness = particle.fitness;
     particle.best_pos = particle.position;
   }
   // Update global optimal particles
   particles_lock_.lock();
   // Update expand points
   for (auto pos : particle.position)
     expand.emplace_back(Node(pos.first, pos.second));
   if (particle.best_fitness > best_particle.fitness)
   {
     best_particle.fitness = particle.best_fitness;
     best_particle.position = particle.position;
   }
   particles_lock_.unlock();
 }
References global_planner::Particle::best_fitness, global_planner::Particle::best_pos, calFitnessValue(), global_planner::Particle::fitness, particles_lock_, global_planner::Particle::position, updateParticlePosition(), and updateParticleVelocity().
Referenced by plan().
plan()
bool global_planner::PSO::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
PSO implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process(unused)
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   start_ = std::pair<double, double>(static_cast<double>(start.x_), static_cast<double>(start.y_));
   goal_ = std::pair<double, double>(static_cast<double>(goal.x_), static_cast<double>(goal.y_));
   costmap_ = global_costmap;
   expand.clear();
   // variable initialization
   double init_fitness;
   Particle best_particle;
   PositionSequence init_positions;
   std::vector<Particle> particles;
   // Generate initial position of particle swarm
   initializePositions(init_positions, start, goal, init_mode_);
   // Particle initialization
   for (int i = 0; i < n_particles_; ++i)
   {
     std::vector<std::pair<int, int>> init_position;
     if ((i < n_inherited_) && (inherited_particles_.size() == n_inherited_))
       init_position = inherited_particles_[i].best_pos;
     else
       init_position = init_positions[i];
     std::vector<std::pair<int, int>> init_velocity(point_num_, std::make_pair(0, 0));
     // Calculate fitness
     init_fitness = calFitnessValue(init_position);
     if ((i == 0) || (init_fitness > best_particle.fitness))
     {
       best_particle.fitness = init_fitness;
       best_particle.position = init_position;
     }
     // Create and add particle objects to containers
     particles.emplace_back(init_position, init_velocity, init_fitness);
   }
   // random data
   std::random_device rd;
   std::mt19937 gen(rd());
   // Iterative optimization
   for (size_t iter = 0; iter < max_iter_; iter++)
   {
     std::vector<std::thread> particle_list = std::vector<std::thread>(n_particles_);
     for (size_t i = 0; i < n_particles_; ++i)
       particle_list[i] = std::thread(&PSO::optimizeParticle, this, std::ref(particles[i]), std::ref(best_particle),
                                      std::ref(gen), std::ref(expand));
     for (size_t i = 0; i < n_particles_; ++i)
       particle_list[i].join();
   }
   // Generating Paths from Optimal Particles
   std::vector<std::pair<double, double>> points, b_path;
   points.emplace_back(static_cast<double>(start.x_), static_cast<double>(start.y_));
   for (const auto& pos : best_particle.position)
     points.emplace_back(static_cast<double>(pos.first), static_cast<double>(pos.second));
   points.emplace_back(static_cast<double>(goal.x_), static_cast<double>(goal.y_));
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_.run(points, b_path);
   // Path data structure conversion
   path.clear();
   if (!b_path.empty())
   {
     // Add the last point
     path.emplace_back(static_cast<int>(b_path.back().first), static_cast<int>(b_path.back().second), 0.0, 0.0,
                       static_cast<int>(b_path.size()) - 1, 0);
     // Iterate in reverse order, starting from the second-to-last point
     for (int p = b_path.size() - 2; p >= 0; --p)
     {
       int x = static_cast<int>(b_path[p].first);
       int y = static_cast<int>(b_path[p].second);
       // Check if the current point is different from the last point
       if (x != path.back().x_ || y != path.back().y_)
         path.emplace_back(x, y, 0.0, 0.0, p, 0);
     }
   }
   // Update inheritance particles based on optimal fitness
   std::sort(particles.begin(), particles.end(),
             [](const Particle& a, const Particle& b) { return a.best_fitness > b.best_fitness; });
   inherited_particles_.clear();
   for (size_t inherit = 0; inherit < n_inherited_; ++inherit)
     inherited_particles_.emplace_back(particles[inherit]);
   return !path.empty();
 }
References bspline_gen_, calFitnessValue(), costmap_, global_planner::Particle::fitness, goal_, inherited_particles_, init_mode_, initializePositions(), max_iter_, n_inherited_, n_particles_, optimizeParticle(), point_num_, global_planner::Particle::position, trajectory_generation::BSpline::run(), start_, Node::x_, and Node::y_.
updateParticlePosition()
void global_planner::PSO::updateParticlePosition (Particle & particle)
A function to update the particle position.
Parameters
particle Particles to be updated for velocity
 {
   // update Position
   for (size_t i = 0; i < point_num_; ++i)
   {
     particle.position[i].first += particle.velocity[i].first;
     particle.position[i].second += particle.velocity[i].second;
     // Position limit
     particle.position[i].first = helper::clamp(particle.position[i].first, 1, nx_ - 1);
     particle.position[i].second = helper::clamp(particle.position[i].second, 1, ny_ - 1);
   }
 }
References helper::clamp(), global_planner::GlobalPlanner::nx_, global_planner::GlobalPlanner::ny_, point_num_, global_planner::Particle::position, and global_planner::Particle::velocity.
Referenced by optimizeParticle().
updateParticleVelocity()
void global_planner::PSO::updateParticleVelocity (Particle & particle, const Particle & global_best, std::mt19937 & gen)
A function to update the particle velocity.
Parameters
particle Particles to be updated for velocity
global_best Global optimal particle
gen randomizer
 {
   // The random numbers are distributed between [0, 1).
   std::uniform_real_distribution<double> dist(0.0, 1.0);
   // update Velocity
   for (size_t i = 0; i < point_num_; ++i)
   {
     double rand1 = dist(gen);
     double rand2 = dist(gen);
     particle.velocity[i].first =
         static_cast<int>(w_inertial_ * particle.velocity[i].first +
                          w_social_ * rand1 * (particle.best_pos[i].first - particle.position[i].first) +
                          w_cognitive_ * rand2 * (global_best.position[i].first - particle.position[i].first));
     particle.velocity[i].second =
         static_cast<int>(w_inertial_ * particle.velocity[i].second +
                          w_social_ * rand1 * (particle.best_pos[i].second - particle.position[i].second) +
                          w_cognitive_ * rand2 * (global_best.position[i].second - particle.position[i].second));
     // Velocity limit
     particle.velocity[i].first = helper::clamp(particle.velocity[i].first, -1 * max_speed_, max_speed_);
     particle.velocity[i].second = helper::clamp(particle.velocity[i].second, -1 * max_speed_, max_speed_);
   }
 }
References global_planner::Particle::best_pos, helper::clamp(), helper::dist(), max_speed_, point_num_, global_planner::Particle::position, global_planner::Particle::velocity, w_cognitive_, w_inertial_, and w_social_.
Referenced by optimizeParticle().
Member Data Documentation
bspline_gen_
trajectory_generation::BSpline global_planner::PSO::bspline_gen_ private
Referenced by calFitnessValue(), and plan().
costmap_
const unsigned char* global_planner::PSO::costmap_ protected
Referenced by calFitnessValue(), and plan().
goal_
std::pair<double, double> global_planner::PSO::goal_ protected
Referenced by calFitnessValue(), and plan().
inherited_particles_
std::vector<Particle> global_planner::PSO::inherited_particles_ private
Referenced by plan(), and PSO().
init_mode_
int global_planner::PSO::init_mode_ protected
Referenced by plan().
max_iter_
int global_planner::PSO::max_iter_ protected
Referenced by plan().
max_speed_
int global_planner::PSO::max_speed_ protected
Referenced by updateParticleVelocity().
n_inherited_
int global_planner::PSO::n_inherited_ protected
Referenced by plan().
n_particles_
int global_planner::PSO::n_particles_ protected
Referenced by initializePositions(), and plan().
particles_lock_
std::mutex global_planner::PSO::particles_lock_ private
Referenced by optimizeParticle().
point_num_
int global_planner::PSO::point_num_ protected
Referenced by initializePositions(), plan(), updateParticlePosition(), and updateParticleVelocity().
start_
std::pair<double, double> global_planner::PSO::start_ protected
Referenced by calFitnessValue(), and plan().
w_cognitive_
double global_planner::PSO::w_cognitive_ protected
Referenced by updateParticleVelocity().
w_inertial_
double global_planner::PSO::w_inertial_ protected
Referenced by updateParticleVelocity().
w_social_
double global_planner::PSO::w_social_ protected
Referenced by updateParticleVelocity().
The documentation for this class was generated from the following files:
src/core/global_planner/evolutionary_planner/include/pso.h
src/core/global_planner/evolutionary_planner/src/pso.cpp