ROS Motion Planning: global_planner::ThetaStar Class Reference
global_planner::ThetaStar Class Reference
Class for objects that plan using the Theta* algorithm.
#include <theta_star.h>
Public Member Functions
ThetaStar (int nx, int ny, double resolution)
Construct a new ThetaStar object.
bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)
Theta* implementation.
Public Member Functions inherited from global_planner::GlobalPlanner
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
void _updateVertex (const Node &parent, Node &child)
update the g value of child node
bool _lineOfSight (const Node &parent, const Node &child)
Bresenham algorithm to check if there is any obstacle between parent and child.
Protected Member Functions inherited from global_planner::GlobalPlanner
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
const unsigned char * costs_
Protected Attributes inherited from global_planner::GlobalPlanner
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Class for objects that plan using the Theta* algorithm.
Constructor & Destructor Documentation
ThetaStar()
global_planner::ThetaStar::ThetaStar (int nx, int ny, double resolution)
Construct a new ThetaStar object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
                                                       : GlobalPlanner(nx, ny, resolution)
 {
   factor_ = 0.35;
 };
References global_planner::GlobalPlanner::factor_.
Member Function Documentation
_lineOfSight()
bool global_planner::ThetaStar::_lineOfSight (const Node & parent, const Node & child) protected
Bresenham algorithm to check if there is any obstacle between parent and child.
Parameters
parent
child
Returns
true if no obstacle, else false
 {
   int s_x = (parent.x_ - child.x_ == 0) ? 0 : (parent.x_ - child.x_) / std::abs(parent.x_ - child.x_);
   int s_y = (parent.y_ - child.y_ == 0) ? 0 : (parent.y_ - child.y_) / std::abs(parent.y_ - child.y_);
   int d_x = std::abs(parent.x_ - child.x_);
   int d_y = std::abs(parent.y_ - child.y_);
   // check if any obstacle exists between parent and child
   if (d_x > d_y)
   {
     int tau = d_y - d_x;
     int x = child.x_, y = child.y_;
     int e = 0;
     while (x != parent.x_)
     {
       if (e * 2 > tau)
       {
         x += s_x;
         e -= d_y;
       }
       else if (e * 2 < tau)
       {
         y += s_y;
         e += d_x;
       }
       else
       {
         x += s_x;
         y += s_y;
         e += d_x - d_y;
       }
       if (costs_[grid2Index(x, y)] >= lethal_cost_ * factor_ && costs_[grid2Index(x, y)] >= costs_[parent.id_])
         // obstacle detected
         return false;
     }
   }
   else
   {
     // similar. swap x and y
     int tau = d_x - d_y;
     int x = child.x_, y = child.y_;
     int e = 0;
     while (y != parent.y_)
     {
       if (e * 2 > tau)
       {
         y += s_y;
         e -= d_x;
       }
       else if (e * 2 < tau)
       {
         x += s_x;
         e += d_y;
       }
       else
       {
         x += s_x;
         y += s_y;
         e += d_y - d_x;
       }
       if (costs_[grid2Index(x, y)] >= lethal_cost_ * factor_ && costs_[grid2Index(x, y)] >= costs_[parent.id_])
         // obstacle detected
         return false;
     }
   }
   return true;
 }
References RVO::abs(), costs_, global_planner::GlobalPlanner::factor_, global_planner::GlobalPlanner::grid2Index(), Node::id_, global_planner::GlobalPlanner::lethal_cost_, Node::x_, and Node::y_.
Referenced by global_planner::LazyThetaStar::_setVertex(), and _updateVertex().
_updateVertex()
void global_planner::ThetaStar::_updateVertex (const Node & parent, Node & child) protected
update the g value of child node
Parameters
parent
child
 {
   if (_lineOfSight(parent, child))
   {
     // path 2
     if (parent.g_ + helper::dist(parent, child) < child.g_)
     {
       child.g_ = parent.g_ + helper::dist(parent, child);
       child.pid_ = parent.id_;
     }
   }
 }
References _lineOfSight(), helper::dist(), Node::g_, Node::id_, and Node::pid_.
Referenced by plan().
plan()
bool global_planner::ThetaStar::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) virtual
Theta* implementation.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements global_planner::GlobalPlanner.
 {
   // initialize
   costs_ = global_costmap;
   path.clear();
   expand.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start);
   // get all possible motions
   const std::vector<Node> motion = Node::getMotion();
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     Node current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id_) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id_, current));
     expand.push_back(current);
     // goal found
     if (current == goal)
     {
       path = _convertClosedListToPath(closed_list, start, goal);
       return true;
     }
     // explore neighbor of current node
     for (const auto& m : motion)
     {
       // explore a new node
       // path 1
       Node node_new = current + m;  // add the x_, y_, g_
       node_new.h_ = helper::dist(node_new, goal);
       node_new.id_ = grid2Index(node_new.x_, node_new.y_);
       node_new.pid_ = current.id_;
       // current node do not exist in closed list
       if (closed_list.find(node_new.id_) != closed_list.end())
         continue;
       // next node hit the boundary or obstacle
       if ((node_new.id_ < 0) || (node_new.id_ >= ns_) ||
           (costs_[node_new.id_] >= lethal_cost_ * factor_ && costs_[node_new.id_] >= costs_[current.id_]))
         continue;
       // get the coordinate of parent node
       Node parent;
       parent.id_ = current.pid_;
       index2Grid(parent.id_, parent.x_, parent.y_);
       // update g value
       auto find_parent = closed_list.find(parent.id_);
       if (find_parent != closed_list.end())
       {
         parent = find_parent->second;
         _updateVertex(parent, node_new);
       }
       open_list.push(node_new);
     }
   }
   return false;
 }
References global_planner::GlobalPlanner::_convertClosedListToPath(), _updateVertex(), costs_, helper::dist(), global_planner::GlobalPlanner::factor_, Node::getMotion(), global_planner::GlobalPlanner::grid2Index(), Node::h_, Node::id_, global_planner::GlobalPlanner::index2Grid(), global_planner::GlobalPlanner::lethal_cost_, global_planner::GlobalPlanner::ns_, Node::pid_, Node::x_, and Node::y_.
Member Data Documentation
costs_
const unsigned char* global_planner::ThetaStar::costs_ protected
Referenced by _lineOfSight(), plan(), and global_planner::LazyThetaStar::plan().
The documentation for this class was generated from the following files:
src/core/global_planner/graph_planner/include/theta_star.h
src/core/global_planner/graph_planner/src/theta_star.cpp