ROS Motion Planning: utils::Vector2d Class Reference
utils::Vector2d Class Reference
#include <vector2d.hpp>
Public Member Functions
Vector2d ()
Vector2d (double x, double y)
virtual ~Vector2d ()
double operator() (int index) const
double operator[] (int index) const
bool operator== (const Vector2d &other) const
bool operator< (const Vector2d &other) const
double getX () const
double getY () const
Vector2d & set (double x, double y)
Vector2d & setX (double x)
Vector2d & setY (double y)
Vector2d & incX (double inc_x)
Vector2d & incY (double inc_y)
Vector2d & inc (double inc_x, double inc_y)
const Angle angle () const
Angle angleTo (const Vector2d &other) const
double squaredNorm () const
double norm () const
double dot (const Vector2d &other) const
Vector2d & normalize ()
Vector2d normalized () const
Vector2d & operator*= (double scalar)
Vector2d operator* (double scalar) const
Vector2d & operator/= (double scalar)
Vector2d operator/ (double scalar) const
Vector2d leftNormalVector () const
Vector2d rightNormalVector () const
Vector2d & operator+= (const Vector2d &other)
Vector2d operator+ (const Vector2d &other) const
Vector2d & operator-= (const Vector2d &other)
Vector2d operator- (const Vector2d &other) const
Vector2d operator- () const
Static Public Member Functions
static const Vector2d & Zero ()
Private Attributes
double x
double y
Constructor & Destructor Documentation
Vector2d() [1/2]
utils::Vector2d::Vector2d () inline
              : x(0), y(0)
   {
   }
Referenced by leftNormalVector(), operator*(), operator+(), operator-(), operator/(), and rightNormalVector().
Vector2d() [2/2]
utils::Vector2d::Vector2d (double x, double y) inline
                                : x(x), y(y)
   {
   }
~Vector2d()
virtual utils::Vector2d::~Vector2d () inline virtual
   {
   }
Member Function Documentation
angle()
const Angle utils::Vector2d::angle () const inline
   {
     return Angle::fromRadian(std::atan2(y, x));
   }
References utils::Angle::fromRadian(), x, and y.
Referenced by angleTo(), and sfm::SocialForceModel::updatePosition().
angleTo()
Angle utils::Vector2d::angleTo (const Vector2d & other) const inline
   {
     return other.angle() - angle();
   }
References angle().
Referenced by sfm::SocialForceModel::computeSocialForce().
dot()
double utils::Vector2d::dot (const Vector2d & other) const inline
   {
     return x * other.x + y * other.y;
   }
References x, and y.
Referenced by sfm::SocialForceModel::computeGroupForce().
getX()
double utils::Vector2d::getX () const inline
   {
     return x;
   }
References x.
Referenced by gazebo::PedestrianSFMPlugin::OnUpdate(), and std::operator<<().
getY()
double utils::Vector2d::getY () const inline
   {
     return y;
   }
References y.
Referenced by gazebo::PedestrianSFMPlugin::OnUpdate(), and std::operator<<().
inc()
Vector2d& utils::Vector2d::inc (double inc_x, double inc_y) inline
   {
     x += inc_x;
     y += inc_y;
     return *this;
   }
References x, and y.
incX()
Vector2d& utils::Vector2d::incX (double inc_x) inline
   {
     x += inc_x;
     return *this;
   }
References x.
incY()
Vector2d& utils::Vector2d::incY (double inc_y) inline
   {
     y += inc_y;
     return *this;
   }
References y.
leftNormalVector()
Vector2d utils::Vector2d::leftNormalVector () const inline
   {
     return Vector2d(-y, x);
   }
References Vector2d(), x, and y.
Referenced by sfm::SocialForceModel::computeSocialForce().
norm()
double utils::Vector2d::norm () const inline
   {
     return std::sqrt(squaredNorm());
   }
References squaredNorm().
Referenced by sfm::SocialForceModel::computeGroupForce(), sfm::SocialForceModel::computeObstacleForce(), sfm::SocialForceModel::computeSocialForce(), normalize(), and sfm::SocialForceModel::updatePosition().
normalize()
Vector2d& utils::Vector2d::normalize () inline
   {
     double n = norm();
     if (n > 0)
     {
       x /= n;
       y /= n;
     }
     return *this;
   }
References norm(), x, and y.
Referenced by normalized(), and sfm::SocialForceModel::updatePosition().
normalized()
Vector2d utils::Vector2d::normalized () const inline
   {
     Vector2d v(*this);
     v.normalize();
     return v;
   }
References normalize().
Referenced by sfm::SocialForceModel::computeDesiredForce(), sfm::SocialForceModel::computeGroupForce(), sfm::SocialForceModel::computeObstacleForce(), and sfm::SocialForceModel::computeSocialForce().
operator()()
double utils::Vector2d::operator() (int index) const inline
   {
     return index == 0 ? x : y;
   }
References x, and y.
operator*()
Vector2d utils::Vector2d::operator* (double scalar) const inline
   {
     return Vector2d(x * scalar, y * scalar);
   }
References Vector2d(), x, and y.
operator*=()
Vector2d& utils::Vector2d::operator*= (double scalar) inline
   {
     x *= scalar;
     y *= scalar;
     return *this;
   }
References x, and y.
operator+()
Vector2d utils::Vector2d::operator+ (const Vector2d & other) const inline
   {
     return Vector2d(x + other.x, y + other.y);
   }
References Vector2d(), x, and y.
operator+=()
Vector2d& utils::Vector2d::operator+= (const Vector2d & other) inline
   {
     set(x + other.x, y + other.y);
     return *this;
   }
References set(), x, and y.
operator-() [1/2]
Vector2d utils::Vector2d::operator- () const inline
   {
     return Vector2d(-x, -y);
   }
References Vector2d(), x, and y.
operator-() [2/2]
Vector2d utils::Vector2d::operator- (const Vector2d & other) const inline
   {
     return Vector2d(x - other.x, y - other.y);
   }
References Vector2d(), x, and y.
operator-=()
Vector2d& utils::Vector2d::operator-= (const Vector2d & other) inline
   {
     set(x - other.x, y - other.y);
     return *this;
   }
References set(), x, and y.
operator/()
Vector2d utils::Vector2d::operator/ (double scalar) const inline
   {
     return Vector2d(x / scalar, y / scalar);
   }
References Vector2d(), x, and y.
operator/=()
Vector2d& utils::Vector2d::operator/= (double scalar) inline
   {
     x /= scalar;
     y /= scalar;
     return *this;
   }
References x, and y.
operator<()
bool utils::Vector2d::operator< (const Vector2d & other) const inline
   {
     return x < other.x || (x == other.x && y < other.y);
   }
References x, and y.
operator==()
bool utils::Vector2d::operator== (const Vector2d & other) const inline
   {
     return x == other.x && y == other.y;
   }
References x, and y.
operator[]()
double utils::Vector2d::operator[] (int index) const inline
   {
     return index == 0 ? x : y;
   }
References x, and y.
rightNormalVector()
Vector2d utils::Vector2d::rightNormalVector () const inline
   {
     return Vector2d(y, -x);
   }
References Vector2d(), x, and y.
set()
Vector2d& utils::Vector2d::set (double x, double y) inline
   {
     Vector2d::x = x;
     Vector2d::y = y;
     return *this;
   }
References x, and y.
Referenced by sfm::SocialForceModel::computeGroupForce(), sfm::SocialForceModel::computeObstacleForce(), sfm::SocialForceModel::computeSocialForce(), gazebo::PedestrianSFMPlugin::handlePedestrians(), sfm::Agent::move(), operator+=(), operator-=(), gazebo::PedestrianSFMPlugin::Reset(), and sfm::SocialForceModel::updatePosition().
setX()
Vector2d& utils::Vector2d::setX (double x) inline
   {
     Vector2d::x = x;
     return *this;
   }
References x.
setY()
Vector2d& utils::Vector2d::setY (double y) inline
   {
     Vector2d::y = y;
     return *this;
   }
References y.
squaredNorm()
double utils::Vector2d::squaredNorm () const inline
   {
     return x * x + y * y;
   }
References x, and y.
Referenced by sfm::SocialForceModel::computeGroupForce(), and norm().
Zero()
static const Vector2d& utils::Vector2d::Zero () inline static
   {
     static Vector2d zero;
     return zero;
   }
Member Data Documentation
x
double utils::Vector2d::x private
Referenced by angle(), dot(), getX(), inc(), incX(), leftNormalVector(), normalize(), operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator==(), operator[](), rightNormalVector(), set(), setX(), and squaredNorm().
y
double utils::Vector2d::y private
Referenced by angle(), dot(), getY(), inc(), incY(), leftNormalVector(), normalize(), operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator==(), operator[](), rightNormalVector(), set(), setY(), and squaredNorm().
The documentation for this class was generated from the following file:
src/third_party/gazebo_plugins/pedestrian_sfm_plugin/include/lightsfm/vector2d.hpp