ROS Motion Planning: global_planner::GlobalPlanner Class Reference
global_planner::GlobalPlanner Class Reference abstract
Abstract class that is inherited by concerete implementaions of global planner classes. The Plan function is a pure virtual funciton that is overloaded.
#include <global_planner.h>
Public Member Functions
GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
virtual ~GlobalPlanner ()=default
Destroy the Global Planner object.
virtual bool plan (const unsigned char *global_costmap, const Node &start, const Node &goal, std::vector< Node > &path, std::vector< Node > &expand)=0
Pure virtual function that is overloadde by planner implementations.
void setSize (int nx, int ny)
Set or reset costmap size.
void setResolution (double resolution)
Set or reset costmap resolution.
void setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
void setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
void setFactor (double factor)
Set or reset obstacle factor.
void setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
void setConvertOffset (double convert_offset)
Set convert offset.
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
void map2Grid (double mx, double my, int &gx, int &gy)
Transform from grid map(x, y) to grid map(x, y)
void grid2Map (int gx, int gy, double &mx, double &my)
Transform from costmap(x, y) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap (unsigned char *costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
Protected Attributes
unsigned char lethal_cost_
unsigned char neutral_cost_
int nx_
int ny_
int ns_
double resolution_
double factor_
double origin_x_
double origin_y_
double convert_offset_
Detailed Description
Abstract class that is inherited by concerete implementaions of global planner classes. The Plan function is a pure virtual funciton that is overloaded.
Constructor & Destructor Documentation
GlobalPlanner()
global_planner::GlobalPlanner::GlobalPlanner (int nx, int ny, double resolution)
Construct a new Global Planner object.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
resolution costmap resolution
   : lethal_cost_(LETHAL_COST), neutral_cost_(NEUTRAL_COST), factor_(OBSTACLE_FACTOR)
 {
   setSize(nx, ny);
   setResolution(resolution);
 }
References setResolution(), and setSize().
~GlobalPlanner()
virtual global_planner::GlobalPlanner::~GlobalPlanner () virtual default
Destroy the Global Planner object.
Member Function Documentation
_convertClosedListToPath()
std::vector< Node > global_planner::GlobalPlanner::_convertClosedListToPath (std::unordered_map< int, Node > & closed_list, const Node & start, const Node & goal) protected
Convert closed list to path.
Parameters
closed_list closed list
start start node
goal goal node
Returns
vector containing path nodes
 {
   std::vector<Node> path;
   auto current = closed_list.find(goal.id_);
   while (current->second != start)
   {
     path.emplace_back(current->second.x_, current->second.y_);
     auto it = closed_list.find(current->second.pid_);
     if (it != closed_list.end())
       current = it;
     else
       return {};
   }
   path.push_back(start);
   return path;
 }
References Node::id_.
Referenced by global_planner::RRTStar::plan(), global_planner::AStar::plan(), global_planner::ThetaStar::plan(), global_planner::InformedRRT::plan(), global_planner::JumpPointSearch::plan(), global_planner::RRT::plan(), global_planner::LazyThetaStar::plan(), and global_planner::VoronoiPlanner::searchPathWithVoronoi().
grid2Index()
int global_planner::GlobalPlanner::grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
Parameters
x grid map x
y grid map y
Returns
index
 {
   return x + nx_ * y;
 }
References nx_.
Referenced by global_planner::RRT::_checkGoal(), global_planner::RRTStar::_findNearestPoint(), global_planner::RRT::_findNearestPoint(), global_planner::RRT::_isAnyObstacleInPath(), global_planner::ThetaStar::_lineOfSight(), global_planner::LazyThetaStar::_setVertex(), global_planner::InformedRRT::_transform(), global_planner::HybridAStar::_worldToIndex(), global_planner::ACO::calFitnessValue(), global_planner::GA::calFitnessValue(), global_planner::PSO::calFitnessValue(), global_planner::JumpPointSearch::detectForceNeighbor(), global_planner::HybridAStar::dubinsShot(), global_planner::HybridAStar::genHeurisiticMap(), global_planner::ACO::initializePositions(), global_planner::GA::initializePositions(), global_planner::PSO::initializePositions(), global_planner::DStar::initMap(), global_planner::LPAStar::initMap(), global_planner::DStarLite::initMap(), global_planner::JumpPointSearch::jump(), sample_planner::SamplePlanner::makePlan(), graph_planner::GraphPlanner::makePlan(), evolutionary_planner::EvolutionaryPlanner::makePlan(), global_planner::ACO::optimizeAnt(), global_planner::GA::optimizeGenets(), global_planner::RRTConnect::plan(), global_planner::AStar::plan(), global_planner::ThetaStar::plan(), global_planner::InformedRRT::plan(), global_planner::LazyThetaStar::plan(), global_planner::HybridAStar::plan(), global_planner::DStar::plan(), global_planner::LPAStar::plan(), global_planner::DStarLite::plan(), and global_planner::VoronoiPlanner::searchPathWithVoronoi().
grid2Map()
void global_planner::GlobalPlanner::grid2Map (int gx, int gy, double & mx, double & my)
Transform from costmap(x, y) to grid map(x, y)
Parameters
gx grid map x
gy grid map y
mx costmap x
my costmap y
 {
   mx = resolution_ * (gx + 0.5);
   my = resolution_ * (gy + 0.5);
 }
References resolution_.
Referenced by sample_planner::SamplePlanner::_pubLine().
index2Grid()
void global_planner::GlobalPlanner::index2Grid (int i, int & x, int & y)
Transform from grid index(i) to grid map(x, y)
Parameters
i grid index i
x grid map x
y grid map y
 {
   x = i % nx_;
   y = i / nx_;
 }
References nx_.
Referenced by global_planner::RRT::_generateRandomNode(), sample_planner::SamplePlanner::_pubLine(), global_planner::LazyThetaStar::_setVertex(), global_planner::DStar::extractPath(), global_planner::ThetaStar::plan(), and global_planner::LazyThetaStar::plan().
map2Grid()
void global_planner::GlobalPlanner::map2Grid (double mx, double my, int & gx, int & gy)
Transform from grid map(x, y) to grid map(x, y)
Transform from grid map(x, y) to costmap(x, y)
Parameters
gx grid map x
gy grid map y
mx costmap x
my costmap y
 {
   gx = (int)mx;
   gy = (int)my;
 }
Referenced by global_planner::HybridAStar::_worldToGrid(), sample_planner::SamplePlanner::makePlan(), graph_planner::GraphPlanner::makePlan(), and evolutionary_planner::EvolutionaryPlanner::makePlan().
map2World()
void global_planner::GlobalPlanner::map2World (double mx, double my, double & wx, double & wy)
Tranform from costmap(x, y) to world map(x, y)
Parameters
mx costmap x
my costmap y
wx world map x
wy world map y
 {
   wx = origin_x_ + (mx + convert_offset_) * resolution_;
   wy = origin_y_ + (my + convert_offset_) * resolution_;
 }
References convert_offset_, origin_x_, origin_y_, and resolution_.
Referenced by evolutionary_planner::EvolutionaryPlanner::_getPlanFromPath(), sample_planner::SamplePlanner::_getPlanFromPath(), and graph_planner::GraphPlanner::_getPlanFromPath().
outlineMap()
void global_planner::GlobalPlanner::outlineMap (unsigned char * costarr)
Inflate the boundary of costmap into obstacles to prevent cross planning.
Parameters
costarr costmap pointer
 {
   unsigned char* pc = costarr;
   for (int i = 0; i < nx_; i++)
     *pc++ = costmap_2d::LETHAL_OBSTACLE;
   pc = costarr + (ny_ - 1) * nx_;
   for (int i = 0; i < nx_; i++)
     *pc++ = costmap_2d::LETHAL_OBSTACLE;
   pc = costarr;
   for (int i = 0; i < ny_; i++, pc += nx_)
     *pc = costmap_2d::LETHAL_OBSTACLE;
   pc = costarr + nx_ - 1;
   for (int i = 0; i < ny_; i++, pc += nx_)
     *pc = costmap_2d::LETHAL_OBSTACLE;
 }
References nx_, and ny_.
Referenced by graph_planner::GraphPlanner::makePlan(), sample_planner::SamplePlanner::makePlan(), and evolutionary_planner::EvolutionaryPlanner::makePlan().
plan()
virtual bool global_planner::GlobalPlanner::plan (const unsigned char * global_costmap, const Node & start, const Node & goal, std::vector< Node > & path, std::vector< Node > & expand) pure virtual
Pure virtual function that is overloadde by planner implementations.
Parameters
global_costmap global costmap
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implemented in global_planner::DStarLite, global_planner::LPAStar, global_planner::DStar, global_planner::HybridAStar, global_planner::PSO, global_planner::GA, global_planner::ACO, global_planner::LazyThetaStar, global_planner::VoronoiPlanner, global_planner::RRT, global_planner::JumpPointSearch, global_planner::AStar, global_planner::ThetaStar, global_planner::InformedRRT, global_planner::RRTConnect, and global_planner::RRTStar.
Referenced by graph_planner::GraphPlanner::makePlan(), sample_planner::SamplePlanner::makePlan(), and evolutionary_planner::EvolutionaryPlanner::makePlan().
setConvertOffset()
void global_planner::GlobalPlanner::setConvertOffset (double convert_offset)
Set convert offset.
Parameters
origin_x origin in costmap x direction
origin_y origin in costmap y direction
 {
   convert_offset_ = convert_offset;
 }
References convert_offset_.
Referenced by graph_planner::GraphPlanner::initialize(), evolutionary_planner::EvolutionaryPlanner::initialize(), and sample_planner::SamplePlanner::initialize().
setFactor()
void global_planner::GlobalPlanner::setFactor (double factor)
Set or reset obstacle factor.
Parameters
factor obstacle factor
 {
   factor_ = factor;
 }
References factor_.
setLethalCost()
void global_planner::GlobalPlanner::setLethalCost (unsigned char lethal_cost)
Set or reset lethal cost.
Parameters
lethal_cost lethal cost
 {
   lethal_cost_ = lethal_cost;
 }
References lethal_cost_.
setNeutralCost()
void global_planner::GlobalPlanner::setNeutralCost (unsigned char neutral_cost)
Set or reset neutral cost.
Parameters
neutral_cost neutral cost
 {
   neutral_cost_ = neutral_cost;
 }
References neutral_cost_.
setOrigin()
void global_planner::GlobalPlanner::setOrigin (double origin_x, double origin_y)
Set or reset costmap origin.
Parameters
origin_x origin in costmap x direction
origin_y origin in costmap y direction
 {
   origin_x_ = origin_x;
   origin_y_ = origin_y;
 }
References origin_x_, and origin_y_.
Referenced by graph_planner::GraphPlanner::initialize(), evolutionary_planner::EvolutionaryPlanner::initialize(), and sample_planner::SamplePlanner::initialize().
setResolution()
void global_planner::GlobalPlanner::setResolution (double resolution)
Set or reset costmap resolution.
Parameters
resolution costmap resolution
 {
   resolution_ = resolution;
 }
References resolution_.
Referenced by GlobalPlanner().
setSize()
void global_planner::GlobalPlanner::setSize (int nx, int ny)
Set or reset costmap size.
Parameters
nx pixel number in costmap x direction
ny pixel number in costmap y direction
 {
   nx_ = nx;
   ny_ = ny;
   ns_ = nx * ny;
 }
References ns_, nx_, and ny_.
Referenced by GlobalPlanner().
world2Map()
bool global_planner::GlobalPlanner::world2Map (double wx, double wy, double & mx, double & my)
Tranform from world map(x, y) to costmap(x, y)
Parameters
mx costmap x
my costmap y
wx world map x
wy world map y
Returns
true if successfull, else false
 {
   if (wx < origin_x_ || wy < origin_y_)
     return false;
   mx = (wx - origin_x_) / resolution_ - convert_offset_;
   my = (wy - origin_y_) / resolution_ - convert_offset_;
   if (mx < nx_ && my < ny_)
     return true;
   return false;
 }
References convert_offset_, nx_, ny_, origin_x_, origin_y_, and resolution_.
Referenced by global_planner::HybridAStar::_worldToGrid(), global_planner::HybridAStar::dubinsShot(), graph_planner::GraphPlanner::makePlan(), sample_planner::SamplePlanner::makePlan(), evolutionary_planner::EvolutionaryPlanner::makePlan(), and global_planner::HybridAStar::plan().
Member Data Documentation
convert_offset_
double global_planner::GlobalPlanner::convert_offset_ protected
Referenced by map2World(), setConvertOffset(), and world2Map().
factor_
double global_planner::GlobalPlanner::factor_ protected
Referenced by global_planner::RRT::_isAnyObstacleInPath(), global_planner::ThetaStar::_lineOfSight(), global_planner::AStar::AStar(), global_planner::ACO::calFitnessValue(), global_planner::GA::calFitnessValue(), global_planner::PSO::calFitnessValue(), global_planner::JumpPointSearch::detectForceNeighbor(), global_planner::DStar::DStar(), global_planner::DStarLite::DStarLite(), global_planner::HybridAStar::dubinsShot(), global_planner::DStar::isCollision(), global_planner::LPAStar::isCollision(), global_planner::DStarLite::isCollision(), global_planner::JumpPointSearch::jump(), global_planner::LazyThetaStar::LazyThetaStar(), global_planner::GA::optimizeGenets(), global_planner::RRTConnect::plan(), global_planner::RRTStar::plan(), global_planner::InformedRRT::plan(), global_planner::ThetaStar::plan(), global_planner::AStar::plan(), global_planner::RRT::plan(), global_planner::LazyThetaStar::plan(), global_planner::HybridAStar::plan(), setFactor(), and global_planner::ThetaStar::ThetaStar().
lethal_cost_
unsigned char global_planner::GlobalPlanner::lethal_cost_ protected
Referenced by global_planner::RRT::_isAnyObstacleInPath(), global_planner::ThetaStar::_lineOfSight(), global_planner::ACO::calFitnessValue(), global_planner::GA::calFitnessValue(), global_planner::PSO::calFitnessValue(), global_planner::JumpPointSearch::detectForceNeighbor(), global_planner::HybridAStar::dubinsShot(), global_planner::DStar::isCollision(), global_planner::LPAStar::isCollision(), global_planner::DStarLite::isCollision(), global_planner::JumpPointSearch::jump(), global_planner::GA::optimizeGenets(), global_planner::RRTStar::plan(), global_planner::RRTConnect::plan(), global_planner::InformedRRT::plan(), global_planner::ThetaStar::plan(), global_planner::AStar::plan(), global_planner::RRT::plan(), global_planner::LazyThetaStar::plan(), global_planner::HybridAStar::plan(), and setLethalCost().
neutral_cost_
unsigned char global_planner::GlobalPlanner::neutral_cost_ protected
Referenced by setNeutralCost().
ns_
int global_planner::GlobalPlanner::ns_ protected
Referenced by global_planner::InformedRRT::_generateRandomNode(), global_planner::RRT::_generateRandomNode(), global_planner::ACO::calFitnessValue(), global_planner::GA::calFitnessValue(), global_planner::PSO::calFitnessValue(), global_planner::DStar::DStar(), global_planner::DStarLite::DStarLite(), global_planner::HybridAStar::genHeurisiticMap(), global_planner::JumpPointSearch::jump(), global_planner::LPAStar::LPAStar(), global_planner::GA::optimizeGenets(), global_planner::ThetaStar::plan(), global_planner::AStar::plan(), global_planner::LazyThetaStar::plan(), global_planner::HybridAStar::plan(), global_planner::DStar::plan(), global_planner::LPAStar::plan(), global_planner::DStarLite::plan(), global_planner::VoronoiPlanner::searchPathWithVoronoi(), and setSize().
nx_
int global_planner::GlobalPlanner::nx_ protected
Referenced by global_planner::ACO::ACO(), global_planner::DStar::extractExpand(), global_planner::DStar::getNeighbours(), global_planner::LPAStar::getNeighbours(), global_planner::DStarLite::getNeighbours(), grid2Index(), index2Grid(), global_planner::ACO::initializePositions(), global_planner::GA::initializePositions(), global_planner::PSO::initializePositions(), global_planner::DStar::initMap(), global_planner::LPAStar::initMap(), global_planner::DStarLite::initMap(), outlineMap(), global_planner::VoronoiPlanner::plan(), global_planner::ACO::plan(), global_planner::DStar::plan(), global_planner::LPAStar::plan(), global_planner::DStarLite::plan(), global_planner::DStar::reset(), global_planner::LPAStar::reset(), global_planner::DStarLite::reset(), setSize(), global_planner::PSO::updateParticlePosition(), global_planner::VoronoiPlanner::VoronoiPlanner(), world2Map(), and global_planner::VoronoiPlanner::~VoronoiPlanner().
ny_
int global_planner::GlobalPlanner::ny_ protected
Referenced by global_planner::ACO::ACO(), global_planner::DStar::extractExpand(), global_planner::DStar::getNeighbours(), global_planner::LPAStar::getNeighbours(), global_planner::DStarLite::getNeighbours(), global_planner::ACO::initializePositions(), global_planner::GA::initializePositions(), global_planner::PSO::initializePositions(), global_planner::DStar::initMap(), global_planner::LPAStar::initMap(), global_planner::DStarLite::initMap(), outlineMap(), global_planner::VoronoiPlanner::plan(), global_planner::ACO::plan(), global_planner::DStar::plan(), global_planner::LPAStar::plan(), global_planner::DStarLite::plan(), global_planner::DStar::reset(), global_planner::LPAStar::reset(), global_planner::DStarLite::reset(), setSize(), global_planner::PSO::updateParticlePosition(), global_planner::VoronoiPlanner::VoronoiPlanner(), and world2Map().
origin_x_
double global_planner::GlobalPlanner::origin_x_ protected
Referenced by map2World(), setOrigin(), and world2Map().
origin_y_
double global_planner::GlobalPlanner::origin_y_ protected
Referenced by map2World(), setOrigin(), and world2Map().
resolution_
double global_planner::GlobalPlanner::resolution_ protected
Referenced by global_planner::RRT::_isAnyObstacleInPath(), grid2Map(), map2World(), global_planner::VoronoiPlanner::plan(), setResolution(), global_planner::HybridAStar::updateHeuristic(), and world2Map().
The documentation for this class was generated from the following files:
src/core/global_planner/global_planner/include/global_planner.h
src/core/global_planner/global_planner/src/global_planner.cpp