ROS Motion Planning: send_test_msgs Namespace Reference
send_test_msgs Namespace Reference
Functions
def setPoseAndTwistFromAngle (pose, twist, angle, radius)
def createTrackAndDetection (tracks, detections, track_id, detection_id, angle, radius)
Variables
string trackTopic = '/spencer/tracked_persons'
trackPublisher = rospy.Publisher(trackTopic, TrackedPersons)
string observationTopic = '/spencer/detected_persons'
observationPublisher = rospy.Publisher(observationTopic, DetectedPersons)
br = tf.TransformBroadcaster()
startTime = rospy.Time.now()
int currentCycle = 0
float currentAngle = 0.0
float angleStep = 4.5 * pi / 180.
int idShift = 0
int updateRateHz = 10
tuple frameOffset = (0, 0, 0)
frameOrientation = tf.transformations.quaternion_from_euler(0, 0, 0)
rate = rospy.Rate(updateRateHz)
trackedPersons = TrackedPersons()
frame_id
stamp
detectedPersons = DetectedPersons()
header
tracks = trackedPersons.tracks;
detections = detectedPersons.detections;
Function Documentation
createTrackAndDetection()
def send_test_msgs.createTrackAndDetection (tracks, detections, track_id, detection_id, angle, radius)
 def createTrackAndDetection( tracks, detections, track_id, detection_id, angle, radius ) :
     trackedPerson = TrackedPerson()
     trackedPerson.track_id = track_id
     if detection_id >= 0 :
         trackedPerson.detection_id = detection_id
         trackedPerson.is_occluded = False
     else :
         trackedPerson.is_occluded = True
     trackedPerson.age = rospy.Time.now() - startTime
     setPoseAndTwistFromAngle(trackedPerson.pose, trackedPerson.twist, angle, radius)
     tracks.append(trackedPerson)
     if detection_id >= 0:
         detectedPerson = DetectedPerson()
         detectedPerson.detection_id = detection_id
         detectedPerson.confidence = random.random()
         detectedPerson.pose = copy.deepcopy(trackedPerson.pose)
         detectedPerson.pose.pose.position.x += random.random() * 0.5 - 0.25 # introduce some noise on observation position
         detectedPerson.pose.pose.position.y += random.random() * 0.5 - 0.25
         detections.append(detectedPerson)
     return
 # Main code
References setPoseAndTwistFromAngle().
setPoseAndTwistFromAngle()
def send_test_msgs.setPoseAndTwistFromAngle (pose, twist, angle, radius)
 def setPoseAndTwistFromAngle( pose, twist, angle, radius ) :
     currentx = radius * cos(angle)
     currenty = radius * sin(angle)
     nextx = radius * cos(angle + angleStep)
     nexty = radius * sin(angle + angleStep)
     pose.pose.position.x = currentx
     pose.pose.position.y = currenty
     pose.pose.position.z = 0.0
     quaternion = tf.transformations.quaternion_from_euler(0, 0, angle + pi/2.0)
     pose.pose.orientation.x = quaternion[0]
     pose.pose.orientation.y = quaternion[1]
     pose.pose.orientation.z = quaternion[2]
     pose.pose.orientation.w = quaternion[3]
     pose.covariance[0 + 0 * 6] = 0.4 # x
     pose.covariance[1 + 1 * 6] = 0.2 # y
     pose.covariance[2 + 2 * 6] = 999999 # z
     pose.covariance[3 + 3 * 6] = 0.0 # x rotation
     pose.covariance[4 + 5 * 6] = 0.0 # y rotation
     pose.covariance[4 + 5 * 6] = 0.1 # z rotation
     twist.twist.linear.x = nextx - currentx
     twist.twist.linear.y = nexty - currenty
     twist.twist.linear.z = 0
     for i in range(0, 3):
         twist.covariance[i + i * 6] = 1.0 # linear velocity
     for i in range(3, 6):
         twist.covariance[i + i * 6] = float("inf") # rotational velocity
Referenced by createTrackAndDetection().
Variable Documentation
angleStep
float send_test_msgs.angleStep = 4.5 * pi / 180.
br
send_test_msgs.br = tf.TransformBroadcaster()
Referenced by DynamicVoronoi.prune().
currentAngle
float send_test_msgs.currentAngle = 0.0
currentCycle
int send_test_msgs.currentCycle = 0
detectedPersons
send_test_msgs.detectedPersons = DetectedPersons()
detections
send_test_msgs.detections = detectedPersons.detections;
frame_id
send_test_msgs.frame_id
Referenced by evolutionary_planner::EvolutionaryPlanner.initialize(), sample_planner::SamplePlanner.initialize(), and sample_planner::SamplePlanner.SamplePlanner().
frameOffset
tuple send_test_msgs.frameOffset = (0, 0, 0)
frameOrientation
send_test_msgs.frameOrientation = tf.transformations.quaternion_from_euler(0, 0, 0)
Referenced by spencer_tracking_rviz_plugin::TrackedPersonsCache.processTrackedPersonsMessage().
header
send_test_msgs.header
idShift
int send_test_msgs.idShift = 0
observationPublisher
send_test_msgs.observationPublisher = rospy.Publisher(observationTopic, DetectedPersons)
observationTopic
string send_test_msgs.observationTopic = '/spencer/detected_persons'
rate
send_test_msgs.rate = rospy.Rate(updateRateHz)
Referenced by orca_planner::OrcaPlanner.initialize().
stamp
send_test_msgs.stamp
startTime
send_test_msgs.startTime = rospy.Time.now()
trackedPersons
send_test_msgs.trackedPersons = TrackedPersons()
trackPublisher
send_test_msgs.trackPublisher = rospy.Publisher(trackTopic, TrackedPersons)
tracks
send_test_msgs.tracks = trackedPersons.tracks;
trackTopic
string send_test_msgs.trackTopic = '/spencer/tracked_persons'
updateRateHz
int send_test_msgs.updateRateHz = 10