ROS Motion Planning: RVO Namespace Reference
RVO Namespace Reference
Contains all classes, functions, and constants used in the library.
Namespaces
anonymous_namespace{Agent.cc}
anonymous_namespace{KdTree.cc}
Classes
class Agent
Defines an agent in the simulation.
class KdTree
Defines k-D trees for agents and static obstacles in the simulation.
class Line
Defines a directed line.
class Obstacle
Defines static obstacles in the simulation.
class RVOSimulator
Defines the simulation. The main class of the library that contains all simulation functionality.
class Vector2
Defines a two-dimensional vector.
Functions
Vector2 operator* (float scalar, const Vector2 &vector)
std::ostream & operator<< (std::ostream &stream, const Vector2 &vector)
float abs (const Vector2 &vector)
float absSq (const Vector2 &vector)
float det (const Vector2 &vector1, const Vector2 &vector2)
float leftOf (const Vector2 &vector1, const Vector2 &vector2, const Vector2 &vector3)
Computes the signed distance from a line connecting th specified points to a specified point.
Vector2 normalize (const Vector2 &vector)
Variables
const std::size_t RVO_ERROR = std::numeric_limits<std::size_t>::max()
const float RVO_EPSILON = 0.00001F
A sufficiently small positive number.
Detailed Description
Contains all classes, functions, and constants used in the library.
Function Documentation
abs()
float RVO::abs (const Vector2 & vector) related
 { return std::sqrt(vector * vector); }
Referenced by global_planner::ThetaStar::_lineOfSight(), lqr_planner::LQRPlanner::_lqrControl(), DynamicVoronoi::checkVoro(), RVO::Agent::computeNewVelocity(), orca_planner::OrcaPlanner::computeVelocityCommands(), normalize(), global_planner::HybridAStar::HybridNode::operator==(), and spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::setMeanCovariance().
absSq()
float RVO::absSq (const Vector2 & vector) related
 { return vector * vector; }
Referenced by RVO::Agent::computeNewVelocity(), RVO::Agent::insertAgentNeighbor(), RVO::Agent::insertObstacleNeighbor(), RVO::KdTree::queryObstacleTreeRecursive(), and RVO::KdTree::queryVisibilityRecursive().
det()
float RVO::det (const Vector2 & vector1, const Vector2 & vector2) related
{
   return vector1.x() * vector2.y() - vector1.y() * vector2.x();
 }
References RVO::Vector2::x(), and RVO::Vector2::y().
Referenced by RVO::KdTree::buildObstacleTreeRecursive(), RVO::Agent::computeNewVelocity(), and leftOf().
leftOf()
float RVO::leftOf (const Vector2 & vector1, const Vector2 & vector2, const Vector2 & vector3)
Computes the signed distance from a line connecting th specified points to a specified point.
Parameters
[in] vector1 The first point on the line.
[in] vector2 The second point on the line.
[in] vector3 The point to which the signed distance is to be calculated.
Returns
Positive when the point vector3 lies to the left of the line vector1-vector2.
{
   return det(vector1 - vector3, vector2 - vector1);
 }
References det().
Referenced by RVO::RVOSimulator::addObstacle(), RVO::KdTree::buildObstacleTreeRecursive(), RVO::KdTree::queryObstacleTreeRecursive(), and RVO::KdTree::queryVisibilityRecursive().
normalize()
Vector2 RVO::normalize (const Vector2 & vector) related
 { return vector / abs(vector); }
References abs().
Referenced by RVO::RVOSimulator::addObstacle(), RVO::Agent::computeNewVelocity(), and orca_planner::OrcaPlanner::updateState().
operator*()
Vector2 RVO::operator* (float scalar, const Vector2 & vector) related
{
   return Vector2(scalar * vector.x(), scalar * vector.y());
 }
References RVO::Vector2::x(), and RVO::Vector2::y().
operator<<()
std::ostream& RVO::operator<< (std::ostream & stream, const Vector2 & vector) related
{
   stream << "(" << vector.x() << "," << vector.y() << ")";
   return stream;
 }
References RVO::Vector2::x(), and RVO::Vector2::y().
Variable Documentation
RVO_EPSILON
const float RVO::RVO_EPSILON = 0.00001F
A sufficiently small positive number.
Referenced by RVO::KdTree::buildObstacleTreeRecursive(), and RVO::Agent::computeNewVelocity().
RVO_ERROR
const std::size_t RVO::RVO_ERROR = std::numeric_limits<std::size_t>::max() related