ROS Motion Planning: helper Namespace Reference
helper Namespace Reference
Functions
double dist (const Node &node1, const Node &node2)
Calculate distance between the 2 nodes.
double dist (const std::pair< double, double > &node1, const std::pair< double, double > &node2)
double dist (const Eigen::Vector2d &node1, const Eigen::Vector2d &node2)
double dist (const geometry_msgs::PoseStamped &node1, const geometry_msgs::PoseStamped &node2)
double angle (const Node &node1, const Node &node2)
Calculate the angle of x-axis between the 2 nodes.
double angle (const std::pair< double, double > &node1, const std::pair< double, double > &node2)
double angle (const geometry_msgs::PoseStamped &node1, const geometry_msgs::PoseStamped &node2)
double mod2pi (double theta)
Perform modulus operation on 2π.
double pi2pi (double theta)
Truncate the angle to the interval of -π to π.
std::vector< std::pair< double, double > > circleSegmentIntersection (const std::pair< double, double > &p1, const std::pair< double, double > &p2, double r)
Formula for intersection of a line with a circle centered at the origin.
template<typename T >
const T & clamp (const T &value, const T &low, const T &high)
Clamps a value within a specified range.
template<typename Iter , typename Func >
Iter getMinFuncVal (Iter begin, Iter end, Func cal)
Find the first element in iterator with the minimum calculated value.
template<typename Iter , typename Func , typename Val >
Iter firstIntegratedDistance (Iter begin, Iter end, Func dist, Val cmp_val)
Find the first element in iterator that is greater integrated distance than compared value.
Function Documentation
angle() [1/3]
double helper::angle (const geometry_msgs::PoseStamped & node1, const geometry_msgs::PoseStamped & node2)
 {
   return atan2(node2.pose.position.y - node1.pose.position.y, node2.pose.position.x - node1.pose.position.x);
 }
angle() [2/3]
double helper::angle (const Node & node1, const Node & node2)
Calculate the angle of x-axis between the 2 nodes.
Parameters
n1 Node 1
n2 Node 2
Returns
the angle of x-axis between the 2 node
 {
   return atan2(node2.y_ - node1.y_, node2.x_ - node1.x_);
 }
References Node::x_, and Node::y_.
Referenced by global_planner::RRTStar::_findNearestPoint(), global_planner::RRT::_findNearestPoint(), global_planner::RRT::_isAnyObstacleInPath(), global_planner::InformedRRT::_transform(), global_planner::ACO::initializePositions(), global_planner::GA::initializePositions(), global_planner::PSO::initializePositions(), global_planner::RRTConnect::plan(), local_planner::LocalPlanner::regularizeAngle(), trajectory_generation::Bezier::run(), trajectory_generation::Dubins::run(), trajectory_generation::ReedsShepp::run(), and trajectory_generation::Polynomial::run().
angle() [3/3]
double helper::angle (const std::pair< double, double > & node1, const std::pair< double, double > & node2)
 {
   return atan2(node2.second - node1.second, node2.first - node1.first);
 }
circleSegmentIntersection()
std::vector< std::pair< double, double > > helper::circleSegmentIntersection (const std::pair< double, double > & p1, const std::pair< double, double > & p2, double r)
Formula for intersection of a line with a circle centered at the origin.
Note
https://mathworld.wolfram.com/Circle-LineIntersection.html
Parameters
p1/p2 the two point in the segment
r the radius of circle centered at the origin
Returns
points the intersection points of a line and the circle
 {
   std::vector<std::pair<double, double>> i_points;
   double x1 = p1.first;
   double x2 = p2.first;
   double y1 = p1.second;
   double y2 = p2.second;
   double dx = x2 - x1;
   double dy = y2 - y1;
   double dr2 = dx * dx + dy * dy;
   double D = x1 * y2 - x2 * y1;
   // the first element is the point within segment
   double d1 = x1 * x1 + y1 * y1;
   double d2 = x2 * x2 + y2 * y2;
   double dd = d2 - d1;
   double delta = std::sqrt(r * r * dr2 - D * D);
   if (delta >= 0)
   {
     if (delta == 0)
       i_points.emplace_back(D * dy / dr2, -D * dx / dr2);
     else
     {
       i_points.emplace_back((D * dy + std::copysign(1.0, dd) * dx * delta) / dr2,
                             (-D * dx + std::copysign(1.0, dd) * dy * delta) / dr2);
       i_points.emplace_back((D * dy - std::copysign(1.0, dd) * dx * delta) / dr2,
                             (-D * dx - std::copysign(1.0, dd) * dy * delta) / dr2);
     }
   }
   return i_points;
 }
References rviz_generate::r.
Referenced by local_planner::LocalPlanner::getLookAheadPoint().
clamp()
template<typename T > const T& helper::clamp (const T & value, const T & low, const T & high)
Clamps a value within a specified range.
Parameters
value The value to be clamped.
low The lower bound of the range.
high The upper bound of the range.
Returns
const T& The clamped value within the specified range.
 {
   return std::max(low, std::min(value, high));
 }
Referenced by trajectory_optimization::CGOptimizer::calCurvatureTerm(), local_planner::LocalPlanner::getLookAheadDistance(), gazebo::PedestrianSFMPlugin::handleObstacles(), global_planner::PSO::updateParticlePosition(), and global_planner::PSO::updateParticleVelocity().
dist() [1/4]
double helper::dist (const Eigen::Vector2d & node1, const Eigen::Vector2d & node2)
 {
   return std::hypot(point1.x() - point2.x(), point1.y() - point2.y());
 }
dist() [2/4]
double helper::dist (const geometry_msgs::PoseStamped & node1, const geometry_msgs::PoseStamped & node2)
 {
   return std::hypot(node1.pose.position.x - node2.pose.position.x, node1.pose.position.y - node2.pose.position.y);
 }
dist() [3/4]
double helper::dist (const Node & node1, const Node & node2)
Calculate distance between the 2 nodes.
Parameters
n1 Node 1
n2 Node 2
Returns
distance between nodes
 {
   return std::hypot(node1.x_ - node2.x_, node1.y_ - node2.y_);
 }
References Node::x_, and Node::y_.
Referenced by rpp_planner::RPPPlanner::_applyApproachConstraint(), global_planner::RRT::_checkGoal(), kd_tree::KDTree< PointT >::_distance(), global_planner::RRTStar::_findNearestPoint(), global_planner::RRT::_findNearestPoint(), global_planner::RRT::_isAnyObstacleInPath(), kd_tree::KDTree< PointT >::_knnSearchRecursive(), kd_tree::KDTree< PointT >::_nnSearchRecursive(), kd_tree::KDTree< PointT >::_radiusSearchRecursive(), global_planner::LazyThetaStar::_setVertex(), global_planner::ThetaStar::_updateVertex(), global_planner::LazyThetaStar::_updateVertex(), firstIntegratedDistance(), trajectory_generation::Bezier::generation(), trajectory_generation::Dubins::generation(), trajectory_generation::Bezier::getControlPoints(), apf_planner::APFPlanner::getRepulsiveForce(), global_planner::ACO::initializePositions(), global_planner::GA::initializePositions(), global_planner::PSO::initializePositions(), trajectory_generation::Curve::len(), trajectory_generation::Dubins::LRL(), trajectory_generation::Dubins::LSL(), trajectory_generation::Dubins::LSR(), trajectory_generation::BSpline::paramSelection(), global_planner::RRTConnect::plan(), global_planner::AStar::plan(), global_planner::ThetaStar::plan(), global_planner::InformedRRT::plan(), global_planner::LazyThetaStar::plan(), local_planner::LocalPlanner::prune(), trajectory_generation::Dubins::RLR(), trajectory_generation::Dubins::RSL(), trajectory_generation::Dubins::RSR(), trajectory_generation::CubicSpline::run(), local_planner::LocalPlanner::shouldRotateToGoal(), and global_planner::PSO::updateParticleVelocity().
dist() [4/4]
double helper::dist (const std::pair< double, double > & node1, const std::pair< double, double > & node2)
 {
   return std::hypot(node1.first - node2.first, node1.second - node2.second);
 }
firstIntegratedDistance()
template<typename Iter , typename Func , typename Val > Iter helper::firstIntegratedDistance (Iter begin, Iter end, Func dist, Val cmp_val)
Find the first element in iterator that is greater integrated distance than compared value.
Parameters
begin The begin of iterator
end The end of iterator
dist The distance metric function
cmp_val The compared value
Returns
it The first element in iterator that is greater integrated distance than compared value
 {
   if (begin == end)
     return end;
   Val d = 0.0;
   for (Iter it = begin; it != end - 1; it++)
   {
     d += dist(*it, *(it + 1));
     if (d > cmp_val)
       return it + 1;
   }
   return end;
 }
References rviz_generate::d, and dist().
Referenced by local_planner::LocalPlanner::prune().
getMinFuncVal()
template<typename Iter , typename Func > Iter helper::getMinFuncVal (Iter begin, Iter end, Func cal)
Find the first element in iterator with the minimum calculated value.
Parameters
begin The begin of iterator
end The end of iterator
cal The customer calculated function
Returns
it The first element in iterator with the minimum calculated value
 {
   if (begin == end)
     return end;
   auto min_val = cal(*begin);
   Iter min_iter = begin;
   for (Iter it = ++begin; it != end; it++)
   {
     auto val = cal(*it);
     if (val <= min_val)
     {
       min_val = val;
       min_iter = it;
     }
   }
   return min_iter;
 }
Referenced by local_planner::LocalPlanner::prune().
mod2pi()
double helper::mod2pi (double theta)
Perform modulus operation on 2π.
Parameters
theta the angle to modulu
Returns
theta_m the angle after modulus operator
 {
   return theta - 2.0 * M_PI * floor(theta / M_PI / 2.0);
 }
Referenced by trajectory_generation::Dubins::generation(), trajectory_generation::Dubins::LRL(), trajectory_generation::Dubins::LSL(), trajectory_generation::Dubins::LSR(), global_planner::HybridAStar::HybridNode::operator+(), trajectory_generation::Dubins::RLR(), trajectory_generation::Dubins::RSL(), and trajectory_generation::Dubins::RSR().
pi2pi()
double helper::pi2pi (double theta)
Truncate the angle to the interval of -π to π.
Parameters
theta the angle to truncate
Returns
theta_t the truncated angle
 {
   while (theta > M_PI)
     theta -= 2.0 * M_PI;
   while (theta < -M_PI)
     theta += 2.0 * M_PI;
   return theta;
 }
Referenced by trajectory_generation::ReedsShepp::M().