ROS Motion Planning: src/third_party/rviz_plugins/spencer_tracking_rviz_plugin/src/social_activities_display.cpp File Reference
social_activities_display.cpp File Reference
#include <rviz/visualization_manager.h>
#include <rviz/frame_manager.h>
#include "rviz/selection/selection_manager.h"
#include "social_activities_display.h"
#include <boost/lexical_cast.hpp>
#include <boost/tokenizer.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/range/adaptor/map.hpp>
#include <boost/foreach.hpp>
#include <pluginlib/class_list_macros.h>
Namespaces
spencer_tracking_rviz_plugin
Macros
#define foreach BOOST_FOREACH
Functions
const Ogre::Quaternion shapeQuaternion (Ogre::Degree(90), Ogre::Vector3(1, 0, 0))
bool spencer_tracking_rviz_plugin::CompareActivityByType (const SocialActivitiesDisplay::ActivityWithConfidence &first, const SocialActivitiesDisplay::ActivityWithConfidence &second)
Macro Definition Documentation
foreach
#define foreach BOOST_FOREACH
Function Documentation
shapeQuaternion()
const Ogre::Quaternion shapeQuaternion (Ogre::Degree(90) , Ogre::Vector3(1, 0, 0))
Referenced by spencer_tracking_rviz_plugin::HumanAttributesDisplay::processMessage(), spencer_tracking_rviz_plugin::DetectedPersonsDisplay::processMessage(), spencer_tracking_rviz_plugin::SocialActivitiesDisplay::processMessage(), spencer_tracking_rviz_plugin::TrackedGroupsDisplay::processMessage(), spencer_tracking_rviz_plugin::TrackedPersonsDisplay::processMessage(), spencer_tracking_rviz_plugin::TrackedPersonsDisplay::stylesChanged(), spencer_tracking_rviz_plugin::TrackedGroupsDisplay::updateHistoryStyles(), and spencer_tracking_rviz_plugin::SocialActivitiesDisplay::updateSocialActivityVisualStyles().